// Generates sw.js with a precache list kept in sync with index.html, and a
// cache version derived from the hash of every asset's contents — so any change
// to any file produces a new cache name and clients update automatically.
const fs = require('fs');
const crypto = require('crypto');

const html = fs.readFileSync('index.html', 'utf8');

// Scripts, in load order, from index.html
const scripts = [];
const scriptRe = /<script src="([^"]+)"><\/script>/g;
let m;
while ((m = scriptRe.exec(html)) !== null) scripts.push(m[1]);

// Stylesheet(s) referenced from index.html
const styles = [];
const linkRe = /<link[^>]+rel="stylesheet"[^>]+href="([^"]+)"/g;
while ((m = linkRe.exec(html)) !== null) styles.push(m[1]);

const staticAssets = [
  'index.html',
  'manifest.webmanifest',
  'favicon-16.png', 'favicon-32.png',
  'icon-180.png', 'icon-192.png', 'icon-512.png',
  'icon-192-maskable.png', 'icon-512-maskable.png',
];

// Deduplicate, keep order: shell first, then data/scripts, then static
const assets = [];
const seen = new Set();
['index.html', ...styles, ...scripts, ...staticAssets].forEach(a => {
  if (!seen.has(a)) { seen.add(a); assets.push(a); }
});

// Version hash across all cacheable files that exist on disk
const hash = crypto.createHash('sha256');
assets.forEach(a => {
  try { hash.update(a); hash.update(fs.readFileSync(a)); } catch (e) { /* skip missing */ }
});
const version = hash.digest('hex').slice(0, 12);

// Precache URLs are relative to the SW scope (the app root). Include './' so the
// bare directory URL (start_url) resolves offline too.
const urls = ['./', ...assets.map(a => './' + a)];

const sw = `/* DataSense service worker — generated by build_sw.js. Do not edit by hand. */
const CACHE = 'datasense-${version}';
const ASSETS = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) { if (k !== CACHE) return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

// Cache-first for same-origin GET. Everything is precached and the cache name is
// content-versioned, so this is fast offline and still updates on redeploy.
self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && res.ok && res.type === 'basic') {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      }).catch(function () {
        if (req.mode === 'navigate') return caches.match('./index.html');
      });
    })
  );
});

// Allow the page to trigger an immediate update.
self.addEventListener('message', function (e) {
  if (e.data === 'skipWaiting') self.skipWaiting();
});
`;

fs.writeFileSync('sw.js', sw);
console.log('sw.js written · version', version, '·', urls.length, 'precached URLs');
