/* Python coding test — problem bank 1: the warm-ups and the string/list work that
   opens almost every screening test. Each problem is written the way a real test
   writes them: a short brief, a signature, worked examples, then test cases —
   some of them hidden while the clock is running. */
(function () {
  window.PYTESTS = window.PYTESTS || [];

  window.PYTESTS.push(

    { id: 'pt-sum-evens', group: 'Warm-ups', lvl: 1,
      title: 'Sum of even numbers',
      fn: 'sum_evens',
      brief: 'Given a list of whole numbers, return the sum of the even ones.\n\nAn empty list sums to 0.',
      sig: 'def sum_evens(nums: list[int]) -> int',
      starter: 'def sum_evens(nums):\n    # your code here\n    pass\n',
      examples: [
        { in: 'sum_evens([1, 2, 3, 4])', out: '6', note: '2 + 4' },
        { in: 'sum_evens([1, 3, 5])', out: '0', note: 'nothing even' }],
      tests: [
        { call: 'sum_evens([1, 2, 3, 4])', expect: '6' },
        { call: 'sum_evens([1, 3, 5])', expect: '0' },
        { call: 'sum_evens([])', expect: '0', name: 'empty list' },
        { call: 'sum_evens([-2, -3, 4])', expect: '2', hidden: true, name: 'negatives' },
        { call: 'sum_evens([0])', expect: '0', hidden: true, name: 'zero is even' }],
      hint: 'n % 2 == 0 tests for even. You can filter first and sum after.',
      solution: 'def sum_evens(nums):\n    return sum(n for n in nums if n % 2 == 0)\n',
      walk: 'A generator expression inside sum() does the whole job: filter to the evens, add them up. sum() of nothing is 0, so the empty case takes care of itself. Watch the negatives — -2 % 2 is 0 in Python, so they count as even, which is what you want.',
      complexity: 'O(n) time, O(1) extra space.' },

    { id: 'pt-reverse-words', group: 'Warm-ups', lvl: 1,
      title: 'Reverse the words',
      fn: 'reverse_words',
      brief: 'Given a sentence, return it with the words in reverse order.\n\nWords are separated by spaces. Collapse any run of extra spaces down to one, and trim the ends.',
      sig: 'def reverse_words(s: str) -> str',
      starter: 'def reverse_words(s):\n    # your code here\n    pass\n',
      examples: [
        { in: "reverse_words('the sky is blue')", out: "'blue is sky the'" },
        { in: "reverse_words('  hello   world  ')", out: "'world hello'", note: 'extra spaces collapse' }],
      tests: [
        { call: "reverse_words('the sky is blue')", expect: "'blue is sky the'" },
        { call: "reverse_words('  hello   world  ')", expect: "'world hello'" },
        { call: "reverse_words('single')", expect: "'single'", name: 'one word' },
        { call: "reverse_words('')", expect: "''", hidden: true, name: 'empty string' },
        { call: "reverse_words('a b c d')", expect: "'d c b a'", hidden: true }],
      hint: 's.split() with no argument already collapses runs of whitespace and drops the empties.',
      solution: "def reverse_words(s):\n    return ' '.join(reversed(s.split()))\n",
      walk: "split() with no argument is the trick: it splits on any run of whitespace and throws away the empty pieces, so the messy-spacing case needs no extra work. reversed() flips the list, join glues it back with single spaces. s.split(' ') would NOT do this — it keeps every empty string between doubled spaces.",
      complexity: 'O(n) time and space.' },

    { id: 'pt-count-vowels', group: 'Warm-ups', lvl: 1,
      title: 'Count the vowels',
      fn: 'count_vowels',
      brief: 'Return how many vowels (a, e, i, o, u) appear in a string.\n\nCount upper and lower case alike.',
      sig: 'def count_vowels(s: str) -> int',
      starter: 'def count_vowels(s):\n    # your code here\n    pass\n',
      examples: [
        { in: "count_vowels('Hello World')", out: '3', note: 'e, o, o' }],
      tests: [
        { call: "count_vowels('Hello World')", expect: '3' },
        { call: "count_vowels('xyz')", expect: '0' },
        { call: "count_vowels('AEIOU')", expect: '5', name: 'upper case counts' },
        { call: "count_vowels('')", expect: '0', hidden: true },
        { call: "count_vowels('Programming Test 123')", expect: '4', hidden: true }],
      hint: 'Lowercase the string once at the start, then you only have five characters to check against.',
      solution: "def count_vowels(s):\n    return sum(1 for ch in s.lower() if ch in 'aeiou')\n",
      walk: "Normalise the case once rather than checking ten characters. `ch in 'aeiou'` is a substring test on a five-character string — fast enough here, and it reads plainly. sum(1 for ...) counts matches without building a list.",
      complexity: 'O(n) time, O(1) extra space (O(n) if you count the lowercased copy).' },

    { id: 'pt-fizzbuzz', group: 'Warm-ups', lvl: 1,
      title: 'FizzBuzz',
      fn: 'fizzbuzz',
      brief: 'Return a list of length n. For each number from 1 to n: "Fizz" if it divides by 3, "Buzz" if by 5, "FizzBuzz" if by both, otherwise the number itself as a string.\n\nYes, really — it still gets asked.',
      sig: 'def fizzbuzz(n: int) -> list[str]',
      starter: 'def fizzbuzz(n):\n    # your code here\n    pass\n',
      examples: [
        { in: 'fizzbuzz(5)', out: "['1', '2', 'Fizz', '4', 'Buzz']" }],
      tests: [
        { call: 'fizzbuzz(5)', expect: "['1', '2', 'Fizz', '4', 'Buzz']" },
        { call: 'fizzbuzz(15)[-1]', expect: "'FizzBuzz'", name: '15 is both' },
        { call: 'len(fizzbuzz(100))', expect: '100' },
        { call: 'fizzbuzz(0)', expect: '[]', hidden: true, name: 'n = 0' },
        { call: 'fizzbuzz(3)', expect: "['1', '2', 'Fizz']", hidden: true }],
      hint: 'Test the both-case first, or build the word by concatenation and fall back to str(i) when it is empty.',
      solution: "def fizzbuzz(n):\n    out = []\n    for i in range(1, n + 1):\n        word = ''\n        if i % 3 == 0:\n            word += 'Fizz'\n        if i % 5 == 0:\n            word += 'Buzz'\n        out.append(word or str(i))\n    return out\n",
      walk: "Building the word by concatenation avoids the classic bug of checking 3 and 5 before checking 15. `word or str(i)` leans on the empty string being falsy. Note range(1, n + 1) — the numbers are 1-based, and n = 0 then produces an empty list for free.",
      complexity: 'O(n) time and space.' },

    { id: 'pt-two-sum', group: 'Arrays & hashing', lvl: 2,
      title: 'Two sum',
      fn: 'two_sum',
      brief: 'Given a list of numbers and a target, return the positions of the two numbers that add up to the target, smallest position first.\n\nExactly one pair will work, and you may not use the same element twice. Aim for a single pass.',
      sig: 'def two_sum(nums: list[int], target: int) -> list[int]',
      starter: 'def two_sum(nums, target):\n    # your code here\n    pass\n',
      examples: [
        { in: 'two_sum([2, 7, 11, 15], 9)', out: '[0, 1]', note: '2 + 7 = 9' },
        { in: 'two_sum([3, 2, 4], 6)', out: '[1, 2]' }],
      tests: [
        { call: 'two_sum([2, 7, 11, 15], 9)', expect: '[0, 1]' },
        { call: 'two_sum([3, 2, 4], 6)', expect: '[1, 2]' },
        { call: 'two_sum([3, 3], 6)', expect: '[0, 1]', name: 'repeated value' },
        { call: 'two_sum([-1, -2, -3, -4], -6)', expect: '[1, 3]', hidden: true, name: 'negatives' },
        { call: 'two_sum(list(range(10000)) + [99999], 100002)', expect: '[3, 10000]', hidden: true, name: 'must be fast' }],
      hint: 'As you walk the list, ask "have I already seen the number that would complete this pair?" A dict of value → index answers that in O(1).',
      solution: 'def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        need = target - n\n        if need in seen:\n            return [seen[need], i]\n        seen[n] = i\n    return []\n',
      walk: 'The nested-loop version is O(n²) and the hidden speed test will time it out. Instead, store each number you pass in a dict against its index; before storing, check whether the number you NEED has already gone by. Checking before storing is what stops an element pairing with itself.',
      complexity: 'O(n) time, O(n) space — the classic trade of memory for speed.' },

    { id: 'pt-first-unique', group: 'Arrays & hashing', lvl: 2,
      title: 'First non-repeating character',
      fn: 'first_unique',
      brief: 'Return the first character in a string that appears exactly once.\n\nIf every character repeats, return None.',
      sig: 'def first_unique(s: str) -> str | None',
      starter: 'def first_unique(s):\n    # your code here\n    pass\n',
      examples: [
        { in: "first_unique('swiss')", out: "'w'" },
        { in: "first_unique('aabb')", out: 'None' }],
      tests: [
        { call: "first_unique('swiss')", expect: "'w'" },
        { call: "first_unique('aabb')", expect: 'None' },
        { call: "first_unique('leetcode')", expect: "'l'" },
        { call: "first_unique('')", expect: 'None', hidden: true },
        { call: "first_unique('aabbc')", expect: "'c'", hidden: true, name: 'last character' }],
      hint: 'Two passes: count everything first, then walk the string again in order and return the first character with a count of 1.',
      solution: "from collections import Counter\n\ndef first_unique(s):\n    counts = Counter(s)\n    for ch in s:\n        if counts[ch] == 1:\n            return ch\n    return None\n",
      walk: 'The order matters, so a set of seen characters is not enough — you need the counts. Count in one pass, then walk the original string (not the counter) so you keep the original order. Returning None explicitly beats falling off the end of the function, even though Python does it for you.',
      complexity: 'O(n) time, O(k) space for k distinct characters.' },

    { id: 'pt-anagram', group: 'Arrays & hashing', lvl: 1,
      title: 'Valid anagram',
      fn: 'is_anagram',
      brief: 'Return True if two strings are anagrams of each other — the same letters, rearranged.\n\nCase-insensitive; ignore spaces.',
      sig: 'def is_anagram(a: str, b: str) -> bool',
      starter: 'def is_anagram(a, b):\n    # your code here\n    pass\n',
      examples: [
        { in: "is_anagram('listen', 'silent')", out: 'True' },
        { in: "is_anagram('hello', 'world')", out: 'False' }],
      tests: [
        { call: "is_anagram('listen', 'silent')", expect: 'True' },
        { call: "is_anagram('hello', 'world')", expect: 'False' },
        { call: "is_anagram('Dormitory', 'Dirty Room')", expect: 'True', name: 'case and spaces' },
        { call: "is_anagram('a', 'aa')", expect: 'False', hidden: true, name: 'different lengths' },
        { call: "is_anagram('', '')", expect: 'True', hidden: true }],
      hint: 'Normalise both strings the same way first — lowercase, spaces removed — then compare sorted letters or letter counts.',
      solution: "def is_anagram(a, b):\n    def norm(s):\n        return sorted(s.lower().replace(' ', ''))\n    return norm(a) == norm(b)\n",
      walk: 'Do the normalising in one small helper so both strings get treated identically — that is where these answers usually go wrong. sorted() gives O(n log n); Counter() would give O(n) and is equally acceptable in an interview. Different lengths fall out automatically: the sorted lists cannot match.',
      complexity: 'O(n log n) with sorting, O(n) with a Counter.' },

    { id: 'pt-max-consecutive', group: 'Arrays & hashing', lvl: 2,
      title: 'Longest run of the same value',
      fn: 'longest_run',
      brief: 'Given a list, return the length of the longest run of identical values sitting next to each other.\n\nAn empty list has a longest run of 0.',
      sig: 'def longest_run(items: list) -> int',
      starter: 'def longest_run(items):\n    # your code here\n    pass\n',
      examples: [
        { in: 'longest_run([1, 1, 2, 2, 2, 3])', out: '3' },
        { in: "longest_run(['a', 'b', 'a'])", out: '1' }],
      tests: [
        { call: 'longest_run([1, 1, 2, 2, 2, 3])', expect: '3' },
        { call: "longest_run(['a', 'b', 'a'])", expect: '1' },
        { call: 'longest_run([])', expect: '0' },
        { call: 'longest_run([5])', expect: '1', hidden: true },
        { call: 'longest_run([7, 7, 7, 7])', expect: '4', hidden: true, name: 'all the same' }],
      hint: 'Keep two counters: the current run and the best run so far. Reset the current one whenever the value changes.',
      solution: 'def longest_run(items):\n    best = current = 0\n    previous = object()\n    for item in items:\n        current = current + 1 if item == previous else 1\n        best = max(best, current)\n        previous = item\n    return best\n',
      walk: 'The subtle part is the starting value of `previous`: using None would break on a list that genuinely contains None. A fresh object() can never equal anything else, so the first comparison is always False. Update `best` inside the loop, not after it, or a run that ends at the last element gets missed.',
      complexity: 'O(n) time, O(1) space.' },

    { id: 'pt-word-count', group: 'Text handling', lvl: 2,
      title: 'Word frequencies',
      fn: 'word_count',
      brief: 'Count how often each word appears in a piece of text.\n\nLowercase everything, ignore punctuation, and return a plain dict of word → count.',
      sig: 'def word_count(text: str) -> dict[str, int]',
      starter: 'def word_count(text):\n    # your code here\n    pass\n',
      examples: [
        { in: "word_count('the cat the dog')", out: "{'the': 2, 'cat': 1, 'dog': 1}" },
        { in: "word_count('Hello, hello!')", out: "{'hello': 2}", note: 'punctuation ignored' }],
      tests: [
        { call: "word_count('the cat the dog')", expect: "{'the': 2, 'cat': 1, 'dog': 1}" },
        { call: "word_count('Hello, hello!')", expect: "{'hello': 2}" },
        { call: "word_count('')", expect: '{}' },
        { call: "word_count('One. Two, one; TWO!')", expect: "{'one': 2, 'two': 2}", hidden: true },
        { call: "word_count('a-b a b')['a']", expect: '2', hidden: true, name: 'hyphen splits' }],
      hint: 'A regex like re.findall(r"[a-z]+", text.lower()) pulls out the words and drops the punctuation in one step.',
      solution: "import re\nfrom collections import Counter\n\ndef word_count(text):\n    words = re.findall(r'[a-z0-9]+', text.lower())\n    return dict(Counter(words))\n",
      walk: "Splitting on spaces leaves 'hello,' and 'hello' as different words, so strip the punctuation first — findall of letter runs is the cleanest way. Counter does the tallying; dict() converts it back because the brief asked for a plain dict, and a Counter compares equal to one anyway.",
      complexity: 'O(n) time and space.' },

    { id: 'pt-palindrome', group: 'Text handling', lvl: 1,
      title: 'Palindrome check',
      fn: 'is_palindrome',
      brief: 'Return True if a string reads the same forwards and backwards.\n\nIgnore case, spaces and punctuation — only letters and digits count.',
      sig: 'def is_palindrome(s: str) -> bool',
      starter: 'def is_palindrome(s):\n    # your code here\n    pass\n',
      examples: [
        { in: "is_palindrome('A man, a plan, a canal: Panama')", out: 'True' },
        { in: "is_palindrome('hello')", out: 'False' }],
      tests: [
        { call: "is_palindrome('A man, a plan, a canal: Panama')", expect: 'True' },
        { call: "is_palindrome('hello')", expect: 'False' },
        { call: "is_palindrome('')", expect: 'True', name: 'empty is a palindrome' },
        { call: "is_palindrome('ab@ba')", expect: 'True', hidden: true },
        { call: "is_palindrome('0P')", expect: 'False', hidden: true, name: 'case matters after cleaning' }],
      hint: 'Clean the string down to lowercase letters and digits, then compare it with its reverse.',
      solution: "def is_palindrome(s):\n    cleaned = [ch for ch in s.lower() if ch.isalnum()]\n    return cleaned == cleaned[::-1]\n",
      walk: "isalnum() keeps letters and digits and drops everything else, which is exactly the brief. Comparing a list with its reversed copy is O(n) space; the two-pointer version walks in from both ends in O(1) space and is worth mentioning out loud in an interview.",
      complexity: 'O(n) time, O(n) space (O(1) with two pointers).' },

    { id: 'pt-title-case', group: 'Text handling', lvl: 2,
      title: 'Capitalise each word',
      fn: 'title_case',
      brief: 'Capitalise the first letter of every word and lowercase the rest, keeping single spaces between words.\n\nYou may not use the built-in str.title().',
      sig: 'def title_case(s: str) -> str',
      starter: 'def title_case(s):\n    # your code here\n    pass\n',
      examples: [
        { in: "title_case('hello WORLD')", out: "'Hello World'" }],
      tests: [
        { call: "title_case('hello WORLD')", expect: "'Hello World'" },
        { call: "title_case('a')", expect: "'A'" },
        { call: "title_case('')", expect: "''" },
        { call: "title_case('  spaced   out  ')", expect: "'Spaced Out'", hidden: true },
        { call: "title_case('mcdonald and o brien')", expect: "'Mcdonald And O Brien'", hidden: true }],
      hint: 'word[0].upper() + word[1:].lower() handles one word. Do that for each word from split().',
      solution: "def title_case(s):\n    return ' '.join(w[0].upper() + w[1:].lower() for w in s.split())\n",
      walk: "split() with no argument collapses the messy spacing for you. w[1:] on a one-character word is the empty string rather than an error, so single letters need no special case — that is the detail this question is really testing.",
      complexity: 'O(n) time and space.' },

    { id: 'pt-fib', group: 'Algorithms', lvl: 2,
      title: 'Fibonacci, quickly',
      fn: 'fib',
      brief: 'Return the nth Fibonacci number, with fib(0) = 0 and fib(1) = 1.\n\nIt must answer fib(60) instantly — a plain recursion will not.',
      sig: 'def fib(n: int) -> int',
      starter: 'def fib(n):\n    # your code here\n    pass\n',
      examples: [
        { in: 'fib(0)', out: '0' },
        { in: 'fib(10)', out: '55' }],
      tests: [
        { call: 'fib(0)', expect: '0' },
        { call: 'fib(1)', expect: '1' },
        { call: 'fib(10)', expect: '55' },
        { call: 'fib(60)', expect: '1548008755920', hidden: true, name: 'must be fast' },
        { call: 'fib(2)', expect: '1', hidden: true }],
      hint: 'You only ever need the last two values. Two variables and a loop, or memoise the recursion with @lru_cache.',
      solution: 'def fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n',
      walk: 'The naive recursion recomputes the same values exponentially often — fib(60) would take longer than the test allows. Iterating keeps only the last two numbers, in O(n) time and constant space. The tuple assignment a, b = b, a + b updates both at once, using the OLD a on the right-hand side.',
      complexity: 'O(n) time, O(1) space.' },

    { id: 'pt-binary-search', group: 'Algorithms', lvl: 2,
      title: 'Binary search',
      fn: 'search',
      brief: 'Given a list sorted smallest-first, return the index of the target, or -1 if it is not there.\n\nIt must be O(log n) — the hidden test uses a list of a million numbers.',
      sig: 'def search(nums: list[int], target: int) -> int',
      starter: 'def search(nums, target):\n    # your code here\n    pass\n',
      examples: [
        { in: 'search([1, 3, 5, 7, 9], 7)', out: '3' },
        { in: 'search([1, 3, 5], 4)', out: '-1' }],
      tests: [
        { call: 'search([1, 3, 5, 7, 9], 7)', expect: '3' },
        { call: 'search([1, 3, 5], 4)', expect: '-1' },
        { call: 'search([], 1)', expect: '-1', name: 'empty list' },
        { call: 'search([5], 5)', expect: '0', hidden: true },
        { call: 'search(list(range(1000000)), 999999)', expect: '999999', hidden: true, name: 'a million items' }],
      hint: 'Keep low and high pointers. Look at the middle, then throw half of what is left away.',
      solution: 'def search(nums, target):\n    low, high = 0, len(nums) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1\n',
      walk: 'Two details decide whether this works: `while low <= high` (not <), so a single remaining element still gets checked; and moving to mid + 1 / mid - 1 rather than mid, so the range always shrinks and the loop cannot hang. Integer division keeps mid an index.',
      complexity: 'O(log n) time, O(1) space.' },

    { id: 'pt-merge-sorted', group: 'Algorithms', lvl: 3,
      title: 'Merge two sorted lists',
      fn: 'merge',
      brief: 'Given two lists that are each already sorted smallest-first, return one sorted list holding everything from both.\n\nDo it in one pass — sorting the concatenation is not the answer being looked for.',
      sig: 'def merge(a: list[int], b: list[int]) -> list[int]',
      starter: 'def merge(a, b):\n    # your code here\n    pass\n',
      examples: [
        { in: 'merge([1, 3, 5], [2, 4])', out: '[1, 2, 3, 4, 5]' }],
      tests: [
        { call: 'merge([1, 3, 5], [2, 4])', expect: '[1, 2, 3, 4, 5]' },
        { call: 'merge([], [1, 2])', expect: '[1, 2]' },
        { call: 'merge([1], [])', expect: '[1]' },
        { call: 'merge([1, 1], [1])', expect: '[1, 1, 1]', hidden: true, name: 'duplicates' },
        { call: 'merge([1, 2, 3], [4, 5, 6])', expect: '[1, 2, 3, 4, 5, 6]', hidden: true, name: 'no interleaving' }],
      hint: 'Walk both lists with an index each, always taking the smaller head. When one runs out, extend with the rest of the other.',
      solution: 'def merge(a, b):\n    out = []\n    i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            out.append(a[i])\n            i += 1\n        else:\n            out.append(b[j])\n            j += 1\n    out.extend(a[i:])\n    out.extend(b[j:])\n    return out\n',
      walk: 'This is the merge step of merge sort. The two extends at the end are what handle the leftovers — a slice past the end of a list is simply empty, so no special cases are needed. Using <= rather than < keeps equal values in their original relative order (a stable merge).',
      complexity: 'O(n + m) time, O(n + m) space.' },

    { id: 'pt-group-anagrams', group: 'Algorithms', lvl: 3,
      title: 'Group the anagrams',
      fn: 'group_anagrams',
      brief: 'Given a list of words, group them so that words made of the same letters sit together.\n\nReturn a list of groups. The order of the groups, and of words inside a group, does not matter.',
      sig: 'def group_anagrams(words: list[str]) -> list[list[str]]',
      starter: 'def group_anagrams(words):\n    # your code here\n    pass\n',
      examples: [
        { in: "group_anagrams(['eat', 'tea', 'tan', 'ate'])", out: "[['eat', 'tea', 'ate'], ['tan']]" }],
      unordered: true,
      tests: [
        { call: "sorted([sorted(g) for g in group_anagrams(['eat','tea','tan','ate','nat','bat'])])", expect: "[['ate','eat','tea'], ['bat'], ['nat','tan']]" },
        { call: 'group_anagrams([])', expect: '[]' },
        { call: "sorted([sorted(g) for g in group_anagrams(['a'])])", expect: "[['a']]", hidden: true },
        { call: "len(group_anagrams(['abc','cba','bac','xyz']))", expect: '2', hidden: true }],
      hint: 'Anagrams share a signature: their sorted letters. Use that as a dict key.',
      solution: "from collections import defaultdict\n\ndef group_anagrams(words):\n    groups = defaultdict(list)\n    for w in words:\n        groups[''.join(sorted(w))].append(w)\n    return list(groups.values())\n",
      walk: "The whole problem is choosing the key. Sorted letters give every anagram the same signature; a tuple of 26 letter counts would too, and is O(n) per word rather than O(n log n). defaultdict(list) saves the 'create the list if missing' dance.",
      complexity: 'O(n · k log k) for n words of length k.' },

    { id: 'pt-moving-average', group: 'Algorithms', lvl: 3,
      title: 'Moving average',
      fn: 'moving_average',
      brief: 'Return the k-period moving average of a list of numbers.\n\nThe result is shorter than the input: one value for each full window. If the list is shorter than k, return an empty list.',
      sig: 'def moving_average(nums: list[float], k: int) -> list[float]',
      starter: 'def moving_average(nums, k):\n    # your code here\n    pass\n',
      examples: [
        { in: 'moving_average([1, 2, 3, 4], 2)', out: '[1.5, 2.5, 3.5]' }],
      tests: [
        { call: 'moving_average([1, 2, 3, 4], 2)', expect: '[1.5, 2.5, 3.5]' },
        { call: 'moving_average([1, 2], 3)', expect: '[]', name: 'window bigger than the list' },
        { call: 'moving_average([2, 2, 2], 3)', expect: '[2.0]' },
        { call: 'moving_average([], 2)', expect: '[]', hidden: true },
        { call: 'len(moving_average(list(range(1000)), 10))', expect: '991', hidden: true, name: 'length is n - k + 1' }],
      hint: 'There are len(nums) - k + 1 windows. Either slice each one, or keep a running total and slide it.',
      solution: 'def moving_average(nums, k):\n    if k <= 0 or len(nums) < k:\n        return []\n    total = sum(nums[:k])\n    out = [total / k]\n    for i in range(k, len(nums)):\n        total += nums[i] - nums[i - k]\n        out.append(total / k)\n    return out\n',
      walk: 'The sliding total is the point of the question: add the value entering the window, subtract the one leaving, and you get O(n) instead of O(n·k). Guard the short-list case first — range() would quietly produce nothing, but sum(nums[:k]) / k would divide by zero if k were 0.',
      complexity: 'O(n) time with a sliding sum, O(n) space for the output.' },

    { id: 'pt-flatten', group: 'Algorithms', lvl: 3,
      title: 'Flatten a nested list',
      fn: 'flatten',
      brief: 'Flatten a list that may contain other lists, to any depth, into a single flat list.\n\nKeep the original left-to-right order.',
      sig: 'def flatten(items: list) -> list',
      starter: 'def flatten(items):\n    # your code here\n    pass\n',
      examples: [
        { in: 'flatten([1, [2, [3, 4]], 5])', out: '[1, 2, 3, 4, 5]' }],
      tests: [
        { call: 'flatten([1, [2, [3, 4]], 5])', expect: '[1, 2, 3, 4, 5]' },
        { call: 'flatten([])', expect: '[]' },
        { call: 'flatten([[[[1]]]])', expect: '[1]', name: 'deeply nested' },
        { call: 'flatten([1, [], 2])', expect: '[1, 2]', hidden: true, name: 'empty inner list' },
        { call: "flatten(['a', ['b']])", expect: "['a', 'b']", hidden: true, name: 'strings are not lists here' }],
      hint: 'Recursion: for each item, either extend with the flattened sublist or append the item itself.',
      solution: 'def flatten(items):\n    out = []\n    for item in items:\n        if isinstance(item, list):\n            out.extend(flatten(item))\n        else:\n            out.append(item)\n    return out\n',
      walk: "isinstance(item, list) is the decision, and it is why strings survive intact — a string is iterable but not a list, so it gets appended whole. Recursing on the sublist and extending with the result keeps the order. An explicit stack would do the same job without recursion depth limits.",
      complexity: 'O(n) in the total number of elements.' },

    { id: 'pt-roman', group: 'Algorithms', lvl: 3,
      title: 'Roman numerals to integer',
      fn: 'roman_to_int',
      brief: 'Convert a Roman numeral string to a number.\n\nThe values are I=1, V=5, X=10, L=50, C=100, D=500, M=1000. A smaller value before a larger one is subtracted: IV is 4, IX is 9, CM is 900.',
      sig: 'def roman_to_int(s: str) -> int',
      starter: 'def roman_to_int(s):\n    # your code here\n    pass\n',
      examples: [
        { in: "roman_to_int('III')", out: '3' },
        { in: "roman_to_int('MCMXCIV')", out: '1994', note: 'M + CM + XC + IV' }],
      tests: [
        { call: "roman_to_int('III')", expect: '3' },
        { call: "roman_to_int('IV')", expect: '4' },
        { call: "roman_to_int('MCMXCIV')", expect: '1994' },
        { call: "roman_to_int('LVIII')", expect: '58', hidden: true },
        { call: "roman_to_int('MMMCMXCIX')", expect: '3999', hidden: true, name: 'the largest' }],
      hint: 'Walk left to right. If this numeral is worth less than the next one, subtract it instead of adding it.',
      solution: "def roman_to_int(s):\n    values = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}\n    total = 0\n    for i, ch in enumerate(s):\n        if i + 1 < len(s) and values[ch] < values[s[i + 1]]:\n            total -= values[ch]\n        else:\n            total += values[ch]\n    return total\n",
      walk: 'Rather than special-casing the six subtractive pairs, notice the single rule underneath them: a numeral smaller than the one after it is subtracted. The bounds check `i + 1 < len(s)` keeps the last character safe.',
      complexity: 'O(n) time, O(1) space.' }
  );
})();
