/* Coding problems, one tiny step at a time — part 1: numbers and text.
   Each problem changes ONE thing from the one before it. If you can do the last
   one, you can do the next one; the only question is whether you can type it. */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var G = 'One step at a time';

  function P(id, title, fn, brief, sig, starter, examples, tests, hint, solution, walk) {
    window.PYTESTS.push({ id: id, group: G, lvl: 1, title: title, fn: fn, brief: brief, sig: sig,
      starter: starter, examples: examples, tests: tests, hint: hint, solution: solution, walk: walk,
      complexity: 'O(1) unless it loops — and most of these do not.' });
  }

  P('st-give-five', 'Give back five', 'five',
    'Write a function called five that takes nothing and gives back the number 5.',
    'def five() -> int',
    'def five():\n    # your code here\n    pass\n',
    [{ in: 'five()', out: '5' }],
    [{ call: 'five()', expect: '5' },
     { call: 'five() + 1', expect: '6', name: 'it really is a number' },
     { call: 'five() * 2', expect: '10' },
     { call: 'type(five()).__name__', expect: "'int'", hidden: true, name: 'a number, not text' },
     { call: 'five() == 5', expect: 'True', hidden: true }],
    'return 5 — that is the whole body.',
    'def five():\n    return 5\n',
    'The smallest possible function, and the one everything else is built on: a def line, and a return. Note that `print(5)` would NOT pass — printing shows something on the screen, returning hands the value back to whoever called you.');

  P('st-give-back', 'Give back what you were given', 'same',
    'Write a function called same that takes one number and gives back that same number.',
    'def same(n: int) -> int',
    'def same(n):\n    # your code here\n    pass\n',
    [{ in: 'same(7)', out: '7' }],
    [{ call: 'same(7)', expect: '7' },
     { call: 'same(0)', expect: '0' },
     { call: 'same(-3)', expect: '-3', name: 'negatives too' },
     { call: 'same(1000)', expect: '1000', hidden: true },
     { call: 'same(2) + same(3)', expect: '5', hidden: true }],
    'The value arrives in n. Give n back.',
    'def same(n):\n    return n\n',
    'One inch further than the last one: the number now comes IN through the brackets. Whatever the caller puts in n, you hand straight back.');

  P('st-add-one', 'One more', 'add_one',
    'Write a function called add_one that takes a number and gives back that number plus 1.',
    'def add_one(n: int) -> int',
    'def add_one(n):\n    # your code here\n    pass\n',
    [{ in: 'add_one(7)', out: '8' }],
    [{ call: 'add_one(7)', expect: '8' },
     { call: 'add_one(0)', expect: '1' },
     { call: 'add_one(-1)', expect: '0', name: 'minus one plus one is zero' },
     { call: 'add_one(99)', expect: '100', hidden: true },
     { call: 'add_one(add_one(1))', expect: '3', hidden: true, name: 'called twice' }],
    'return n + 1',
    'def add_one(n):\n    return n + 1\n',
    'The same shape again, with one small sum added before the value goes back. Everything after this is variations on "do something to n, then return it".');

  P('st-add-ten', 'Ten more', 'add_ten',
    'Write a function called add_ten that takes a number and gives back that number plus 10.',
    'def add_ten(n: int) -> int',
    'def add_ten(n):\n    # your code here\n    pass\n',
    [{ in: 'add_ten(7)', out: '17' }],
    [{ call: 'add_ten(7)', expect: '17' },
     { call: 'add_ten(0)', expect: '10' },
     { call: 'add_ten(-10)', expect: '0' },
     { call: 'add_ten(90)', expect: '100', hidden: true },
     { call: 'add_ten(0.5)', expect: '10.5', hidden: true, name: 'decimals work too' }],
    'Exactly the last one, with 10 instead of 1.',
    'def add_ten(n):\n    return n + 10\n',
    'Deliberately almost identical to the last problem. The point is that changing WHAT you do is a one-character edit once the shape is automatic.');

  P('st-double-it', 'Twice as much', 'double',
    'Write a function called double that takes a number and gives back twice that number.',
    'def double(n: int) -> int',
    'def double(n):\n    # your code here\n    pass\n',
    [{ in: 'double(7)', out: '14' }],
    [{ call: 'double(7)', expect: '14' },
     { call: 'double(0)', expect: '0' },
     { call: 'double(-3)', expect: '-6' },
     { call: 'double(2.5)', expect: '5.0', hidden: true },
     { call: 'double(double(3))', expect: '12', hidden: true }],
    'Multiply by 2 with the * sign.',
    'def double(n):\n    return n * 2\n',
    'Plus became times. `n + n` also works and is worth noticing — there is usually more than one right answer, and neither is cleverer than the other.');

  P('st-add-two-nums', 'Add the two numbers', 'add',
    'Write a function called add that takes TWO numbers and gives back their total.',
    'def add(a: int, b: int) -> int',
    'def add(a, b):\n    # your code here\n    pass\n',
    [{ in: 'add(2, 3)', out: '5' }],
    [{ call: 'add(2, 3)', expect: '5' },
     { call: 'add(0, 0)', expect: '0' },
     { call: 'add(-2, 2)', expect: '0', name: 'they cancel out' },
     { call: 'add(10, 90)', expect: '100', hidden: true },
     { call: 'add(1.5, 2.5)', expect: '4.0', hidden: true }],
    'Two names in the brackets, separated by a comma. return a + b.',
    'def add(a, b):\n    return a + b\n',
    'The step here is TWO parameters instead of one. They arrive in the order they were written, so add(2, 3) puts 2 into a and 3 into b.');

  P('st-subtract', 'Take one away from the other', 'subtract',
    'Write a function called subtract that takes two numbers and gives back the first take away the second.',
    'def subtract(a: int, b: int) -> int',
    'def subtract(a, b):\n    # your code here\n    pass\n',
    [{ in: 'subtract(5, 2)', out: '3' }],
    [{ call: 'subtract(5, 2)', expect: '3' },
     { call: 'subtract(2, 5)', expect: '-3', name: 'the order matters' },
     { call: 'subtract(0, 0)', expect: '0' },
     { call: 'subtract(10, 10)', expect: '0', hidden: true },
     { call: 'subtract(-5, -5)', expect: '0', hidden: true }],
    'return a - b, in that order.',
    'def subtract(a, b):\n    return a - b\n',
    'One character different from the last problem — and one test that fails if you write it the other way round. Order matters as soon as the operation is not symmetrical.');

  P('st-multiply', 'Times the two numbers', 'multiply',
    'Write a function called multiply that takes two numbers and gives back them multiplied together.',
    'def multiply(a: int, b: int) -> int',
    'def multiply(a, b):\n    # your code here\n    pass\n',
    [{ in: 'multiply(3, 4)', out: '12' }],
    [{ call: 'multiply(3, 4)', expect: '12' },
     { call: 'multiply(5, 0)', expect: '0', name: 'anything times zero' },
     { call: 'multiply(-2, 3)', expect: '-6' },
     { call: 'multiply(1, 99)', expect: '99', hidden: true },
     { call: 'multiply(2.5, 4)', expect: '10.0', hidden: true }],
    'The times sign in Python is *.',
    'def multiply(a, b):\n    return a * b\n',
    'Same shape, third operator. By now the def/return frame should be costing you no thought at all — which is the entire purpose of doing it four times.');

  P('st-area', 'Area of a rectangle, in a function', 'area',
    'Write a function called area that takes a width and a height and gives back the area — width times height.',
    'def area(width: float, height: float) -> float',
    'def area(width, height):\n    # your code here\n    pass\n',
    [{ in: 'area(3, 4)', out: '12' }],
    [{ call: 'area(3, 4)', expect: '12' },
     { call: 'area(1, 1)', expect: '1' },
     { call: 'area(0, 5)', expect: '0', name: 'no width, no area' },
     { call: 'area(2.5, 4)', expect: '10.0', hidden: true },
     { call: 'area(10, 10)', expect: '100', hidden: true }],
    'Exactly multiply, with the parameters renamed.',
    'def area(width, height):\n    return width * height\n',
    'The same code as the last problem with better names. That is a real lesson: `width` and `height` tell the next reader what the numbers mean, and cost nothing.');

  P('st-average-two', 'The average of two numbers', 'average_two',
    'Write a function called average_two that takes two numbers and gives back their average.\n\nThe answer may have a decimal part.',
    'def average_two(a: float, b: float) -> float',
    'def average_two(a, b):\n    # your code here\n    pass\n',
    [{ in: 'average_two(2, 4)', out: '3.0' }],
    [{ call: 'average_two(2, 4)', expect: '3.0' },
     { call: 'average_two(5, 5)', expect: '5.0' },
     { call: 'average_two(0, 1)', expect: '0.5', name: 'the answer is not always whole' },
     { call: 'average_two(-2, 2)', expect: '0.0', hidden: true },
     { call: 'average_two(1, 2)', expect: '1.5', hidden: true }],
    'Add them, then divide by 2 — and mind the brackets.',
    'def average_two(a, b):\n    return (a + b) / 2\n',
    'The new thing is the brackets. Without them, `a + b / 2` divides only b, because times and divide happen before plus and minus. Division always gives a decimal in Python, which is why the answers show as 3.0 rather than 3.');

  P('st-remainder', 'What is left over', 'remainder',
    'Write a function called remainder that takes two numbers and gives back what is left when the first is divided by the second.',
    'def remainder(a: int, b: int) -> int',
    'def remainder(a, b):\n    # your code here\n    pass\n',
    [{ in: 'remainder(7, 2)', out: '1' }],
    [{ call: 'remainder(7, 2)', expect: '1' },
     { call: 'remainder(10, 5)', expect: '0', name: 'it divided exactly' },
     { call: 'remainder(9, 4)', expect: '1' },
     { call: 'remainder(3, 10)', expect: '3', hidden: true, name: 'it does not go in at all' },
     { call: 'remainder(100, 7)', expect: '2', hidden: true }],
    'The percent sign gives the remainder.',
    'def remainder(a, b):\n    return a % b\n',
    'One new operator: %. A remainder of 0 means it divided exactly, which is how every "is it even" and "every third one" test is written.');

  P('st-is-even', 'Even or not', 'is_even',
    'Write a function called is_even that takes a whole number and gives back True if it is even and False if it is not.',
    'def is_even(n: int) -> bool',
    'def is_even(n):\n    # your code here\n    pass\n',
    [{ in: 'is_even(4)', out: 'True' }],
    [{ call: 'is_even(4)', expect: 'True' },
     { call: 'is_even(7)', expect: 'False' },
     { call: 'is_even(0)', expect: 'True', name: 'zero is even' },
     { call: 'is_even(-2)', expect: 'True', hidden: true, name: 'negatives count too' },
     { call: 'is_even(1001)', expect: 'False', hidden: true }],
    'A number is even when the remainder after dividing by 2 is 0.',
    'def is_even(n):\n    return n % 2 == 0\n',
    'Straight on from the last problem: take the remainder, then compare it to 0. The comparison IS the True or False — no if needed. Writing `if n % 2 == 0: return True else: return False` gives the same answer four times as long.');

  P('st-is-positive', 'Above zero', 'is_positive',
    'Write a function called is_positive that gives back True when the number is above zero, and False otherwise.\n\nZero itself is not positive.',
    'def is_positive(n: float) -> bool',
    'def is_positive(n):\n    # your code here\n    pass\n',
    [{ in: 'is_positive(3)', out: 'True' }],
    [{ call: 'is_positive(3)', expect: 'True' },
     { call: 'is_positive(-3)', expect: 'False' },
     { call: 'is_positive(0)', expect: 'False', name: 'zero is not above zero' },
     { call: 'is_positive(0.1)', expect: 'True', hidden: true },
     { call: 'is_positive(-0.1)', expect: 'False', hidden: true }],
    'return n > 0',
    'def is_positive(n):\n    return n > 0\n',
    'The same idea as is_even with a different comparison. The zero test is the one that catches people who write >= without thinking.');

  P('st-bigger-of-two', 'Whichever is bigger', 'bigger',
    'Write a function called bigger that takes two numbers and gives back the larger one.\n\nIf they are equal, give back either.',
    'def bigger(a: float, b: float) -> float',
    'def bigger(a, b):\n    # your code here\n    pass\n',
    [{ in: 'bigger(3, 7)', out: '7' }],
    [{ call: 'bigger(3, 7)', expect: '7' },
     { call: 'bigger(7, 3)', expect: '7', name: 'either way round' },
     { call: 'bigger(5, 5)', expect: '5' },
     { call: 'bigger(-1, -9)', expect: '-1', hidden: true, name: 'both negative' },
     { call: 'bigger(0, -1)', expect: '0', hidden: true }],
    'max(a, b) does it in one go — or an if that returns a when a is bigger.',
    'def bigger(a, b):\n    return max(a, b)\n',
    'Two right answers: `max(a, b)`, or `if a > b: return a` followed by `return b`. Both are fine. The negative test is there because "start from 0 and compare" would get it wrong.');

  P('st-shout-text', 'Say it louder', 'shout',
    'Write a function called shout that takes some text and gives it back in CAPITALS.',
    'def shout(text: str) -> str',
    'def shout(text):\n    # your code here\n    pass\n',
    [{ in: "shout('hello')", out: "'HELLO'" }],
    [{ call: "shout('hello')", expect: "'HELLO'" },
     { call: "shout('Ann')", expect: "'ANN'" },
     { call: "shout('')", expect: "''", name: 'empty text stays empty' },
     { call: "shout('hello there')", expect: "'HELLO THERE'", hidden: true },
     { call: "shout('abc123')", expect: "'ABC123'", hidden: true, name: 'digits are left alone' }],
    'Text can do things to itself: text.upper()',
    'def shout(text):\n    return text.upper()\n',
    'The first problem where the value coming in is text rather than a number. `.upper()` gives back a NEW piece of text — it does not change the original, because text in Python can never be changed in place.');

  P('st-whisper-text', 'Say it quietly', 'whisper',
    'Write a function called whisper that takes some text and gives it back in lower case.',
    'def whisper(text: str) -> str',
    'def whisper(text):\n    # your code here\n    pass\n',
    [{ in: "whisper('HELLO')", out: "'hello'" }],
    [{ call: "whisper('HELLO')", expect: "'hello'" },
     { call: "whisper('Ann')", expect: "'ann'" },
     { call: "whisper('')", expect: "''" },
     { call: "whisper('MiXeD')", expect: "'mixed'", hidden: true },
     { call: "whisper('ABC 123')", expect: "'abc 123'", hidden: true }],
    'The opposite method to the last one.',
    'def whisper(text):\n    return text.lower()\n',
    'Deliberately the same problem with one word changed. Lower-casing is what you do before comparing anything a person typed, so this line will come up again and again.');

  P('st-text-length', 'How long is it', 'length',
    'Write a function called length that takes some text and gives back how many characters it has.\n\nSpaces count.',
    'def length(text: str) -> int',
    'def length(text):\n    # your code here\n    pass\n',
    [{ in: "length('hello')", out: '5' }],
    [{ call: "length('hello')", expect: '5' },
     { call: "length('')", expect: '0', name: 'nothing is zero long' },
     { call: "length('a b')", expect: '3', name: 'the space counts' },
     { call: "length('  ')", expect: '2', hidden: true },
     { call: "length('hello there')", expect: '11', hidden: true }],
    'len(text) counts the characters.',
    'def length(text):\n    return len(text)\n',
    'len() is a function you call ON something, rather than a method the thing has. It counts characters in text, and items in a list — the same word for both, which is why it is worth meeting early.');

  P('st-first-letter', 'The first letter', 'first_letter',
    'Write a function called first_letter that gives back the first character of some text.\n\nYou can assume the text is never empty.',
    'def first_letter(text: str) -> str',
    'def first_letter(text):\n    # your code here\n    pass\n',
    [{ in: "first_letter('hello')", out: "'h'" }],
    [{ call: "first_letter('hello')", expect: "'h'" },
     { call: "first_letter('Ann')", expect: "'A'" },
     { call: "first_letter('x')", expect: "'x'", name: 'one character' },
     { call: "first_letter(' space first')", expect: "' '", hidden: true, name: 'a space is a character' },
     { call: "first_letter('123')", expect: "'1'", hidden: true }],
    'Positions count from 0, so the first character is text[0].',
    'def first_letter(text):\n    return text[0]\n',
    'The big idea here is that Python counts from ZERO. text[0] is the first character, text[1] the second. It feels wrong for about a week and then never again.');

  P('st-last-letter', 'The last letter', 'last_letter',
    'Write a function called last_letter that gives back the last character of some text.\n\nYou can assume the text is never empty.',
    'def last_letter(text: str) -> str',
    'def last_letter(text):\n    # your code here\n    pass\n',
    [{ in: "last_letter('hello')", out: "'o'" }],
    [{ call: "last_letter('hello')", expect: "'o'" },
     { call: "last_letter('Ann')", expect: "'n'" },
     { call: "last_letter('x')", expect: "'x'", name: 'first and last are the same here' },
     { call: "last_letter('abc ')", expect: "' '", hidden: true },
     { call: "last_letter('12345')", expect: "'5'", hidden: true }],
    'text[-1] means one from the end.',
    'def last_letter(text):\n    return text[-1]\n',
    'A minus sign counts from the end, so text[-1] is the last character however long the text is. `text[len(text) - 1]` is the same thing the long way round.');

  P('st-initials-one', 'The first letter, in capitals', 'initial',
    'Write a function called initial that takes a name and gives back its first letter as a capital.',
    'def initial(name: str) -> str',
    'def initial(name):\n    # your code here\n    pass\n',
    [{ in: "initial('ann')", out: "'A'" }],
    [{ call: "initial('ann')", expect: "'A'" },
     { call: "initial('Bob')", expect: "'B'", name: 'already a capital' },
     { call: "initial('x')", expect: "'X'" },
     { call: "initial('éclair')", expect: "'É'", hidden: true, name: 'accents work too' },
     { call: "initial('zoe smith')", expect: "'Z'", hidden: true }],
    'Take the first character, then make it upper case — one after the other.',
    'def initial(name):\n    return name[0].upper()\n',
    'Two things you already know, joined: take position 0, then call .upper() on what came out. Methods chain left to right, so `name[0].upper()` reads as "first character, then capitalise it".');

  P('st-greet-name', 'Hello by name', 'greet',
    "Write a function called greet that takes a name and gives back the text hello, then a space, then the name.",
    'def greet(name: str) -> str',
    'def greet(name):\n    # your code here\n    pass\n',
    [{ in: "greet('Ann')", out: "'hello Ann'" }],
    [{ call: "greet('Ann')", expect: "'hello Ann'" },
     { call: "greet('Bob')", expect: "'hello Bob'" },
     { call: "greet('')", expect: "'hello '", name: 'the space is still there' },
     { call: "greet('Zoe Smith')", expect: "'hello Zoe Smith'", hidden: true },
     { call: "len(greet('Ann'))", expect: '9', hidden: true, name: 'no extra spaces' }],
    "An f-string: f'hello {name}'",
    "def greet(name):\n    return f'hello {name}'\n",
    "The f in front of the quotes lets you drop a value in curly brackets. `'hello ' + name` gives exactly the same answer — the f-string just stops you losing track of the space, which is what the length test is checking.");

  P('st-repeat-text', 'Say it twice', 'twice',
    'Write a function called twice that takes some text and gives it back repeated two times, with a space between.',
    'def twice(text: str) -> str',
    'def twice(text):\n    # your code here\n    pass\n',
    [{ in: "twice('ho')", out: "'ho ho'" }],
    [{ call: "twice('ho')", expect: "'ho ho'" },
     { call: "twice('a')", expect: "'a a'" },
     { call: "twice('')", expect: "' '", name: 'just the space is left' },
     { call: "twice('hello')", expect: "'hello hello'", hidden: true },
     { call: "len(twice('ab'))", expect: '5', hidden: true }],
    "f'{text} {text}' — the same value twice.",
    "def twice(text):\n    return f'{text} {text}'\n",
    'You can use the same name as many times as you like in an f-string. `text + \' \' + text` is the same answer; `text * 2` is NOT, because it would leave out the space.');

  P('st-round-money', 'Round it like money', 'money',
    'Write a function called money that takes a number and gives it back rounded to 2 decimal places, as a NUMBER.',
    'def money(n: float) -> float',
    'def money(n):\n    # your code here\n    pass\n',
    [{ in: 'money(1.239)', out: '1.24' }],
    [{ call: 'money(1.239)', expect: '1.24' },
     { call: 'money(2)', expect: '2' },
     { call: 'money(0.005)', expect: '0.01', name: 'rounds up' },
     { call: 'money(19.994)', expect: '19.99', hidden: true },
     { call: 'money(-1.239)', expect: '-1.24', hidden: true, name: 'negatives round the same way' }],
    'round(n, 2) rounds to two places.',
    'def money(n):\n    return round(n, 2)\n',
    'round() with a second argument says how many decimal places to keep. Note the answer is a NUMBER, so 2 stays as 2 rather than becoming the text "2.00" — formatting for display is a different job, and it comes later.');

  P('st-percent-of', 'A percentage of a number', 'percent_of',
    'Write a function called percent_of that takes a percentage and a number, and gives back that percentage OF the number.\n\npercent_of(10, 200) is 20.',
    'def percent_of(percent: float, total: float) -> float',
    'def percent_of(percent, total):\n    # your code here\n    pass\n',
    [{ in: 'percent_of(10, 200)', out: '20.0' }],
    [{ call: 'percent_of(10, 200)', expect: '20.0' },
     { call: 'percent_of(50, 10)', expect: '5.0', name: 'half of ten' },
     { call: 'percent_of(0, 99)', expect: '0.0' },
     { call: 'percent_of(100, 7)', expect: '7.0', hidden: true, name: 'all of it' },
     { call: 'percent_of(25, 8)', expect: '2.0', hidden: true }],
    'A percentage is a fraction out of 100: divide by 100, then multiply.',
    'def percent_of(percent, total):\n    return total * percent / 100\n',
    'The only trick is remembering that 10% means 10 divided by 100. Once that is in the line, the rest is multiplication you already know.');

  P('st-add-vat', 'Add the VAT on', 'add_vat',
    'Write a function called add_vat that takes a price and gives back the price with 20 percent added, rounded to 2 decimal places.',
    'def add_vat(price: float) -> float',
    'def add_vat(price):\n    # your code here\n    pass\n',
    [{ in: 'add_vat(10)', out: '12.0' }],
    [{ call: 'add_vat(10)', expect: '12.0' },
     { call: 'add_vat(0)', expect: '0' },
     { call: 'add_vat(19.99)', expect: '23.99', name: 'rounded to the penny' },
     { call: 'add_vat(100)', expect: '120.0', hidden: true },
     { call: 'add_vat(1.005)', expect: '1.21', hidden: true }],
    'Adding 20 percent is multiplying by 1.2. Then round to 2 places.',
    'def add_vat(price):\n    return round(price * 1.2, 2)\n',
    'Two steps you have already done, in one line: multiply, then round. Notice the order — round LAST, once the sum is finished, never partway through.');
})();
