/* Coding problems, one tiny step at a time — part 2: lists, loops, dictionaries
   and records. Same rule: one new idea per problem, and never two at once. */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var G = 'One step at a time';

  function P(id, title, fn, brief, sig, starter, examples, tests, hint, solution, walk, complexity) {
    window.PYTESTS.push({ id: id, group: G, lvl: 1, title: title, fn: fn, brief: brief, sig: sig,
      starter: starter, examples: examples, tests: tests, hint: hint, solution: solution, walk: walk,
      complexity: complexity || 'O(n) — one pass over the items.' });
  }

  P('st-first-item', 'The first item', 'first',
    'Write a function called first that takes a list and gives back its first item.\n\nYou can assume the list is never empty.',
    'def first(items: list)',
    'def first(items):\n    # your code here\n    pass\n',
    [{ in: 'first([9, 8, 7])', out: '9' }],
    [{ call: 'first([9, 8, 7])', expect: '9' },
     { call: "first(['a', 'b'])", expect: "'a'", name: 'works for text too' },
     { call: 'first([5])', expect: '5', name: 'a list of one' },
     { call: 'first([[1, 2], [3]])', expect: '[1, 2]', hidden: true, name: 'the item can be a list' },
     { call: 'first(list(range(100)))', expect: '0', hidden: true }],
    'Lists are numbered from 0, exactly like text.',
    'def first(items):\n    return items[0]\n',
    'The same square brackets you used on text work on a list. That is not a coincidence — both are sequences, and everything you learn about positions works on both.',
    'O(1).');

  P('st-last-item', 'The last item', 'last',
    'Write a function called last that takes a list and gives back its last item.\n\nYou can assume the list is never empty.',
    'def last(items: list)',
    'def last(items):\n    # your code here\n    pass\n',
    [{ in: 'last([9, 8, 7])', out: '7' }],
    [{ call: 'last([9, 8, 7])', expect: '7' },
     { call: "last(['a', 'b'])", expect: "'b'" },
     { call: 'last([5])', expect: '5' },
     { call: 'last(list(range(100)))', expect: '99', hidden: true },
     { call: 'last([1, 2, 3][:2])', expect: '2', hidden: true }],
    'Minus one counts from the end.',
    'def last(items):\n    return items[-1]\n',
    'Exactly the text version with a list instead. If you found yourself writing `items[len(items) - 1]`, that works too — but -1 is what everyone reads faster.',
    'O(1).');

  P('st-how-many', 'How many are there', 'how_many',
    'Write a function called how_many that takes a list and gives back how many items it holds.',
    'def how_many(items: list) -> int',
    'def how_many(items):\n    # your code here\n    pass\n',
    [{ in: 'how_many([9, 8, 7])', out: '3' }],
    [{ call: 'how_many([9, 8, 7])', expect: '3' },
     { call: 'how_many([])', expect: '0', name: 'an empty list' },
     { call: "how_many(['only one'])", expect: '1' },
     { call: 'how_many(list(range(50)))', expect: '50', hidden: true },
     { call: 'how_many([[1, 2], [3]])', expect: '2', hidden: true, name: 'two items, not three' }],
    'len() again — it counts list items as well as characters.',
    'def how_many(items):\n    return len(items)\n',
    'The hidden test is the interesting one: a list holding two lists has a length of 2, not 3. len() counts the items at the top level and never looks inside them.',
    'O(1).');

  P('st-total-list', 'Add them all up', 'total',
    'Write a function called total that takes a list of numbers and gives back their sum.\n\nAn empty list totals 0.',
    'def total(nums: list) -> float',
    'def total(nums):\n    # your code here\n    pass\n',
    [{ in: 'total([1, 2, 3])', out: '6' }],
    [{ call: 'total([1, 2, 3])', expect: '6' },
     { call: 'total([])', expect: '0', name: 'nothing adds up to nothing' },
     { call: 'total([5])', expect: '5' },
     { call: 'total([-1, 1])', expect: '0', hidden: true },
     { call: 'total([0.5, 0.5])', expect: '1.0', hidden: true }],
    'sum(nums) does it in one word.',
    'def total(nums):\n    return sum(nums)\n',
    'sum() already gives 0 for an empty list, so the awkward case is handled for you. Writing the loop by hand — total = 0, then add each one — gives the same answer and is worth doing once.');

  P('st-largest', 'The biggest one', 'largest',
    'Write a function called largest that takes a list of numbers and gives back the biggest.\n\nYou can assume the list is never empty.',
    'def largest(nums: list) -> float',
    'def largest(nums):\n    # your code here\n    pass\n',
    [{ in: 'largest([3, 9, 4])', out: '9' }],
    [{ call: 'largest([3, 9, 4])', expect: '9' },
     { call: 'largest([5])', expect: '5' },
     { call: 'largest([-5, -1, -9])', expect: '-1', name: 'all negative' },
     { call: 'largest([2.5, 2.6])', expect: '2.6', hidden: true },
     { call: 'largest(list(range(100)))', expect: '99', hidden: true }],
    'max(nums).',
    'def largest(nums):\n    return max(nums)\n',
    'The all-negative test is there for anyone who reaches for a loop starting at `best = 0`. Starting from the FIRST item instead of zero is the fix, and max() does that for you.');

  P('st-smallest', 'The smallest one', 'smallest',
    'Write a function called smallest that takes a list of numbers and gives back the smallest.\n\nYou can assume the list is never empty.',
    'def smallest(nums: list) -> float',
    'def smallest(nums):\n    # your code here\n    pass\n',
    [{ in: 'smallest([3, 9, 4])', out: '3' }],
    [{ call: 'smallest([3, 9, 4])', expect: '3' },
     { call: 'smallest([5])', expect: '5' },
     { call: 'smallest([-5, -1])', expect: '-5' },
     { call: 'smallest([0, 100])', expect: '0', hidden: true },
     { call: 'smallest([1.5, 1.4])', expect: '1.4', hidden: true }],
    'The opposite of the last one.',
    'def smallest(nums):\n    return min(nums)\n',
    'One word different from the previous problem. Doing them back to back is the point: max and min take exactly the same shape of argument and hand back the same kind of answer.');

  P('st-average-list', 'The average of a list', 'average',
    'Write a function called average that takes a list of numbers and gives back their average.\n\nAn empty list gives 0 — not a crash.',
    'def average(nums: list) -> float',
    'def average(nums):\n    # your code here\n    pass\n',
    [{ in: 'average([2, 4])', out: '3.0' }],
    [{ call: 'average([2, 4])', expect: '3.0' },
     { call: 'average([5])', expect: '5.0' },
     { call: 'average([])', expect: '0', name: 'no crash on an empty list' },
     { call: 'average([1, 2, 3, 4])', expect: '2.5', hidden: true },
     { call: 'average([-2, 2])', expect: '0.0', hidden: true }],
    'sum divided by len — but check the list is not empty first.',
    'def average(nums):\n    if not nums:\n        return 0\n    return sum(nums) / len(nums)\n',
    'The new idea is the GUARD: deal with the impossible case first, then get on with the normal one. Without it, an empty list divides by zero and the whole program stops.');

  P('st-double-each', 'Double every number', 'double_all',
    'Write a function called double_all that takes a list of numbers and gives back a NEW list with every number doubled.\n\nThe list you were given must not change.',
    'def double_all(nums: list) -> list',
    'def double_all(nums):\n    # your code here\n    pass\n',
    [{ in: 'double_all([1, 2, 3])', out: '[2, 4, 6]' }],
    [{ call: 'double_all([1, 2, 3])', expect: '[2, 4, 6]' },
     { call: 'double_all([])', expect: '[]', name: 'nothing to double' },
     { call: 'double_all([0, -1])', expect: '[0, -2]' },
     { call: '_unchanged()', expect: 'True', hidden: true, name: 'the original list is untouched' },
     { call: 'double_all([2.5])', expect: '[5.0]', hidden: true }],
    'Start an empty list, loop, append each doubled number — or write it as a one-line comprehension.',
    'def double_all(nums):\n    return [n * 2 for n in nums]\n',
    'The collecting shape, in one line. The long version — `out = []`, a for loop, `out.append(n * 2)`, `return out` — is exactly the same thing and is worth writing once so the short version makes sense.');
  window.PYTESTS[window.PYTESTS.length - 1].setup = 'def _unchanged():\n    given = [1, 2]\n    double_all(given)\n    return given == [1, 2]\n';

  P('st-only-positive', 'Keep the positive ones', 'positives',
    'Write a function called positives that takes a list of numbers and gives back a new list holding only the ones above zero.',
    'def positives(nums: list) -> list',
    'def positives(nums):\n    # your code here\n    pass\n',
    [{ in: 'positives([1, -2, 3])', out: '[1, 3]' }],
    [{ call: 'positives([1, -2, 3])', expect: '[1, 3]' },
     { call: 'positives([])', expect: '[]' },
     { call: 'positives([-1, -2])', expect: '[]', name: 'none of them qualify' },
     { call: 'positives([0, 1])', expect: '[1]', hidden: true, name: 'zero is not above zero' },
     { call: 'positives([5, 5])', expect: '[5, 5]', hidden: true, name: 'duplicates both stay' }],
    'Same as the last one with an if on the end of the comprehension.',
    'def positives(nums):\n    return [n for n in nums if n > 0]\n',
    'One inch on from double_all: instead of changing each item, you decide whether to keep it. In a comprehension the `if` goes at the END, after the loop part.');

  P('st-count-above', 'How many beat the bar', 'count_above',
    'Write a function called count_above that takes a list of numbers and a limit, and gives back how many of them are above the limit.',
    'def count_above(nums: list, limit: float) -> int',
    'def count_above(nums, limit):\n    # your code here\n    pass\n',
    [{ in: 'count_above([1, 5, 9], 4)', out: '2' }],
    [{ call: 'count_above([1, 5, 9], 4)', expect: '2' },
     { call: 'count_above([], 4)', expect: '0' },
     { call: 'count_above([4, 4], 4)', expect: '0', name: 'above, not equal to' },
     { call: 'count_above([1, 2, 3], 0)', expect: '3', hidden: true },
     { call: 'count_above([-1, -2], -3)', expect: '2', hidden: true }],
    'Filter to the ones above the limit, then take the length — or count with a loop.',
    'def count_above(nums, limit):\n    return len([n for n in nums if n > limit])\n',
    'Two things joined: the filter you just wrote, then len() of the result. `sum(1 for n in nums if n > limit)` is the other common way and does not build the list at all.');

  P('st-sort-list', 'Put them in order', 'in_order',
    'Write a function called in_order that gives back a NEW list holding the same numbers sorted smallest first.\n\nThe list you were given must not change.',
    'def in_order(nums: list) -> list',
    'def in_order(nums):\n    # your code here\n    pass\n',
    [{ in: 'in_order([3, 1, 2])', out: '[1, 2, 3]' }],
    [{ call: 'in_order([3, 1, 2])', expect: '[1, 2, 3]' },
     { call: 'in_order([])', expect: '[]' },
     { call: 'in_order([2, 2, 1])', expect: '[1, 2, 2]', name: 'duplicates stay' },
     { call: '_kept()', expect: 'True', hidden: true, name: 'the original order survives' },
     { call: "in_order(['b', 'a'])", expect: "['a', 'b']", hidden: true, name: 'text sorts alphabetically' }],
    'sorted(nums) gives a new list; nums.sort() would change the one you were given.',
    'def in_order(nums):\n    return sorted(nums)\n',
    'The distinction this problem exists for: `sorted(x)` hands back a NEW list, `x.sort()` rearranges the list in place and returns None. The hidden test fails if you use the wrong one.',
    'O(n log n).');
  window.PYTESTS[window.PYTESTS.length - 1].setup = 'def _kept():\n    given = [3, 1, 2]\n    in_order(given)\n    return given == [3, 1, 2]\n';

  P('st-reverse-list', 'Back to front', 'backwards',
    'Write a function called backwards that gives back a new list holding the same items in the opposite order.',
    'def backwards(items: list) -> list',
    'def backwards(items):\n    # your code here\n    pass\n',
    [{ in: 'backwards([1, 2, 3])', out: '[3, 2, 1]' }],
    [{ call: 'backwards([1, 2, 3])', expect: '[3, 2, 1]' },
     { call: 'backwards([])', expect: '[]' },
     { call: "backwards(['a'])", expect: "['a']", name: 'one item is its own reverse' },
     { call: '_still_forwards()', expect: 'True', hidden: true, name: 'the original is untouched' },
     { call: 'backwards([1, 1, 2])', expect: '[2, 1, 1]', hidden: true }],
    'items[::-1] walks the list backwards and gives a new list.',
    'def backwards(items):\n    return items[::-1]\n',
    'The slice with a step of minus one. `list(reversed(items))` is the same answer spelled out, and `items.reverse()` is the in-place one that would fail the hidden test.');
  window.PYTESTS[window.PYTESTS.length - 1].setup = 'def _still_forwards():\n    given = [1, 2, 3]\n    backwards(given)\n    return given == [1, 2, 3]\n';

  P('st-has-item', 'Is it in there', 'has',
    'Write a function called has that takes a list and a value, and gives back True if the value is in the list.',
    'def has(items: list, value) -> bool',
    'def has(items, value):\n    # your code here\n    pass\n',
    [{ in: 'has([1, 2], 2)', out: 'True' }],
    [{ call: 'has([1, 2], 2)', expect: 'True' },
     { call: 'has([1, 2], 9)', expect: 'False' },
     { call: 'has([], 1)', expect: 'False', name: 'nothing is in an empty list' },
     { call: "has(['a', 'b'], 'a')", expect: 'True', hidden: true },
     { call: "has([1, 2], '1')", expect: 'False', hidden: true, name: 'text 1 is not the number 1' }],
    'The word in already answers this.',
    'def has(items, value):\n    return value in items\n',
    'One word does the whole job. The hidden test is the lesson: the text "1" and the number 1 are different things, and a list holding one does not contain the other.');

  P('st-join-words', 'Make a sentence', 'sentence',
    'Write a function called sentence that takes a list of words and joins them into one piece of text with single spaces between.',
    'def sentence(words: list) -> str',
    'def sentence(words):\n    # your code here\n    pass\n',
    [{ in: "sentence(['hello', 'there'])", out: "'hello there'" }],
    [{ call: "sentence(['hello', 'there'])", expect: "'hello there'" },
     { call: "sentence(['one'])", expect: "'one'", name: 'no stray space on the end' },
     { call: 'sentence([])', expect: "''", name: 'nothing joins to nothing' },
     { call: "sentence(['a', 'b', 'c'])", expect: "'a b c'", hidden: true },
     { call: "len(sentence(['ab', 'cd']))", expect: '5', hidden: true }],
    "' '.join(words) — the separator goes first, then .join.",
    "def sentence(words):\n    return ' '.join(words)\n",
    "join is written back to front from how it sounds: the separator is the thing you call it on. The single-word test is what catches the loop-and-add-a-space version, which leaves a space dangling on the end.");

  P('st-split-words', 'Break it into words', 'words_of',
    'Write a function called words_of that takes a sentence and gives back a list of its words.\n\nAny amount of spacing between words counts as one gap.',
    'def words_of(text: str) -> list',
    'def words_of(text):\n    # your code here\n    pass\n',
    [{ in: "words_of('hello there')", out: "['hello', 'there']" }],
    [{ call: "words_of('hello there')", expect: "['hello', 'there']" },
     { call: "words_of('one')", expect: "['one']" },
     { call: "words_of('')", expect: '[]', name: 'no words at all' },
     { call: "words_of('  spaced   out  ')", expect: "['spaced', 'out']", hidden: true, name: 'extra spaces ignored' },
     { call: "len(words_of('a b c'))", expect: '3', hidden: true }],
    'text.split() with no argument splits on any run of whitespace.',
    'def words_of(text):\n    return text.split()\n',
    "The exact opposite of the last problem. `split()` with NO argument is the one you want here — `split(' ')` would give you empty strings back wherever two spaces sat together.");

  P('st-count-word', 'How often does it appear', 'count_word',
    'Write a function called count_word that takes a sentence and a word, and gives back how many times that word appears.\n\nCompare whole words, and ignore capitals.',
    'def count_word(text: str, word: str) -> int',
    'def count_word(text, word):\n    # your code here\n    pass\n',
    [{ in: "count_word('the cat and the hat', 'the')", out: '2' }],
    [{ call: "count_word('the cat and the hat', 'the')", expect: '2' },
     { call: "count_word('', 'the')", expect: '0' },
     { call: "count_word('The the THE', 'the')", expect: '3', name: 'capitals ignored' },
     { call: "count_word('theatre', 'the')", expect: '0', hidden: true, name: 'whole words only' },
     { call: "count_word('a b a', 'a')", expect: '2', hidden: true }],
    'Lower-case it, split it into words, then count how many equal the word.',
    'def count_word(text, word):\n    return text.lower().split().count(word.lower())\n',
    'Three things you already know in a row: lower(), split(), count(). The "theatre" test is why splitting into words matters — counting the letters "the" inside the whole sentence would wrongly find one there.');

  P('st-dict-lookup', 'Look it up', 'price_of',
    "Write a function called price_of that takes a dictionary of prices and an item name, and gives back that item's price.\n\nIf the item is not there, give back 0.",
    'def price_of(prices: dict, item: str) -> float',
    'def price_of(prices, item):\n    # your code here\n    pass\n',
    [{ in: "price_of({'tea': 2}, 'tea')", out: '2' }],
    [{ call: "price_of({'tea': 2}, 'tea')", expect: '2' },
     { call: "price_of({'tea': 2}, 'jam')", expect: '0', name: 'missing items cost nothing' },
     { call: "price_of({}, 'tea')", expect: '0' },
     { call: "price_of({'tea': 2, 'jam': 3}, 'jam')", expect: '3', hidden: true },
     { call: "price_of({'tea': 0}, 'tea')", expect: '0', hidden: true, name: 'a real price of zero' }],
    "prices.get(item, 0) — get never raises when the key is missing.",
    'def price_of(prices, item):\n    return prices.get(item, 0)\n',
    "`prices[item]` would raise a KeyError on the missing case; `.get(item, 0)` hands back the fallback instead. The default of 0 is what makes the tally-style code you meet next possible.");

  P('st-dict-total', 'Add up the values', 'total_of',
    'Write a function called total_of that takes a dictionary whose values are numbers, and gives back the total of those values.',
    'def total_of(counts: dict) -> float',
    'def total_of(counts):\n    # your code here\n    pass\n',
    [{ in: "total_of({'a': 1, 'b': 2})", out: '3' }],
    [{ call: "total_of({'a': 1, 'b': 2})", expect: '3' },
     { call: 'total_of({})', expect: '0', name: 'an empty dictionary' },
     { call: "total_of({'a': 5})", expect: '5' },
     { call: "total_of({'a': -1, 'b': 1})", expect: '0', hidden: true },
     { call: "total_of({'a': 0.5, 'b': 0.5})", expect: '1.0', hidden: true }],
    'sum() the .values() of the dictionary.',
    'def total_of(counts):\n    return sum(counts.values())\n',
    'A dictionary hands you three views: .keys(), .values() and .items(). Summing the values is the same sum() you used on a list — the only new part is asking for the values first.');

  P('st-tally', 'Count each one', 'tally',
    'Write a function called tally that takes a list of words and gives back a dictionary saying how many times each word appears.',
    'def tally(words: list) -> dict',
    'def tally(words):\n    # your code here\n    pass\n',
    [{ in: "tally(['a', 'b', 'a'])", out: "{'a': 2, 'b': 1}" }],
    [{ call: "tally(['a', 'b', 'a'])", expect: "{'a': 2, 'b': 1}" },
     { call: 'tally([])', expect: '{}', name: 'nothing to count' },
     { call: "tally(['x'])", expect: "{'x': 1}" },
     { call: "tally(['a', 'a', 'a'])", expect: "{'a': 3}", hidden: true },
     { call: "len(tally(['a', 'b', 'c']))", expect: '3', hidden: true }],
    'Start with an empty dictionary, and for each word do counts[word] = counts.get(word, 0) + 1.',
    'def tally(words):\n    counts = {}\n    for word in words:\n        counts[word] = counts.get(word, 0) + 1\n    return counts\n',
    'The most-asked beginner exercise there is, and it is only four lines. `.get(word, 0)` is what makes the first sighting of a word work without a separate if. `collections.Counter(words)` does the whole thing in one line once you know it exists.');

  P('st-record-field', 'One field out of a record', 'name_of',
    "Write a function called name_of that takes a dictionary describing a person and gives back the value under the key name.\n\nIf there is no name, give back the text unknown.",
    'def name_of(person: dict) -> str',
    'def name_of(person):\n    # your code here\n    pass\n',
    [{ in: "name_of({'name': 'Ann'})", out: "'Ann'" }],
    [{ call: "name_of({'name': 'Ann'})", expect: "'Ann'" },
     { call: "name_of({'age': 30})", expect: "'unknown'", name: 'no name in the record' },
     { call: 'name_of({})', expect: "'unknown'" },
     { call: "name_of({'name': '', 'age': 1})", expect: "''", hidden: true, name: 'an empty name is still a name' },
     { call: "name_of({'name': 'Bob', 'city': 'Leeds'})", expect: "'Bob'", hidden: true }],
    "person.get('name', 'unknown')",
    "def name_of(person):\n    return person.get('name', 'unknown')\n",
    'A "record" is just a dictionary with agreed keys — it is how a row of a spreadsheet arrives in plain Python. The empty-name test is a nudge that `.get` only falls back when the key is MISSING, not when its value is empty.');

  P('st-names-list', 'All the names', 'all_names',
    'Write a function called all_names that takes a list of person dictionaries and gives back a list of their names, in order.\n\nEvery person has a name.',
    'def all_names(people: list) -> list',
    'def all_names(people):\n    # your code here\n    pass\n',
    [{ in: "all_names([{'name': 'Ann'}, {'name': 'Bob'}])", out: "['Ann', 'Bob']" }],
    [{ call: "all_names([{'name': 'Ann'}, {'name': 'Bob'}])", expect: "['Ann', 'Bob']" },
     { call: 'all_names([])', expect: '[]' },
     { call: "all_names([{'name': 'Ann', 'age': 30}])", expect: "['Ann']", name: 'the other keys are ignored' },
     { call: "len(all_names([{'name': 'a'}, {'name': 'b'}, {'name': 'c'}]))", expect: '3', hidden: true },
     { call: "all_names([{'name': 'Zoe'}])", expect: "['Zoe']", hidden: true }],
    "A comprehension over the list: [person['name'] for person in people]",
    "def all_names(people):\n    return [person['name'] for person in people]\n",
    'A list of dictionaries is the shape almost all real data arrives in. Pulling one field out of every record is the first thing you ever do with it, and this comprehension is that move.');

  P('st-filter-records', 'Only the ones that qualify', 'over_age',
    'Write a function called over_age that takes a list of person dictionaries and an age, and gives back only the people older than that age.\n\nEvery person has an age.',
    'def over_age(people: list, limit: int) -> list',
    'def over_age(people, limit):\n    # your code here\n    pass\n',
    [{ in: "over_age([{'name': 'Ann', 'age': 30}], 18)", out: "[{'name': 'Ann', 'age': 30}]" }],
    [{ call: "over_age([{'name': 'Ann', 'age': 30}], 18)", expect: "[{'name': 'Ann', 'age': 30}]" },
     { call: "over_age([{'name': 'Kid', 'age': 10}], 18)", expect: '[]', name: 'nobody qualifies' },
     { call: "over_age([], 18)", expect: '[]' },
     { call: "[p['name'] for p in over_age([{'name': 'A', 'age': 20}, {'name': 'B', 'age': 15}], 18)]", expect: "['A']", hidden: true },
     { call: "over_age([{'name': 'Edge', 'age': 18}], 18)", expect: '[]', hidden: true, name: 'older than, not equal to' }],
    "[person for person in people if person['age'] > limit]",
    "def over_age(people, limit):\n    return [person for person in people if person['age'] > limit]\n",
    'The filtering comprehension again, with a dictionary lookup inside the condition. Notice the whole PERSON is kept, not just their name — read the brief carefully, because "give me the people" and "give me their names" are one word apart.');

  P('st-sum-field', 'Add up one field', 'total_spend',
    'Write a function called total_spend that takes a list of order dictionaries and adds up the value under the key amount.\n\nAn order with no amount counts as 0.',
    'def total_spend(orders: list) -> float',
    'def total_spend(orders):\n    # your code here\n    pass\n',
    [{ in: "total_spend([{'amount': 10}, {'amount': 5}])", out: '15' }],
    [{ call: "total_spend([{'amount': 10}, {'amount': 5}])", expect: '15' },
     { call: 'total_spend([])', expect: '0' },
     { call: "total_spend([{'amount': 10}, {'id': 2}])", expect: '10', name: 'a missing amount counts as nothing' },
     { call: "total_spend([{'amount': 2.5}, {'amount': 2.5}])", expect: '5.0', hidden: true },
     { call: "total_spend([{'amount': -5}, {'amount': 5}])", expect: '0', hidden: true }],
    "sum(order.get('amount', 0) for order in orders)",
    "def total_spend(orders):\n    return sum(order.get('amount', 0) for order in orders)\n",
    'Summing one field across records — the plain-Python version of what a spreadsheet does with a column. Using `.get(..., 0)` rather than `[...]` is what makes the missing-field row a zero instead of a crash.');

  P('st-best-record', 'Whose is the biggest', 'top_spender',
    "Write a function called top_spender that takes a list of order dictionaries with keys name and amount, and gives back the NAME of the biggest order.\n\nAn empty list gives back None.",
    'def top_spender(orders: list) -> str',
    'def top_spender(orders):\n    # your code here\n    pass\n',
    [{ in: "top_spender([{'name': 'Ann', 'amount': 10}, {'name': 'Bob', 'amount': 20}])", out: "'Bob'" }],
    [{ call: "top_spender([{'name': 'Ann', 'amount': 10}, {'name': 'Bob', 'amount': 20}])", expect: "'Bob'" },
     { call: "top_spender([{'name': 'Solo', 'amount': 1}])", expect: "'Solo'" },
     { call: 'top_spender([])', expect: 'None', name: 'nobody to pick' },
     { call: "top_spender([{'name': 'A', 'amount': -5}, {'name': 'B', 'amount': -1}])", expect: "'B'", hidden: true, name: 'all negative' },
     { call: "top_spender([{'name': 'First', 'amount': 5}, {'name': 'Second', 'amount': 5}])", expect: "'First'", hidden: true, name: 'a tie keeps the earlier one' }],
    "max(orders, key=lambda order: order['amount']) gives the whole record — then take its name.",
    "def top_spender(orders):\n    if not orders:\n        return None\n    best = max(orders, key=lambda order: order['amount'])\n    return best['name']\n",
    "The new idea is `key=`: it tells max WHAT to compare, while still handing back the whole record. Ties go to the first one max met, which is what the hidden test pins down. And the empty guard is back — max() of nothing raises.");
})();
