/* Coding problems, one tiny step at a time — part 3: the rungs between the ones
   already there. Numbers and text first, then lists, dictionaries and records. */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var G = 'One step at a time';

  function P(id, title, fn, brief, sig, starter, examples, tests, hint, solution, walk, complexity) {
    window.PYTESTS.push({ id: id, group: G, lvl: 1, title: title, fn: fn, brief: brief, sig: sig,
      starter: starter, examples: examples, tests: tests, hint: hint, solution: solution, walk: walk,
      complexity: complexity || 'O(n) — one pass over the items.' });
  }

  /* ---------------- numbers ---------------- */
  P('st-triple', 'Three times as much', 'triple',
    'Write a function called triple that gives back three times the number it is given.',
    'def triple(n: float) -> float',
    'def triple(n):\n    # your code here\n    pass\n',
    [{ in: 'triple(4)', out: '12' }],
    [{ call: 'triple(4)', expect: '12' },
     { call: 'triple(0)', expect: '0' },
     { call: 'triple(-2)', expect: '-6' },
     { call: 'triple(1.5)', expect: '4.5', hidden: true },
     { call: 'triple(triple(1))', expect: '9', hidden: true, name: 'three times three' }],
    'One character different from double.',
    'def triple(n):\n    return n * 3\n',
    'Deliberately the same problem as double with one digit changed. If that felt too easy, good — that is what it is for.',
    'O(1).');

  P('st-square', 'A number times itself', 'square',
    'Write a function called square that gives back the number multiplied by itself.',
    'def square(n: float) -> float',
    'def square(n):\n    # your code here\n    pass\n',
    [{ in: 'square(5)', out: '25' }],
    [{ call: 'square(5)', expect: '25' },
     { call: 'square(0)', expect: '0' },
     { call: 'square(-3)', expect: '9', name: 'a negative squared is positive' },
     { call: 'square(1.5)', expect: '2.25', hidden: true },
     { call: 'square(10)', expect: '100', hidden: true }],
    'n * n, or n ** 2 — both are right.',
    'def square(n):\n    return n * n\n',
    'Two right answers: n * n, or the power operator n ** 2. The negative test is the interesting one — two minuses make a plus, so squaring always gives something positive.',
    'O(1).');

  P('st-smaller', 'Whichever is smaller', 'smaller',
    'Write a function called smaller that takes two numbers and gives back the lesser one.',
    'def smaller(a: float, b: float) -> float',
    'def smaller(a, b):\n    # your code here\n    pass\n',
    [{ in: 'smaller(3, 7)', out: '3' }],
    [{ call: 'smaller(3, 7)', expect: '3' },
     { call: 'smaller(7, 3)', expect: '3', name: 'either way round' },
     { call: 'smaller(5, 5)', expect: '5' },
     { call: 'smaller(-1, -9)', expect: '-9', hidden: true, name: 'both negative' },
     { call: 'smaller(0, -1)', expect: '-1', hidden: true }],
    'min(a, b) — the mirror of the bigger problem.',
    'def smaller(a, b):\n    return min(a, b)\n',
    'One word different from bigger. The negative tests are there because "smaller" and "closer to zero" are not the same thing.',
    'O(1).');

  P('st-biggest-three', 'The biggest of three', 'biggest3',
    'Write a function called biggest3 that takes three numbers and gives back the largest.',
    'def biggest3(a: float, b: float, c: float) -> float',
    'def biggest3(a, b, c):\n    # your code here\n    pass\n',
    [{ in: 'biggest3(3, 9, 4)', out: '9' }],
    [{ call: 'biggest3(3, 9, 4)', expect: '9' },
     { call: 'biggest3(9, 3, 4)', expect: '9', name: 'first is biggest' },
     { call: 'biggest3(3, 4, 9)', expect: '9', name: 'last is biggest' },
     { call: 'biggest3(2, 2, 2)', expect: '2', hidden: true },
     { call: 'biggest3(-5, -1, -9)', expect: '-1', hidden: true }],
    'max takes as many numbers as you give it.',
    'def biggest3(a, b, c):\n    return max(a, b, c)\n',
    'max is not limited to two. The three tests cover the largest arriving first, in the middle and last — a hand-written chain of ifs usually fails one of them.',
    'O(1).');

  P('st-abs', 'How far from zero', 'distance_from_zero',
    'Write a function called distance_from_zero that gives back the size of a number, ignoring any minus sign.',
    'def distance_from_zero(n: float) -> float',
    'def distance_from_zero(n):\n    # your code here\n    pass\n',
    [{ in: 'distance_from_zero(-4)', out: '4' }],
    [{ call: 'distance_from_zero(-4)', expect: '4' },
     { call: 'distance_from_zero(4)', expect: '4', name: 'positives are unchanged' },
     { call: 'distance_from_zero(0)', expect: '0' },
     { call: 'distance_from_zero(-0.5)', expect: '0.5', hidden: true },
     { call: 'distance_from_zero(-100)', expect: '100', hidden: true }],
    'abs(n) gives the size without the sign.',
    'def distance_from_zero(n):\n    return abs(n)\n',
    'abs() is how you compare sizes when direction does not matter — the gap between two numbers, or how far a prediction was out either way.',
    'O(1).');

  P('st-round-whole', 'To the nearest whole number', 'to_whole',
    'Write a function called to_whole that rounds a number to the nearest whole number.',
    'def to_whole(n: float) -> int',
    'def to_whole(n):\n    # your code here\n    pass\n',
    [{ in: 'to_whole(2.6)', out: '3' }],
    [{ call: 'to_whole(2.6)', expect: '3' },
     { call: 'to_whole(2.4)', expect: '2' },
     { call: 'to_whole(-2.6)', expect: '-3', name: 'negatives round away from zero' },
     { call: 'to_whole(5)', expect: '5', hidden: true },
     { call: 'to_whole(2.5)', expect: '2', hidden: true, name: 'halves go to the nearest EVEN number' }],
    'round(n) with no second argument.',
    'def to_whole(n):\n    return round(n)\n',
    "The hidden test is the surprise: Python rounds halves to the nearest EVEN number, so round(2.5) is 2 and round(3.5) is 4. It keeps long columns of numbers from drifting upwards, and it catches everyone once.",
    'O(1).');

  P('st-safe-divide-two', 'Divide without crashing', 'divide',
    'Write a function called divide that divides the first number by the second, giving back None when the second is 0.',
    'def divide(a: float, b: float)',
    'def divide(a, b):\n    # your code here\n    pass\n',
    [{ in: 'divide(10, 2)', out: '5.0' }],
    [{ call: 'divide(10, 2)', expect: '5.0' },
     { call: 'divide(1, 0)', expect: 'None', name: 'no crash on zero' },
     { call: 'divide(0, 5)', expect: '0.0', name: 'zero divided by something is fine' },
     { call: 'divide(-10, 4)', expect: '-2.5', hidden: true },
     { call: 'divide(0, 0)', expect: 'None', hidden: true }],
    'Check b first, then divide.',
    'def divide(a, b):\n    if b == 0:\n        return None\n    return a / b\n',
    'The guard again, this time on the divisor. Note the two zero tests are opposites: zero divided BY something is a perfectly good 0.0, while dividing by zero is the one that raises.',
    'O(1).');

  P('st-last-digit', 'The last digit', 'last_digit',
    'Write a function called last_digit that gives back the last digit of a whole number.\n\nFor a negative number, give the last digit of its size.',
    'def last_digit(n: int) -> int',
    'def last_digit(n):\n    # your code here\n    pass\n',
    [{ in: 'last_digit(1234)', out: '4' }],
    [{ call: 'last_digit(1234)', expect: '4' },
     { call: 'last_digit(7)', expect: '7', name: 'one digit is its own last digit' },
     { call: 'last_digit(40)', expect: '0' },
     { call: 'last_digit(-25)', expect: '5', hidden: true, name: 'ignore the minus sign' },
     { call: 'last_digit(0)', expect: '0', hidden: true }],
    'The remainder after dividing by 10 — but take abs() first so negatives behave.',
    'def last_digit(n):\n    return abs(n) % 10\n',
    'Two things you already know in one line. Without the abs, -25 % 10 gives 5 in Python but 25 % 10 is clearer about what you meant — and in most other languages the negative version would give -5.',
    'O(1).');

  P('st-divisible', 'Does it divide exactly', 'divides_by',
    'Write a function called divides_by that says whether the first number divides exactly by the second.',
    'def divides_by(n: int, d: int) -> bool',
    'def divides_by(n, d):\n    # your code here\n    pass\n',
    [{ in: 'divides_by(9, 3)', out: 'True' }],
    [{ call: 'divides_by(9, 3)', expect: 'True' },
     { call: 'divides_by(10, 3)', expect: 'False' },
     { call: 'divides_by(0, 5)', expect: 'True', name: 'zero divides by anything' },
     { call: 'divides_by(-9, 3)', expect: 'True', hidden: true },
     { call: 'divides_by(7, 7)', expect: 'True', hidden: true }],
    'A remainder of 0 means it went in exactly.',
    'def divides_by(n, d):\n    return n % d == 0\n',
    'This is is_even with the 2 replaced by whatever you are given. Every "every third row", "multiple of five" and FizzBuzz question is this line.',
    'O(1).');

  P('st-text-to-number', 'Turn typed text into a number', 'to_number',
    'Write a function called to_number that turns text into a whole number, giving back 0 when the text is not a number.',
    'def to_number(text: str) -> int',
    'def to_number(text):\n    # your code here\n    pass\n',
    [{ in: "to_number('42')", out: '42' }],
    [{ call: "to_number('42')", expect: '42' },
     { call: "to_number('abc')", expect: '0', name: 'not a number at all' },
     { call: "to_number('')", expect: '0' },
     { call: "to_number(' 7 ')", expect: '7', hidden: true, name: 'spaces are allowed' },
     { call: "to_number('3.5')", expect: '0', hidden: true, name: 'int() will not take a decimal string' }],
    'Wrap int(text) in try/except ValueError and return 0 in the except.',
    'def to_number(text):\n    try:\n        return int(text)\n    except ValueError:\n        return 0\n',
    "Anything typed by a person arrives as text and may be rubbish. try/except turns the crash into a decision. int(' 7 ') works because int strips spaces itself, but int('3.5') does not — that needs float() first.",
    'O(1).');

  /* ---------------- text ---------------- */
  P('st-last-two', 'The last two characters', 'last_two',
    'Write a function called last_two that gives back the last two characters of some text.\n\nShorter text comes back as it is.',
    'def last_two(text: str) -> str',
    'def last_two(text):\n    # your code here\n    pass\n',
    [{ in: "last_two('hello')", out: "'lo'" }],
    [{ call: "last_two('hello')", expect: "'lo'" },
     { call: "last_two('a')", expect: "'a'", name: 'shorter than two' },
     { call: "last_two('')", expect: "''" },
     { call: "last_two('ab')", expect: "'ab'", hidden: true },
     { call: "last_two('12345')", expect: "'45'", hidden: true }],
    'text[-2:] takes from two before the end onwards.',
    'def last_two(text):\n    return text[-2:]\n',
    'Slicing never raises for being out of range, which is why one-character text needs no special handling. That is unusual and worth relying on.',
    'O(1).');

  P('st-ends-with', 'Does it end with that', 'ends_with',
    'Write a function called ends_with that says whether some text ends with a given suffix.',
    'def ends_with(text: str, suffix: str) -> bool',
    'def ends_with(text, suffix):\n    # your code here\n    pass\n',
    [{ in: "ends_with('report.csv', '.csv')", out: 'True' }],
    [{ call: "ends_with('report.csv', '.csv')", expect: 'True' },
     { call: "ends_with('report.txt', '.csv')", expect: 'False' },
     { call: "ends_with('report.csv', '')", expect: 'True', name: 'everything ends with nothing' },
     { call: "ends_with('CSV.csv', 'CSV')", expect: 'False', hidden: true, name: 'the END, not the start' },
     { call: "ends_with('', '.csv')", expect: 'False', hidden: true }],
    'Text has .endswith(suffix), which already answers True or False.',
    'def ends_with(text, suffix):\n    return text.endswith(suffix)\n',
    'The mirror of startswith, and the line behind every "is this a CSV" check you will ever write. Lower-case both sides first if the extension might be capitalised.',
    'O(n) over the suffix.');

  P('st-contains', 'Is it in there', 'contains',
    'Write a function called contains that says whether one piece of text appears inside another, ignoring capitals.',
    'def contains(text: str, part: str) -> bool',
    'def contains(text, part):\n    # your code here\n    pass\n',
    [{ in: "contains('Hello there', 'HELLO')", out: 'True' }],
    [{ call: "contains('Hello there', 'HELLO')", expect: 'True' },
     { call: "contains('Hello there', 'goodbye')", expect: 'False' },
     { call: "contains('abc', '')", expect: 'True', name: 'nothing is inside everything' },
     { call: "contains('', 'a')", expect: 'False', hidden: true },
     { call: "contains('concatenate', 'cat')", expect: 'True', hidden: true, name: 'it is a substring match' }],
    'Lower-case both sides, then use the word in.',
    'def contains(text, part):\n    return part.lower() in text.lower()\n',
    "Lower-casing BOTH sides is what makes it case-insensitive — doing one and not the other is a bug that only shows up on some inputs. The 'concatenate' test is the reminder that this finds substrings, not whole words.",
    'O(n).');

  P('st-swap-words', 'Swap two words round', 'swap_words',
    'Write a function called swap_words that takes a two-word sentence and gives it back with the words the other way round.',
    'def swap_words(text: str) -> str',
    'def swap_words(text):\n    # your code here\n    pass\n',
    [{ in: "swap_words('hello there')", out: "'there hello'" }],
    [{ call: "swap_words('hello there')", expect: "'there hello'" },
     { call: "swap_words('Ann Smith')", expect: "'Smith Ann'" },
     { call: "swap_words('one')", expect: "'one'", name: 'one word swaps with nothing' },
     { call: "swap_words('a b')", expect: "'b a'", hidden: true },
     { call: "swap_words('')", expect: "''", hidden: true }],
    'Split into words, reverse the list, then join it back with a space.',
    "def swap_words(text):\n    words = text.split()\n    return ' '.join(reversed(words))\n",
    'Three moves you have already met, in a row: split, reverse, join. The one-word and empty cases fall out for free, which is a good sign the approach is right.',
    'O(n).');

  P('st-initials-two', 'Initials from a full name', 'initials',
    'Write a function called initials that turns a full name into capital initials separated by dots.\n\n"ann smith" becomes "A.S."',
    'def initials(name: str) -> str',
    'def initials(name):\n    # your code here\n    pass\n',
    [{ in: "initials('ann smith')", out: "'A.S.'" }],
    [{ call: "initials('ann smith')", expect: "'A.S.'" },
     { call: "initials('Bob')", expect: "'B.'", name: 'one name, one initial' },
     { call: "initials('')", expect: "''", name: 'no name, nothing back' },
     { call: "initials('mary jane watson')", expect: "'M.J.W.'", hidden: true },
     { call: "initials('  ann   smith  ')", expect: "'A.S.'", hidden: true, name: 'extra spaces ignored' }],
    "Split into words, take word[0].upper() from each, and add a dot after every one.",
    "def initials(name):\n    return ''.join(word[0].upper() + '.' for word in name.split())\n",
    "split() with no argument ignores runs of spaces, which is what makes the messy-spacing test pass without any extra work. Joining with '' means the dots you added are the only separator.",
    'O(n).');

  P('st-pad-number', 'Pad a number with zeros', 'pad',
    'Write a function called pad that turns a whole number into text at least 3 characters long, padded with zeros on the left.',
    'def pad(n: int) -> str',
    'def pad(n):\n    # your code here\n    pass\n',
    [{ in: 'pad(7)', out: "'007'" }],
    [{ call: 'pad(7)', expect: "'007'" },
     { call: 'pad(42)', expect: "'042'" },
     { call: 'pad(123)', expect: "'123'", name: 'already long enough' },
     { call: 'pad(1234)', expect: "'1234'", hidden: true, name: 'longer is left alone' },
     { call: 'pad(0)', expect: "'000'", hidden: true }],
    "f'{n:03d}' — or str(n).zfill(3).",
    "def pad(n):\n    return f'{n:03d}'\n",
    'Two right answers again: the format spec 03d, or str(n).zfill(3). Padding never TRUNCATES, so a longer number comes through unharmed — which the hidden test checks.',
    'O(1).');

  P('st-money-text', 'Format it as money', 'as_money',
    'Write a function called as_money that turns a number into text with a pound sign, thousands separated, and exactly two decimal places.',
    'def as_money(n: float) -> str',
    'def as_money(n):\n    # your code here\n    pass\n',
    [{ in: 'as_money(1234.5)', out: "'£1,234.50'" }],
    [{ call: 'as_money(1234.5)', expect: "'£1,234.50'" },
     { call: 'as_money(0)', expect: "'£0.00'", name: 'zero still gets its decimals' },
     { call: 'as_money(9.999)', expect: "'£10.00'", name: 'rounded to the penny' },
     { call: 'as_money(1000000)', expect: "'£1,000,000.00'", hidden: true },
     { call: 'as_money(-5)', expect: "'£-5.00'", hidden: true, name: 'the minus stays where it falls' }],
    "An f-string with a format spec: f'£{n:,.2f}'.",
    "def as_money(n):\n    return f'£{n:,.2f}'\n",
    'The comma groups thousands and .2f fixes two decimals — both inside one spec, in that order. This exact line ends up in nearly every report you write.',
    'O(1).');

  /* ---------------- lists ---------------- */
  P('st-second', 'The second item', 'second',
    'Write a function called second that gives back the second item of a list, or None when there is not one.',
    'def second(items: list)',
    'def second(items):\n    # your code here\n    pass\n',
    [{ in: 'second([10, 20, 30])', out: '20' }],
    [{ call: 'second([10, 20, 30])', expect: '20' },
     { call: 'second([10])', expect: 'None', name: 'only one item' },
     { call: 'second([])', expect: 'None' },
     { call: "second(['a', 'b'])", expect: "'b'", hidden: true },
     { call: 'second([0, 0])', expect: '0', hidden: true, name: 'zero is a real second item' }],
    'Position 1 is the second — but check the list is long enough first.',
    'def second(items):\n    if len(items) < 2:\n        return None\n    return items[1]\n',
    'The guard has to check the LENGTH, not whether the list is empty — a one-item list is not empty but still has no second item. The [0, 0] test makes sure you guarded the list rather than the value.',
    'O(1).');

  P('st-without', 'Everything except one value', 'without',
    'Write a function called without that gives back a new list with every copy of a value removed.',
    'def without(items: list, value) -> list',
    'def without(items, value):\n    # your code here\n    pass\n',
    [{ in: 'without([1, 2, 1, 3], 1)', out: '[2, 3]' }],
    [{ call: 'without([1, 2, 1, 3], 1)', expect: '[2, 3]' },
     { call: 'without([1, 2], 9)', expect: '[1, 2]', name: 'not there, nothing removed' },
     { call: 'without([], 1)', expect: '[]' },
     { call: 'without([1, 1, 1], 1)', expect: '[]', hidden: true, name: 'all of them go' },
     { call: '_original_kept()', expect: 'True', hidden: true, name: 'the original is untouched' }],
    'A comprehension keeping the items that are NOT the value.',
    'def without(items, value):\n    return [x for x in items if x != value]\n',
    "list.remove(value) takes out only the FIRST copy and raises when there is none — the comprehension removes every copy, never raises, and leaves the original list alone.",
    'O(n).');
  window.PYTESTS[window.PYTESTS.length - 1].setup = 'def _original_kept():\n    given = [1, 2, 1]\n    without(given, 1)\n    return given == [1, 2, 1]\n';

  P('st-dedupe', 'Remove duplicates, keep the order', 'unique',
    'Write a function called unique that gives back a new list with duplicates removed, keeping the first appearance of each.',
    'def unique(items: list) -> list',
    'def unique(items):\n    # your code here\n    pass\n',
    [{ in: 'unique([3, 1, 3, 2, 1])', out: '[3, 1, 2]' }],
    [{ call: 'unique([3, 1, 3, 2, 1])', expect: '[3, 1, 2]' },
     { call: 'unique([])', expect: '[]' },
     { call: 'unique([1, 1, 1])', expect: '[1]' },
     { call: "unique(['b', 'a', 'b'])", expect: "['b', 'a']", hidden: true, name: 'order of first appearance' },
     { call: 'unique([1, 2, 3])', expect: '[1, 2, 3]', hidden: true, name: 'nothing to remove' }],
    'list(dict.fromkeys(items)) keeps the order — or loop with a seen set.',
    'def unique(items):\n    return list(dict.fromkeys(items))\n',
    "set(items) would also remove duplicates but loses the order, which is why the tests check the order of first appearance. dict.fromkeys works because dictionaries keep insertion order and cannot hold a key twice.",
    'O(n).');

  P('st-index-of', 'Where is it', 'index_of',
    'Write a function called index_of that gives back the position of the first copy of a value, or -1 when it is not there.',
    'def index_of(items: list, value) -> int',
    'def index_of(items, value):\n    # your code here\n    pass\n',
    [{ in: 'index_of([10, 20, 30], 20)', out: '1' }],
    [{ call: 'index_of([10, 20, 30], 20)', expect: '1' },
     { call: 'index_of([10, 20], 99)', expect: '-1', name: 'not there' },
     { call: 'index_of([], 1)', expect: '-1' },
     { call: 'index_of([5, 5, 5], 5)', expect: '0', hidden: true, name: 'the FIRST one' },
     { call: "index_of(['a', 'b'], 'b')", expect: '1', hidden: true }],
    'Check with in first, because .index() raises when the value is missing.',
    'def index_of(items, value):\n    if value not in items:\n        return -1\n    return items.index(value)\n',
    "`.index()` raises ValueError when the value is absent, so the check has to come first. Counting from zero means the second item is at position 1 — the same rule as everywhere else.",
    'O(n).');

  P('st-sum-slice', 'Total the first few', 'total_first',
    'Write a function called total_first that adds up the first n numbers of a list.\n\nIf n is bigger than the list, add up what there is.',
    'def total_first(nums: list, n: int) -> float',
    'def total_first(nums, n):\n    # your code here\n    pass\n',
    [{ in: 'total_first([1, 2, 3, 4], 2)', out: '3' }],
    [{ call: 'total_first([1, 2, 3, 4], 2)', expect: '3' },
     { call: 'total_first([1, 2], 5)', expect: '3', name: 'more than there is' },
     { call: 'total_first([1, 2, 3], 0)', expect: '0', name: 'none of them' },
     { call: 'total_first([], 3)', expect: '0', hidden: true },
     { call: 'total_first([5], 1)', expect: '5', hidden: true }],
    'Slice first, then sum: sum(nums[:n]).',
    'def total_first(nums, n):\n    return sum(nums[:n])\n',
    'Two things you know, in one line — and both the awkward cases handle themselves, because slicing past the end is safe and sum of nothing is 0.',
    'O(n).');

  P('st-pairs', 'Pair two lists up', 'pair_up',
    'Write a function called pair_up that turns two lists into a list of pairs.\n\nStop at the shorter list.',
    'def pair_up(a: list, b: list) -> list',
    'def pair_up(a, b):\n    # your code here\n    pass\n',
    [{ in: "pair_up(['x', 'y'], [1, 2])", out: "[('x', 1), ('y', 2)]" }],
    [{ call: "pair_up(['x', 'y'], [1, 2])", expect: "[('x', 1), ('y', 2)]" },
     { call: "pair_up(['x'], [1, 2, 3])", expect: "[('x', 1)]", name: 'stops at the shorter one' },
     { call: 'pair_up([], [1])', expect: '[]' },
     { call: 'pair_up([1, 2], [])', expect: '[]', hidden: true },
     { call: "len(pair_up(['a', 'b', 'c'], [1, 2, 3]))", expect: '3', hidden: true }],
    'zip(a, b) pairs them; wrap it in list() to see them.',
    'def pair_up(a, b):\n    return list(zip(a, b))\n',
    'zip stops at the shorter input without complaining, which is exactly what was asked for here — but is worth remembering as a silent trap when you expected the lists to match.',
    'O(n).');

  P('st-running', 'A running total', 'running_total',
    'Write a function called running_total that gives back a list of totals so far, one per position.',
    'def running_total(nums: list) -> list',
    'def running_total(nums):\n    # your code here\n    pass\n',
    [{ in: 'running_total([1, 2, 3])', out: '[1, 3, 6]' }],
    [{ call: 'running_total([1, 2, 3])', expect: '[1, 3, 6]' },
     { call: 'running_total([])', expect: '[]', name: 'nothing to total' },
     { call: 'running_total([5])', expect: '[5]' },
     { call: 'running_total([1, -1, 1])', expect: '[1, 0, 1]', hidden: true, name: 'it can go back down' },
     { call: 'len(running_total([1, 2, 3, 4]))', expect: '4', hidden: true, name: 'one entry per item' }],
    'Keep a total as you loop, appending it after each addition.',
    'def running_total(nums):\n    out = []\n    total = 0\n    for n in nums:\n        total += n\n        out.append(total)\n    return out\n',
    'The totalling loop and the collecting loop at the same time: add, then append. The output is always the same length as the input, which the hidden test pins down. itertools.accumulate(nums) is the library version.',
    'O(n).');

  P('st-shares', 'Each one as a percentage', 'shares',
    'Write a function called shares that turns a list of numbers into their percentages of the total, each rounded to 1 decimal place.\n\nAn empty list gives an empty list, and a total of 0 gives all zeros.',
    'def shares(nums: list) -> list',
    'def shares(nums):\n    # your code here\n    pass\n',
    [{ in: 'shares([1, 3])', out: '[25.0, 75.0]' }],
    [{ call: 'shares([1, 3])', expect: '[25.0, 75.0]' },
     { call: 'shares([])', expect: '[]' },
     { call: 'shares([0, 0])', expect: '[0.0, 0.0]', name: 'no total to share out' },
     { call: 'shares([2, 2, 2, 2])', expect: '[25.0, 25.0, 25.0, 25.0]', hidden: true },
     { call: 'sum(shares([1, 2, 3]))', expect: '100.0', hidden: true, name: 'they add up to 100' }],
    'Work out the total first, guard it being 0, then divide each number by it.',
    'def shares(nums):\n    total = sum(nums)\n    if total == 0:\n        return [0.0 for _ in nums]\n    return [round(100 * n / total, 1) for n in nums]\n',
    'A guard and a comprehension together. The all-zeros case is the one people forget — and it has to give back a list of the right LENGTH, not an empty one.',
    'O(n).');

  /* ---------------- dictionaries and records ---------------- */
  P('st-invert', 'Turn a dictionary inside out', 'invert',
    'Write a function called invert that swaps the keys and values of a dictionary.\n\nYou can assume the values are unique.',
    'def invert(d: dict) -> dict',
    'def invert(d):\n    # your code here\n    pass\n',
    [{ in: "invert({'a': 1, 'b': 2})", out: "{1: 'a', 2: 'b'}" }],
    [{ call: "invert({'a': 1, 'b': 2})", expect: "{1: 'a', 2: 'b'}" },
     { call: 'invert({})', expect: '{}' },
     { call: "invert({'only': 'one'})", expect: "{'one': 'only'}" },
     { call: "len(invert({'a': 1, 'b': 2, 'c': 3}))", expect: '3', hidden: true },
     { call: "invert({'a': 1, 'b': 1})", expect: "{1: 'b'}", hidden: true, name: 'a repeated value keeps the last key' }],
    'A dictionary comprehension: {value: key for key, value in d.items()}.',
    'def invert(d):\n    return {value: key for key, value in d.items()}\n',
    'A dictionary comprehension has the same shape as a list one, with a key and a value. The hidden test shows why "values are unique" was in the brief: a repeated value can only end up pointing at one key, and it is the last one seen.',
    'O(n).');

  P('st-merge-dicts', 'Merge two dictionaries', 'merge',
    'Write a function called merge that combines two dictionaries into a new one, with the second winning any clash.\n\nNeither input may change.',
    'def merge(a: dict, b: dict) -> dict',
    'def merge(a, b):\n    # your code here\n    pass\n',
    [{ in: "merge({'x': 1}, {'y': 2})", out: "{'x': 1, 'y': 2}" }],
    [{ call: "merge({'x': 1}, {'y': 2})", expect: "{'x': 1, 'y': 2}" },
     { call: "merge({'x': 1}, {'x': 9})", expect: "{'x': 9}", name: 'the second one wins' },
     { call: 'merge({}, {})', expect: '{}' },
     { call: '_inputs_kept()', expect: 'True', hidden: true, name: 'neither input changes' },
     { call: "merge({'a': 1}, {})", expect: "{'a': 1}", hidden: true }],
    'Copy the first, then update the copy with the second.',
    'def merge(a, b):\n    out = dict(a)\n    out.update(b)\n    return out\n',
    "The order decides who wins a clash — update(b) means b overwrites. On Python 3.9 and later {**a, **b} and a | b do the same thing in one expression.",
    'O(n).');
  window.PYTESTS[window.PYTESTS.length - 1].setup = "def _inputs_kept():\n    x, y = {'k': 1}, {'k': 2}\n    merge(x, y)\n    return x == {'k': 1} and y == {'k': 2}\n";

  P('st-group-by-letter', 'Group words by first letter', 'group_by_letter',
    'Write a function called group_by_letter that groups words into a dictionary keyed by their first letter, in lower case.\n\nEmpty strings are skipped.',
    'def group_by_letter(words: list) -> dict',
    'def group_by_letter(words):\n    # your code here\n    pass\n',
    [{ in: "group_by_letter(['ant', 'bee', 'ape'])", out: "{'a': ['ant', 'ape'], 'b': ['bee']}" }],
    [{ call: "group_by_letter(['ant', 'bee', 'ape'])", expect: "{'a': ['ant', 'ape'], 'b': ['bee']}" },
     { call: 'group_by_letter([])', expect: '{}' },
     { call: "group_by_letter(['Ant', 'ape'])", expect: "{'a': ['Ant', 'ape']}", name: 'the key is lower case, the word is not changed' },
     { call: "group_by_letter([''])", expect: '{}', hidden: true, name: 'empty words are skipped' },
     { call: "len(group_by_letter(['a', 'b', 'c']))", expect: '3', hidden: true }],
    'Loop, take word[0].lower() as the key, and use setdefault(key, []) before appending.',
    "def group_by_letter(words):\n    groups = {}\n    for word in words:\n        if not word:\n            continue\n        key = word[0].lower()\n        groups.setdefault(key, []).append(word)\n    return groups\n",
    'The grouping pattern: a dictionary whose values are lists. setdefault creates the empty list the first time a letter appears, so the append always has somewhere to go. The skip for empty words has to come first, or word[0] raises IndexError.',
    'O(n).');

  P('st-sort-records', 'Sort records by a field', 'by_score',
    'Write a function called by_score that sorts a list of record dictionaries by their score, highest first.\n\nThe list you were given must not change.',
    'def by_score(rows: list) -> list',
    'def by_score(rows):\n    # your code here\n    pass\n',
    [{ in: "by_score([{'name': 'A', 'score': 1}, {'name': 'B', 'score': 9}])", out: "B first, then A" }],
    [{ call: "[r['name'] for r in by_score([{'name': 'A', 'score': 1}, {'name': 'B', 'score': 9}])]", expect: "['B', 'A']" },
     { call: 'by_score([])', expect: '[]' },
     { call: "[r['name'] for r in by_score([{'name': 'A', 'score': 5}])]", expect: "['A']" },
     { call: "[r['name'] for r in by_score([{'name': 'A', 'score': 5}, {'name': 'B', 'score': 5}])]", expect: "['A', 'B']", hidden: true, name: 'a tie keeps the original order' },
     { call: '_rows_kept()', expect: 'True', hidden: true, name: 'the original list is untouched' }],
    "sorted(rows, key=lambda r: r['score'], reverse=True)",
    "def by_score(rows):\n    return sorted(rows, key=lambda r: r['score'], reverse=True)\n",
    "key= tells sorted WHAT to compare while still handing back the whole record. Python's sort is stable, so records with the same score stay in the order they arrived — which the hidden test relies on.",
    'O(n log n).');
  window.PYTESTS[window.PYTESTS.length - 1].setup = "def _rows_kept():\n    rows = [{'name': 'A', 'score': 1}, {'name': 'B', 'score': 9}]\n    by_score(rows)\n    return rows[0]['name'] == 'A'\n";

  P('st-count-field', 'Count records by a field', 'count_by_city',
    'Write a function called count_by_city that counts how many records there are for each city.\n\nA record with no city counts under the word unknown.',
    'def count_by_city(rows: list) -> dict',
    'def count_by_city(rows):\n    # your code here\n    pass\n',
    [{ in: "count_by_city([{'city': 'Leeds'}, {'city': 'Leeds'}, {'city': 'York'}])", out: "{'Leeds': 2, 'York': 1}" }],
    [{ call: "count_by_city([{'city': 'Leeds'}, {'city': 'Leeds'}, {'city': 'York'}])", expect: "{'Leeds': 2, 'York': 1}" },
     { call: 'count_by_city([])', expect: '{}' },
     { call: "count_by_city([{'name': 'Ann'}])", expect: "{'unknown': 1}", name: 'no city recorded' },
     { call: "count_by_city([{'city': 'Leeds'}, {'name': 'Bob'}])", expect: "{'Leeds': 1, 'unknown': 1}", hidden: true },
     { call: "len(count_by_city([{'city': 'A'}, {'city': 'B'}]))", expect: '2', hidden: true }],
    "Loop the rows, take row.get('city', 'unknown'), and tally it with counts.get(key, 0) + 1.",
    "def count_by_city(rows):\n    counts = {}\n    for row in rows:\n        key = row.get('city', 'unknown')\n        counts[key] = counts.get(key, 0) + 1\n    return counts\n",
    "The tally pattern with a .get on both sides: one for the missing field, one for the first time a city is seen. This is exactly what df.groupby('city').size() does later, written out in full.",
    'O(n).');

  P('st-field-average', 'Average one field', 'average_score',
    'Write a function called average_score that gives back the average score across a list of records.\n\nRecords without a score are ignored, and an empty result gives 0.',
    'def average_score(rows: list) -> float',
    'def average_score(rows):\n    # your code here\n    pass\n',
    [{ in: "average_score([{'score': 2}, {'score': 4}])", out: '3.0' }],
    [{ call: "average_score([{'score': 2}, {'score': 4}])", expect: '3.0' },
     { call: 'average_score([])', expect: '0' },
     { call: "average_score([{'name': 'Ann'}])", expect: '0', name: 'nothing usable' },
     { call: "average_score([{'score': 5}, {'name': 'Bob'}])", expect: '5.0', hidden: true, name: 'the record with no score is ignored, not counted as zero' },
     { call: "average_score([{'score': 0}, {'score': 0}])", expect: '0.0', hidden: true }],
    'Collect the scores that exist first, then guard the empty case before dividing.',
    "def average_score(rows):\n    scores = [r['score'] for r in rows if 'score' in r]\n    if not scores:\n        return 0\n    return sum(scores) / len(scores)\n",
    "The hidden test is the whole point: a missing score must not count as a zero, or the average is dragged down by records that never had one. Filter first, then divide by how many SURVIVED.",
    'O(n).');

  P('st-field-values', 'The distinct values of a field', 'cities_in',
    'Write a function called cities_in that lists the distinct cities across a list of records, in alphabetical order.\n\nRecords with no city are skipped.',
    'def cities_in(rows: list) -> list',
    'def cities_in(rows):\n    # your code here\n    pass\n',
    [{ in: "cities_in([{'city': 'York'}, {'city': 'Leeds'}, {'city': 'York'}])", out: "['Leeds', 'York']" }],
    [{ call: "cities_in([{'city': 'York'}, {'city': 'Leeds'}, {'city': 'York'}])", expect: "['Leeds', 'York']" },
     { call: 'cities_in([])', expect: '[]' },
     { call: "cities_in([{'name': 'Ann'}])", expect: '[]', name: 'no city, nothing listed' },
     { call: "cities_in([{'city': 'A'}, {'city': 'a'}])", expect: "['A', 'a']", hidden: true, name: 'capitals count as different' },
     { call: "len(cities_in([{'city': 'X'}] * 5))", expect: '1', hidden: true }],
    "Collect the cities that exist into a set, then sorted() it.",
    "def cities_in(rows):\n    found = {r['city'] for r in rows if 'city' in r}\n    return sorted(found)\n",
    "A set comprehension — curly brackets, no key — removes the duplicates, and sorted() turns it into a list in a predictable order. The hidden test is a reminder to standardise case BEFORE you rely on distinct values.",
    'O(n log n).');
})();
