/* For loops, one rung at a time.

   A ladder that does nothing but loops, in the order you meet them:
   walk a list · build a new list · build up one answer · an if inside the loop ·
   keep the best so far · range() · index and enumerate · loop a string ·
   loop a dictionary · loop records and nested lists · break and continue.

   Every rung is one small change from the rung before it. Where a one-line
   built-in would do the job (sum, len, max, ''.join, list, [::-1]) an extra
   test checks the answer really was written as a loop — that is the point of
   the exercise. That check is the helper uses_a_loop(), defined in SETUP. */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var G = 'For loops, one rung at a time';

  /* Runs before the candidate's code. uses_a_loop(f) is True when f's compiled
     body actually iterates, so calling sum() or len() instead cannot pass. */
  var SETUP = [
    'import dis',
    'def uses_a_loop(f):',
    '    return any(i.opname == "FOR_ITER" for i in dis.get_instructions(f))',
    ''
  ].join('\n');

  function P(id, title, fn, brief, sig, starter, examples, tests, hint, solution, walk, complexity) {
    window.PYTESTS.push({ id: id, group: G, lvl: 1, title: title, fn: fn, brief: brief, sig: sig,
      starter: starter, examples: examples, tests: tests, hint: hint, solution: solution, walk: walk,
      setup: SETUP, complexity: complexity || 'O(n) — one pass over the items.' });
  }
  /* The "you must write the loop" test, phrased the same way everywhere. */
  function loopCheck(fn) {
    return { call: 'uses_a_loop(' + fn + ')', expect: 'True', name: 'written as a loop, not a built-in' };
  }
  function stub(sig) { return 'def ' + sig + ':\n    # your code here\n    pass\n'; }

  /* ============ A · walk the items and build a new list ============ */

  P('lp-copy', 'Walk a list, item by item', 'copy_list',
    'Write a function called copy_list that walks through the items with a for loop and gives back a new list holding the same items, in the same order. One of the tests checks you really looped rather than copying the list in one go.',
    'def copy_list(items: list) -> list',
    stub('copy_list(items)'),
    [{ in: 'copy_list([1, 2, 3])', out: '[1, 2, 3]' }],
    [{ call: 'copy_list([1, 2, 3])', expect: '[1, 2, 3]' },
     { call: 'copy_list([])', expect: '[]', name: 'nothing to walk' },
     { call: "copy_list(['a'])", expect: "['a']" },
     loopCheck('copy_list'),
     { call: '(lambda a: copy_list(a) is a)([1, 2])', expect: 'False', hidden: true, name: 'a new list, not the same one' }],
    'out = []  then  for item in items:  then  out.append(item)  then  return out.',
    'def copy_list(items):\n    out = []\n    for item in items:\n        out.append(item)\n    return out\n',
    'This is the shape you will use for the rest of your life: an empty list before the loop, one append inside it, a return after it. Nothing is changed on the way through yet — every rung from here changes just the line inside the loop.');

  P('lp-shout-each', 'Shout every word', 'shout_each',
    'Write a function called shout_each that gives back a new list with every word in CAPITALS. Same loop as before — one method call added inside it.',
    'def shout_each(words: list) -> list',
    stub('shout_each(words)'),
    [{ in: "shout_each(['dog', 'cat'])", out: "['DOG', 'CAT']" }],
    [{ call: "shout_each(['dog', 'cat'])", expect: "['DOG', 'CAT']" },
     { call: 'shout_each([])', expect: '[]' },
     { call: "shout_each(['a'])", expect: "['A']" },
     { call: "shout_each(['Mixed Case'])", expect: "['MIXED CASE']", hidden: true },
     { call: "shout_each(['one', 'two', 'three'])", expect: "['ONE', 'TWO', 'THREE']", hidden: true }],
    'out.append(word.upper()) — the only change from copy_list.',
    'def shout_each(words):\n    out = []\n    for word in words:\n        out.append(word.upper())\n    return out\n',
    'One word of difference from the last problem: .upper() on the way into the list. Change what goes inside append and you change what the loop builds.');

  P('lp-add-one-each', 'One more, all the way down', 'add_one_each',
    'Write a function called add_one_each that gives back a new list with every number one bigger.',
    'def add_one_each(nums: list) -> list',
    stub('add_one_each(nums)'),
    [{ in: 'add_one_each([1, 2, 3])', out: '[2, 3, 4]' }],
    [{ call: 'add_one_each([1, 2, 3])', expect: '[2, 3, 4]' },
     { call: 'add_one_each([])', expect: '[]' },
     { call: 'add_one_each([-1])', expect: '[0]', name: 'negatives count too' },
     { call: 'add_one_each([0, 0])', expect: '[1, 1]', hidden: true },
     { call: 'add_one_each([1.5])', expect: '[2.5]', hidden: true }],
    'out.append(n + 1).',
    'def add_one_each(nums):\n    out = []\n    for n in nums:\n        out.append(n + 1)\n    return out\n',
    'The loop is untouched again. Notice the loop variable is called n now, not word — the name is yours to choose, and a good one says what a single item is.');

  P('lp-double-each', 'Twice as much, all the way down', 'double_each',
    'Write a function called double_each that gives back a new list with every number doubled.',
    'def double_each(nums: list) -> list',
    stub('double_each(nums)'),
    [{ in: 'double_each([1, 2, 3])', out: '[2, 4, 6]' }],
    [{ call: 'double_each([1, 2, 3])', expect: '[2, 4, 6]' },
     { call: 'double_each([])', expect: '[]' },
     { call: 'double_each([-2])', expect: '[-4]' },
     { call: 'double_each([0])', expect: '[0]', hidden: true },
     { call: 'double_each([1.5, 2.5])', expect: '[3.0, 5.0]', hidden: true }],
    'out.append(n * 2).',
    'def double_each(nums):\n    out = []\n    for n in nums:\n        out.append(n * 2)\n    return out\n',
    'Third time with the same skeleton, on purpose. When the shape is automatic you stop thinking about the loop and start thinking about the one line inside it.');

  P('lp-lengths', 'How long is each one', 'lengths',
    'Write a function called lengths that gives back a list of how many characters are in each word.',
    'def lengths(words: list) -> list',
    stub('lengths(words)'),
    [{ in: "lengths(['dog', 'horse'])", out: '[3, 5]' }],
    [{ call: "lengths(['dog', 'horse'])", expect: '[3, 5]' },
     { call: 'lengths([])', expect: '[]' },
     { call: "lengths([''])", expect: '[0]', name: 'an empty word is length 0' },
     { call: "lengths(['a', 'bb', 'ccc'])", expect: '[1, 2, 3]', hidden: true }],
    'out.append(len(word)).',
    'def lengths(words):\n    out = []\n    for word in words:\n        out.append(len(word))\n    return out\n',
    'The list that comes out does not have to hold the same kind of thing as the list that went in: words go in, numbers come out.');

  P('lp-greet-each', 'Say hello to everyone', 'greet_each',
    "Write a function called greet_each that turns each name into 'Hello, NAME' — for example 'Ana' becomes 'Hello, Ana'.",
    'def greet_each(names: list) -> list',
    stub('greet_each(names)'),
    [{ in: "greet_each(['Ana', 'Bo'])", out: "['Hello, Ana', 'Hello, Bo']" }],
    [{ call: "greet_each(['Ana', 'Bo'])", expect: "['Hello, Ana', 'Hello, Bo']" },
     { call: 'greet_each([])', expect: '[]' },
     { call: "greet_each(['Sam'])", expect: "['Hello, Sam']" },
     { call: "greet_each(['Ana', 'Bo', 'Cai'])", expect: "['Hello, Ana', 'Hello, Bo', 'Hello, Cai']", hidden: true }],
    "out.append(f'Hello, {name}') — mind the comma and the space.",
    "def greet_each(names):\n    out = []\n    for name in names:\n        out.append(f'Hello, {name}')\n    return out\n",
    'An f-string inside the loop. The tests are fussy about the exact punctuation, which is realistic: a report that says "Hello,Ana" is a bug someone will report.');

  /* ============ B · build up one answer as you go ============ */

  P('lp-count', 'Count them by hand', 'count_items',
    'Write a function called count_items that gives back how many items are in the list — counted with a loop, not with len(). Start a counter at 0 and add one each time round.',
    'def count_items(items: list) -> int',
    stub('count_items(items)'),
    [{ in: 'count_items([1, 2, 3])', out: '3' }],
    [{ call: 'count_items([1, 2, 3])', expect: '3' },
     { call: 'count_items([])', expect: '0', name: 'an empty list counts 0' },
     { call: "count_items(['a'])", expect: '1' },
     loopCheck('count_items'),
     { call: 'count_items([0, 0, 0, 0])', expect: '4', hidden: true, name: 'zeros are still items' }],
    'n = 0 before the loop, n = n + 1 inside it, return n after it.',
    'def count_items(items):\n    n = 0\n    for item in items:\n        n = n + 1\n    return n\n',
    'The other half of the pattern: instead of building a list you build a single number. The variable is set up before the loop, changed inside it, and returned after it. len() would be the real answer at work — here you are learning what len() is doing.');

  P('lp-total', 'Add them up by hand', 'total_up',
    'Write a function called total_up that adds up the numbers with a loop — no sum(). An empty list totals 0.',
    'def total_up(nums: list) -> float',
    stub('total_up(nums)'),
    [{ in: 'total_up([1, 2, 3])', out: '6' }],
    [{ call: 'total_up([1, 2, 3])', expect: '6' },
     { call: 'total_up([])', expect: '0', name: 'nothing adds up to nothing' },
     { call: 'total_up([-1, 1])', expect: '0' },
     loopCheck('total_up'),
     { call: 'total_up([2.5, 2.5])', expect: '5.0', hidden: true }],
    'running = 0 before the loop, running = running + n inside it.',
    'def total_up(nums):\n    running = 0\n    for n in nums:\n        running = running + n\n    return running\n',
    'Same skeleton as counting, with n instead of 1 added each time. Starting at 0 is what makes the empty list give 0 for free — you do not need a special case for it.');

  P('lp-product', 'Multiply them all together', 'product',
    'Write a function called product that multiplies all the numbers together. An empty list gives back 1.',
    'def product(nums: list) -> float',
    stub('product(nums)'),
    [{ in: 'product([2, 3, 4])', out: '24' }],
    [{ call: 'product([2, 3, 4])', expect: '24' },
     { call: 'product([])', expect: '1', name: 'nothing multiplied is 1' },
     { call: 'product([5])', expect: '5' },
     { call: 'product([2, 0, 9])', expect: '0', hidden: true, name: 'one zero and it is all over' },
     { call: 'product([-2, 3])', expect: '-6', hidden: true }],
    'Start at 1, not 0 — starting at 0 would make every answer 0.',
    'def product(nums):\n    running = 1\n    for n in nums:\n        running = running * n\n    return running\n',
    'The one thing that changes from total_up is the starting value. Adding starts at 0 because 0 changes nothing when you add it; multiplying starts at 1 for exactly the same reason.');

  P('lp-total-letters', 'How many letters altogether', 'total_letters',
    'Write a function called total_letters that adds up the lengths of all the words.',
    'def total_letters(words: list) -> int',
    stub('total_letters(words)'),
    [{ in: "total_letters(['dog', 'cat'])", out: '6' }],
    [{ call: "total_letters(['dog', 'cat'])", expect: '6' },
     { call: 'total_letters([])', expect: '0' },
     { call: "total_letters([''])", expect: '0', name: 'one empty word' },
     { call: "total_letters(['a', 'bb', 'ccc'])", expect: '6', hidden: true }],
    'running = running + len(word).',
    'def total_letters(words):\n    running = 0\n    for word in words:\n        running = running + len(word)\n    return running\n',
    'Two ideas you already have, stacked: measure each item (len) and add the measurement to a running total. Most real loops are two or three small ideas stacked like this.');

  P('lp-join-all', 'Glue the words into one string', 'join_all',
    "Write a function called join_all that sticks all the words together into a single string, with nothing between them — no ''.join(). An empty list gives back an empty string.",
    'def join_all(words: list) -> str',
    stub('join_all(words)'),
    [{ in: "join_all(['a', 'b', 'c'])", out: "'abc'" }],
    [{ call: "join_all(['a', 'b', 'c'])", expect: "'abc'" },
     { call: 'join_all([])', expect: "''", name: 'nothing glued is an empty string' },
     { call: "join_all(['hi'])", expect: "'hi'" },
     loopCheck('join_all'),
     { call: "join_all(['one', 'two', 'three'])", expect: "'onetwothree'", hidden: true }],
    "out = '' before the loop, out = out + word inside it.",
    "def join_all(words):\n    out = ''\n    for word in words:\n        out = out + word\n    return out\n",
    "The running total does not have to be a number. Text starts at '' for the same reason numbers start at 0: gluing an empty string on changes nothing.");

  P('lp-average', 'An average, the long way', 'average_of',
    'Write a function called average_of that gives back the mean of the numbers, working out the total with a loop first. An empty list gives back 0.0 rather than crashing.',
    'def average_of(nums: list) -> float',
    stub('average_of(nums)'),
    [{ in: 'average_of([2, 4])', out: '3.0' }],
    [{ call: 'average_of([2, 4])', expect: '3.0' },
     { call: 'average_of([])', expect: '0.0', name: 'no crash on an empty list' },
     { call: 'average_of([5])', expect: '5.0' },
     { call: 'average_of([1, 2, 3, 4])', expect: '2.5', hidden: true },
     { call: 'average_of([-2, 2])', expect: '0.0', hidden: true }],
    'Loop up the total, then guard: if there are no numbers, return 0.0 before you divide.',
    'def average_of(nums):\n    if not nums:\n        return 0.0\n    running = 0\n    for n in nums:\n        running = running + n\n    return running / len(nums)\n',
    'The guard comes first because dividing by zero raises ZeroDivisionError, and a report that crashes on an empty day is worse than one that shows 0.0. Notice the division happens after the loop, not inside it.');

  /* ============ C · an if inside the loop ============ */

  P('lp-count-positives', 'Count only the ones above zero', 'count_positives',
    'Write a function called count_positives that counts how many of the numbers are above zero. Zero itself does not count.',
    'def count_positives(nums: list) -> int',
    stub('count_positives(nums)'),
    [{ in: 'count_positives([1, -2, 3])', out: '2' }],
    [{ call: 'count_positives([1, -2, 3])', expect: '2' },
     { call: 'count_positives([])', expect: '0' },
     { call: 'count_positives([-1, -2])', expect: '0' },
     { call: 'count_positives([0, 1])', expect: '1', name: 'zero is not above zero' },
     { call: 'count_positives([5, 5, 5])', expect: '3', hidden: true }],
    'Put an if inside the loop and only add one when the test passes.',
    'def count_positives(nums):\n    n = 0\n    for x in nums:\n        if x > 0:\n            n = n + 1\n    return n\n',
    'The new idea is the second level of indent: for, then if, then the work. Everything under the if only happens for the items that pass, and the loop carries on regardless.');

  P('lp-keep-positives', 'Keep only the ones above zero', 'keep_positives',
    'Write a function called keep_positives that gives back a new list holding only the numbers above zero, in the order they came.',
    'def keep_positives(nums: list) -> list',
    stub('keep_positives(nums)'),
    [{ in: 'keep_positives([1, -2, 3])', out: '[1, 3]' }],
    [{ call: 'keep_positives([1, -2, 3])', expect: '[1, 3]' },
     { call: 'keep_positives([])', expect: '[]' },
     { call: 'keep_positives([-1])', expect: '[]', name: 'everything filtered out' },
     { call: 'keep_positives([0, 2])', expect: '[2]', hidden: true },
     { call: 'keep_positives([4, 5])', expect: '[4, 5]', hidden: true }],
    'Same if as the last one, but append instead of counting.',
    'def keep_positives(nums):\n    out = []\n    for x in nums:\n        if x > 0:\n            out.append(x)\n    return out\n',
    'The two halves you have learned, joined: build-a-list from part A, if-inside-the-loop from the last problem. Counting and filtering are the same walk with a different line inside the if.');

  P('lp-count-over', 'How many beat the bar', 'count_over',
    'Write a function called count_over that takes a list of numbers and a bar, and counts how many are strictly above the bar. Something exactly on the bar does not count.',
    'def count_over(nums: list, bar: float) -> int',
    stub('count_over(nums, bar)'),
    [{ in: 'count_over([1, 5, 9], 4)', out: '2' }],
    [{ call: 'count_over([1, 5, 9], 4)', expect: '2' },
     { call: 'count_over([], 0)', expect: '0' },
     { call: 'count_over([4, 4], 4)', expect: '0', name: 'on the bar is not over it' },
     { call: 'count_over([10], 1)', expect: '1', hidden: true },
     { call: 'count_over([-5, -1], -3)', expect: '1', hidden: true }],
    'if x > bar — the bar is a parameter now, not a fixed 0.',
    'def count_over(nums, bar):\n    n = 0\n    for x in nums:\n        if x > bar:\n            n = n + 1\n    return n\n',
    'One character of difference from count_positives: 0 became bar. The moment a fixed number in your code becomes a parameter, one function does a hundred jobs.');

  P('lp-long-words', 'Words longer than that', 'long_words',
    'Write a function called long_words that keeps only the words with more than n characters. A word exactly n long does not make the cut.',
    'def long_words(words: list, n: int) -> list',
    stub('long_words(words, n)'),
    [{ in: "long_words(['a', 'abcd'], 3)", out: "['abcd']" }],
    [{ call: "long_words(['a', 'abcd'], 3)", expect: "['abcd']" },
     { call: 'long_words([], 1)', expect: '[]' },
     { call: "long_words(['abc'], 3)", expect: '[]', name: 'exactly three is not more than three' },
     { call: "long_words(['hello', 'hi', 'there'], 2)", expect: "['hello', 'there']", hidden: true }],
    'if len(word) > n: out.append(word).',
    'def long_words(words, n):\n    out = []\n    for word in words:\n        if len(word) > n:\n            out.append(word)\n    return out\n',
    'The test inside the if can be any expression at all, including a call like len(word). Read it out loud — "if the length of the word is more than n, keep it" — and the code is the sentence.');

  P('lp-total-positive', 'Total only the good news', 'total_positive',
    'Write a function called total_positive that adds up only the numbers above zero and ignores the rest.',
    'def total_positive(nums: list) -> float',
    stub('total_positive(nums)'),
    [{ in: 'total_positive([1, -5, 4])', out: '5' }],
    [{ call: 'total_positive([1, -5, 4])', expect: '5' },
     { call: 'total_positive([])', expect: '0' },
     { call: 'total_positive([-1])', expect: '0', name: 'nothing qualifies' },
     { call: 'total_positive([0, 3])', expect: '3', hidden: true },
     { call: 'total_positive([2.5, -2.5])', expect: '2.5', hidden: true }],
    'A running total with an if in front of the addition.',
    'def total_positive(nums):\n    running = 0\n    for x in nums:\n        if x > 0:\n            running = running + x\n    return running\n',
    'Third variation on the same walk: count them, keep them, or total them. Once you see that the loop and the if never change, only the line inside, most of these stop being separate problems.');

  P('lp-drop-blanks', 'Throw away the blank ones', 'drop_blanks',
    'Write a function called drop_blanks that tidies each entry with .strip() and keeps only the ones that still have something in them.',
    'def drop_blanks(words: list) -> list',
    stub('drop_blanks(words)'),
    [{ in: "drop_blanks(['a', '  ', 'b'])", out: "['a', 'b']" }],
    [{ call: "drop_blanks(['a', '  ', 'b'])", expect: "['a', 'b']" },
     { call: 'drop_blanks([])', expect: '[]' },
     { call: "drop_blanks(['  '])", expect: '[]', name: 'spaces only is blank' },
     { call: "drop_blanks([' hi '])", expect: "['hi']", hidden: true, name: 'the kept one comes back tidy' },
     { call: "drop_blanks(['', 'x'])", expect: "['x']", hidden: true }],
    'Tidy first into a variable, then test that variable — do not strip twice.',
    "def drop_blanks(words):\n    out = []\n    for word in words:\n        tidy = word.strip()\n        if tidy:\n            out.append(tidy)\n    return out\n",
    'Two lines inside the loop now, and the order matters: clean it, then judge it, then keep the cleaned one. `if tidy:` is Python shorthand for "if there is anything in it" — an empty string counts as False.');

  P('lp-first-over', 'The first one above the bar', 'first_over',
    'Write a function called first_over that gives back the first number above the bar. If none of them beat it, give back None.',
    'def first_over(nums: list, bar: float) -> float',
    stub('first_over(nums, bar)'),
    [{ in: 'first_over([1, 5, 9], 4)', out: '5' }],
    [{ call: 'first_over([1, 5, 9], 4)', expect: '5', name: 'the first, not the biggest' },
     { call: 'first_over([1, 2], 9)', expect: 'None' },
     { call: 'first_over([], 0)', expect: 'None' },
     { call: 'first_over([10, 20], 5)', expect: '10', hidden: true },
     { call: 'first_over([-1, -0.5], -0.8)', expect: '-0.5', hidden: true }],
    'return inside the loop — it stops there and then. The final return None only runs if the loop finished without finding one.',
    'def first_over(nums, bar):\n    for x in nums:\n        if x > bar:\n            return x\n    return None\n',
    'The first rung where the loop can end early. A return inside a loop leaves the function immediately, so 9 is never even looked at. The lone return None at the bottom is the "we got all the way through and found nothing" answer.');

  P('lp-any-over', 'Is any one of them above the bar', 'any_over',
    'Write a function called any_over that gives back True if at least one number is above the bar, and False otherwise.',
    'def any_over(nums: list, bar: float) -> bool',
    stub('any_over(nums, bar)'),
    [{ in: 'any_over([1, 5], 4)', out: 'True' }],
    [{ call: 'any_over([1, 5], 4)', expect: 'True' },
     { call: 'any_over([1, 2], 9)', expect: 'False' },
     { call: 'any_over([], 0)', expect: 'False', name: 'nothing there, so no' },
     { call: 'any_over([4], 4)', expect: 'False', hidden: true },
     { call: 'any_over([9, 9], 1)', expect: 'True', hidden: true }],
    'return True as soon as you find one; return False after the loop.',
    'def any_over(nums, bar):\n    for x in nums:\n        if x > bar:\n            return True\n    return False\n',
    'The same shape as first_over with True in place of the value. This is exactly how the built-in any() works, and writing it once is the best way to remember what it does.');

  P('lp-all-positive', 'Are they all above zero', 'all_positive',
    'Write a function called all_positive that gives back True only if every number is above zero. An empty list counts as True — there is nothing in it to break the rule.',
    'def all_positive(nums: list) -> bool',
    stub('all_positive(nums)'),
    [{ in: 'all_positive([1, 2])', out: 'True' }],
    [{ call: 'all_positive([1, 2])', expect: 'True' },
     { call: 'all_positive([1, -1])', expect: 'False' },
     { call: 'all_positive([])', expect: 'True', name: 'nothing breaks the rule' },
     { call: 'all_positive([0])', expect: 'False', hidden: true, name: 'zero is not above zero' },
     { call: 'all_positive([-1, -1])', expect: 'False', hidden: true }],
    'This one is upside down: return False the moment you find a bad one, and True only after the loop survives to the end.',
    'def all_positive(nums):\n    for x in nums:\n        if x <= 0:\n            return False\n    return True\n',
    'Flipping "any" gives "all": look for a counter-example, and if the loop finishes without finding one, the answer is yes. Getting the empty case right falls out of the shape for free.');

  /* ============ D · keep the best one seen so far ============ */

  P('lp-biggest', 'The biggest, found by hand', 'biggest',
    'Write a function called biggest that finds the largest number with a loop — no max(). An empty list gives back None.',
    'def biggest(nums: list) -> float',
    stub('biggest(nums)'),
    [{ in: 'biggest([3, 9, 4])', out: '9' }],
    [{ call: 'biggest([3, 9, 4])', expect: '9' },
     { call: 'biggest([])', expect: 'None', name: 'nothing to be biggest' },
     { call: 'biggest([5])', expect: '5' },
     loopCheck('biggest'),
     { call: 'biggest([-3, -9])', expect: '-3', hidden: true, name: 'all negative, so the biggest is still negative' }],
    'Start with the first item as the best so far, then walk the rest and replace it whenever you meet something larger.',
    'def biggest(nums):\n    if not nums:\n        return None\n    best = nums[0]\n    for x in nums:\n        if x > best:\n            best = x\n    return best\n',
    'A new starting value: not 0, but the first item. Starting at 0 is the classic bug here — a list of all-negative numbers would wrongly answer 0, which is why the negative test exists.');

  P('lp-smallest', 'The smallest, found by hand', 'smallest_of',
    'Write a function called smallest_of that finds the lowest number with a loop — no min(). An empty list gives back None.',
    'def smallest_of(nums: list) -> float',
    stub('smallest_of(nums)'),
    [{ in: 'smallest_of([3, 9, 4])', out: '3' }],
    [{ call: 'smallest_of([3, 9, 4])', expect: '3' },
     { call: 'smallest_of([])', expect: 'None' },
     { call: 'smallest_of([5])', expect: '5' },
     loopCheck('smallest_of'),
     { call: 'smallest_of([2, -7, 0])', expect: '-7', hidden: true }],
    'The mirror of biggest: one < instead of >.',
    'def smallest_of(nums):\n    if not nums:\n        return None\n    best = nums[0]\n    for x in nums:\n        if x < best:\n            best = x\n    return best\n',
    'One character of difference from biggest. Deliberately so — the shape is the thing worth owning, and the comparison is the only decision left.');

  P('lp-longest', 'The longest word', 'longest',
    'Write a function called longest that gives back the longest word. If two are the same length, keep the first one you met. An empty list gives back None.',
    'def longest(words: list) -> str',
    stub('longest(words)'),
    [{ in: "longest(['a', 'abc', 'xy'])", out: "'abc'" }],
    [{ call: "longest(['a', 'abc', 'xy'])", expect: "'abc'" },
     { call: 'longest([])', expect: 'None' },
     { call: "longest(['ab', 'cd'])", expect: "'ab'", name: 'a tie keeps the first' },
     { call: "longest(['hi'])", expect: "'hi'", hidden: true },
     { call: "longest(['', 'x'])", expect: "'x'", hidden: true }],
    'Compare len(word) > len(best), not word > best. Using > rather than >= is what keeps the first of a tie.',
    'def longest(words):\n    if not words:\n        return None\n    best = words[0]\n    for word in words:\n        if len(word) > len(best):\n            best = word\n    return best\n',
    'Best-so-far again, but you compare a measurement and keep the item. That split — judge by one thing, return another — is most of what "find the top row" means in real work.');

  P('lp-where-biggest', 'Where the biggest one is', 'where_biggest',
    'Write a function called where_biggest that gives back the position of the largest number, counting from 0. On a tie give the earliest position. An empty list gives back -1.',
    'def where_biggest(nums: list) -> int',
    stub('where_biggest(nums)'),
    [{ in: 'where_biggest([3, 9, 4])', out: '1' }],
    [{ call: 'where_biggest([3, 9, 4])', expect: '1' },
     { call: 'where_biggest([])', expect: '-1' },
     { call: 'where_biggest([5])', expect: '0', name: 'the only item is at position 0' },
     { call: 'where_biggest([1, 9, 9])', expect: '1', hidden: true, name: 'earliest of a tie' },
     { call: 'where_biggest([-1, -2])', expect: '0', hidden: true }],
    'Track two things: the best value so far and where you found it. Update both together.',
    'def where_biggest(nums):\n    if not nums:\n        return -1\n    best = nums[0]\n    where = 0\n    for i in range(len(nums)):\n        if nums[i] > best:\n            best = nums[i]\n            where = i\n    return where\n',
    'Two variables changing together inside the loop, and the first sight of range(len(...)) — you loop over the positions because the position is part of the answer. Section F does this properly with enumerate.');

  /* ============ E · range(): loop when there is no list yet ============ */

  P('lp-numbers-to', 'Count from one to n', 'numbers_to',
    'Write a function called numbers_to that gives back the list [1, 2, 3, ... n]. If n is 0 or less, give back an empty list.',
    'def numbers_to(n: int) -> list',
    stub('numbers_to(n)'),
    [{ in: 'numbers_to(3)', out: '[1, 2, 3]' }],
    [{ call: 'numbers_to(3)', expect: '[1, 2, 3]' },
     { call: 'numbers_to(0)', expect: '[]', name: 'nothing to count' },
     { call: 'numbers_to(1)', expect: '[1]' },
     { call: 'numbers_to(5)', expect: '[1, 2, 3, 4, 5]', hidden: true },
     { call: 'numbers_to(-2)', expect: '[]', hidden: true }],
    'range(1, n + 1) — the stop value is never reached, so you have to go one past.',
    'def numbers_to(n):\n    out = []\n    for i in range(1, n + 1):\n        out.append(i)\n    return out\n',
    'Until now every loop needed a list to walk. range() makes the numbers for you. The off-by-one is the whole lesson: range(1, 4) gives 1, 2, 3 — it stops before the stop.');

  P('lp-sum-to', 'Add up one to n', 'sum_to',
    'Write a function called sum_to that adds up every whole number from 1 to n. sum_to(0) is 0.',
    'def sum_to(n: int) -> int',
    stub('sum_to(n)'),
    [{ in: 'sum_to(3)', out: '6' }],
    [{ call: 'sum_to(3)', expect: '6' },
     { call: 'sum_to(0)', expect: '0' },
     { call: 'sum_to(1)', expect: '1' },
     { call: 'sum_to(10)', expect: '55', hidden: true },
     { call: 'sum_to(-3)', expect: '0', hidden: true, name: 'a negative n loops zero times' }],
    'A running total over range(1, n + 1).',
    'def sum_to(n):\n    running = 0\n    for i in range(1, n + 1):\n        running = running + i\n    return running\n',
    'The accumulator from part B over a range instead of a list. Note what happens with a negative n: range(1, -2) is simply empty, the loop body never runs, and 0 comes back without any special case.');

  P('lp-times-table', 'A times table', 'times_table',
    'Write a function called times_table that gives back the first ten multiples of n — so times_table(3) is [3, 6, 9, ... 30].',
    'def times_table(n: int) -> list',
    stub('times_table(n)'),
    [{ in: 'times_table(3)', out: '[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]' }],
    [{ call: 'times_table(3)', expect: '[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]' },
     { call: 'times_table(1)', expect: '[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]' },
     { call: 'times_table(0)', expect: '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]', name: 'ten zeros' },
     { call: 'len(times_table(7))', expect: '10', hidden: true, name: 'always ten of them' },
     { call: 'times_table(-2)', expect: '[-2, -4, -6, -8, -10, -12, -14, -16, -18, -20]', hidden: true }],
    'for i in range(1, 11) — 11 so that 10 is included.',
    'def times_table(n):\n    out = []\n    for i in range(1, 11):\n        out.append(n * i)\n    return out\n',
    'The range is fixed and the multiplier comes from the parameter. Ten items every time, whatever n is — which is what the hidden len() test is checking.');

  P('lp-evens-to', 'Every even number up to n', 'evens_to',
    'Write a function called evens_to that gives back the even numbers from 2 up to and including n.',
    'def evens_to(n: int) -> list',
    stub('evens_to(n)'),
    [{ in: 'evens_to(6)', out: '[2, 4, 6]' }],
    [{ call: 'evens_to(6)', expect: '[2, 4, 6]' },
     { call: 'evens_to(1)', expect: '[]', name: 'no evens below 2' },
     { call: 'evens_to(2)', expect: '[2]' },
     { call: 'evens_to(9)', expect: '[2, 4, 6, 8]', hidden: true, name: 'stops below an odd n' },
     { call: 'evens_to(0)', expect: '[]', hidden: true }],
    'range(2, n + 1, 2) — the third number is the step. An if with % 2 works too.',
    'def evens_to(n):\n    out = []\n    for i in range(2, n + 1, 2):\n        out.append(i)\n    return out\n',
    'The third argument to range is how far to jump each time. Two right answers here: step by 2, or step by 1 and skip the odd ones with an if — the stepping version does half the work.');

  P('lp-countdown', 'Count backwards', 'countdown',
    'Write a function called countdown that gives back [n, n-1, ... 1]. countdown(0) is an empty list.',
    'def countdown(n: int) -> list',
    stub('countdown(n)'),
    [{ in: 'countdown(3)', out: '[3, 2, 1]' }],
    [{ call: 'countdown(3)', expect: '[3, 2, 1]' },
     { call: 'countdown(0)', expect: '[]' },
     { call: 'countdown(1)', expect: '[1]' },
     { call: 'countdown(5)', expect: '[5, 4, 3, 2, 1]', hidden: true },
     { call: 'countdown(-1)', expect: '[]', hidden: true }],
    'range(n, 0, -1) — start high, stop just before 0, step down by one.',
    'def countdown(n):\n    out = []\n    for i in range(n, 0, -1):\n        out.append(i)\n    return out\n',
    'A negative step counts down. The stop is 0 rather than 1 because range always stops before the stop value, in this direction too.');

  P('lp-repeat-lines', 'Say the same thing n times', 'repeat_lines',
    'Write a function called repeat_lines that gives back a list holding the same text n times.',
    'def repeat_lines(text: str, n: int) -> list',
    stub('repeat_lines(text, n)'),
    [{ in: "repeat_lines('hi', 3)", out: "['hi', 'hi', 'hi']" }],
    [{ call: "repeat_lines('hi', 3)", expect: "['hi', 'hi', 'hi']" },
     { call: "repeat_lines('x', 0)", expect: '[]', name: 'zero times is empty' },
     { call: "repeat_lines('a', 1)", expect: "['a']" },
     { call: "len(repeat_lines('z', 4))", expect: '4', hidden: true },
     { call: "repeat_lines('', 2)", expect: "['', '']", hidden: true }],
    'for _ in range(n) — the underscore says "I am not using the counter".',
    "def repeat_lines(text, n):\n    out = []\n    for _ in range(n):\n        out.append(text)\n    return out\n",
    'Sometimes you only want the loop to happen n times and do not care which time it is. Naming the loop variable _ is how Python programmers say that out loud.');

  P('lp-squares-to', 'The first n square numbers', 'squares_to',
    'Write a function called squares_to that gives back [1, 4, 9, ...] — the first n square numbers.',
    'def squares_to(n: int) -> list',
    stub('squares_to(n)'),
    [{ in: 'squares_to(3)', out: '[1, 4, 9]' }],
    [{ call: 'squares_to(3)', expect: '[1, 4, 9]' },
     { call: 'squares_to(0)', expect: '[]' },
     { call: 'squares_to(1)', expect: '[1]' },
     { call: 'squares_to(5)', expect: '[1, 4, 9, 16, 25]', hidden: true },
     { call: 'squares_to(-1)', expect: '[]', hidden: true }],
    'out.append(i * i) over range(1, n + 1).',
    'def squares_to(n):\n    out = []\n    for i in range(1, n + 1):\n        out.append(i * i)\n    return out\n',
    'Same range as numbers_to, one change to the appended value. You have now written that range three times — that is the point of a ladder.');

  /* ============ F · the position as well as the item ============ */

  P('lp-numbered', 'Number the lines', 'numbered',
    "Write a function called numbered that turns ['a', 'b'] into ['1. a', '2. b'] — the position counting from 1, then a full stop and a space.",
    'def numbered(items: list) -> list',
    stub('numbered(items)'),
    [{ in: "numbered(['a', 'b'])", out: "['1. a', '2. b']" }],
    [{ call: "numbered(['a', 'b'])", expect: "['1. a', '2. b']" },
     { call: 'numbered([])', expect: '[]' },
     { call: "numbered(['x'])", expect: "['1. x']", name: 'the first line is 1, not 0' },
     { call: "numbered(['p', 'q', 'r'])", expect: "['1. p', '2. q', '3. r']", hidden: true }],
    "for i, item in enumerate(items, start=1) hands you both at once.",
    "def numbered(items):\n    out = []\n    for i, item in enumerate(items, start=1):\n        out.append(f'{i}. {item}')\n    return out\n",
    'enumerate gives you the position and the item together, so you never have to write items[i]. start=1 shifts the numbering for humans, who do not count from zero.');

  P('lp-every-other', 'Every other item', 'every_other',
    'Write a function called every_other that keeps the items at positions 0, 2, 4 and so on.',
    'def every_other(items: list) -> list',
    stub('every_other(items)'),
    [{ in: 'every_other([1, 2, 3, 4, 5])', out: '[1, 3, 5]' }],
    [{ call: 'every_other([1, 2, 3, 4, 5])', expect: '[1, 3, 5]' },
     { call: 'every_other([])', expect: '[]' },
     { call: 'every_other([1])', expect: '[1]' },
     { call: 'every_other([1, 2])', expect: '[1]', hidden: true },
     { call: "every_other(['a', 'b', 'c', 'd'])", expect: "['a', 'c']", hidden: true }],
    'for i in range(0, len(items), 2), then append items[i].',
    'def every_other(items):\n    out = []\n    for i in range(0, len(items), 2):\n        out.append(items[i])\n    return out\n',
    'When the pattern is about positions rather than values, loop over range(len(...)) and index in. This is the one case where enumerate does not help you.');

  P('lp-positions', 'Everywhere it appears', 'positions',
    'Write a function called positions that gives back every position where the target appears, counting from 0.',
    'def positions(items: list, target) -> list',
    stub('positions(items, target)'),
    [{ in: "positions(['a', 'b', 'a'], 'a')", out: '[0, 2]' }],
    [{ call: "positions(['a', 'b', 'a'], 'a')", expect: '[0, 2]' },
     { call: "positions([], 'a')", expect: '[]' },
     { call: "positions(['b'], 'a')", expect: '[]', name: 'never appears' },
     { call: 'positions([1, 1, 1], 1)', expect: '[0, 1, 2]', hidden: true },
     { call: "positions(['a', 'A'], 'a')", expect: '[0]', hidden: true, name: 'case matters' }],
    'enumerate again, but this time you append i and not the item.',
    'def positions(items, target):\n    out = []\n    for i, item in enumerate(items):\n        if item == target:\n            out.append(i)\n    return out\n',
    'The list .index() method only ever gives you the first hit. A loop gives you all of them, which is usually what you actually wanted.');

  P('lp-pair-names', 'Two lists, side by side', 'pair_names',
    "Write a function called pair_names that takes a list of names and a list of scores and gives back lines like 'Ana: 3'. The two lists are always the same length.",
    'def pair_names(names: list, scores: list) -> list',
    stub('pair_names(names, scores)'),
    [{ in: "pair_names(['Ana', 'Bo'], [3, 4])", out: "['Ana: 3', 'Bo: 4']" }],
    [{ call: "pair_names(['Ana', 'Bo'], [3, 4])", expect: "['Ana: 3', 'Bo: 4']" },
     { call: 'pair_names([], [])', expect: '[]' },
     { call: "pair_names(['Sam'], [10])", expect: "['Sam: 10']" },
     { call: "pair_names(['a', 'b', 'c'], [1, 2, 3])", expect: "['a: 1', 'b: 2', 'c: 3']", hidden: true }],
    'for name, score in zip(names, scores) walks both lists in step.',
    "def pair_names(names, scores):\n    out = []\n    for name, score in zip(names, scores):\n        out.append(f'{name}: {score}')\n    return out\n",
    'zip is the tool for "walk two lists together". It stops at the shorter one, which is a feature when the lists match and a silent bug when they do not — so check they match before you trust it.');

  P('lp-is-rising', 'Is each one bigger than the last', 'is_rising',
    'Write a function called is_rising that gives back True when every number is strictly bigger than the one before it. A list of nought or one numbers counts as rising.',
    'def is_rising(nums: list) -> bool',
    stub('is_rising(nums)'),
    [{ in: 'is_rising([1, 2, 3])', out: 'True' }],
    [{ call: 'is_rising([1, 2, 3])', expect: 'True' },
     { call: 'is_rising([1, 1])', expect: 'False', name: 'equal is not bigger' },
     { call: 'is_rising([3, 2])', expect: 'False' },
     { call: 'is_rising([])', expect: 'True', hidden: true },
     { call: 'is_rising([5])', expect: 'True', hidden: true, name: 'one number has nothing to fall from' }],
    'Start the range at 1 and compare nums[i] with nums[i - 1].',
    'def is_rising(nums):\n    for i in range(1, len(nums)):\n        if nums[i] <= nums[i - 1]:\n            return False\n    return True\n',
    'Comparing neighbours means starting at 1, not 0 — there is nothing before position 0 to compare against. Start at 0 and you get an IndexError from nums[-1] quietly reading the last item instead.');

  /* ============ G · a string is a list of characters ============ */

  P('lp-letters', 'Split a word into letters', 'letters',
    'Write a function called letters that gives back a list of the characters in the word — built with a loop, not with list().',
    'def letters(word: str) -> list',
    stub('letters(word)'),
    [{ in: "letters('cat')", out: "['c', 'a', 't']" }],
    [{ call: "letters('cat')", expect: "['c', 'a', 't']" },
     { call: "letters('')", expect: '[]', name: 'an empty word has no letters' },
     { call: "letters('a')", expect: "['a']" },
     loopCheck('letters'),
     { call: "letters('hi there')", expect: "['h', 'i', ' ', 't', 'h', 'e', 'r', 'e']", hidden: true, name: 'a space is a character too' }],
    'for ch in word — a for loop walks a string one character at a time.',
    'def letters(word):\n    out = []\n    for ch in word:\n        out.append(ch)\n    return out\n',
    'The big reveal of this section: you do not need a list to loop. A string hands out its characters one at a time, spaces and punctuation included.');

  P('lp-count-vowels', 'Count the vowels', 'count_vowels',
    'Write a function called count_vowels that counts the vowels (a, e, i, o, u) in the word. Capitals count as vowels too.',
    'def count_vowels(word: str) -> int',
    stub('count_vowels(word)'),
    [{ in: "count_vowels('banana')", out: '3' }],
    [{ call: "count_vowels('banana')", expect: '3' },
     { call: "count_vowels('')", expect: '0' },
     { call: "count_vowels('xyz')", expect: '0', name: 'no vowels at all' },
     { call: "count_vowels('AEIOU')", expect: '5', hidden: true, name: 'capitals count' },
     { call: "count_vowels('Hello There')", expect: '4', hidden: true }],
    "if ch.lower() in 'aeiou' — the `in` test asks whether the character is one of those five.",
    "def count_vowels(word):\n    n = 0\n    for ch in word:\n        if ch.lower() in 'aeiou':\n            n = n + 1\n    return n\n",
    "Counting-with-an-if from section C, now over a string. Lower-casing the character rather than the whole word is a habit worth having: you test what you are looking at, and leave the original alone.");

  P('lp-strip-vowels', 'Throw the vowels away', 'strip_vowels',
    'Write a function called strip_vowels that gives back the word with every vowel removed, keeping everything else exactly as it was.',
    'def strip_vowels(word: str) -> str',
    stub('strip_vowels(word)'),
    [{ in: "strip_vowels('banana')", out: "'bnn'" }],
    [{ call: "strip_vowels('banana')", expect: "'bnn'" },
     { call: "strip_vowels('')", expect: "''" },
     { call: "strip_vowels('AEIOU')", expect: "''", name: 'nothing left' },
     { call: "strip_vowels('Hello')", expect: "'Hll'", hidden: true, name: 'the capital H survives' },
     { call: "strip_vowels('xyz')", expect: "'xyz'", hidden: true }],
    "Build a string: out = '' before the loop, out = out + ch when the character is not a vowel.",
    "def strip_vowels(word):\n    out = ''\n    for ch in word:\n        if ch.lower() not in 'aeiou':\n            out = out + ch\n    return out\n",
    "`not in` is the whole change from counting them. Keeping the original ch — not ch.lower() — is what leaves the capital H standing.");

  P('lp-backwards', 'Reverse a word by hand', 'backwards',
    'Write a function called backwards that gives back the text in reverse, built with a loop — no [::-1] and no reversed().',
    'def backwards(text: str) -> str',
    stub('backwards(text)'),
    [{ in: "backwards('cat')", out: "'tac'" }],
    [{ call: "backwards('cat')", expect: "'tac'" },
     { call: "backwards('')", expect: "''" },
     { call: "backwards('a')", expect: "'a'" },
     loopCheck('backwards'),
     { call: "backwards('level')", expect: "'level'", hidden: true, name: 'the same either way round' }],
    'Put each new character in front of what you have so far: out = ch + out.',
    "def backwards(text):\n    out = ''\n    for ch in text:\n        out = ch + out\n    return out\n",
    'The only difference from gluing words together is which side the new piece goes on. out + ch builds forwards; ch + out builds backwards. Read it slowly with three characters and it clicks.');

  /* ============ H · loop over a dictionary ============ */

  P('lp-key-list', 'List the keys with a loop', 'key_list',
    'Write a function called key_list that gives back the keys of the dictionary in a list, in the order they were added — built with a loop, not with list().',
    'def key_list(prices: dict) -> list',
    stub('key_list(prices)'),
    [{ in: "key_list({'a': 1, 'b': 2})", out: "['a', 'b']" }],
    [{ call: "key_list({'a': 1, 'b': 2})", expect: "['a', 'b']" },
     { call: 'key_list({})', expect: '[]' },
     { call: "key_list({'only': 9})", expect: "['only']" },
     loopCheck('key_list'),
     { call: "key_list({'z': 1, 'a': 2})", expect: "['z', 'a']", hidden: true, name: 'insertion order, not alphabetical' }],
    'for key in prices — looping a dictionary hands you the keys, not the values.',
    'def key_list(prices):\n    out = []\n    for key in prices:\n        out.append(key)\n    return out\n',
    'The thing to remember for good: a bare for over a dictionary walks the keys. Modern Python keeps them in the order they were put in, which the last test is checking.');

  P('lp-total-values', 'Add up the values', 'total_values',
    'Write a function called total_values that adds up all the values in the dictionary.',
    'def total_values(counts: dict) -> float',
    stub('total_values(counts)'),
    [{ in: "total_values({'a': 1, 'b': 2})", out: '3' }],
    [{ call: "total_values({'a': 1, 'b': 2})", expect: '3' },
     { call: 'total_values({})', expect: '0' },
     { call: "total_values({'x': 5})", expect: '5' },
     { call: "total_values({'a': 1.5, 'b': 2.5})", expect: '4.0', hidden: true },
     { call: "total_values({'a': -1, 'b': 1})", expect: '0', hidden: true }],
    'Either walk the keys and add counts[key], or walk counts.values() directly.',
    'def total_values(counts):\n    running = 0\n    for key in counts:\n        running = running + counts[key]\n    return running\n',
    'Two right answers again: look each value up by its key, or ask for .values() and skip the keys entirely. The second reads better when the key is not part of the sum.');

  P('lp-lines-of', 'One line per entry', 'lines_of',
    "Write a function called lines_of that turns {'a': 1} into ['a: 1'] — the key, a colon, a space, then the value.",
    'def lines_of(d: dict) -> list',
    stub('lines_of(d)'),
    [{ in: "lines_of({'a': 1, 'b': 2})", out: "['a: 1', 'b: 2']" }],
    [{ call: "lines_of({'a': 1, 'b': 2})", expect: "['a: 1', 'b: 2']" },
     { call: 'lines_of({})', expect: '[]' },
     { call: "lines_of({'total': 10})", expect: "['total: 10']" },
     { call: "lines_of({'x': 'y'})", expect: "['x: y']", hidden: true, name: 'the values need not be numbers' }],
    "for key, value in d.items() unpacks both in one go.",
    "def lines_of(d):\n    out = []\n    for key, value in d.items():\n        out.append(f'{key}: {value}')\n    return out\n",
    '.items() is the dictionary version of enumerate: two names on the left of the `in`, both handed to you each time round. It is how nearly every real dictionary loop is written.');

  P('lp-over-price', 'Which ones cost more than that', 'over_price',
    'Write a function called over_price that gives back the keys whose value is above the bar, in the order they appear.',
    'def over_price(prices: dict, bar: float) -> list',
    stub('over_price(prices, bar)'),
    [{ in: "over_price({'a': 1, 'b': 5}, 3)", out: "['b']" }],
    [{ call: "over_price({'a': 1, 'b': 5}, 3)", expect: "['b']" },
     { call: 'over_price({}, 0)', expect: '[]' },
     { call: "over_price({'a': 3}, 3)", expect: '[]', name: 'exactly on the bar does not count' },
     { call: "over_price({'a': 9, 'b': 8}, 1)", expect: "['a', 'b']", hidden: true },
     { call: "over_price({'a': 1}, 9)", expect: '[]', hidden: true }],
    'Walk .items(), test the value, append the key.',
    'def over_price(prices, bar):\n    out = []\n    for key, value in prices.items():\n        if value > bar:\n            out.append(key)\n    return out\n',
    'Judge one thing, keep another — the same split as longest(). Filtering a dictionary almost always looks like this: test the value, collect the key.');

  P('lp-count-each', 'Tally them up', 'count_each',
    'Write a function called count_each that counts how many times each item appears, and gives back a dictionary like {\'a\': 2, \'b\': 1}.',
    'def count_each(items: list) -> dict',
    stub('count_each(items)'),
    [{ in: "count_each(['a', 'b', 'a'])", out: "{'a': 2, 'b': 1}" }],
    [{ call: "count_each(['a', 'b', 'a'])", expect: "{'a': 2, 'b': 1}" },
     { call: 'count_each([])', expect: '{}' },
     { call: "count_each(['x'])", expect: "{'x': 1}" },
     { call: 'count_each([1, 1, 1])', expect: '{1: 3}', hidden: true, name: 'numbers work as keys too' },
     { call: "count_each(['a', 'A'])", expect: "{'a': 1, 'A': 1}", hidden: true, name: 'case matters' }],
    "counts[item] = counts.get(item, 0) + 1 — .get gives 0 the first time an item shows up.",
    'def count_each(items):\n    counts = {}\n    for item in items:\n        counts[item] = counts.get(item, 0) + 1\n    return counts\n',
    'The accumulator from part B, except the thing being built up is a dictionary. .get(item, 0) is what saves you from a KeyError on the very first sighting of each item.');

  P('lp-top-key', 'Which key has the biggest value', 'top_key',
    'Write a function called top_key that gives back the key with the largest value. On a tie keep the first one you met. An empty dictionary gives back None.',
    'def top_key(d: dict) -> str',
    stub('top_key(d)'),
    [{ in: "top_key({'a': 1, 'b': 5})", out: "'b'" }],
    [{ call: "top_key({'a': 1, 'b': 5})", expect: "'b'" },
     { call: 'top_key({})', expect: 'None' },
     { call: "top_key({'a': 2})", expect: "'a'" },
     { call: "top_key({'a': 5, 'b': 5})", expect: "'a'", hidden: true, name: 'first of a tie' },
     { call: "top_key({'a': -5, 'b': -1})", expect: "'b'", hidden: true }],
    'Best-so-far, but start with best = None and treat "nothing yet" as the first special case.',
    'def top_key(d):\n    best = None\n    for key, value in d.items():\n        if best is None or value > d[best]:\n            best = key\n    return best\n',
    'Starting at None instead of the first item means the empty case needs no separate check — the loop never runs and None comes straight back out. `best is None or ...` short-circuits, so the lookup on the right never happens on the first pass.');

  /* ============ I · records, and a loop inside a loop ============ */

  P('lp-row-names', 'Pull one field out of every row', 'row_names',
    "Write a function called row_names that takes a list of dictionaries and gives back the value of each row's 'name'.",
    'def row_names(rows: list) -> list',
    stub('row_names(rows)'),
    [{ in: "row_names([{'name': 'Ana'}, {'name': 'Bo'}])", out: "['Ana', 'Bo']" }],
    [{ call: "row_names([{'name': 'Ana'}, {'name': 'Bo'}])", expect: "['Ana', 'Bo']" },
     { call: 'row_names([])', expect: '[]' },
     { call: "row_names([{'name': 'Sam', 'age': 30}])", expect: "['Sam']", name: 'other fields are ignored' },
     { call: "row_names([{'name': ''}])", expect: "['']", hidden: true }],
    "out.append(row['name']) — each item in the list is itself a dictionary.",
    "def row_names(rows):\n    out = []\n    for row in rows:\n        out.append(row['name'])\n    return out\n",
    'A list of dictionaries is what a table looks like in plain Python, and one row at a time is how you read it. The loop variable is a whole record now, so row[\'name\'] is "this row\'s name column".');

  P('lp-row-total', 'Total one column', 'row_total',
    'Write a function called row_total that adds up one named field across every row.',
    'def row_total(rows: list, field: str) -> float',
    stub('row_total(rows, field)'),
    [{ in: "row_total([{'spend': 10}, {'spend': 5}], 'spend')", out: '15' }],
    [{ call: "row_total([{'spend': 10}, {'spend': 5}], 'spend')", expect: '15' },
     { call: "row_total([], 'spend')", expect: '0' },
     { call: "row_total([{'spend': 3, 'age': 40}], 'spend')", expect: '3', name: 'only the field you asked for' },
     { call: "row_total([{'a': 1}, {'a': 2}], 'a')", expect: '3', hidden: true },
     { call: "row_total([{'spend': -5}], 'spend')", expect: '-5', hidden: true }],
    'running = running + row[field] — the column name is a parameter, so it goes in square brackets without quotes.',
    'def row_total(rows, field):\n    running = 0\n    for row in rows:\n        running = running + row[field]\n    return running\n',
    "row['spend'] looks up the column called spend; row[field] looks up whichever column the caller named. That one difference turns a report into a tool.");

  P('lp-flatten', 'A loop inside a loop', 'flatten',
    'Write a function called flatten that takes a list of lists and gives back one flat list with everything in it, in order.',
    'def flatten(lists: list) -> list',
    stub('flatten(lists)'),
    [{ in: 'flatten([[1, 2], [3]])', out: '[1, 2, 3]' }],
    [{ call: 'flatten([[1, 2], [3]])', expect: '[1, 2, 3]' },
     { call: 'flatten([])', expect: '[]', name: 'no inner lists at all' },
     { call: 'flatten([[]])', expect: '[]', name: 'one empty inner list' },
     { call: "flatten([['a'], ['b', 'c']])", expect: "['a', 'b', 'c']", hidden: true },
     { call: 'flatten([[1], [], [2]])', expect: '[1, 2]', hidden: true }],
    'The outer loop walks the inner lists; the inner loop walks the items in one of them.',
    'def flatten(lists):\n    out = []\n    for inner in lists:\n        for item in inner:\n            out.append(item)\n    return out\n',
    'Three levels of indent, and each one means something: for each inner list, for each item in it, keep it. Say that sentence before you write the code and the indentation writes itself.');

  P('lp-grid-total', 'Total a grid', 'grid_total',
    'Write a function called grid_total that adds up every number in a list of rows of numbers.',
    'def grid_total(rows: list) -> float',
    stub('grid_total(rows)'),
    [{ in: 'grid_total([[1, 2], [3]])', out: '6' }],
    [{ call: 'grid_total([[1, 2], [3]])', expect: '6' },
     { call: 'grid_total([])', expect: '0' },
     { call: 'grid_total([[]])', expect: '0', name: 'an empty row adds nothing' },
     { call: 'grid_total([[1, 1], [1, 1]])', expect: '4', hidden: true },
     { call: 'grid_total([[-1], [1]])', expect: '0', hidden: true }],
    'One running total, declared before both loops, added to in the inner one.',
    'def grid_total(rows):\n    running = 0\n    for row in rows:\n        for value in row:\n            running = running + value\n    return running\n',
    'Where you put the running total decides what you get. Outside both loops it totals the whole grid; move it inside the outer loop and you would be totalling each row separately.');

  /* ============ J · leaving early, and skipping a turn ============ */

  P('lp-stop-at-negative', 'Stop when things go wrong', 'total_until_negative',
    'Write a function called total_until_negative that adds up the numbers but stops the moment it meets one below zero — that number and everything after it is ignored.',
    'def total_until_negative(nums: list) -> float',
    stub('total_until_negative(nums)'),
    [{ in: 'total_until_negative([1, 2, -1, 50])', out: '3' }],
    [{ call: 'total_until_negative([1, 2, -1, 50])', expect: '3', name: 'the 50 is never reached' },
     { call: 'total_until_negative([1, 2])', expect: '3', name: 'no negative, so everything counts' },
     { call: 'total_until_negative([-1])', expect: '0' },
     { call: 'total_until_negative([])', expect: '0', hidden: true },
     { call: 'total_until_negative([0, 1, -1])', expect: '1', hidden: true, name: 'zero is not negative' }],
    'break leaves the loop immediately; the code after the loop still runs.',
    'def total_until_negative(nums):\n    running = 0\n    for n in nums:\n        if n < 0:\n            break\n        running = running + n\n    return running\n',
    'break is return\'s smaller cousin: it ends the loop but stays in the function, so the return at the bottom still hands back what you gathered. Notice the break comes before the addition, so the negative number itself is not counted.');

  P('lp-skip-negatives', 'Skip the ones you do not want', 'skip_negatives',
    'Write a function called skip_negatives that gives back the numbers that are not below zero, using continue to skip the ones that are.',
    'def skip_negatives(nums: list) -> list',
    stub('skip_negatives(nums)'),
    [{ in: 'skip_negatives([1, -2, 3])', out: '[1, 3]' }],
    [{ call: 'skip_negatives([1, -2, 3])', expect: '[1, 3]' },
     { call: 'skip_negatives([])', expect: '[]' },
     { call: 'skip_negatives([0])', expect: '[0]', name: 'zero is not below zero' },
     { call: 'skip_negatives([-1, -2])', expect: '[]', hidden: true },
     { call: 'skip_negatives([5, 6])', expect: '[5, 6]', hidden: true }],
    'if n < 0: continue — then the append below it, with no else needed.',
    'def skip_negatives(nums):\n    out = []\n    for n in nums:\n        if n < 0:\n            continue\n        out.append(n)\n    return out\n',
    'The same answer as keep_positives written the other way round: instead of saying which ones to keep, say which ones to skip. continue jumps straight to the next item. With one condition it is a matter of taste; with three things to rule out first, skipping early reads far better than nesting three ifs.');

  P('lp-count-until', 'How many before the stop sign', 'count_until',
    'Write a function called count_until that counts the items before the stop value first appears. If the stop value is never there, count all of them.',
    'def count_until(items: list, stop) -> int',
    stub('count_until(items, stop)'),
    [{ in: "count_until(['a', 'b', 'x', 'c'], 'x')", out: '2' }],
    [{ call: "count_until(['a', 'b', 'x', 'c'], 'x')", expect: '2' },
     { call: "count_until(['a'], 'x')", expect: '1', name: 'never appears, so count everything' },
     { call: "count_until([], 'x')", expect: '0' },
     { call: "count_until(['x'], 'x')", expect: '0', hidden: true, name: 'stops straight away' },
     { call: 'count_until([1, 2, 3], 2)', expect: '1', hidden: true }],
    'Count as you go and break when you meet the stop value — before you add one.',
    'def count_until(items, stop):\n    n = 0\n    for item in items:\n        if item == stop:\n            break\n        n = n + 1\n    return n\n',
    'Everything from this ladder in six lines: a counter set up before the loop, a test inside it, an early exit, and the answer returned after. If this one reads easily now, the ladder did its job.');
})();
