/* Python coding test — problem bank 5: more algorithms.
   Sliding windows, matrices, stacks, and the small number problems that fill out
   the middle of a screening test. */
(function () {
  window.PYTESTS = window.PYTESTS || [];

  window.PYTESTS.push(

    { id: 'pt-max-window', group: 'Algorithms', lvl: 3,
      title: 'Best window of k',
      fn: 'max_window_sum',
      brief: 'Return the largest sum of any k consecutive numbers in a list.\n\nIf the list is shorter than k, return 0.',
      sig: 'def max_window_sum(nums: list[int], k: int) -> int',
      starter: 'def max_window_sum(nums, k):\n    # your code here\n    pass\n',
      examples: [
        { in: 'max_window_sum([1, 9, 2, 3], 2)', out: '11', note: '9 + 2' }],
      tests: [
        { call: 'max_window_sum([1, 9, 2, 3], 2)', expect: '11' },
        { call: 'max_window_sum([5], 3)', expect: '0', name: 'too short' },
        { call: 'max_window_sum([1, 1, 1], 3)', expect: '3' },
        { call: 'max_window_sum([-5, -1, -9], 1)', expect: '-1', hidden: true, name: 'all negative' },
        { call: 'max_window_sum(list(range(200000)), 3)', expect: '599994', hidden: true, name: 'must slide, not re-sum' }],
      hint: 'Sum the first window, then for each step add the number coming in and subtract the one going out.',
      solution: 'def max_window_sum(nums, k):\n    if k <= 0 or len(nums) < k:\n        return 0\n    window = sum(nums[:k])\n    best = window\n    for i in range(k, len(nums)):\n        window += nums[i] - nums[i - k]\n        best = max(best, window)\n    return best\n',
      walk: 'The sliding window is the point: re-summing each window is O(n·k) and the 200,000-element test will time out. Seeding `best` with the first window rather than 0 is what keeps the all-negative case honest.',
      complexity: 'O(n) time, O(1) space.' },

    { id: 'pt-parens', group: 'Algorithms', lvl: 2,
      title: 'Balanced brackets',
      fn: 'is_balanced',
      brief: 'Return True if every bracket in a string is closed by the right kind, in the right order.\n\nHandle ( ), [ ] and { }. Ignore any other character.',
      sig: 'def is_balanced(s: str) -> bool',
      starter: 'def is_balanced(s):\n    # your code here\n    pass\n',
      examples: [
        { in: "is_balanced('a(b[c]d)')", out: 'True' },
        { in: "is_balanced('(]')", out: 'False' }],
      tests: [
        { call: "is_balanced('a(b[c]d)')", expect: 'True' },
        { call: "is_balanced('(]')", expect: 'False' },
        { call: "is_balanced('')", expect: 'True', name: 'nothing is balanced' },
        { call: "is_balanced('(((')", expect: 'False', hidden: true, name: 'left open' },
        { call: "is_balanced('{[()]}')", expect: 'True', hidden: true }],
      hint: 'Push every opening bracket onto a stack; on a closing one, check the top of the stack matches.',
      solution: "def is_balanced(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for ch in s:\n        if ch in '([{':\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n    return not stack\n",
      walk: "A list used as a stack is all this needs. Two failure modes to cover: a closing bracket with nothing open (`not stack`), and one that closes the wrong kind. The final `return not stack` catches brackets left open at the end — forgetting it is the usual bug.",
      complexity: 'O(n) time, O(n) space in the worst case.' },

    { id: 'pt-missing-number', group: 'Algorithms', lvl: 2,
      title: 'The missing number',
      fn: 'missing_number',
      brief: 'A list holds all the numbers from 0 to n except one. Return the missing one.\n\nThe list is not sorted.',
      sig: 'def missing_number(nums: list[int]) -> int',
      starter: 'def missing_number(nums):\n    # your code here\n    pass\n',
      examples: [
        { in: 'missing_number([3, 0, 1])', out: '2' }],
      tests: [
        { call: 'missing_number([3, 0, 1])', expect: '2' },
        { call: 'missing_number([0])', expect: '1', name: 'the missing one can be n itself' },
        { call: 'missing_number([1])', expect: '0' },
        { call: 'missing_number([9,6,4,2,3,5,7,0,1])', expect: '8', hidden: true },
        { call: 'missing_number(list(range(100000)))', expect: '100000', hidden: true, name: 'must be linear' }],
      hint: 'The numbers 0 to n have a known total: n(n+1)/2. Compare that with what you actually have.',
      solution: 'def missing_number(nums):\n    n = len(nums)\n    return n * (n + 1) // 2 - sum(nums)\n',
      walk: 'Sorting works but costs O(n log n); the arithmetic-series trick is one pass and no extra memory. Note that with one number missing, len(nums) IS n — which is why the formula uses the length directly. XOR of the indices and values is the other classic answer.',
      complexity: 'O(n) time, O(1) space.' },

    { id: 'pt-rotate-matrix', group: 'Algorithms', lvl: 3,
      title: 'Rotate a grid',
      fn: 'rotate',
      brief: 'Rotate a square grid (a list of equal-length lists) 90° clockwise, returning a new grid.',
      sig: 'def rotate(grid: list[list]) -> list[list]',
      starter: 'def rotate(grid):\n    # your code here\n    pass\n',
      examples: [
        { in: 'rotate([[1, 2], [3, 4]])', out: '[[3, 1], [4, 2]]' }],
      tests: [
        { call: 'rotate([[1, 2], [3, 4]])', expect: '[[3, 1], [4, 2]]' },
        { call: 'rotate([[1]])', expect: '[[1]]' },
        { call: 'rotate([])', expect: '[]' },
        { call: 'rotate([[1,2,3],[4,5,6],[7,8,9]])', expect: '[[7,4,1],[8,5,2],[9,6,3]]', hidden: true },
        { call: 'rotate(rotate(rotate(rotate([[1,2],[3,4]]))))', expect: '[[1, 2], [3, 4]]', hidden: true, name: 'four turns is a full circle' }],
      hint: 'Rotating clockwise is a transpose followed by reversing each row. zip(*grid) transposes.',
      solution: 'def rotate(grid):\n    return [list(row) for row in zip(*reversed(grid))]\n',
      walk: 'zip(*grid) is the Python idiom for a transpose — the star unpacks the rows as separate arguments. Reversing the rows first (rather than after) gives the clockwise direction; reversing after gives anticlockwise. zip yields tuples, so wrap them back into lists to match the expected type.',
      complexity: 'O(n²) for an n×n grid.' },

    { id: 'pt-chunk', group: 'Algorithms', lvl: 2,
      title: 'Chunk a list',
      fn: 'chunk',
      brief: 'Split a list into consecutive chunks of at most size n, keeping the order.\n\nThe last chunk may be shorter. A size of 0 or less returns an empty list.',
      sig: 'def chunk(items: list, n: int) -> list[list]',
      starter: 'def chunk(items, n):\n    # your code here\n    pass\n',
      examples: [
        { in: 'chunk([1, 2, 3, 4, 5], 2)', out: '[[1, 2], [3, 4], [5]]' }],
      tests: [
        { call: 'chunk([1, 2, 3, 4, 5], 2)', expect: '[[1, 2], [3, 4], [5]]' },
        { call: 'chunk([], 3)', expect: '[]' },
        { call: 'chunk([1, 2], 5)', expect: '[[1, 2]]', name: 'one short chunk' },
        { call: 'chunk([1, 2], 0)', expect: '[]', hidden: true, name: 'a zero size must not hang' },
        { call: 'len(chunk(list(range(1000)), 100))', expect: '10', hidden: true }],
      hint: 'range(0, len(items), n) gives you the start of each chunk; slice from there.',
      solution: 'def chunk(items, n):\n    if n <= 0:\n        return []\n    return [items[i:i + n] for i in range(0, len(items), n)]\n',
      walk: 'The stepped range is the whole trick, and slicing past the end is safe so the short final chunk needs no special handling. Guard n <= 0 first: range with a step of 0 raises ValueError, and a negative step would loop the wrong way.',
      complexity: 'O(n) time and space.' },

    { id: 'pt-common-prefix', group: 'Algorithms', lvl: 3,
      title: 'Longest common prefix',
      fn: 'common_prefix',
      brief: 'Return the longest string that every word in the list starts with.\n\nIf there is none, or the list is empty, return an empty string.',
      sig: 'def common_prefix(words: list[str]) -> str',
      starter: 'def common_prefix(words):\n    # your code here\n    pass\n',
      examples: [
        { in: "common_prefix(['flower', 'flow', 'flight'])", out: "'fl'" },
        { in: "common_prefix(['dog', 'cat'])", out: "''" }],
      tests: [
        { call: "common_prefix(['flower', 'flow', 'flight'])", expect: "'fl'" },
        { call: "common_prefix(['dog', 'cat'])", expect: "''" },
        { call: "common_prefix([])", expect: "''" },
        { call: "common_prefix(['same', 'same'])", expect: "'same'", hidden: true },
        { call: "common_prefix(['a', ''])", expect: "''", hidden: true, name: 'an empty word kills the prefix' }],
      hint: 'The answer can never be longer than the shortest word. Compare position by position, or lean on min() and max() in alphabetical order.',
      solution: "def common_prefix(words):\n    if not words:\n        return ''\n    first, last = min(words), max(words)\n    for i, ch in enumerate(first):\n        if i >= len(last) or last[i] != ch:\n            return first[:i]\n    return first\n",
      walk: 'A neat trick: in alphabetical order, only the smallest and largest strings matter — anything shared by those two is shared by everything in between. Comparing character by character against the shortest word is the more obvious answer and just as acceptable.',
      complexity: 'O(n·m) in the worst case, where m is the prefix length.' },

    { id: 'pt-intersection', group: 'Algorithms', lvl: 2,
      title: 'Shared values',
      fn: 'shared',
      brief: 'Return the values that appear in both lists, each once, sorted smallest first.',
      sig: 'def shared(a: list, b: list) -> list',
      starter: 'def shared(a, b):\n    # your code here\n    pass\n',
      examples: [
        { in: 'shared([1, 2, 2, 3], [2, 3, 4])', out: '[2, 3]' }],
      tests: [
        { call: 'shared([1, 2, 2, 3], [2, 3, 4])', expect: '[2, 3]' },
        { call: 'shared([1], [2])', expect: '[]' },
        { call: 'shared([], [1, 2])', expect: '[]' },
        { call: 'shared([3, 1, 2], [2, 1, 3])', expect: '[1, 2, 3]', hidden: true, name: 'sorted, not input order' },
        { call: 'len(shared(list(range(50000)), list(range(25000, 75000))))', expect: '25000', hidden: true, name: 'must not be O(n*m)' }],
      hint: 'Sets give you intersection in one operator, and O(1) membership tests.',
      solution: 'def shared(a, b):\n    return sorted(set(a) & set(b))\n',
      walk: 'The nested-loop version is O(n·m) and the last test punishes it. Sets deduplicate and intersect in near-linear time; sorted() at the end turns the unordered set back into the list the brief asks for.',
      complexity: 'O(n + m) to build the sets, O(k log k) to sort the result.' },

    { id: 'pt-digits', group: 'Algorithms', lvl: 1,
      title: 'Sum the digits',
      fn: 'digit_sum',
      brief: 'Return the sum of the digits of a whole number.\n\nNegative numbers count as their digits alone: -123 sums to 6.',
      sig: 'def digit_sum(n: int) -> int',
      starter: 'def digit_sum(n):\n    # your code here\n    pass\n',
      examples: [
        { in: 'digit_sum(123)', out: '6' },
        { in: 'digit_sum(-123)', out: '6' }],
      tests: [
        { call: 'digit_sum(123)', expect: '6' },
        { call: 'digit_sum(-123)', expect: '6' },
        { call: 'digit_sum(0)', expect: '0' },
        { call: 'digit_sum(999999)', expect: '54', hidden: true },
        { call: 'digit_sum(1000000007)', expect: '8', hidden: true }],
      hint: 'Either walk the string form, or repeatedly take n % 10 and divide by 10.',
      solution: 'def digit_sum(n):\n    return sum(int(ch) for ch in str(abs(n)))\n',
      walk: "abs() first, or the minus sign becomes a character int() cannot parse. The arithmetic version — while n: total += n % 10; n //= 10 — avoids the string conversion and is the answer an interviewer usually wants to see next.",
      complexity: 'O(d) in the number of digits.' },

    { id: 'pt-primes', group: 'Algorithms', lvl: 2,
      title: 'Is it prime?',
      fn: 'is_prime',
      brief: 'Return True if a whole number is prime.\n\n0, 1 and every negative number are not prime. It must answer for numbers up to a few million quickly.',
      sig: 'def is_prime(n: int) -> bool',
      starter: 'def is_prime(n):\n    # your code here\n    pass\n',
      examples: [
        { in: 'is_prime(7)', out: 'True' },
        { in: 'is_prime(9)', out: 'False' }],
      tests: [
        { call: 'is_prime(7)', expect: 'True' },
        { call: 'is_prime(9)', expect: 'False' },
        { call: 'is_prime(1)', expect: 'False', name: '1 is not prime' },
        { call: 'is_prime(2)', expect: 'True', hidden: true, name: 'the only even prime' },
        { call: 'is_prime(1000003)', expect: 'True', hidden: true, name: 'must stop at the square root' }],
      hint: 'You only need to test divisors up to the square root — beyond that, the pairs repeat.',
      solution: 'def is_prime(n):\n    if n < 2:\n        return False\n    if n % 2 == 0:\n        return n == 2\n    i = 3\n    while i * i <= n:\n        if n % i == 0:\n            return False\n        i += 2\n    return True\n',
      walk: 'Testing every number up to n is O(n) and too slow for the last case. Stopping at √n is the key insight: if n = a·b then one of the factors is at or below the square root. Handling 2 separately then stepping by 2 halves the remaining work.',
      complexity: 'O(√n) time, O(1) space.' },

    { id: 'pt-caesar', group: 'Text handling', lvl: 3,
      title: 'Caesar cipher',
      fn: 'shift_letters',
      brief: 'Shift every letter forward through the alphabet by n places, wrapping z round to a.\n\nKeep the case, and leave anything that is not a letter alone.',
      sig: 'def shift_letters(s: str, n: int) -> str',
      starter: 'def shift_letters(s, n):\n    # your code here\n    pass\n',
      examples: [
        { in: "shift_letters('abc', 1)", out: "'bcd'" },
        { in: "shift_letters('Zoo!', 1)", out: "'App!'" }],
      tests: [
        { call: "shift_letters('abc', 1)", expect: "'bcd'" },
        { call: "shift_letters('Zoo!', 1)", expect: "'App!'" },
        { call: "shift_letters('abc', 0)", expect: "'abc'" },
        { call: "shift_letters('abc', 26)", expect: "'abc'", hidden: true, name: 'a full turn changes nothing' },
        { call: "shift_letters('abc', -1)", expect: "'zab'", hidden: true, name: 'negative shifts work too' }],
      hint: 'ord() gives a character its number and chr() turns it back. Subtract the base letter, add n, take mod 26, add the base back.',
      solution: "def shift_letters(s, n):\n    out = []\n    for ch in s:\n        if ch.isalpha():\n            base = ord('A') if ch.isupper() else ord('a')\n            out.append(chr((ord(ch) - base + n) % 26 + base))\n        else:\n            out.append(ch)\n    return ''.join(out)\n",
      walk: "Shifting into a 0-25 range, doing the arithmetic there and shifting back is the pattern for every wrap-around problem. Python's modulo returns a non-negative result for a positive divisor, so negative shifts wrap correctly with no extra work.",
      complexity: 'O(n) time and space.' },

    { id: 'pt-dedupe-order', group: 'Algorithms', lvl: 2,
      title: 'Remove duplicates, keep the order',
      fn: 'dedupe',
      brief: 'Return the list with duplicates removed, keeping the first appearance of each value in its original position.',
      sig: 'def dedupe(items: list) -> list',
      starter: 'def dedupe(items):\n    # your code here\n    pass\n',
      examples: [
        { in: 'dedupe([3, 1, 3, 2, 1])', out: '[3, 1, 2]' }],
      tests: [
        { call: 'dedupe([3, 1, 3, 2, 1])', expect: '[3, 1, 2]' },
        { call: 'dedupe([])', expect: '[]' },
        { call: "dedupe(['a', 'a'])", expect: "['a']" },
        { call: 'dedupe([1, 2, 3])', expect: '[1, 2, 3]', hidden: true },
        { call: 'len(dedupe(list(range(20000)) * 3))', expect: '20000', hidden: true, name: 'must use a set, not a list, to remember' }],
      hint: 'Keep a set of what you have already seen — checking membership in a set is O(1), in a list it is O(n).',
      solution: 'def dedupe(items):\n    seen = set()\n    out = []\n    for item in items:\n        if item not in seen:\n            seen.add(item)\n            out.append(item)\n    return out\n',
      walk: 'set(items) alone loses the order, which the brief forbids. Tracking seen values in a set while building the output list keeps both. list(dict.fromkeys(items)) does the same thing in one line and is worth knowing — dicts have kept insertion order since 3.7.',
      complexity: 'O(n) time, O(n) space.' },

    { id: 'pt-second-largest', group: 'Algorithms', lvl: 2,
      title: 'Second largest',
      fn: 'second_largest',
      brief: 'Return the second largest DISTINCT value in a list.\n\nIf there is no second distinct value, return None.',
      sig: 'def second_largest(nums: list) -> object',
      starter: 'def second_largest(nums):\n    # your code here\n    pass\n',
      examples: [
        { in: 'second_largest([5, 1, 5, 3])', out: '3', note: '5 is the largest; 3 is next' }],
      tests: [
        { call: 'second_largest([5, 1, 5, 3])', expect: '3' },
        { call: 'second_largest([2, 2, 2])', expect: 'None', name: 'no distinct second' },
        { call: 'second_largest([])', expect: 'None' },
        { call: 'second_largest([1, 2])', expect: '1', hidden: true },
        { call: 'second_largest([-1, -5])', expect: '-5', hidden: true, name: 'negatives' }],
      hint: 'Deduplicate first, then the question becomes trivial — but mind the case where fewer than two values survive.',
      solution: 'def second_largest(nums):\n    distinct = sorted(set(nums), reverse=True)\n    return distinct[1] if len(distinct) > 1 else None\n',
      walk: 'The word "distinct" is the whole question: [5, 5, 3] must give 3, not 5. Deduplicating with a set makes that automatic. Sorting is O(n log n); a single pass tracking the best two would be O(n) and is the follow-up an interviewer asks for.',
      complexity: 'O(n log n) as written, O(n) with a one-pass version.' }
  );
})();
