/* More definitions: model selection/tuning, scikit-learn, interpretability, class imbalance,
   regression & boosting. Standard glossary terms, each DEFS-tagged with a reveal so it flows
   into the Definitions filter, flashcards and read+recall. Loads before app.js. */
(function () {
  var Q = (window.QUESTIONS = window.QUESTIONS || {});
  var D = (window.DEFS = window.DEFS || {});
  function def(qk, q, correct, distractors, name, text, explain, simple) {
    (Q[qk] = Q[qk] || []).push({ q: q, choices: [correct].concat(distractors), explain: explain, simple: simple, widget: { reveal: { name: name, text: text } } });
    D[q] = 1;
  }

  /* ===================== Model selection / tuning (msel1) — 12 ===================== */

  def("msel1",
    "What is Bayesian optimisation for hyperparameter tuning?",
    "A search that builds a probabilistic model of the score and uses it to pick promising settings.",
    ["A method that exhaustively evaluates every combination on a fixed grid before ranking them by mean cross-validated score.",
     "A rule that always chooses the simplest model whenever two candidates score within one standard error of each other.",
     "A technique that samples settings uniformly at random within the search space and keeps the best.",
     "A schedule that lowers the learning rate over epochs to help the optimiser settle into a minimum."],
    "Bayesian optimisation",
    "A tuning strategy that fits a surrogate model (e.g. a Gaussian process) to observed scores and proposes the next hyperparameters where improvement looks most likely.",
    "It exploits the trade-off between exploring uncertain regions and exploiting good ones, so it usually finds strong settings in fewer trials than grid or random search.",
    "Instead of guessing blindly, it learns from past trials to decide what to try next.");

  def("msel1",
    "What does successive halving do during a hyperparameter search?",
    "Gives every candidate a small budget, keeps the top fraction, then repeats with more budget.",
    ["Splits the training data in half repeatedly and averages the score obtained on each of the resulting folds.",
     "Doubles the number of trees on each round until the validation score stops improving noticeably.",
     "Evaluates all candidates fully and discards the worst-scoring half after a single complete pass.",
     "Halves the learning rate whenever the validation loss plateaus for a fixed number of iterations."],
    "Successive halving",
    "An adaptive search (HalvingGridSearchCV / HalvingRandomSearchCV) that starts many candidates on little data and iteratively promotes only the best to larger budgets.",
    "Weak candidates are eliminated cheaply and resources are concentrated on the survivors, so more of the compute goes to configurations that look promising.",
    "It quickly weeds out bad settings on tiny budgets and spends the rest on the good ones.");

  def("msel1",
    "What is the difference between a hyperparameter and a parameter?",
    "A hyperparameter is set before training; a parameter is learned from the data during training.",
    ["A hyperparameter is any numeric value in the model, whereas a parameter is any categorical or boolean value that the model uses.",
     "A hyperparameter is always tuned automatically by the optimiser, while a parameter must always be chosen by hand before fitting.",
     "A hyperparameter only affects speed; a parameter only affects accuracy.",
     "They are two names for the same thing and the distinction is purely historical."],
    "Hyperparameter vs parameter",
    "Parameters (e.g. weights) are fitted by the learning algorithm; hyperparameters (e.g. tree depth, C, k) configure that algorithm and are chosen by you or a search.",
    "Because hyperparameters aren't learned from the training loss, you must select them using validation data or a tuning procedure rather than fitting.",
    "The model learns its parameters; you (or a search) pick the hyperparameters.");

  def("msel1",
    "What is the search space in hyperparameter tuning?",
    "The set of hyperparameter values and ranges a tuner is allowed to explore.",
    ["The portion of the training set that is temporarily held out so that each candidate can be scored during the search.",
     "The collection of all models that have already been evaluated together with the cross-validated score each of them received.",
     "The memory footprint required to store every fitted model produced during the search.",
     "The number of CPU cores made available to run candidate evaluations in parallel."],
    "Search space",
    "The domain of a search: which hyperparameters vary and over what values or distributions (a grid, discrete lists, or continuous ranges).",
    "Its size and shape decide how many configurations exist and how a search must sample them; too wide wastes budget, too narrow may miss the optimum.",
    "It's the menu of settings the tuner is allowed to try.");

  def("msel1",
    "What does the scoring parameter control in a tuning search?",
    "Which metric is used to rank and select candidate configurations.",
    ["Which fraction of the training data is set aside as a validation fold during each round of the cross-validation loop.",
     "Which random seed is used to shuffle the data before it is partitioned into cross-validation folds.",
     "How many candidate configurations the search is permitted to evaluate before stopping.",
     "How the fitted best model is retrained on the full dataset once searching is complete."],
    "Scoring parameter (in tuning)",
    "In tools like GridSearchCV it names the objective (e.g. 'f1', 'roc_auc', 'neg_root_mean_squared_error') that decides which hyperparameters win.",
    "The right choice matters: optimising accuracy on imbalanced data can select a very different model than optimising F1 or PR-AUC.",
    "It's the yardstick the search uses to decide which settings are best.");

  def("msel1",
    "What does 'refit' mean after a cross-validated search?",
    "Retraining the chosen best settings on the whole dataset to produce the final model.",
    ["Rerunning the entire grid a second time with a finer resolution around the region that scored highest.",
     "Recomputing the cross-validation score of the winning configuration using a fresh set of random folds.",
     "Replacing the loss function partway through fitting once the validation score levels off.",
     "Averaging the fold models together into a single ensemble prediction."],
    "Refit",
    "After a search identifies the best hyperparameters using cross-validation, refit trains one model on all available data with those settings for deployment.",
    "Cross-validation scores come from models fitted on folds; refitting on everything uses all the data and gives a single estimator to predict with.",
    "Once you know the best settings, you train one final model on all your data.");

  def("msel1",
    "What is a tuning budget?",
    "A cap on the resources (trials, time, or compute) a search may spend.",
    ["The subset of hyperparameters that a practitioner decides are worth tuning while leaving the rest at their defaults.",
     "The amount of memory reserved for holding the intermediate results and fitted models generated by the search.",
     "The gap between training and validation score that a model is allowed to have before it counts as overfit.",
     "The number of folds chosen for the cross-validation loop."],
    "Tuning budget",
    "The limit you place on a search, such as n_iter in random search or a wall-clock/trial cap, which forces a trade-off between breadth and depth of exploration.",
    "Search methods differ in how efficiently they spend a fixed budget; random and adaptive methods often beat exhaustive grids when the budget is tight.",
    "It's how much time or how many tries you let the tuner use.");

  def("msel1",
    "What is Optuna?",
    "A library for hyperparameter optimisation using adaptive sampling and pruning.",
    ["A visualisation dashboard that plots learning curves and confusion matrices for models trained inside scikit-learn pipelines.",
     "A gradient-boosting implementation that competes with XGBoost by growing its trees leaf-wise instead of level-wise.",
     "A cross-validation splitter that keeps groups intact so that no group appears in both training and validation folds.",
     "A metric that averages precision across all recall levels."],
    "Optuna",
    "An open-source framework that defines search spaces in code and uses samplers (e.g. TPE) plus early-stopping pruners to find good hyperparameters efficiently.",
    "It lets you write an objective function, suggest hyperparameters dynamically, and prune unpromising trials, making it popular for tuning boosting models and networks.",
    "It's a popular tool that searches for good hyperparameters for you.");

  def("msel1",
    "What is Hyperband?",
    "A bandit method that races configurations across increasing budgets, discarding poor ones early.",
    ["A regularisation term that penalises large coefficients so that the resulting model generalises better to unseen data.",
     "A calibration technique that maps raw classifier scores onto well-behaved probabilities using a held-out fold.",
     "A grid-based search that evaluates every hyperparameter combination at full budget from the start.",
     "A learning-rate warm-up schedule used at the beginning of neural-network training."],
    "Hyperband",
    "A tuning algorithm that wraps successive halving in an outer loop over different starting budgets to balance many cheap trials against fewer expensive ones.",
    "By running several 'brackets' with different aggressiveness, it hedges against how much budget each configuration really needs to reveal its quality.",
    "It's a smart way to try lots of settings cheaply and only fully train the winners.");

  def("msel1",
    "What does a validation curve show?",
    "Model score plotted against a single hyperparameter's value.",
    ["The relationship between the amount of training data used and the resulting training and validation performance of a fixed model.",
     "The trajectory of the loss recorded after each successive gradient-descent iteration during the training of one model.",
     "The trade-off between precision and recall as the classification decision threshold is varied.",
     "The cumulative variance explained as principal components are added one by one."],
    "Validation curve",
    "A diagnostic that varies one hyperparameter (e.g. tree depth, C) and plots training and validation scores to reveal under- and over-fitting regions.",
    "The gap and shape of the two curves show where a setting is too simple (both low) or too complex (train high, validation dropping), guiding the choice.",
    "It plots how good the model is as you dial one setting up or down.");

  def("msel1",
    "What is coarse-to-fine hyperparameter search?",
    "First searching a wide, sparse space, then zooming into the best region.",
    ["Starting with a complex model and progressively removing features until validation performance begins to deteriorate.",
     "Running cross-validation with many folds first and then confirming the result with a single large holdout set.",
     "Training on a small data sample first and then scaling up to the full dataset once settings are fixed.",
     "Averaging several models trained with slightly different random seeds."],
    "Coarse-to-fine search",
    "A two-stage strategy: a broad, low-resolution search locates a promising neighbourhood, then a finer search refines values there.",
    "It spends little budget mapping the landscape, then concentrates the remaining budget where the good scores were, often faster than one dense grid.",
    "Look roughly everywhere first, then search carefully near what worked.");

  def("msel1",
    "What is trial pruning in a hyperparameter search?",
    "Stopping an unpromising trial early before it consumes its full budget.",
    ["Removing hyperparameters from the search space once they are found to have no measurable effect on the final validation score.",
     "Cutting branches of a decision tree after fitting so that the final model generalises better to unseen examples.",
     "Discarding cross-validation folds whose scores differ too much from the mean of the other folds.",
     "Deleting saved model checkpoints to free up disk space during a long search."],
    "Trial pruning",
    "An efficiency feature (e.g. in Optuna) that monitors a trial's intermediate results and terminates it if it is clearly worse than promising ones.",
    "Like successive halving, pruning reallocates budget away from configurations that are already lagging, so more compute goes to viable candidates.",
    "If a setting is clearly losing, stop it early and try the next one.");

  /* ===================== scikit-learn (skl1) — 10 ===================== */

  def("skl1",
    "What does make_pipeline do?",
    "Builds a Pipeline from a list of steps, naming each step automatically.",
    ["Combines several column transformers into one estimator that applies different preprocessing to different subsets of columns.",
     "Searches over the structure of a pipeline to decide which preprocessing and model components should be included in it.",
     "Clones an existing fitted estimator so that it can be refitted on a new dataset without altering the original.",
     "Runs cross-validation on a pipeline and returns the mean score across folds."],
    "make_pipeline",
    "A convenience constructor that returns a Pipeline, deriving step names from the estimator class names so you don't specify them by hand.",
    "It's shorthand for Pipeline([...]) when you don't need custom step names, chaining transformers and a final estimator into one fit/predict object.",
    "It's a quick way to glue preprocessing and a model into one pipeline.");

  def("skl1",
    "What does make_column_transformer do?",
    "Creates a ColumnTransformer that applies chosen transformers to chosen columns.",
    ["Assembles a sequence of transformers and a final estimator so they are fitted one after another as a single object.",
     "Automatically detects which columns are numeric and which are categorical and applies a default scaler to all of them.",
     "Splits a dataframe into training and testing subsets while preserving the class proportions in each part.",
     "Encodes a single categorical column as a set of binary indicator columns."],
    "make_column_transformer",
    "A helper that builds a ColumnTransformer without explicit names, mapping (transformer, columns) pairs so numeric and categorical features get different preprocessing.",
    "It routes subsets of columns to their own transformers and concatenates the results, letting one estimator handle mixed-type tabular data.",
    "It lets you apply different preprocessing to different columns in one step.");

  def("skl1",
    "What does SimpleImputer do?",
    "Fills in missing values using a strategy like mean, median, or most frequent.",
    ["Removes every row that contains at least one missing value before the data is passed on to the next step of the pipeline.",
     "Predicts each missing entry by training a separate regression model on the other columns of the dataset.",
     "Scales features so that each has zero mean and unit variance across the training set.",
     "Encodes categorical features as integer codes based on their sorted order."],
    "SimpleImputer",
    "A transformer that replaces missing entries in a column with a constant or a statistic (mean/median/mode) learned from the training data.",
    "Fitting it on the training split only, then transforming train and test, keeps imputation leak-free and gives every row usable feature values.",
    "It plugs holes in your data with a sensible fill value.");

  def("skl1",
    "What does OrdinalEncoder do?",
    "Maps each category of a feature to an integer code.",
    ["Creates one binary indicator column for each category so that no artificial order is imposed between the categories.",
     "Replaces each category with the mean of the target variable computed over the rows belonging to that category.",
     "Standardises a numeric feature by subtracting its mean and dividing by its standard deviation.",
     "Groups rare categories together into a single 'other' bucket before encoding."],
    "OrdinalEncoder",
    "A transformer that converts categorical columns into integer codes (0,1,2,...), suitable when categories have a natural order or for tree models.",
    "Unlike one-hot encoding it keeps a single column, but the integers imply an ordering, which can mislead linear or distance-based models.",
    "It turns categories into plain numbers.");

  def("skl1",
    "What does MinMaxScaler do?",
    "Rescales each feature to a fixed range, usually 0 to 1.",
    ["Subtracts the mean of each feature and divides by its standard deviation so the feature has unit variance.",
     "Clips extreme values to a chosen percentile so that outliers do not dominate the fitted transformation.",
     "Transforms features so that their median is zero and their interquartile range is one.",
     "Projects the features onto their leading principal components."],
    "MinMaxScaler",
    "A transformer that linearly maps each feature so its minimum becomes 0 and its maximum becomes 1 (or another chosen range), using bounds from the training data.",
    "It preserves the shape of the distribution and is useful when you need bounded inputs, though it is sensitive to outliers that stretch the range.",
    "It squeezes each feature into a 0-to-1 range.");

  def("skl1",
    "What does LabelEncoder do?",
    "Encodes target class labels as integers from 0 to n_classes minus 1.",
    ["Creates a separate binary indicator column for each distinct value found in a categorical feature of the input matrix.",
     "Assigns integer codes to every categorical feature column of the input matrix so a model can consume them directly.",
     "Balances the classes by duplicating rows from the minority class until the classes are equal in size.",
     "Splits the target vector into training and testing portions."],
    "LabelEncoder",
    "A utility that converts a 1-D array of class labels into integer codes; it is meant for the target y, not for encoding feature columns.",
    "Because it operates on a single vector, using it on features is a common mistake; use OrdinalEncoder or OneHotEncoder for the input matrix instead.",
    "It turns the target's class names into numbers.");

  def("skl1",
    "What does FunctionTransformer do?",
    "Wraps an arbitrary function so it can act as a pipeline transformer.",
    ["Learns a mapping from the training data during fit and then applies that learned mapping to any new data during transform.",
     "Selects the subset of columns that a downstream estimator should receive based on a scoring function evaluated per feature.",
     "Applies a different user-supplied function to each column depending on that column's inferred data type.",
     "Caches the output of a transformer so repeated fits do not recompute it."],
    "FunctionTransformer",
    "A transformer that turns a stateless function (e.g. np.log1p) into an estimator with fit/transform, so custom operations slot into pipelines.",
    "It carries no learned state by default, making it ideal for fixed transformations you want inside a Pipeline or ColumnTransformer.",
    "It lets you drop any function into a pipeline as a step.");

  def("skl1",
    "What does sklearn.base.clone do?",
    "Makes an unfitted copy of an estimator with the same hyperparameters.",
    ["Serialises a fitted estimator to disk so that it can be reloaded and used for prediction in a later session.",
     "Copies a fitted estimator together with all of its learned parameters so predictions are reproduced exactly.",
     "Duplicates a dataset while preserving the original class proportions in the copy.",
     "Combines several estimators into a voting ensemble."],
    "clone",
    "A helper that returns a fresh estimator with identical constructor arguments but no fitted state, used to get independent copies for each fold or trial.",
    "Search and cross-validation utilities clone the estimator so every fold trains from scratch without leaking learned parameters between runs.",
    "It copies a model's settings but not its training, giving you a clean slate.");

  def("skl1",
    "What do get_params and set_params do on an estimator?",
    "Read and change an estimator's hyperparameters programmatically.",
    ["Return the coefficients and intercepts that the estimator learned from the training data after it has been fitted.",
     "Serialise the estimator's full internal state so that it can be transmitted across a network to another machine.",
     "Report the cross-validated score achieved by the estimator under each candidate hyperparameter setting.",
     "Reset the estimator to its default configuration and clear any fitted attributes."],
    "get_params / set_params",
    "Methods every scikit-learn estimator exposes so its hyperparameters can be inspected and updated; search tools rely on them to set candidate values.",
    "They are part of the estimator contract, enabling GridSearchCV and pipelines to configure nested parameters using the 'step__param' naming convention.",
    "They let tools read and set a model's knobs by name.");

  def("skl1",
    "What does cross_validate provide that cross_val_score does not?",
    "Multiple metrics plus fit and score times in one call.",
    ["A single averaged score computed from the default metric of the estimator across all of the cross-validation folds.",
     "An automatic refit of the best configuration on the full dataset once every fold has been evaluated in turn.",
     "A guarantee that the class proportions are preserved within each of the cross-validation folds.",
     "A plot of the learning curve as training-set size increases."],
    "cross_validate",
    "A cross-validation utility that can evaluate several scoring metrics at once and also returns timing (and optionally train scores and fitted estimators).",
    "Where cross_val_score returns just one array of scores, cross_validate returns a dict, making it better for multi-metric reporting and diagnostics.",
    "It's like cross_val_score but reports several metrics and timings.");

  /* ===================== Interpretability (interp) — 14 ===================== */

  def("interp",
    "What is feature importance?",
    "A score ranking how much each feature contributes to a model's predictions.",
    ["A visualisation showing how the predicted outcome changes as one feature is varied while all others are held fixed at their averages.",
     "A measure of how strongly two input features are correlated with each other across the rows of the training data.",
     "The fraction of variance in the target that a single feature explains on its own in a univariate regression.",
     "The number of times a feature appears anywhere in the trained model."],
    "Feature importance",
    "Any method that assigns each input feature a number reflecting its influence on the model, used to rank features globally.",
    "Different methods (impurity-based, permutation, coefficient magnitude) can disagree, so importance says how much a model uses a feature, not that it causes the outcome.",
    "It ranks which inputs matter most to the model.");

  def("interp",
    "What is permutation importance?",
    "Measuring a feature's importance by the score drop when its values are shuffled.",
    ["Ranking features by how often they are chosen as the splitting variable across all of the nodes in a fitted decision tree.",
     "Estimating each feature's contribution to a single prediction by fitting a simple local model around that one instance.",
     "Computing the average change in prediction as a feature is swept across its whole observed range.",
     "Counting how many principal components a feature loads onto after dimensionality reduction."],
    "Permutation importance",
    "A model-agnostic method that randomly permutes one feature's column and records how much the model's performance worsens; a bigger drop means more importance.",
    "Because it breaks the feature's relationship with the target while keeping the model fixed, it reflects reliance on that feature and works for any fitted model.",
    "Scramble a column and see how much the model gets worse.");

  def("interp",
    "What is an ICE plot?",
    "A plot showing how one row's prediction changes as a feature is varied.",
    ["A curve that averages the predicted response over the whole dataset as a single chosen feature is swept across its range of values.",
     "A ranking of features by the total reduction in impurity they produce across all of the splits in a tree ensemble.",
     "A heatmap of the pairwise correlations between every pair of input features in the dataset.",
     "A bar chart of how many times each feature was used by the model."],
    "ICE plot",
    "An Individual Conditional Expectation plot draws one line per instance showing its prediction as a feature changes, revealing heterogeneous effects a PDP would average away.",
    "Where a partial dependence plot shows the average effect, ICE lines expose interactions and subgroups whose curves differ in slope or shape.",
    "It shows the feature's effect for each individual, not just on average.");

  def("interp",
    "What is a surrogate model in interpretability?",
    "A simple model trained to mimic a complex model's predictions.",
    ["A held-out copy of the training data that is used to check whether the main model has memorised the examples it was trained on.",
     "A second model trained on the residuals of the first so that together they correct each other's systematic errors.",
     "A calibration layer that adjusts a classifier's output scores so they behave like true probabilities.",
     "A baseline that always predicts the most common class."],
    "Surrogate model",
    "An interpretable model (e.g. a shallow tree or linear model) fitted to reproduce a black box's outputs, giving an approximate, explainable view of its behaviour.",
    "The surrogate explains the black box only as well as it fits it; a high fidelity means its rules are a trustworthy summary, a low fidelity means caution.",
    "Train a simple model to imitate a complex one so you can read it.");

  def("interp",
    "What is a counterfactual explanation?",
    "The smallest change to an input that would flip the model's decision.",
    ["A ranking of all input features according to how much each one contributed, on average, to predictions across the entire dataset.",
     "A synthetic example generated to augment the minority class so that the classifier sees more balanced training data.",
     "A statement of how confident the model is in its prediction expressed as a calibrated probability.",
     "A plot of the average prediction as one feature is varied."],
    "Counterfactual explanation",
    "A local explanation of the form 'if these feature values had been different, the outcome would have changed', identifying minimal, actionable edits.",
    "It answers 'what would need to change to get a different result?', which is often more useful to end users than a list of importances.",
    "It tells you what you'd have to change to get a different answer.");

  def("interp",
    "What are anchors in model interpretability?",
    "If-then rules that pin a prediction with high precision locally.",
    ["Continuous curves that trace how the model's average output shifts as a single input feature is gradually increased or decreased.",
     "Fixed reference points in feature space chosen so that every other example can be explained by its distance to them.",
     "Weights assigned to training examples so that harder cases receive more attention during fitting.",
     "The support vectors that lie on the margin of a fitted classifier."],
    "Anchors",
    "A rule-based local explanation method: an anchor is a set of feature conditions that, when met, almost always yield the same prediction regardless of other features.",
    "Each anchor comes with a precision (how reliably the rule holds) and coverage (how many instances it applies to), giving human-readable if-then explanations.",
    "They give a simple rule that reliably locks in the model's answer.");

  def("interp",
    "What is a saliency map?",
    "A heatmap highlighting the input regions that most affect a prediction.",
    ["A ranked list of the training examples whose removal would change the model's parameters by the largest amount.",
     "A plot of how the model's predicted probability changes as the classification threshold is moved from zero to one.",
     "A projection of high-dimensional inputs onto two axes so that similar inputs appear close together.",
     "A table of how often each feature is used across an ensemble of trees."],
    "Saliency map",
    "A local explanation, common for image models, that scores how sensitive the output is to each input pixel or region, typically via gradients.",
    "Bright areas mark inputs the model reacted to most; it is fast to compute but can be noisy and sensitive to how it is calculated.",
    "It shows which parts of an image the model looked at.");

  def("interp",
    "What does 'attention as explanation' refer to?",
    "Using a model's attention weights to suggest which inputs it focused on.",
    ["Training a separate simple model whose only job is to approximate and thereby explain the behaviour of a larger network.",
     "Perturbing each input feature in turn and measuring the resulting change in the network's predicted output distribution.",
     "Averaging predictions over many dropout masks to estimate how uncertain the model is about each input.",
     "Highlighting the pixels of an image with the largest output gradient."],
    "Attention as explanation",
    "The practice of reading attention weights in neural networks as indicators of input importance; it is intuitive but its faithfulness is debated.",
    "Attention shows where computation was routed, but studies show high-attention tokens aren't always the ones that determine the output, so treat it cautiously.",
    "Attention weights hint at what the model focused on, but aren't a guaranteed explanation.");

  def("interp",
    "What distinguishes transparent models from post-hoc explanations?",
    "Transparent models are readable directly; post-hoc explains a fitted black box.",
    ["Transparent models are always more accurate than black boxes, whereas post-hoc explanations are only ever applied to models that underperform.",
     "Transparent models require no training data at all, whereas post-hoc explanations must be recomputed for every new example that the model receives.",
     "Transparent models work only on images while post-hoc explanations work only on tabular data.",
     "There is no real difference; the two terms describe the same technique."],
    "Transparency vs post-hoc",
    "Intrinsic transparency means the model's structure is itself understandable (e.g. linear models, short trees); post-hoc methods explain an already-trained opaque model from outside.",
    "The choice is a trade-off: transparent models give trustworthy explanations by construction, while post-hoc methods let you keep a powerful model but only approximate its reasoning.",
    "Some models you can just read; for the rest you add tools to explain them afterward.");

  def("interp",
    "What are monotonic constraints in interpretable modelling?",
    "Rules forcing the prediction to move only one way with a feature.",
    ["Restrictions that limit the total number of features a model is allowed to use so that the final model stays small and readable.",
     "Conditions that require every leaf of a decision tree to contain at least a minimum number of training examples before a split is allowed.",
     "Penalties added to the loss so that the model's coefficients shrink toward zero during fitting.",
     "Bounds that keep predicted probabilities strictly between zero and one."],
    "Monotonic constraints",
    "Constraints (supported by boosting libraries) requiring the model output to be non-decreasing or non-increasing in a chosen feature, encoding domain knowledge.",
    "They make behaviour predictable and defensible (e.g. risk rises with debt), improving trust and sometimes generalisation by ruling out implausible wiggles.",
    "They make the model respect 'more of X should only push the result one direction'.");

  def("interp",
    "What is an intrinsically interpretable model?",
    "A model whose structure can be understood without extra explanation tools.",
    ["A model that produces a separate textual explanation alongside every prediction it makes on new incoming data.",
     "A model that has been simplified after training by pruning away the components that contribute least to its accuracy.",
     "A model that reaches state-of-the-art accuracy while using the smallest possible number of trainable parameters.",
     "A model trained only on data that a human has already labelled with explanations."],
    "Intrinsically interpretable model",
    "A model (linear/logistic regression, shallow decision tree, rule list) simple enough that its decision logic is directly readable from its parameters or structure.",
    "Interpretability is built in rather than added later, so there is no fidelity gap between the model and its explanation, unlike with surrogate or post-hoc methods.",
    "Some models are simple enough to just read and understand as-is.");

  def("interp",
    "What is an ALE plot?",
    "A plot of a feature's effect that stays reliable when features are correlated.",
    ["A curve showing the average model prediction as a feature is varied while every other feature is held fixed at its own mean value.",
     "A collection of lines, one per instance, tracing how each individual prediction responds to changes in a single chosen feature.",
     "A ranking of features by the drop in accuracy observed when each feature's values are randomly shuffled in turn.",
     "A bar chart of the coefficients learned by a linear model."],
    "Accumulated Local Effects (ALE) plot",
    "Accumulated Local Effects plots show a feature's influence by averaging local changes within small intervals, avoiding the unrealistic extrapolation that biases PDPs under correlation.",
    "By accumulating gradients over the feature's actual distribution rather than fixing other features, ALE gives less misleading effect estimates when predictors are correlated.",
    "It's like a PDP but trustworthy when features move together.");

  def("interp",
    "What is Grad-CAM?",
    "A method that highlights image regions driving a CNN's class prediction.",
    ["A technique that fits an interpretable linear model in the neighbourhood of one prediction to approximate a black box locally.",
     "A procedure that assigns each feature a contribution based on cooperative game theory averaged over all feature orderings.",
     "An augmentation method that generates new minority-class images to rebalance a training set.",
     "A calibration step that rescales a network's output logits into probabilities."],
    "Grad-CAM",
    "Gradient-weighted Class Activation Mapping uses the gradients flowing into a CNN's last convolutional layer to produce a coarse heatmap of the regions important for a class.",
    "It is a widely used visual explanation for convolutional networks, localising the evidence a model used without changing the model's architecture.",
    "It shades the picture areas a CNN used to pick its answer.");

  def("interp",
    "What are integrated gradients?",
    "An attribution method integrating gradients along a path from a baseline.",
    ["A visual explanation that averages the attention weights across every layer of a transformer to show which tokens mattered.",
     "A ranking of training examples by how much each one influenced the final values of the model's learned parameters.",
     "A perturbation method that shuffles one feature at a time and records the resulting change in accuracy.",
     "A rule-based explanation that pins predictions with high-precision conditions."],
    "Integrated gradients",
    "A gradient-based attribution technique that credits each input feature by integrating the model's gradients along a straight path from a reference baseline to the actual input.",
    "It satisfies desirable axioms (sensitivity, completeness) that plain gradients lack, giving more faithful per-feature attributions for differentiable models.",
    "It fairly splits the prediction across inputs by tracing gradients from a blank starting point.");

  /* ===================== Class imbalance (imbal) — 16 ===================== */

  def("imbal",
    "What is ADASYN?",
    "An oversampler that makes more synthetic points for harder minority cases.",
    ["A method that removes majority-class examples lying closest to the decision boundary so that the two classes become easier to separate.",
     "A reweighting scheme that multiplies each example's loss by a factor inversely proportional to the frequency of its class.",
     "A threshold-tuning rule that lowers the decision cutoff until the desired recall on the minority class is achieved.",
     "A metric that summarises the precision-recall curve as a single number."],
    "ADASYN",
    "Adaptive Synthetic Sampling generates synthetic minority examples, focusing more of them where minority points are surrounded by majority points (harder to learn).",
    "Like SMOTE it interpolates new minority samples, but it adapts the number produced per region to the local difficulty, emphasising hard-to-classify areas.",
    "It's SMOTE that makes extra fake examples where the minority is hardest to learn.");

  def("imbal",
    "What is random oversampling?",
    "Duplicating minority-class examples at random to balance the classes.",
    ["Generating brand-new synthetic minority examples by interpolating between existing minority points and their nearest neighbours.",
     "Discarding a random subset of the majority-class examples until the two classes are equal in size.",
     "Assigning larger weights to minority examples so the loss function treats their errors as more costly.",
     "Lowering the classifier's decision threshold to catch more of the minority class."],
    "Random oversampling",
    "The simplest rebalancing method: sample minority rows with replacement and add the copies to the training set until the classes are balanced.",
    "It adds no new information and can encourage overfitting to the repeated points, but it is easy and sometimes effective as a baseline.",
    "Just copy the rare examples until both classes are even.");

  def("imbal",
    "What is random undersampling?",
    "Dropping majority-class examples at random to balance the classes.",
    ["Creating synthetic examples of the majority class so that its distribution is smoother and easier for the model to learn.",
     "Duplicating minority-class examples with replacement until the number of minority rows matches the number of majority rows.",
     "Reweighting the loss so majority-class mistakes count for less during optimisation.",
     "Moving the decision threshold upward to reduce false positives."],
    "Random undersampling",
    "A rebalancing method that randomly removes majority-class rows until the classes are roughly equal, shrinking the training set.",
    "It is fast and reduces majority dominance, but discarding data can throw away useful information, especially when the majority class is not huge.",
    "Throw away some common examples so the rare ones aren't outnumbered.");

  def("imbal",
    "What are Tomek links?",
    "Nearest-neighbour pairs from opposite classes, removed to clean boundaries.",
    ["Synthetic minority examples created by interpolating along the line segment joining a minority point to one of its neighbours.",
     "Majority examples selected because they are surrounded entirely by other majority examples and thus carry little information.",
     "Weights attached to boundary examples so that the classifier pays more attention to them during training.",
     "Clusters of minority points identified before applying oversampling."],
    "Tomek links",
    "A pair of points from different classes that are each other's nearest neighbour; removing the majority member (or both) cleans overlapping class boundaries.",
    "Used as an undersampling or cleaning step, often after SMOTE, to sharpen the decision boundary by deleting ambiguous, borderline majority points.",
    "They're close opposite-class pairs you remove to tidy the border between classes.");

  def("imbal",
    "What is cost-sensitive learning?",
    "Training that assigns different penalties to different kinds of errors.",
    ["Resampling the training data so that both classes contribute an equal number of rows before the model is fitted.",
     "Generating synthetic examples of the minority class to compensate for the small number of real examples available.",
     "Choosing the classification threshold after training so that a target recall on the rare class is reached.",
     "Selecting a metric such as PR-AUC that is robust to class imbalance."],
    "Cost-sensitive learning",
    "An approach that bakes the real-world cost of misclassifications into the objective, so the model prioritises avoiding the more expensive error type.",
    "Rather than changing the data, it changes the loss (e.g. via class weights or a cost matrix) so that, say, missing a fraud costs more than a false alarm.",
    "Teach the model that some mistakes cost more than others.");

  def("imbal",
    "What is threshold moving?",
    "Adjusting the decision cutoff on predicted scores after training.",
    ["Retraining the model repeatedly with different class weights until the desired balance between precision and recall is reached.",
     "Generating additional synthetic minority examples until the model's predicted probabilities become well calibrated.",
     "Removing majority examples near the boundary so the default cutoff of one half becomes appropriate again.",
     "Selecting which evaluation metric best reflects the costs of the problem."],
    "Threshold moving",
    "A post-training technique that changes the probability cutoff used to assign the positive class, trading precision against recall without retraining.",
    "Since the default 0.5 threshold is often wrong under imbalance, tuning it on validation data (e.g. to maximise F1) can improve minority-class performance for free.",
    "Change the cutoff for calling something positive instead of retraining.");

  def("imbal",
    "What is the minority class?",
    "The class with far fewer examples in an imbalanced dataset.",
    ["The class whose examples are hardest to classify because they lie closest to the model's decision boundary.",
     "The class that a model tends to predict most often when it is optimised purely for overall accuracy.",
     "The class that carries the higher misclassification cost in a cost-sensitive setting.",
     "The class used as the positive label when computing the ROC curve."],
    "Minority class",
    "In an imbalanced problem, the under-represented class (often the one of interest, e.g. fraud or disease), which naive models tend to neglect.",
    "Because it contributes few rows, accuracy-driven learners can ignore it while still scoring well, which is exactly why imbalance techniques target it.",
    "It's the rare class you usually care about most.");

  def("imbal",
    "What is the majority class?",
    "The class with far more examples in an imbalanced dataset.",
    ["The class that a well-calibrated model assigns the highest average predicted probability to across the test set.",
     "The class whose examples are removed first whenever an undersampling procedure is applied to the training data.",
     "The class chosen as the negative label when a binary confusion matrix is constructed.",
     "The class that a dummy classifier predicts to maximise recall."],
    "Majority class",
    "The over-represented class in an imbalanced dataset; a trivial model predicting only this class can reach high accuracy while being useless.",
    "Its dominance is what makes accuracy misleading and pushes learners to under-serve the minority, motivating resampling, reweighting, or better metrics.",
    "It's the common class that swamps the rare one.");

  def("imbal",
    "Why must resampling be done inside cross-validation, not before?",
    "Resampling before splitting leaks information and inflates scores.",
    ["Resampling before splitting removes so many rows that the cross-validation folds become too small to give a stable estimate of performance.",
     "Resampling before splitting changes the order of the rows, which prevents the folds from preserving the original class proportions.",
     "Resampling before splitting is slower because the synthetic examples must be regenerated for every fold of the loop.",
     "Resampling before splitting always reduces recall on the minority class."],
    "Resampling inside cross-validation",
    "Oversampling (e.g. SMOTE) the whole dataset before splitting lets synthetic or duplicated minority points appear in both train and validation folds, leaking information.",
    "The fix is to resample only the training fold within each CV iteration (e.g. with an imblearn Pipeline), giving an honest estimate of generalisation.",
    "Balance inside each fold, or the model 'sees' the test data and looks better than it is.");

  def("imbal",
    "What is focal loss?",
    "A loss that down-weights easy examples to focus on hard ones.",
    ["A loss that adds a penalty proportional to the squared magnitude of the model's weights so that the fitted model generalises better.",
     "A loss that scales each example's contribution by the inverse frequency of its class so that rare classes count for more.",
     "A loss that measures the area under the precision-recall curve directly during optimisation.",
     "A loss used only for regression that is quadratic near zero and linear far from it."],
    "Focal loss",
    "A modification of cross-entropy that multiplies each term by a factor which shrinks as the predicted probability grows, concentrating learning on hard, misclassified cases.",
    "Popular in dense object detection, it reduces the flood of gradient from abundant easy negatives so the model spends effort on the difficult minority-like examples.",
    "It tells the model to stop obsessing over easy cases and learn the hard ones.");

  def("imbal",
    "What is EasyEnsemble?",
    "An ensemble trained on several balanced undersampled subsets of the data.",
    ["A single model trained on the full dataset after synthetic minority examples have been added to balance the two classes.",
     "A boosting method that reweights misclassified minority examples more heavily after each successive round of training.",
     "A voting scheme that averages the predictions of models trained with several different random seeds.",
     "A threshold-selection procedure applied to a fitted classifier's probability outputs."],
    "EasyEnsemble",
    "An ensemble method for imbalance that draws multiple balanced subsets by undersampling the majority, trains a learner on each, and combines them.",
    "By using many undersampled subsets it recovers information that a single undersample would discard, while keeping each base learner's classes balanced.",
    "Undersample many times, train a model on each, and combine them.");

  def("imbal",
    "What is balanced bagging?",
    "Bagging where each bootstrap sample is resampled to balance classes.",
    ["A boosting procedure that grows trees sequentially, giving extra weight to the minority examples that the previous trees got wrong.",
     "A single decision tree fitted after the majority class has been undersampled down to the size of the minority class.",
     "A calibration technique that adjusts predicted probabilities so they match observed frequencies on imbalanced data.",
     "A metric that combines precision and recall into a single balanced score."],
    "Balanced bagging",
    "A bagging ensemble (e.g. BalancedBaggingClassifier) in which each base estimator is trained on a class-balanced resample of the bootstrap draw.",
    "It combines the variance reduction of bagging with per-bag rebalancing, so every tree sees comparable class counts without discarding all majority data globally.",
    "It's bagging that rebalances the classes inside each bag.");

  def("imbal",
    "Why is PR-AUC often preferred over ROC-AUC under heavy imbalance?",
    "PR-AUC focuses on the rare positive class and its precision.",
    ["Because ROC-AUC cannot be computed at all when one of the two classes contains only a very small number of examples in the test set.",
     "Because PR-AUC is guaranteed to be higher than ROC-AUC whenever the positive class is the minority class in the dataset.",
     "Because ROC-AUC requires calibrated probabilities while PR-AUC works directly with raw decision-function scores.",
     "Because PR-AUC ignores false positives entirely and rewards recall only."],
    "PR-AUC preference",
    "Precision-recall AUC emphasises performance on the positive (minority) class; ROC-AUC can look optimistic because a huge true-negative count keeps the false-positive rate low.",
    "When positives are rare, precision reflects how many flagged cases are real, which the PR curve captures but the ROC curve can mask, so PR-AUC is the more honest summary.",
    "With rare positives, the PR curve shows the truth that ROC can hide.");

  def("imbal",
    "What is Borderline-SMOTE?",
    "A SMOTE variant that oversamples only minority points near the boundary.",
    ["A SMOTE variant that generates synthetic examples for every minority point equally regardless of where it lies in the feature space.",
     "A cleaning method that deletes majority examples that are the nearest neighbours of minority examples to sharpen the boundary.",
     "A reweighting rule that increases the loss contribution of misclassified boundary examples during training.",
     "A metric that measures how many minority points lie on the wrong side of the decision boundary."],
    "Borderline-SMOTE",
    "A refinement of SMOTE that identifies minority examples on the class border (those with many majority neighbours) and synthesises new points mainly there.",
    "Focusing synthesis on the difficult boundary region, rather than safe interior points, tends to help the classifier draw a better decision surface.",
    "It's SMOTE aimed at the rare examples sitting on the edge between classes.");

  def("imbal",
    "What is Edited Nearest Neighbours (ENN) as a cleaning method?",
    "Removing examples that disagree with their neighbours' majority label.",
    ["Generating synthetic minority examples by interpolating between each minority point and a randomly chosen one of its nearest neighbours.",
     "Duplicating the minority examples whose nearest neighbours mostly belong to the opposite class so the model sees them more often.",
     "Reweighting each training example according to how many of its neighbours share its class label.",
     "Selecting the value of k for a nearest-neighbour classifier by cross-validation."],
    "Edited Nearest Neighbours (ENN)",
    "An undersampling/cleaning rule that deletes any example whose class differs from the majority class of its k nearest neighbours, removing noisy or borderline points.",
    "Often paired with SMOTE (as SMOTE-ENN), it cleans up overlapping regions after synthesis, discarding samples that sit among the wrong class.",
    "Drop points that clash with the crowd around them to clean up the classes.");

  def("imbal",
    "What is NearMiss undersampling?",
    "Undersampling that keeps majority points closest to the minority class.",
    ["Undersampling that removes majority points only when they form a nearest-neighbour pair with a point from the opposite class.",
     "Undersampling that randomly discards majority examples without regard to their position in the feature space.",
     "Oversampling that adds synthetic minority points near the boundary where the classes overlap the most.",
     "Reweighting that gives majority points near the boundary a smaller loss contribution."],
    "NearMiss undersampling",
    "A family of heuristic undersampling methods that select majority examples based on their distance to minority examples, keeping those nearest the minority class.",
    "By retaining informative majority points close to the boundary instead of removing at random, it aims to preserve the decision region while shrinking the majority.",
    "Keep the common examples nearest the rare class and drop the rest.");

  /* ===================== Regression & boosting (regr) — 14 ===================== */

  def("regr",
    "What is ridge regression?",
    "Linear regression with an L2 penalty that shrinks coefficients.",
    ["Linear regression with a penalty on the sum of the absolute values of the coefficients, which drives some of them exactly to zero.",
     "Linear regression that fits a separate slope for every subgroup of the data and then averages the resulting predictions together.",
     "Linear regression whose loss is quadratic for small residuals and linear for large ones to resist outliers.",
     "Linear regression estimated by minimising the absolute rather than the squared residuals."],
    "Ridge regression",
    "A regularised least-squares method that adds a penalty proportional to the sum of squared coefficients (L2), shrinking them toward zero without eliminating any.",
    "The penalty reduces variance and handles multicollinearity by discouraging large weights, trading a little bias for more stable, generalisable estimates.",
    "It's linear regression that keeps the coefficients small to avoid overfitting.");

  def("regr",
    "What is lasso regression?",
    "Linear regression with an L1 penalty that can zero out coefficients.",
    ["Linear regression with a penalty on the sum of the squared coefficients, which shrinks them all toward zero without removing any of them.",
     "Linear regression that combines squared and absolute penalties in a fixed ratio to balance shrinkage against selection.",
     "Linear regression fitted by minimising a loss that is quadratic near zero and becomes linear for large residuals.",
     "Linear regression in which the coefficients are estimated separately for each fold of a cross-validation loop."],
    "Lasso regression",
    "A regularised regression that penalises the sum of absolute coefficient values (L1); the geometry of this penalty forces some coefficients exactly to zero.",
    "Because it sets weak coefficients to zero, lasso performs feature selection as it fits, yielding sparser, more interpretable models than ridge.",
    "It's linear regression that both shrinks and switches off unhelpful features.");

  def("regr",
    "What is mean absolute error (MAE)?",
    "The average of the absolute differences between predictions and truth.",
    ["The square root of the average of the squared differences between the predicted values and the observed target values.",
     "The average of the squared differences between the predicted values and the true values across all of the examples.",
     "The fraction of the variance in the target that the model manages to explain relative to a mean baseline.",
     "The largest single absolute difference between any prediction and its true value."],
    "Mean absolute error (MAE)",
    "A regression metric equal to the mean of |prediction − actual|, expressed in the target's units and treating all errors linearly.",
    "Unlike RMSE it does not square errors, so it is less sensitive to outliers and reflects the typical size of an error directly.",
    "On average, how far off the predictions are.");

  def("regr",
    "What is R-squared (the coefficient of determination)?",
    "The fraction of target variance the model explains.",
    ["The square root of the average squared difference between the predicted values and the true target values across the dataset.",
     "The proportion of predictions that fall within one standard deviation of the corresponding true target value.",
     "The average absolute difference between predictions and the mean of the target variable.",
     "The correlation between two input features expressed as a value between minus one and one."],
    "R-squared",
    "A goodness-of-fit measure equal to 1 minus the ratio of the model's residual sum of squares to the total variance; 1 is perfect, 0 matches predicting the mean.",
    "It reports how much better the model does than always predicting the average; it can go negative on test data when the model is worse than that baseline.",
    "It's the share of the ups and downs in the target the model captures.");

  def("regr",
    "What is a residual in regression?",
    "The difference between an observed value and its predicted value.",
    ["The portion of the target's variance that remains unexplained by the model after all of the predictors have been included.",
     "The penalty term added to the loss that discourages the model from fitting excessively large coefficient values.",
     "The average distance between each data point and the centroid of its assigned cluster.",
     "The gradient of the loss with respect to a single model parameter."],
    "Residual",
    "For one example, residual = actual − predicted; the collection of residuals reveals how well and how evenly a regression model fits.",
    "Patterns in residual plots (curvature, changing spread) diagnose model misspecification, non-linearity, or non-constant variance.",
    "It's how far a single prediction misses the true value.");

  def("regr",
    "What is homoscedasticity?",
    "Constant variance of the residuals across all fitted values.",
    ["A situation in which the residuals grow steadily larger in magnitude as the fitted values increase across their range.",
     "A situation in which the predictor variables are strongly correlated with one another, inflating the variance of the estimates.",
     "A property meaning the residuals are perfectly uncorrelated with every one of the input features.",
     "A property meaning the residuals follow an exactly normal distribution."],
    "Homoscedasticity",
    "An assumption of ordinary linear regression that the error variance is the same for all values of the predictors (residual spread does not change).",
    "When it fails (heteroscedasticity), coefficient estimates stay unbiased but their standard errors are wrong, so inference and prediction intervals become unreliable.",
    "It means the prediction errors are equally spread out everywhere.");

  def("regr",
    "What is multicollinearity in regression?",
    "High correlation among predictors that destabilises coefficients.",
    ["A situation where the spread of the residuals increases as the value of the fitted response variable becomes larger.",
     "A situation where the relationship between a predictor and the target is curved rather than a straight line.",
     "A property whereby the model's residuals are correlated with the order in which the observations were collected.",
     "The presence of a few extreme observations that exert strong leverage on the fitted line."],
    "Multicollinearity",
    "When two or more predictors are highly correlated, the model cannot separate their effects, so individual coefficients become unstable and hard to interpret.",
    "Predictions can still be fine, but coefficient signs and magnitudes swing with small data changes; remedies include dropping variables or using ridge regression.",
    "When inputs overlap heavily, the model can't tell which one deserves the credit.");

  def("regr",
    "What is ordinary least squares (OLS)?",
    "Fitting a line by minimising the sum of squared residuals.",
    ["Fitting a line by minimising the sum of the absolute values of the residuals so that outliers have less influence.",
     "Fitting a line by adding a penalty on the coefficients to the squared-error loss before minimising it.",
     "Fitting a line by maximising the correlation between the predictions and the observed target values.",
     "Fitting a line by minimising the largest single residual over all of the data points."],
    "Ordinary least squares",
    "The classic estimator for linear regression: choose coefficients that minimise the total squared vertical distance between the data points and the fitted line.",
    "Under its assumptions it gives the best linear unbiased estimates, and squaring errors makes the solution closed-form but sensitive to outliers.",
    "It picks the line that makes the squared misses as small as possible.");

  def("regr",
    "What is a gradient boosting regressor?",
    "An ensemble that adds trees fitting the previous model's residuals.",
    ["An ensemble that trains many independent trees on bootstrap samples and averages their predictions to reduce variance.",
     "A single deep regression tree grown until each leaf contains only one training example so it fits the data exactly.",
     "A linear model that adds an L2 penalty to its loss so that the fitted coefficients remain small.",
     "A model that predicts the mean of the target for every input regardless of the features."],
    "Gradient boosting regressor",
    "A boosting ensemble for regression that builds trees sequentially, each new tree fitting the negative gradient (pseudo-residuals) of the loss to correct prior errors.",
    "By adding many shrunken weak learners that focus on what remains unexplained, it produces a strong, flexible regressor, at the cost of careful tuning.",
    "It stacks small trees, each fixing the leftover mistakes of the ones before.");

  def("regr",
    "What is quantile regression?",
    "Regression that predicts a chosen quantile rather than the mean.",
    ["Regression that first bins the target into quantile groups and then predicts which group each example belongs to.",
     "Regression that minimises the squared error but reports the results separately for each quartile of the predictions.",
     "Regression that penalises the coefficients so that only a fixed quantile of them remain non-zero.",
     "Regression that averages the predictions from models fitted on different quantiles of the data."],
    "Quantile regression",
    "A method that estimates a conditional quantile (e.g. the median or the 90th percentile) of the target by minimising an asymmetric pinball loss.",
    "It gives prediction intervals and captures how the whole distribution of the target shifts with the features, not just its average.",
    "It predicts, say, the 90th-percentile outcome instead of the typical one.");

  def("regr",
    "What is Huber loss?",
    "A loss that is squared near zero and linear for large errors.",
    ["A loss that penalises the absolute values of the model coefficients to encourage a sparse and interpretable solution.",
     "A loss that squares every residual so that observations with large errors dominate the total loss value.",
     "A loss that measures the average absolute difference between the predicted and the true target values.",
     "A loss that counts the fraction of predictions falling outside a fixed tolerance band."],
    "Huber loss",
    "A robust regression loss that behaves like squared error for small residuals and like absolute error beyond a threshold, softening the influence of outliers.",
    "It blends the smoothness of MSE near the optimum with the outlier resistance of MAE in the tails, controlled by a tuning parameter delta.",
    "It punishes small misses gently like squares and big misses less harshly, so outliers hurt less.");

  def("regr",
    "What is adjusted R-squared?",
    "R-squared penalised for the number of predictors in the model.",
    ["The proportion of the variance in the target that is explained by the model after the target has been standardised to unit variance.",
     "The value of R-squared computed on a held-out test set rather than on the data the model was fitted on.",
     "The square of the correlation between two predictors used to detect redundancy among the features.",
     "The R-squared recomputed after the least useful predictor has been removed from the model."],
    "Adjusted R-squared",
    "A version of R-squared that increases only if a new predictor improves the fit more than expected by chance, penalising models for extra parameters.",
    "Plain R-squared never decreases when features are added; the adjusted form corrects for this, making it fairer for comparing models with different numbers of predictors.",
    "It's R-squared that doesn't reward you just for adding more inputs.");

  def("regr",
    "What is mean absolute percentage error (MAPE)?",
    "The average absolute error expressed as a percentage of the actual value.",
    ["The average of the squared differences between predictions and true values divided by the range of the target variable.",
     "The percentage of predictions that fall within a fixed tolerance of their corresponding true target values.",
     "The absolute error of the single worst prediction expressed relative to the mean of the target.",
     "The correlation between predicted and actual values reported as a percentage."],
    "Mean absolute percentage error (MAPE)",
    "A scale-free regression metric equal to the mean of |actual − predicted| / |actual|, usually shown as a percentage.",
    "It makes errors comparable across series of different magnitudes, but it is undefined or exploding when actual values are zero or near zero and penalises over- and under-prediction unevenly.",
    "It's how far off you are on average, as a percent of the true value.");

  def("regr",
    "What is polynomial regression?",
    "Linear regression on polynomial-expanded features of the inputs.",
    ["A model that fits a separate straight line to each region of the input space and joins them at fixed breakpoints.",
     "A model that raises the target variable to successive powers before fitting a straight line to the transformed values.",
     "A model that selects the polynomial degree by minimising the absolute rather than the squared residuals.",
     "A model that averages several straight-line fits obtained from different random subsets of the data."],
    "Polynomial regression",
    "A regression that adds powers and products of the original features (x, x^2, x^3, ...) and fits a linear model to them, capturing curved relationships.",
    "It is still linear in its coefficients, so ordinary least squares applies, but high degrees overfit and extrapolate wildly, so the degree must be tuned.",
    "It bends the line by feeding the model squares and cubes of the inputs.");

})();
