/* Python coding test — problem bank: data structures and algorithms.
   Graphs, dynamic programming, intervals, monotonic stacks and trees — the
   questions that come up once a screening test moves past "loop over a list". */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var DS = 'Data structures';
  var AL = 'Algorithms';

  window.PYTESTS.push(

    { id: 'pt-dsa-queue-sim', group: DS, lvl: 1,
      title: 'Serve the queue',
      fn: 'serve',
      brief: 'People join the back of a queue and are served from the front.\n\nGiven a list of instructions — a name to add that person, or the word "serve" to serve whoever is at the front — return the list of names served, in order. Serving an empty queue does nothing.',
      sig: 'def serve(instructions: list[str]) -> list[str]',
      starter: 'def serve(instructions):\n    # your code here\n    pass\n',
      examples: [
        { in: "serve(['ann', 'bob', 'serve', 'serve'])", out: "['ann', 'bob']" }],
      tests: [
        { call: "serve(['ann', 'bob', 'serve', 'serve'])", expect: "['ann', 'bob']" },
        { call: "serve(['serve'])", expect: '[]', name: 'serving nobody' },
        { call: "serve(['ann', 'serve', 'bob', 'serve'])", expect: "['ann', 'bob']" },
        { call: "serve([])", expect: '[]', hidden: true },
        { call: "serve(['a', 'b', 'c', 'serve'])", expect: "['a']", hidden: true, name: 'first in, first out' }],
      hint: 'A queue is first-in-first-out: add to the back, take from the front. collections.deque takes from the front in O(1) with popleft().',
      solution: "from collections import deque\n\n\ndef serve(instructions):\n    queue = deque()\n    served = []\n    for item in instructions:\n        if item == 'serve':\n            if queue:\n                served.append(queue.popleft())\n        else:\n            queue.append(item)\n    return served\n",
      walk: "The whole question is knowing which end you take from. `list.pop(0)` also works and is fine at this size, but it shuffles every remaining element down, so it is O(n) each time; `deque.popleft()` is O(1). The guard `if queue:` is the case they are really testing — popping an empty queue raises.",
      complexity: 'O(n) time over the instructions, O(n) space.' },

    { id: 'pt-dsa-min-stack', group: DS, lvl: 3,
      title: 'A stack that knows its minimum',
      fn: 'MinStack',
      brief: 'Write a class MinStack with .push(x), .pop() and .min().\n\n.pop() removes and returns the top item; .min() returns the smallest item currently on the stack. Both must be O(1) — you cannot scan the stack on every call. On an empty stack, .pop() and .min() both return None.',
      sig: 'class MinStack:  # .push(x), .pop(), .min()',
      starter: 'class MinStack:\n    def __init__(self):\n        # your code here\n        pass\n',
      examples: [
        { in: 's = MinStack(); s.push(3); s.push(1); s.min()', out: '1' }],
      tests: [
        { call: '_stack([3, 1, 4]).min()', expect: '1' },
        { call: 'MinStack().min()', expect: 'None', name: 'empty stack' },
        { call: 'MinStack().pop()', expect: 'None' },
        { call: '_popped([3, 1, 4], 2)', expect: '3', hidden: true, name: 'the minimum comes back after popping' },
        { call: '_stack([2, 2, 5]).min()', expect: '2', hidden: true, name: 'duplicate minimums' }],
      setup: "def _stack(values):\n    s = MinStack()\n    for v in values:\n        s.push(v)\n    return s\n\n\ndef _popped(values, times):\n    s = _stack(values)\n    for _ in range(times):\n        s.pop()\n    return s.min()\n",
      hint: 'Keep a second stack of minimums. Push the smaller of x and the current minimum onto it every time, and pop both stacks together.',
      solution: "class MinStack:\n    def __init__(self):\n        self.items = []\n        self.mins = []\n\n    def push(self, x):\n        self.items.append(x)\n        if not self.mins or x <= self.mins[-1]:\n            self.mins.append(x)\n        else:\n            self.mins.append(self.mins[-1])\n\n    def pop(self):\n        if not self.items:\n            return None\n        self.mins.pop()\n        return self.items.pop()\n\n    def min(self):\n        return self.mins[-1] if self.mins else None\n",
      walk: "The trick is that a stack only ever changes at one end, so the minimum can be remembered per level. Pushing a value onto `mins` for EVERY push — even when it is not the new minimum — keeps the two stacks the same height, which is what makes popping them together correct. The `<=` rather than `<` matters for duplicate minimums: with `<` you would drop one copy too early.",
      complexity: 'O(1) per operation, O(n) extra space.' },

    { id: 'pt-dsa-dfs-reach', group: DS, lvl: 2,
      title: 'Can you get there?',
      fn: 'can_reach',
      brief: 'A graph is given as a dict mapping each node to a list of the nodes it points to.\n\nReturn True if you can get from start to target by following the arrows. A node always reaches itself.',
      sig: 'def can_reach(graph: dict, start, target) -> bool',
      starter: 'def can_reach(graph, start, target):\n    # your code here\n    pass\n',
      examples: [
        { in: "can_reach({'a': ['b'], 'b': ['c'], 'c': []}, 'a', 'c')", out: 'True' },
        { in: "can_reach({'a': ['b'], 'b': [], 'c': []}, 'a', 'c')", out: 'False' }],
      tests: [
        { call: "can_reach({'a': ['b'], 'b': ['c'], 'c': []}, 'a', 'c')", expect: 'True' },
        { call: "can_reach({'a': ['b'], 'b': [], 'c': []}, 'a', 'c')", expect: 'False' },
        { call: "can_reach({'a': []}, 'a', 'a')", expect: 'True', name: 'a node reaches itself' },
        { call: "can_reach({'a': ['b'], 'b': ['a'], 'c': []}, 'a', 'c')", expect: 'False', hidden: true, name: 'a cycle must not hang' },
        { call: "can_reach({'a': ['b', 'c'], 'b': [], 'c': ['d'], 'd': []}, 'a', 'd')", expect: 'True', hidden: true }],
      hint: 'Keep a stack of nodes to visit and a set of nodes already visited. Without the visited set, a cycle loops forever.',
      solution: "def can_reach(graph, start, target):\n    stack = [start]\n    seen = set()\n    while stack:\n        node = stack.pop()\n        if node == target:\n            return True\n        if node in seen:\n            continue\n        seen.add(node)\n        for nxt in graph.get(node, []):\n            stack.append(nxt)\n    return False\n",
      walk: "This is depth-first search written with an explicit stack, which is safer than recursion when a graph might be deep. Two details carry the marks: the `seen` set, without which the a↔b cycle runs forever, and `graph.get(node, [])` rather than `graph[node]`, which keeps it alive when a node is named as a neighbour but has no entry of its own.",
      complexity: 'O(V + E) time, O(V) space.' },

    { id: 'pt-dsa-bfs-steps', group: DS, lvl: 3,
      title: 'Fewest hops',
      fn: 'shortest_hops',
      brief: 'The graph is a dict of node to list of neighbours, and every edge counts as one hop.\n\nReturn the fewest hops from start to target, or -1 if there is no route. start to itself is 0.',
      sig: 'def shortest_hops(graph: dict, start, target) -> int',
      starter: 'def shortest_hops(graph, start, target):\n    # your code here\n    pass\n',
      examples: [
        { in: "shortest_hops({'a': ['b', 'c'], 'b': ['d'], 'c': ['d'], 'd': []}, 'a', 'd')", out: '2' }],
      tests: [
        { call: "shortest_hops({'a': ['b', 'c'], 'b': ['d'], 'c': ['d'], 'd': []}, 'a', 'd')", expect: '2' },
        { call: "shortest_hops({'a': ['b'], 'b': []}, 'a', 'a')", expect: '0', name: 'no hops needed' },
        { call: "shortest_hops({'a': ['b'], 'b': [], 'z': []}, 'a', 'z')", expect: '-1', name: 'no route' },
        { call: "shortest_hops({'a': ['b'], 'b': ['c'], 'c': ['d'], 'd': []}, 'a', 'd')", expect: '3', hidden: true },
        { call: "shortest_hops({'a': ['b', 'z'], 'b': ['z'], 'z': []}, 'a', 'z')", expect: '1', hidden: true, name: 'must find the short way, not the first way' }],
      hint: 'Breadth-first search: a deque holding (node, distance) pairs, taken from the front with popleft. The first time you reach the target is the shortest way.',
      solution: "from collections import deque\n\n\ndef shortest_hops(graph, start, target):\n    queue = deque([(start, 0)])\n    seen = {start}\n    while queue:\n        node, dist = queue.popleft()\n        if node == target:\n            return dist\n        for nxt in graph.get(node, []):\n            if nxt not in seen:\n                seen.add(nxt)\n                queue.append((nxt, dist + 1))\n    return -1\n",
      walk: "Depth-first would find A ROUTE; breadth-first finds the SHORTEST one, because it finishes every node at distance d before it looks at anything at d + 1. Carrying the distance alongside the node in the queue saves keeping a separate dict. Mark nodes as seen when you QUEUE them, not when you pop them, or a diamond-shaped graph queues the same node twice.",
      complexity: 'O(V + E) time, O(V) space.' },

    { id: 'pt-dsa-islands', group: AL, lvl: 3,
      title: 'Count the islands',
      fn: 'count_islands',
      brief: 'A grid is a list of equal-length strings of "1" (land) and "0" (water).\n\nAn island is a group of land squares joined up, down, left or right — not diagonally. Return how many islands there are.',
      sig: 'def count_islands(grid: list[str]) -> int',
      starter: 'def count_islands(grid):\n    # your code here\n    pass\n',
      examples: [
        { in: "count_islands(['110', '010', '001'])", out: '2' }],
      tests: [
        { call: "count_islands(['110', '010', '001'])", expect: '2' },
        { call: "count_islands(['000'])", expect: '0', name: 'all water' },
        { call: "count_islands(['1'])", expect: '1' },
        { call: "count_islands([])", expect: '0', hidden: true, name: 'empty grid' },
        { call: "count_islands(['101', '010', '101'])", expect: '5', hidden: true, name: 'diagonals do not join' }],
      hint: 'Walk every square. When you find land you have not visited, count one island and flood-fill outwards from it, marking every square you reach as visited.',
      solution: "def count_islands(grid):\n    if not grid:\n        return 0\n    rows, cols = len(grid), len(grid[0])\n    seen = set()\n    islands = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] != '1' or (r, c) in seen:\n                continue\n            islands += 1\n            stack = [(r, c)]\n            while stack:\n                y, x = stack.pop()\n                if (y, x) in seen:\n                    continue\n                seen.add((y, x))\n                for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):\n                    ny, nx = y + dy, x + dx\n                    if 0 <= ny < rows and 0 <= nx < cols and grid[ny][nx] == '1':\n                        stack.append((ny, nx))\n            # the whole island is now marked, so it is only counted once\n    return islands\n",
      walk: "Two loops on the outside to find a starting square, a flood fill on the inside to swallow the rest of that island. Because the strings are immutable you cannot sink the land in place, so a `seen` set of (row, col) tuples does the marking. The four moves as a tuple of offsets is the standard way to write neighbours; the bounds check on `ny` and `nx` is what stops it walking off the edge.",
      complexity: 'O(rows × cols) time and space.' },

    { id: 'pt-dsa-stairs', group: AL, lvl: 2,
      title: 'Ways up the stairs',
      fn: 'ways',
      brief: 'You climb a staircase of n steps, taking either 1 or 2 steps at a time.\n\nReturn how many different ways there are to reach the top. ways(0) is 1 — there is one way to stand still.',
      sig: 'def ways(n: int) -> int',
      starter: 'def ways(n):\n    # your code here\n    pass\n',
      examples: [
        { in: 'ways(4)', out: '5', note: '1111, 112, 121, 211, 22' }],
      tests: [
        { call: 'ways(4)', expect: '5' },
        { call: 'ways(0)', expect: '1', name: 'standing still counts' },
        { call: 'ways(1)', expect: '1' },
        { call: 'ways(2)', expect: '2', hidden: true },
        { call: 'ways(60)', expect: '2504730781961', hidden: true, name: 'must not be plain recursion' }],
      hint: 'To reach step n you came from n-1 or n-2, so ways(n) = ways(n-1) + ways(n-2). Build it upwards with two variables rather than recursing.',
      solution: 'def ways(n):\n    a, b = 1, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n',
      walk: "It is Fibonacci wearing a hat. Written as plain recursion it re-computes the same steps exponentially often and the n=60 test will never finish — that test is there precisely to catch it. The loop carries the last two answers in two variables, so it is O(n) time and O(1) memory. `@lru_cache` on the recursive version is the other accepted answer.",
      complexity: 'O(n) time, O(1) space.' },

    { id: 'pt-dsa-coins', group: AL, lvl: 3,
      title: 'Fewest coins',
      fn: 'fewest_coins',
      brief: 'Given a list of coin values and a target amount, return the fewest coins that add up to the amount exactly.\n\nYou have an unlimited number of each coin. Return -1 if the amount cannot be made.',
      sig: 'def fewest_coins(coins: list[int], amount: int) -> int',
      starter: 'def fewest_coins(coins, amount):\n    # your code here\n    pass\n',
      examples: [
        { in: 'fewest_coins([1, 5, 10], 12)', out: '3', note: '10 + 1 + 1' }],
      tests: [
        { call: 'fewest_coins([1, 5, 10], 12)', expect: '3' },
        { call: 'fewest_coins([2], 3)', expect: '-1', name: 'cannot be made' },
        { call: 'fewest_coins([1, 2, 5], 0)', expect: '0', name: 'nothing to pay' },
        { call: 'fewest_coins([1, 3, 4], 6)', expect: '2', hidden: true, name: 'greedy would answer 3' },
        { call: 'fewest_coins([1, 5, 10, 25], 63)', expect: '6', hidden: true }],
      hint: 'Build up an answer for every amount from 0 to the target: best[a] = 1 + the smallest best[a - coin] over the coins that fit.',
      solution: "def fewest_coins(coins, amount):\n    best = [0] + [float('inf')] * amount\n    for a in range(1, amount + 1):\n        for coin in coins:\n            if coin <= a and best[a - coin] + 1 < best[a]:\n                best[a] = best[a - coin] + 1\n    return -1 if best[amount] == float('inf') else best[amount]\n",
      walk: "The hidden [1, 3, 4] → 6 test is the point of the question: taking the biggest coin first gives 4 + 1 + 1 = three coins, but 3 + 3 is two. Greedy is wrong, so you have to try every coin at every amount. `float('inf')` as the starting value means \"not reachable yet\" and compares correctly against any real count.",
      complexity: 'O(amount × len(coins)) time, O(amount) space.' },

    { id: 'pt-dsa-intervals', group: AL, lvl: 3,
      title: 'Merge the overlaps',
      fn: 'merge_intervals',
      brief: 'Given a list of (start, end) pairs, merge any that overlap or touch and return the tidied list, sorted by start.\n\n(1, 3) and (3, 5) touch, so they merge into (1, 5).',
      sig: 'def merge_intervals(intervals: list[tuple]) -> list[tuple]',
      starter: 'def merge_intervals(intervals):\n    # your code here\n    pass\n',
      examples: [
        { in: 'merge_intervals([(1, 3), (2, 6), (8, 10)])', out: '[(1, 6), (8, 10)]' }],
      tests: [
        { call: 'merge_intervals([(1, 3), (2, 6), (8, 10)])', expect: '[(1, 6), (8, 10)]' },
        { call: 'merge_intervals([])', expect: '[]', name: 'nothing to merge' },
        { call: 'merge_intervals([(5, 7), (1, 2)])', expect: '[(1, 2), (5, 7)]', name: 'unsorted input' },
        { call: 'merge_intervals([(1, 3), (3, 5)])', expect: '[(1, 5)]', hidden: true, name: 'touching counts as overlapping' },
        { call: 'merge_intervals([(1, 10), (2, 3)])', expect: '[(1, 10)]', hidden: true, name: 'one swallows the other' }],
      hint: 'Sort by start first. Then walk through, extending the last interval when the next one starts before it ends, and starting a new one when it does not.',
      solution: 'def merge_intervals(intervals):\n    merged = []\n    for start, end in sorted(intervals):\n        if merged and start <= merged[-1][1]:\n            last_start, last_end = merged[-1]\n            merged[-1] = (last_start, max(last_end, end))\n        else:\n            merged.append((start, end))\n    return merged\n',
      walk: "Sorting first is what makes one pass enough — after that, anything overlapping the run so far must overlap its LAST interval. `max(last_end, end)` is the bug most people ship without: when one interval swallows another, taking `end` blindly would shorten the merged range. Calendar clashes, booking systems and log sessions are all this question in disguise.",
      complexity: 'O(n log n) time for the sort, O(n) space.' },

    { id: 'pt-dsa-longest-unique', group: AL, lvl: 3,
      title: 'Longest run without a repeat',
      fn: 'longest_unique',
      brief: 'Return the length of the longest stretch of a string that contains no repeated character.',
      sig: 'def longest_unique(s: str) -> int',
      starter: 'def longest_unique(s):\n    # your code here\n    pass\n',
      examples: [
        { in: "longest_unique('abcabcbb')", out: '3', note: 'abc' }],
      tests: [
        { call: "longest_unique('abcabcbb')", expect: '3' },
        { call: "longest_unique('')", expect: '0', name: 'empty string' },
        { call: "longest_unique('bbbb')", expect: '1' },
        { call: "longest_unique('pwwkew')", expect: '3', hidden: true, name: 'wke, not pwke' },
        { call: "longest_unique('abba')", expect: '2', hidden: true, name: 'the left edge must never go backwards' }],
      hint: 'Slide a window. Remember the last index of every character; when you meet a repeat inside the window, move the left edge to just past it.',
      solution: 'def longest_unique(s):\n    last_seen = {}\n    left = 0\n    best = 0\n    for i, ch in enumerate(s):\n        if ch in last_seen and last_seen[ch] >= left:\n            left = last_seen[ch] + 1\n        last_seen[ch] = i\n        best = max(best, i - left + 1)\n    return best\n',
      walk: "The `last_seen[ch] >= left` test is the whole question. On 'abba', by the time you reach the final 'a' its remembered index is 0, which is behind the window — moving the left edge back there would let 'b' in twice. Checking that the repeat is still inside the window keeps the left edge moving forwards only, which is what makes this one pass rather than a re-scan.",
      complexity: 'O(n) time, O(k) space for the alphabet in play.' },

    { id: 'pt-dsa-warmer', group: AL, lvl: 3,
      title: 'How long until it warms up',
      fn: 'days_until_warmer',
      brief: 'Given a list of daily temperatures, return a list saying, for each day, how many days you wait for a warmer one.\n\nIf no warmer day ever comes, the answer for that day is 0.',
      sig: 'def days_until_warmer(temps: list[int]) -> list[int]',
      starter: 'def days_until_warmer(temps):\n    # your code here\n    pass\n',
      examples: [
        { in: 'days_until_warmer([3, 4, 3, 5])', out: '[1, 2, 1, 0]' }],
      tests: [
        { call: 'days_until_warmer([3, 4, 3, 5])', expect: '[1, 2, 1, 0]' },
        { call: 'days_until_warmer([])', expect: '[]', name: 'no days at all' },
        { call: 'days_until_warmer([5, 4, 3])', expect: '[0, 0, 0]', name: 'only ever colder' },
        { call: 'days_until_warmer([2, 2, 3])', expect: '[2, 1, 0]', hidden: true, name: 'equal is not warmer' },
        { call: 'days_until_warmer(list(range(20000, 0, -1)))', expect: '[0] * 20000', hidden: true, name: 'must not compare every pair' }],
      hint: 'Keep a stack of the days you have not answered yet. When today beats the day on top of the stack, you have just answered it.',
      solution: 'def days_until_warmer(temps):\n    answer = [0] * len(temps)\n    stack = []\n    for i, t in enumerate(temps):\n        while stack and temps[stack[-1]] < t:\n            day = stack.pop()\n            answer[day] = i - day\n        stack.append(i)\n    return answer\n',
      walk: "A monotonic stack: it only ever holds days that are still waiting, in decreasing temperature order. Each day is pushed once and popped at most once, so despite the inner `while` it is O(n) — the 20,000-day test rules out the nested-loop version. Note the strict `<`: with `<=` you would answer a day with an equally warm one, and the [2, 2, 3] test catches exactly that.",
      complexity: 'O(n) time, O(n) space.' },

    { id: 'pt-dsa-tree-depth', group: DS, lvl: 2,
      title: 'How deep is the tree',
      fn: 'depth',
      brief: 'A tree node is a dict {"value": v, "left": node_or_None, "right": node_or_None}.\n\nReturn how many levels the tree has. An empty tree (None) has depth 0.',
      sig: 'def depth(node: dict | None) -> int',
      starter: 'def depth(node):\n    # your code here\n    pass\n',
      examples: [
        { in: "depth({'value': 1, 'left': None, 'right': None})", out: '1' }],
      tests: [
        { call: "depth({'value': 1, 'left': None, 'right': None})", expect: '1' },
        { call: 'depth(None)', expect: '0', name: 'the base case' },
        { call: 'depth(_lopsided(4))', expect: '4', name: 'a chain of four' },
        { call: "depth({'value': 1, 'left': {'value': 2, 'left': None, 'right': None}, 'right': None})", expect: '2', hidden: true },
        { call: 'depth(_lopsided(30))', expect: '30', hidden: true, name: 'a long chain' }],
      setup: "def _lopsided(n):\n    node = None\n    for i in range(n):\n        node = {'value': i, 'left': node, 'right': None}\n    return node\n",
      hint: 'Depth is 1 plus the deeper of the two children. The base case is node being None.',
      solution: "def depth(node):\n    if node is None:\n        return 0\n    return 1 + max(depth(node['left']), depth(node['right']))\n",
      walk: "Three lines, and every recursion question has this shape: answer the empty case outright, then express the whole in terms of the parts. Reaching for max() rather than adding the two sides is the part people fumble — depth is the LONGER path down, not the total number of nodes.",
      complexity: 'O(n) time over the nodes, O(depth) stack space.' },

    { id: 'pt-dsa-inorder', group: DS, lvl: 2,
      title: 'Read the tree in order',
      fn: 'in_order',
      brief: 'Using the same node shape — {"value": v, "left": ..., "right": ...} — return a list of every value, left subtree first, then the node, then the right subtree.\n\nOn a binary search tree that comes out sorted.',
      sig: 'def in_order(node: dict | None) -> list',
      starter: 'def in_order(node):\n    # your code here\n    pass\n',
      examples: [
        { in: '_tree()', out: '[1, 2, 3]', note: 'a 2 with children 1 and 3' }],
      tests: [
        { call: 'in_order(_tree())', expect: '[1, 2, 3]' },
        { call: 'in_order(None)', expect: '[]', name: 'nothing to read' },
        { call: "in_order({'value': 7, 'left': None, 'right': None})", expect: '[7]' },
        { call: 'in_order(_left_chain())', expect: '[3, 2, 1]', hidden: true, name: 'all down the left' },
        { call: 'len(in_order(_tree()))', expect: '3', hidden: true }],
      setup: "def _tree():\n    return {'value': 2,\n            'left': {'value': 1, 'left': None, 'right': None},\n            'right': {'value': 3, 'left': None, 'right': None}}\n\n\ndef _left_chain():\n    return {'value': 1,\n            'left': {'value': 2, 'left': {'value': 3, 'left': None, 'right': None}, 'right': None},\n            'right': None}\n",
      walk: "Left, self, right — swap those three lines around and you have pre-order and post-order too, which is the follow-up question they usually ask. Returning a new list from each call keeps it clean; passing one shared list down and appending to it is the other accepted answer and is a little faster.",
      hint: "Recurse: in_order(left) + [value] + in_order(right), with an empty list as the base case.",
      solution: "def in_order(node):\n    if node is None:\n        return []\n    return in_order(node['left']) + [node['value']] + in_order(node['right'])\n",
      complexity: 'O(n) time, O(n) space for the output.' },

    { id: 'pt-dsa-first-bad', group: AL, lvl: 2,
      title: 'The first bad build',
      fn: 'first_bad',
      brief: 'Builds are numbered 0 to n-1. Everything from some point onwards is broken, and a list of booleans says which builds are broken.\n\nReturn the number of the first broken build, or -1 if none are. Do it in O(log n) — the list stands in for a slow check you cannot afford to run n times.',
      sig: 'def first_bad(broken: list[bool]) -> int',
      starter: 'def first_bad(broken):\n    # your code here\n    pass\n',
      examples: [
        { in: 'first_bad([False, False, True, True])', out: '2' }],
      tests: [
        { call: 'first_bad([False, False, True, True])', expect: '2' },
        { call: 'first_bad([True])', expect: '0', name: 'broken from the start' },
        { call: 'first_bad([False, False])', expect: '-1', name: 'nothing broken' },
        { call: 'first_bad([])', expect: '-1', hidden: true },
        { call: 'first_bad([False] * 500000 + [True] * 500000)', expect: '500000', hidden: true, name: 'must halve, not scan' }],
      hint: 'Binary search on the boundary: if the middle build is broken, the answer is at the middle or to its left; if not, it is strictly to the right.',
      solution: 'def first_bad(broken):\n    low, high = 0, len(broken) - 1\n    answer = -1\n    while low <= high:\n        mid = (low + high) // 2\n        if broken[mid]:\n            answer = mid\n            high = mid - 1\n        else:\n            low = mid + 1\n    return answer\n',
      walk: "Binary search does not need a sorted list of numbers — it needs a condition that goes false, false, true and never flips back. Remembering the best candidate in `answer` and carrying on left is easier to get right than trying to make the loop end exactly on the boundary. This is `git bisect` in eight lines.",
      complexity: 'O(log n) time, O(1) space.' },

    { id: 'pt-dsa-subsets', group: AL, lvl: 3,
      title: 'Every combination',
      fn: 'subsets',
      brief: 'Return every subset of a list of distinct values, each as a list, including the empty one.\n\nOrder the results by size, and within a size keep the original order of the values.',
      sig: 'def subsets(items: list) -> list[list]',
      starter: 'def subsets(items):\n    # your code here\n    pass\n',
      examples: [
        { in: 'subsets([1, 2])', out: '[[], [1], [2], [1, 2]]' }],
      tests: [
        { call: 'subsets([1, 2])', expect: '[[], [1], [2], [1, 2]]' },
        { call: 'subsets([])', expect: '[[]]', name: 'the empty set still has one subset' },
        { call: 'len(subsets([1, 2, 3]))', expect: '8', name: 'two to the power of n' },
        { call: "subsets(['a'])", expect: "[[], ['a']]", hidden: true },
        { call: 'len(subsets(list(range(10))))', expect: '1024', hidden: true }],
      hint: 'itertools.combinations(items, k) gives every subset of size k. Loop k from 0 to len(items).',
      solution: 'from itertools import combinations\n\n\ndef subsets(items):\n    out = []\n    for k in range(len(items) + 1):\n        for combo in combinations(items, k):\n            out.append(list(combo))\n    return out\n',
      walk: "There are 2**n subsets, so this is exponential however you write it — say so out loud in an interview. itertools does the work and keeps the input order inside each group for free. The by-hand answer builds them one value at a time: start from [[]] and, for each item, add copies of everything so far with that item appended.",
      complexity: 'O(n × 2ⁿ) time and output size.' }
  );
})();
