/* Python coding test — problem bank 0b: the step between first programs and the
   screening questions. Loops with a decision inside, dictionaries that tally, and
   the first problems where an edge case decides whether you pass. */
(function () {
  window.PYTESTS = window.PYTESTS || [];

  window.PYTESTS.push(

    { id: 'pt-count-above', group: 'Building up', lvl: 1,
      title: 'Count the ones above a limit',
      fn: 'count_above',
      brief: 'Count how many numbers in a list are strictly above a limit.',
      sig: 'def count_above(nums, limit)',
      starter: 'def count_above(nums, limit):\n    # your code here\n    pass\n',
      examples: [{ in: 'count_above([1, 5, 9], 4)', out: '2' }],
      tests: [
        { call: 'count_above([1, 5, 9], 4)', expect: '2' },
        { call: 'count_above([], 4)', expect: '0' },
        { call: 'count_above([4, 4], 4)', expect: '0', name: 'equal is not above' },
        { call: 'count_above([-5, -1], -3)', expect: '1', hidden: true, name: 'negatives' }],
      hint: 'A counter starting at 0, an if inside the loop — or one line with sum() and a condition.',
      solution: 'def count_above(nums, limit):\n    return sum(1 for n in nums if n > limit)\n',
      walk: 'The word "strictly" in a brief always means `>` rather than `>=`, and there is nearly always a test sitting exactly on the boundary to check you read it.',
      complexity: 'O(n).' },

    { id: 'pt-longest-word', group: 'Building up', lvl: 1,
      title: 'The longest word',
      fn: 'longest_word',
      brief: 'Return the longest word in a sentence.\n\nIf two are equally long, return the one that comes first. An empty sentence returns an empty string.',
      sig: 'def longest_word(sentence)',
      starter: 'def longest_word(sentence):\n    # your code here\n    pass\n',
      examples: [{ in: "longest_word('the quick brown fox')", out: "'quick'" }],
      tests: [
        { call: "longest_word('the quick brown fox')", expect: "'quick'" },
        { call: "longest_word('one two')", expect: "'one'", name: 'a tie keeps the first' },
        { call: "longest_word('')", expect: "''" },
        { call: "longest_word('a bb ccc')", expect: "'ccc'", hidden: true },
        { call: "longest_word('  spaced   words  ')", expect: "'spaced'", hidden: true }],
      hint: 'max() takes a key: max(words, key=len). But an empty list has no maximum — guard it.',
      solution: "def longest_word(sentence):\n    words = sentence.split()\n    if not words:\n        return ''\n    return max(words, key=len)\n",
      walk: 'max() returns the FIRST of any tie, which is exactly what the brief asks for — no extra code needed. `key=len` says "compare them by length, but give me back the word".',
      complexity: 'O(n).' },

    { id: 'pt-vowel-free', group: 'Building up', lvl: 1,
      title: 'Strip the vowels out',
      fn: 'no_vowels',
      brief: 'Return the text with every vowel removed. Keep the case of everything else.',
      sig: 'def no_vowels(text)',
      starter: 'def no_vowels(text):\n    # your code here\n    pass\n',
      examples: [{ in: "no_vowels('Hello World')", out: "'Hll Wrld'" }],
      tests: [
        { call: "no_vowels('Hello World')", expect: "'Hll Wrld'" },
        { call: "no_vowels('AEIOU')", expect: "''", name: 'capitals count as vowels' },
        { call: "no_vowels('')", expect: "''" },
        { call: "no_vowels('xyz')", expect: "'xyz'", hidden: true },
        { call: "no_vowels('Python 3.12')", expect: "'Pythn 3.12'", hidden: true }],
      hint: "Build the answer from the characters you want to keep: ''.join(ch for ch in text if ...).",
      solution: "def no_vowels(text):\n    return ''.join(ch for ch in text if ch.lower() not in 'aeiou')\n",
      walk: 'Testing `ch.lower()` handles both cases without listing ten letters. Building a list and joining beats adding to a string in a loop — each += on a string makes a whole new one.',
      complexity: 'O(n).' },

    { id: 'pt-list-stats', group: 'Building up', lvl: 1,
      title: 'Smallest, largest, average',
      fn: 'stats',
      brief: 'Return a dict with the keys "min", "max" and "mean" for a list of numbers.\n\nAn empty list returns all three as None.',
      sig: 'def stats(nums)',
      starter: 'def stats(nums):\n    # your code here\n    pass\n',
      examples: [{ in: 'stats([1, 2, 3])', out: "{'min': 1, 'max': 3, 'mean': 2.0}" }],
      tests: [
        { call: 'stats([1, 2, 3])', expect: "{'min': 1, 'max': 3, 'mean': 2.0}" },
        { call: 'stats([])', expect: "{'min': None, 'max': None, 'mean': None}", name: 'nothing to measure' },
        { call: 'stats([5])', expect: "{'min': 5, 'max': 5, 'mean': 5.0}" },
        { call: "stats([-2, 2])['mean']", expect: '0.0', hidden: true }],
      hint: 'Deal with the empty list first, then the three built-ins do the work.',
      solution: "def stats(nums):\n    if not nums:\n        return {'min': None, 'max': None, 'mean': None}\n    return {'min': min(nums), 'max': max(nums), 'mean': sum(nums) / len(nums)}\n",
      walk: 'min() and max() raise on an empty list and the mean would divide by zero, so all three failures are prevented by one guard. Returning the same shape of dict either way is what makes the function safe to use.',
      complexity: 'O(n).' },

    { id: 'pt-odd-even-split', group: 'Building up', lvl: 1,
      title: 'Split odds from evens',
      fn: 'split_parity',
      brief: 'Return a tuple of two lists: (the even numbers, the odd numbers), each keeping the original order.',
      sig: 'def split_parity(nums)',
      starter: 'def split_parity(nums):\n    # your code here\n    pass\n',
      examples: [{ in: 'split_parity([1, 2, 3, 4])', out: '([2, 4], [1, 3])' }],
      tests: [
        { call: 'split_parity([1, 2, 3, 4])', expect: '([2, 4], [1, 3])' },
        { call: 'split_parity([])', expect: '([], [])' },
        { call: 'split_parity([2, 2])', expect: '([2, 2], [])', name: 'duplicates are kept' },
        { call: 'split_parity([0])', expect: '([0], [])', hidden: true, name: 'zero is even' },
        { call: 'split_parity([-1, -2])', expect: '([-2], [-1])', hidden: true }],
      hint: 'Two empty lists before the loop, an if/else inside, and return both at the end.',
      solution: 'def split_parity(nums):\n    evens, odds = [], []\n    for n in nums:\n        if n % 2 == 0:\n            evens.append(n)\n        else:\n            odds.append(n)\n    return evens, odds\n',
      walk: 'Both accumulators are created before the loop and returned after it. Note that -2 % 2 is 0 in Python, so negative even numbers land in the right list without any special handling.',
      complexity: 'O(n).' },

    { id: 'pt-tally-letters', group: 'Building up', lvl: 2,
      title: 'Tally the letters',
      fn: 'letter_counts',
      brief: 'Count how often each letter appears in a piece of text, ignoring case and anything that is not a letter.\n\nReturn a dict of letter → count.',
      sig: 'def letter_counts(text)',
      starter: 'def letter_counts(text):\n    # your code here\n    pass\n',
      examples: [{ in: "letter_counts('Hi hi!')", out: "{'h': 2, 'i': 2}" }],
      tests: [
        { call: "letter_counts('Hi hi!')", expect: "{'h': 2, 'i': 2}" },
        { call: "letter_counts('')", expect: '{}' },
        { call: "letter_counts('123')", expect: '{}', name: 'digits are not letters' },
        { call: "letter_counts('aA')['a']", expect: '2', hidden: true },
        { call: "len(letter_counts('the quick brown fox jumps over the lazy dog'))", expect: '26', hidden: true, name: 'a pangram has all 26' }],
      hint: 'Loop the characters, skip anything where .isalpha() is False, and use counts.get(ch, 0) + 1.',
      solution: "def letter_counts(text):\n    counts = {}\n    for ch in text.lower():\n        if ch.isalpha():\n            counts[ch] = counts.get(ch, 0) + 1\n    return counts\n",
      walk: 'Lowercase once at the top rather than per character. `.isalpha()` is what drops spaces, digits and punctuation without listing them. This is the counting pattern that half of all screening questions are built on.',
      complexity: 'O(n).' },

    { id: 'pt-reverse-dict', group: 'Building up', lvl: 2,
      title: 'Turn a dict inside out',
      fn: 'invert',
      brief: 'Swap the keys and values of a dictionary.\n\nIf two keys share a value, keep the one that comes later in the dictionary.',
      sig: 'def invert(d)',
      starter: 'def invert(d):\n    # your code here\n    pass\n',
      examples: [{ in: "invert({'a': 1, 'b': 2})", out: "{1: 'a', 2: 'b'}" }],
      tests: [
        { call: "invert({'a': 1, 'b': 2})", expect: "{1: 'a', 2: 'b'}" },
        { call: 'invert({})', expect: '{}' },
        { call: "invert({'a': 1, 'b': 1})", expect: "{1: 'b'}", name: 'the later key wins' },
        { call: "len(invert({'x': 1, 'y': 2, 'z': 3}))", expect: '3', hidden: true }],
      hint: 'A dict comprehension over d.items() — and think about what happens when the same key is written twice.',
      solution: 'def invert(d):\n    return {value: key for key, value in d.items()}\n',
      walk: 'Duplicate keys are not an error — the last one written simply wins, which gives the behaviour the brief asks for at no cost. Values that are not hashable (a list, say) would raise, which is worth mentioning out loud in an interview.',
      complexity: 'O(n).' },

    { id: 'pt-fizz-count', group: 'Building up', lvl: 2,
      title: 'How many multiples',
      fn: 'count_multiples',
      brief: 'Count the numbers from 1 to n that divide exactly by k.\n\nIf k is 0 or less, return 0 rather than crashing.',
      sig: 'def count_multiples(n, k)',
      starter: 'def count_multiples(n, k):\n    # your code here\n    pass\n',
      examples: [{ in: 'count_multiples(10, 3)', out: '3', note: '3, 6, 9' }],
      tests: [
        { call: 'count_multiples(10, 3)', expect: '3' },
        { call: 'count_multiples(10, 0)', expect: '0', name: 'no dividing by zero' },
        { call: 'count_multiples(0, 3)', expect: '0' },
        { call: 'count_multiples(100, 1)', expect: '100', hidden: true },
        { call: 'count_multiples(1000000, 7)', expect: '142857', hidden: true, name: 'big n — think, do not loop' }],
      hint: 'You could loop… but how many multiples of k are there below n? That is just a division.',
      solution: 'def count_multiples(n, k):\n    if k <= 0:\n        return 0\n    return n // k\n',
      walk: 'The loop version is correct and too slow for the last test. Floor division answers it directly: there are exactly n // k multiples of k in 1..n. Spotting when arithmetic replaces a loop is worth real marks.',
      complexity: 'O(1) with the division, O(n) with a loop.' },

    { id: 'pt-clamp', group: 'Building up', lvl: 1,
      title: 'Keep it in range',
      fn: 'clamp',
      brief: 'Return the number, pulled back inside the range low to high if it falls outside it.',
      sig: 'def clamp(n, low, high)',
      starter: 'def clamp(n, low, high):\n    # your code here\n    pass\n',
      examples: [{ in: 'clamp(15, 0, 10)', out: '10' }, { in: 'clamp(5, 0, 10)', out: '5' }],
      tests: [
        { call: 'clamp(15, 0, 10)', expect: '10' },
        { call: 'clamp(5, 0, 10)', expect: '5' },
        { call: 'clamp(-3, 0, 10)', expect: '0' },
        { call: 'clamp(0, 0, 10)', expect: '0', hidden: true, name: 'exactly on the edge' },
        { call: 'clamp(2.5, 0, 1)', expect: '1', hidden: true }],
      hint: 'Two ifs work. So does one line: min(high, max(low, n)).',
      solution: 'def clamp(n, low, high):\n    return min(high, max(low, n))\n',
      walk: 'Reading it inside out: `max(low, n)` lifts anything too small, then `min(high, ...)` pulls anything too big back down. This is exactly what pandas\' `.clip()` and NumPy\'s `np.clip` do to outliers.',
      complexity: 'O(1).' },

    { id: 'pt-initial-sum', group: 'Building up', lvl: 2,
      title: 'Total per person',
      fn: 'totals',
      brief: 'Given a list of (name, amount) pairs, return a dict of name → total amount.',
      sig: 'def totals(pairs)',
      starter: 'def totals(pairs):\n    # your code here\n    pass\n',
      examples: [{ in: "totals([('a', 5), ('b', 2), ('a', 1)])", out: "{'a': 6, 'b': 2}" }],
      tests: [
        { call: "totals([('a', 5), ('b', 2), ('a', 1)])", expect: "{'a': 6, 'b': 2}" },
        { call: 'totals([])', expect: '{}' },
        { call: "totals([('x', 0)])", expect: "{'x': 0}", name: 'a zero still makes an entry' },
        { call: "totals([('a', -1), ('a', 1)])['a']", expect: '0', hidden: true }],
      hint: 'Unpack each pair in the loop header: for name, amount in pairs.',
      solution: 'def totals(pairs):\n    out = {}\n    for name, amount in pairs:\n        out[name] = out.get(name, 0) + amount\n    return out\n',
      walk: 'Unpacking in the loop header is neater than `pair[0]` and `pair[1]`, and it documents the shape of the data. The rest is the counting pattern with an amount instead of a 1.',
      complexity: 'O(n).' },

    { id: 'pt-safe-divide', group: 'Building up', lvl: 1,
      title: 'Divide without crashing',
      fn: 'safe_divide',
      brief: 'Divide a by b. If b is zero, return None instead of raising.',
      sig: 'def safe_divide(a, b)',
      starter: 'def safe_divide(a, b):\n    # your code here\n    pass\n',
      examples: [{ in: 'safe_divide(10, 2)', out: '5.0' }, { in: 'safe_divide(1, 0)', out: 'None' }],
      tests: [
        { call: 'safe_divide(10, 2)', expect: '5.0' },
        { call: 'safe_divide(1, 0)', expect: 'None' },
        { call: 'safe_divide(0, 5)', expect: '0.0', name: 'zero on top is fine' },
        { call: 'safe_divide(-6, 3)', expect: '-2.0', hidden: true }],
      hint: 'Either check b first, or wrap the division in try / except ZeroDivisionError.',
      solution: 'def safe_divide(a, b):\n    if b == 0:\n        return None\n    return a / b\n',
      walk: 'Checking first is clearer than catching here, because the failure is expected rather than exceptional. Note the third test: 0 / 5 is perfectly valid — it is only a zero DIVISOR that is a problem.',
      complexity: 'O(1).' },

    { id: 'pt-repeat-word', group: 'Building up', lvl: 1,
      title: 'Repeat, with separators',
      fn: 'repeat',
      brief: 'Repeat a word n times, separated by spaces.\n\nn of 0 or less returns an empty string.',
      sig: 'def repeat(word, n)',
      starter: 'def repeat(word, n):\n    # your code here\n    pass\n',
      examples: [{ in: "repeat('ho', 3)", out: "'ho ho ho'" }],
      tests: [
        { call: "repeat('ho', 3)", expect: "'ho ho ho'" },
        { call: "repeat('x', 1)", expect: "'x'", name: 'no trailing space' },
        { call: "repeat('x', 0)", expect: "''" },
        { call: "repeat('x', -2)", expect: "''", hidden: true },
        { call: "len(repeat('ab', 100))", expect: '299', hidden: true }],
      hint: "Build a list of n copies and join it — that puts separators BETWEEN them rather than after each.",
      solution: "def repeat(word, n):\n    if n <= 0:\n        return ''\n    return ' '.join([word] * n)\n",
      walk: "Adding `word + ' '` in a loop leaves a trailing space, which the second test catches. join is designed for exactly this: n items produce n - 1 separators.",
      complexity: 'O(n).' },

    { id: 'pt-first-match', group: 'Building up', lvl: 2,
      title: 'Find the first match',
      fn: 'first_over',
      brief: 'Return the first number in a list that is above a limit, or None if there is not one.',
      sig: 'def first_over(nums, limit)',
      starter: 'def first_over(nums, limit):\n    # your code here\n    pass\n',
      examples: [{ in: 'first_over([1, 5, 9], 4)', out: '5' }],
      tests: [
        { call: 'first_over([1, 5, 9], 4)', expect: '5' },
        { call: 'first_over([1, 2], 10)', expect: 'None', name: 'nothing matches' },
        { call: 'first_over([], 1)', expect: 'None' },
        { call: 'first_over([0, -1], -2)', expect: '0', hidden: true, name: 'a zero is a real answer' }],
      hint: 'Return from inside the loop as soon as you find one — that is what makes it "first" and stops the search early.',
      solution: 'def first_over(nums, limit):\n    for n in nums:\n        if n > limit:\n            return n\n    return None\n',
      walk: 'Returning inside the loop exits the whole function immediately, so nothing after it runs. The final `return None` handles "never found" — and the zero test is there to stop you writing `if n:` and treating a legitimate 0 as no answer.',
      complexity: 'O(n) worst case, but it stops at the first match.' },

    { id: 'pt-word-lengths', group: 'Building up', lvl: 1,
      title: 'How long is each word',
      fn: 'lengths',
      brief: 'Return a dict of word → its length, for each word in a sentence.\n\nIf a word appears twice, one entry is enough.',
      sig: 'def lengths(sentence)',
      starter: 'def lengths(sentence):\n    # your code here\n    pass\n',
      examples: [{ in: "lengths('the sky')", out: "{'the': 3, 'sky': 3}" }],
      tests: [
        { call: "lengths('the sky')", expect: "{'the': 3, 'sky': 3}" },
        { call: "lengths('')", expect: '{}' },
        { call: "lengths('hi hi')", expect: "{'hi': 2}", name: 'one entry per distinct word' },
        { call: "lengths('a bb ccc')['ccc']", expect: '3', hidden: true }],
      hint: 'A dict comprehension over sentence.split().',
      solution: 'def lengths(sentence):\n    return {w: len(w) for w in sentence.split()}\n',
      walk: 'The repeated word collapses on its own: writing the same key twice just overwrites it with the same value. Dict comprehensions read exactly like list ones, with `key: value` in front.',
      complexity: 'O(n).' },

    { id: 'pt-remove-item', group: 'Building up', lvl: 2,
      title: 'Remove every copy',
      fn: 'remove_all',
      brief: 'Return a new list with every copy of a value removed. Do not change the list you were given.',
      sig: 'def remove_all(items, value)',
      starter: 'def remove_all(items, value):\n    # your code here\n    pass\n',
      examples: [{ in: "remove_all([1, 2, 1, 3], 1)", out: '[2, 3]' }],
      tests: [
        { call: 'remove_all([1, 2, 1, 3], 1)', expect: '[2, 3]' },
        { call: 'remove_all([1, 1], 1)', expect: '[]' },
        { call: 'remove_all([], 1)', expect: '[]' },
        { call: "(lambda src: (remove_all(src, 1), src)[1])([1, 2])", expect: '[1, 2]', hidden: true, name: 'the original survives' },
        { call: 'remove_all([0, 1], 0)', expect: '[1]', hidden: true }],
      hint: 'A comprehension that keeps everything not equal to the value. .remove() would only take the first copy — and change the caller\'s list.',
      solution: 'def remove_all(items, value):\n    return [x for x in items if x != value]\n',
      walk: 'Building a new list sidesteps both traps at once: `.remove()` deletes only the first match, and looping while deleting skips elements. The hidden test checks you did not modify the caller\'s list.',
      complexity: 'O(n).' }
  );
})();
