/* Auto-generated: broaden the Definitions set to cover each topic's glossary terms.
   Adds window.DEFS entries for concepts curated (by review) as genuine definitions.
   Loads before app.js so buildIndex/flashDeck see the tags. */
(function () {
  var D = (window.DEFS = window.DEFS || {});
  D["A new point arrives with no label. KNN finds the k labelled points closest to it. What does KNN do with those k points to choose a label?"] = 1;
  D["You set k = 1. KNN finds the one training point closest to the new arrival. What happens next?"] = 1;
  D["Two points sit on a street grid. How is the Manhattan distance between them computed?"] = 1;
  D["A dataset has age (18–70) and salary (£20,000–£90,000). You use the raw numbers. What happens when KNN computes distances?"] = 1;
  D["KNN regression predicts a number, like a price. It finds the k nearest neighbours. How does it turn their values into one prediction?"] = 1;
  D["What must the stored training examples have before KNN can classify anything at all?"] = 1;
  D["You want to know how well your KNN model will do on future, unseen data. What is the standard way to check?"] = 1;
  D["You give KNN raw text categories like 'rock', 'jazz' and 'pop'. Why can't it work?"] = 1;
  D["In distance-weighted KNN, the neighbours' votes are no longer equal. Whose votes count the most?"] = 1;
  D["An app uses daily steps (0–20,000) and sleep hours (0–12) in KNN. What should you do before computing any distances?"] = 1;
  D["Every algorithm relies on one big assumption about the world. What is KNN's?"] = 1;
  D["You change k from large to small. The model now reacts more to individual points and less to the crowd. In bias–variance language, what did you trade?"] = 1;
  D["k is a setting you choose — the model can't learn it, and training accuracy would always point to k = 1. What is the right way to choose it?"] = 1;
  D["Standardising a feature means turning each value x into a z-score. Which formula does that?"] = 1;
  D["You keep adding features (dimensions), and the distances between random points all bunch together. What does the 'nearest neighbour' become?"] = 1;
  D["k-d trees and ball trees make exact neighbour search much faster in low dimensions. How?"] = 1;
  D["Instead of one train/validation split, you rotate the held-out slice five times and average the five scores. What do you gain?"] = 1;
  D["You need a colour column — red, green or blue — inside KNN's distance. What is the standard encoding?"] = 1;
  D["You delete five features and accuracy goes UP. What were those five features, most likely?"] = 1;
  D["Push the number of dimensions towards infinity. Now divide the distance to the farthest point by the distance to the nearest point. What value does that ratio approach?"] = 1;
  D["The two classes truly overlap: the same-looking point can carry either label. For ANY classifier on this data, what is perfect accuracy?"] = 1;
  D["Prototype selection throws away deep-interior points and keeps mostly boundary-area points — yet accuracy barely changes. Why?"] = 1;
  D["Modern vector search runs on approximate methods like HNSW and LSH. What trade do they offer?"] = 1;
  D["Two documents cover the same topic, but one is three times longer, so its word-count vector is three times bigger. Which measure ignores that size difference?"] = 1;
  D["KNN can also repair data. How does KNN imputation fill in a missing value?"] = 1;
  D["Radius neighbours uses 'everyone within distance r' instead of 'the k closest'. It has one failure that plain k-NN can never have. What is it?"] = 1;
  D["You min-max scale income to [0, 1] — but one customer is a billionaire, so the divisor is enormous. What happens to ordinary income differences?"] = 1;
  D["A sales forecaster scores 92% under random cross-validation but only 61% in production. The data is time-ordered. What is the classic cause?"] = 1;
  D["Four classes, k = 7. The vote comes back 3–2–1–1. What does standard KNN predict?"] = 1;
  D["Every feature is binary — just 0 or 1. On this data, Manhattan distance is exactly the same as which named distance?"] = 1;
  D["Set k = 1 and colour the whole map by prediction. What famous structure do the decision regions form?"] = 1;
  D["Forget classification for a moment. The distance from a point to its kth nearest neighbour is widely used as what?"] = 1;
  D["Metric learning (Mahalanobis, LMNN, NCA) makes KNN better without touching k. What does it learn to do?"] = 1;
  D["'Users like you also bought…' Strip away the marketing language. Which algorithm is that recommender running?"] = 1;
  D["A logistic regression model looks at a loan application. What does it actually output?"] = 1;
  D["The model says a customer has a 62% probability of churning. How does that become a yes/no decision?"] = 1;
  D["You give the model total freedom and its weights grow huge. It scores 99% on training data, 78% on validation. What's the standard fix?"] = 1;
  D["A stakeholder asks: 'What does a one-unit increase in income do to the odds of approval?' Which property of logistic regression answers this directly?"] = 1;
  D["Three classes — cat, dog, fox — and logistic regression still works, via softmax. What does softmax guarantee about the three outputs?"] = 1;
  D["You switch the penalty from L2 (sum of squared weights) to L1 (sum of absolute weights). What famous behaviour appears?"] = 1;
  D["Income's weight is 0.00004 and age's weight is 0.3 — a colleague concludes age matters vastly more. Why is that comparison bogus?"] = 1;
  D["Two near-duplicate features — 'income' and 'declared salary' (correlation 0.98) — enter a logistic regression. Predictions stay fine, but the coefficients go haywire: +8.2 on one, −7.9 on the other. What's happening?"] = 1;
  D["Medication helps young patients but harms elderly ones. A logistic regression with features [medication, age] insists the medication effect is one number for everyone. What's missing, and what's the classical fix?"] = 1;
  D["Lasso (L1) on data with a GROUP of five correlated useful features behaves oddly: it picks one of the five at random and zeroes the rest. Elastic net was invented for exactly this. What does it do differently?"] = 1;
  D["In probability, what does the notation P(A | B) — 'the probability of A given B' — mean?"] = 1;
  D["Naive Bayes wants P(spam | words), but from training it can only easily measure P(words | spam). What lets it turn the second into the first?"] = 1;
  D["What makes Naive Bayes a 'generative' model?"] = 1;
  D["An email arrives containing the words 'FREE', 'winner' and 'meeting'. How does Naive Bayes decide whether it's spam?"] = 1;
  D["The 'naive' in Naive Bayes refers to one specific assumption. Which?"] = 1;
  D["The word 'blockchain' never appeared in any training spam. A new spam email contains it. What does raw (unsmoothed) Naive Bayes do?"] = 1;
  D["A feature is continuous — say, transaction amount — rather than a word count. How does Gaussian Naive Bayes handle it?"] = 1;
  D["BernoulliNB expects each of its features in what form?"] = 1;
  D["A test email contains the word 'zumba', which never once appeared in your spam training emails. With no smoothing, what does this single word do to the spam score?"] = 1;
  D["A support-ticket classifier must spot a category that's only 2% of tickets. Plain MultinomialNB keeps under-calling it. Which purpose-built variant targets exactly this, and how?"] = 1;
  D["How does training actually build a decision tree from the data?"] = 1;
  D["What does a decision tree's 'feature importance' tell you?"] = 1;
  D["Training must choose WHERE to place each question's cutoff. What makes one cutoff better than another?"] = 1;
  D["You retrain a tree after removing just three rows of training data — and get a visibly different tree. What is this property called?"] = 1;
  D["min_samples_leaf is the classic pre-pruning knob. Sweep it from 1 to 100 and watch training vs validation accuracy. What is it actually forbidding, and where does validation peak?"] = 1;
  D["Cost-complexity pruning (ccp_alpha) takes the opposite route: grow the tree fully FIRST, then cut. What does raising alpha do to the finished tree?"] = 1;
  D["A decision tree is used for REGRESSION: predicting house price from floor area. What does its prediction curve actually look like across floor areas, and why?"] = 1;
  D["sklearn's DecisionTreeClassifier is an implementation of CART. Against the older ID3/C4.5 family, what marks a CART tree?"] = 1;
  D["Compliance requires: 'higher income must never DECREASE the approval score'. Your tree ensemble occasionally violates this on odd segments. Modern libraries offer a clean fix. What is it?"] = 1;
  D["Many straight lines separate two classes perfectly. Which one does an SVM choose?"] = 1;
  D["Real data is messy — one stray point sits inside the other class. A 'soft margin' SVM handles this how?"] = 1;
  D["One class forms a ring AROUND the other — no straight line can separate them. The kernel idea rescues SVM how?"] = 1;
  D["After training an SVM on 50,000 points, only 900 turn out to be support vectors. What does that mean for the deployed model?"] = 1;
  D["With an RBF kernel, the gamma parameter controls each training point's radius of influence. What does a very LARGE gamma produce?"] = 1;
  D["Mapping data into a rich feature space could mean computing millions of new features per point. The kernel TRICK avoids that how?"] = 1;
  D["Your SVM outputs decision scores like +1.73, but the fraud team demands calibrated probabilities. What's the standard fix?"] = 1;
  D["Support vector REGRESSION (SVR) flips the idea: instead of a street separating classes, it fits a tube around a curve. Which points become its support vectors?"] = 1;
  D["You call predict_proba on sklearn's SVC and it works — but only because probability=True ran something extra at fit time. What is that machinery, and what should you know before trusting it?"] = 1;
  D["sklearn's SVC handles a 10-class problem by silently training 45 binary models — one-vs-one — while most other classifiers use one-vs-rest or native multiclass. Why does the SVM world prefer OvO?"] = 1;
  D["Kernel SVC was your best model at 30k rows; at 3M rows training would take weeks. Which escape routes keep (most of) the kernel magic at linear cost?"] = 1;
  D["A factory has thousands of recordings of NORMAL machine sound and almost no failure examples. One-class SVM is built for this. What does it learn, having only seen one class?"] = 1;
  D["A trained random forest has 300 trees. How does it turn 300 tree outputs into ONE final prediction?"] = 1;
  D["A random forest's max_features setting controls what, exactly, at each split?"] = 1;
  D["A random forest hands you 'feature importances'. As a beginner, how should you read a number like income = 0.41?"] = 1;
  D["Five models each score 86% alone, yet their combined vote scores 91%. What single condition made that possible?"] = 1;
  D["Bagging trains each model on a 'bootstrap sample': n rows drawn from the n training rows WITH replacement. What does one such sample look like?"] = 1;
  D["Bagging: many trees, each trained on its own bootstrap sample, votes averaged. Which weakness of single trees is this aimed squarely at?"] = 1;
  D["Each bagged tree never saw ~37% of the rows. Those left-out rows enable a famous free lunch. Which?"] = 1;
  D["A random forest goes one step beyond bagging: at every split, each tree may only consider a RANDOM SUBSET of the features. Why add that?"] = 1;
  D["A random forest reports feature importances: income 0.41, age 0.22, postcode-ID 0.19… What is that impurity-based number actually measuring?"] = 1;
  D["max_features controls how many features each split may consider. Sweep it from 1 to all 8 on a random forest — what is this knob really trading?"] = 1;
  D["ExtraTrees ('extremely randomized trees') looks like a random forest with the dials turned further. What exactly does it randomise that a random forest doesn't?"] = 1;
  D["A forest's feature_importances_ ranks a random 10,000-level customer ID hash ABOVE genuinely predictive features. What bias in impurity-based importances does this expose?"] = 1;
  D["Income and savings correlate at 0.9. Permutation importance gives income 0.31 and savings 0.02 — yet dropping BOTH craters the model far more than 0.33 suggests. What's the correlated-features trap, and its remedy?"] = 1;
  D["Isolation Forest flips the forest idea to hunt anomalies WITHOUT labels: random splits, and a score based on each point's average PATH DEPTH. Why does depth measure weirdness?"] = 1;
  D["A demand-forecasting forest predicts 120 units, but ops needs 'we're 90% sure demand ≤ X' to set safety stock. Quantile Regression Forests answer this. What do they keep that ordinary forests throw away?"] = 1;
  D["A model scores 99% on its training data but only 71% on new unseen data. What is this gap called?"] = 1;
  D["In gradient boosting, what happens during a single BOOSTING ROUND?"] = 1;
  D["Gradient boosting's learning rate is set to 0.1 instead of 1.0, so each tree's correction counts only a tenth. Why would anyone slow learning down on purpose?"] = 1;
  D["Boosting keeps adding trees, and after round 180 validation accuracy starts sliding while training accuracy still climbs. What's the standard response?"] = 1;
  D["On 10 million rows, XGBoost-family libraries find splits dramatically faster than classic exact search. What's the core speed trick?"] = 1;
  D["Stochastic gradient boosting sets subsample=0.7, so each tree trains on a random 70% of rows. Why would deliberately showing each tree LESS data help?"] = 1;
  D["Boosting libraries default to shallow trees — depth 3 to 6 — while a random forest happily grows its trees deep. Why does boosting specifically want WEAK learners?"] = 1;
  D["XGBoost's stated edge over classic gradient boosting: it uses the loss's SECOND derivative too (Newton boosting). What do the second-order terms buy at each round?"] = 1;
  D["Your GBM denies a loan and the regulator asks 'why, for THIS applicant?'. Global importances can't answer. SHAP values can. What do they guarantee that ad-hoc explanations don't?"] = 1;
  D["You have several trained models. An 'ensemble' does what with them?"] = 1;
  D["Your models each predict a NUMBER (a price, not a class). How does an averaging ensemble combine them?"] = 1;
  D["In WEIGHTED voting, how is the final answer decided differently from plain voting?"] = 1;
  D["The simplest way to combine models is VOTING. What does a voting ensemble actually do?"] = 1;
  D["Stacking trains a 'meta-model' on the base models' predictions. What job does the meta-model do?"] = 1;
  D["Stacking goes beyond averaging: a logistic regression, a forest and a boosted model each make predictions, and then… what happens?"] = 1;
  D["When building the stacking meta-model's training data, the base models' predictions must come from OUT-OF-FOLD predictions. What goes wrong otherwise?"] = 1;
  D["StackingClassifier has passthrough=True, which hands the meta-model the RAW FEATURES alongside the base predictions. When does that flag genuinely earn its keep?"] = 1;
  D["Your 12-model stack wins offline but can't ship: 40ms latency budget, one model's worth of memory. Knowledge distillation promises to keep (most of) the gain. What's the mechanism?"] = 1;
  D["Caruana's classic 'ensemble selection': from a library of 200 assorted fitted models, greedily add (WITH replacement) whichever model most improves the validation-set ensemble average; stop when nothing helps. Why does this crude loop beat elegant weight optimisation so often?"] = 1;
  D["Of all the genuinely negative cases (the truly innocent), what fraction did the model correctly clear? Which metric is this?"] = 1;
  D["A classifier's predictions are compared against the truth. Every single prediction lands in one of exactly four buckets. Which four?"] = 1;
  D["You lower the flag cutoff to catch more real cases. As recall rises, what does precision typically do — and why?"] = 1;
  D["A ROC curve plots a model's behaviour as the cutoff sweeps from strict to lenient. What exactly are its two axes?"] = 1;
  D["Model A has ROC-AUC 0.93; model B has 0.71. Without picking any threshold, what does that difference tell you?"] = 1;
  D["You run 5-fold CV twice with different shuffle seeds and get means of 85.2% and 86.4%. Neither run is buggy. What's the professional response?"] = 1;
  D["You tune hyperparameters with CV, then report that same CV score as the model's expected performance. A reviewer objects. What's the clean fix?"] = 1;
  D["A 5-class ticket classifier scores F1: micro 0.86, macro 0.61, weighted 0.83. Why do the three averages disagree so badly — and which one is watching your rare classes?"] = 1;
  D["Two weather models both hit 83% accuracy, but model A says '90%' when it rains and model B says '55%'. Accuracy can't see the difference. Which metrics grade the PROBABILITIES themselves, and on what principle?"] = 1;
  D["On 95/5 imbalanced data, a lazy model that predicts 'negative' for everyone scores: accuracy 0.95, F1(positive) 0.0, MCC 0.0. Accuracy looked impressive — MCC called the bluff. What makes MCC the hardest single number to fool?"] = 1;
  D["Your model's '80% confident' predictions are correct only 65% of the time. The calibration curve makes this visible — and Expected Calibration Error (ECE) makes it one number. How are they built?"] = 1;
  D["You report 'test accuracy 94.2%' from 500 test rows. A reviewer asks for the uncertainty. Bootstrap gives 94.2% ± 2.1 — and suddenly your 'improvement' over last quarter's 93.1% looks shaky. How does the bootstrap produce that interval, and what's the lesson?"] = 1;
  D["A model scores 99% on the data it was trained on, but only 70% on fresh unseen data. What is this gap called?"] = 1;
  D["Your model underperforms. Before buying more data, you plot scores against training-set size. The two curves have already converged, both around 78%. What does that tell you?"] = 1;
  D["Five diverse models each score 84–88% alone. Averaging their predictions scores 91% — better than every member. What makes that possible?"] = 1;
  D["You tune 60 hyperparameter combos with 5-fold CV and report the winner's CV score as 'the model's performance'. A reviewer objects: that number is biased. Nested cross-validation fixes it — how?"] = 1;
  D["Grid search burns 90% of its budget fully training obviously-bad configurations. Successive halving (and Hyperband) spend the same budget far better. What's the core mechanism?"] = 1;
  D["Random search treats trial #200 exactly like trial #1 — learning nothing along the way. Bayesian optimisation (Optuna, etc.) does learn. What is it actually doing between trials?"] = 1;
  D["Why do many scikit-learn functions like train_test_split and RandomForestClassifier accept a random_state argument?"] = 1;
  D["What does k-fold cross-validation (as in cross_val_score with cv=5) actually do?"] = 1;
  D["A column contains the text values 'red', 'green', and 'blue'. Why must you one-hot encode it before a scikit-learn model can use it?"] = 1;
  D["What does calling .fit(X, y) do to a scikit-learn estimator?"] = 1;
  D["Your dataframe mixes numeric columns (scale them) and categorical columns (one-hot them). Which sklearn tool routes each column to its own preprocessing?"] = 1;
  D["Your search space has 6 hyperparameters. GridSearchCV would need 15,000 fits to cover it. What does RandomizedSearchCV offer instead?"] = 1;
  D["train_test_split(X, y, test_size=0.2, stratify=y) — what does the stratify argument guarantee?"] = 1;
  D["Your gradient-boosted model says '90% confident' but such cases turn out positive only 70% of the time. Which sklearn tool repairs the numbers without retraining the model?"] = 1;
  D["When k-means finishes, how many clusters does each single data point belong to?"] = 1;
  D["In clustering, what exactly is a 'cluster'?"] = 1;
  D["You have 10,000 customers and NO labels of any kind. Clustering promises to 'find the groups'. What is it actually looking for?"] = 1;
  D["K-means repeats two moves until nothing changes. Which two?"] = 1;
  D["K-means needs k chosen in advance. You plot inertia for k = 1…8 and look for the 'elbow'. What are you actually looking for?"] = 1;
  D["Clustering 10 million rows, full k-means grinds. MiniBatchKMeans finishes in minutes with near-identical clusters. What corner does it cut?"] = 1;
  D["A 16-million-colour photo is squeezed to 16 colours using k-means, and it still looks surprisingly good. What is the compression scheme?"] = 1;
  D["Marketing ran k-means twice (different seeds) and got 'different segments', sparking panic. The labels differ — but do the GROUPINGS? Adjusted Rand Index (ARI) answers this. What does it measure, and why 'adjusted'?"] = 1;
  D["Your dataset has 'age' (0-100) and 'height in metres' (0-2). Why should you scale the features before hierarchical clustering?"] = 1;
  D["What does adding a 'connectivity constraint' do to agglomerative clustering?"] = 1;
  D["Agglomerative (hierarchical) clustering starts with every point alone in its own cluster. What happens next, over and over?"] = 1;
  D["Agglomerative clustering builds its tree bottom-up (n−1 merges). There's a mirror-image strategy, divisive clustering, which is rarely used. What is it, and why the rarity?"] = 1;
  D["Ward linkage's formula for the distance between merged clusters is usually computed via the Lance–Williams recurrence, not by re-scanning all points. What does that recurrence buy, and what does it require of your metric?"] = 1;
  D["The cophenetic correlation coefficient is the standard way to ask 'does my dendrogram faithfully represent the original distances?'. What two distances does it correlate, and what does a low value tell you?"] = 1;
  D["BIRCH clusters 50 million rows in one pass using a 'CF-tree' — yet it's still building an agglomerative-style summary. What is the CF-tree, and what's the fundamental trade it makes?"] = 1;
  D["How does the 'k-distance plot' help you choose DBSCAN's eps?"] = 1;
  D["DBSCAN's second parameter is 'minPts' (or min_samples). What does it set?"] = 1;
  D["DBSCAN never asks for k. Instead it grows clusters from 'dense' points. What is its definition of a cluster?"] = 1;
  D["For a customer-similarity graph (nodes = customers, weighted edges = interaction strength), you want to find communities. Spectral clustering is the go-to. What is it fundamentally doing?"] = 1;
  D["In PCA-based anomaly detection you compute a point's 'reconstruction error'. What is it?"] = 1;
  D["PCA's first output is the 'first principal component' (PC1). What is it?"] = 1;
  D["PCA must choose its FIRST axis — the single best line to flatten the data onto. Which line does it pick?"] = 1;
  D["Each principal component comes with 'loadings'. What do loadings tell you?"] = 1;
  D["You want the top 10 principal components of a 500,000 × 20,000 matrix. Exact PCA would eigendecompose a 20,000² covariance matrix — hopeless. Randomized SVD gets the top 10 in seconds. What's the trick?"] = 1;
  D["PCA gave a great low-dimensional embedding but the components are impossible to interpret — every one mixes all 200 features a little. A colleague suggests Non-negative Matrix Factorization (NMF) instead. What does NMF's constraint change?"] = 1;
  D["A dataset has 100,000 mostly-empty columns (one-hot words, TF-IDF). You want to reduce dimensions, but sklearn's PCA errors or blows up memory. Why, and what's the drop-in fix?"] = 1;
  D["t-SNE and PCA both do 'dimensionality reduction'. In plain terms, what is that?"] = 1;
  D["Your data has a raw timestamp like 2026-07-13 09:00. Which engineered features are most likely to help predict store sales?"] = 1;
  D["Hour-of-day runs 0…23, but hour 23 and hour 0 are actually adjacent. How do you encode this so the model knows midnight wraps around?"] = 1;
  D["A category column has 50 values, but 40 of them appear fewer than 5 times each. A common fix is to…"] = 1;
  D["Target encoding uses the label, so it can leak information from the target into the features. What is the standard defense?"] = 1;
  D["A column records the temperature on Mars for each of your loan applicants. It has nothing to do with whether they repay. What kind of feature is this?"] = 1;
  D["What is the 'curse of dimensionality' and why does it motivate feature selection?"] = 1;
  D["You're forecasting next month's sales from past months. Why is ordinary shuffled k-fold the wrong way to validate, and what should you use instead?"] = 1;
  D["What does subsample = 0.8 do in XGBoost?"] = 1;
  D["What does colsample_bytree = 0.6 control?"] = 1;
  D["What does the gamma (min_split_loss) parameter do?"] = 1;
  D["What does min_child_weight do in XGBoost?"] = 1;
  D["Why does XGBoost's histogram tree method (tree_method='hist') speed up training?"] = 1;
  D["XGBoost uses second-order information (the Hessian) when fitting each tree. What is the benefit?"] = 1;
})();
