/* Python coding test — problem bank: regex, JSON, dates and objects.
   The "here is some messy real input, tidy it up" half of a screening test. */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var TXT = 'Text handling';
  var PRS = 'Parsing & files';
  var CLS = 'Classes';

  window.PYTESTS.push(

    { id: 'pt-re-ids', group: TXT, lvl: 2,
      title: 'Pull out the order ids',
      fn: 'find_ids',
      brief: 'Order ids look like ORD- followed by exactly four digits.\n\nReturn every id in the text, in the order they appear. Anything shorter or longer than four digits is not an id.',
      sig: 'def find_ids(text: str) -> list[str]',
      starter: 'import re\n\n\ndef find_ids(text):\n    # your code here\n    pass\n',
      examples: [
        { in: "find_ids('see ORD-1234 and ORD-9999')", out: "['ORD-1234', 'ORD-9999']" }],
      tests: [
        { call: "find_ids('see ORD-1234 and ORD-9999')", expect: "['ORD-1234', 'ORD-9999']" },
        { call: "find_ids('nothing here')", expect: '[]', name: 'no matches' },
        { call: "find_ids('ORD-12 is too short')", expect: '[]', name: 'exactly four digits' },
        { call: "find_ids('ORD-12345')", expect: '[]', hidden: true, name: 'five digits is not an id' },
        { call: "find_ids('a ORD-0001, b ORD-0002.')", expect: "['ORD-0001', 'ORD-0002']", hidden: true }],
      hint: "re.findall with r'ORD-\\d{4}'. To reject longer runs of digits, add a word boundary at each end.",
      solution: "import re\n\n\ndef find_ids(text):\n    return re.findall(r'\\bORD-\\d{4}\\b', text)\n",
      walk: "The whole question is the word boundary. Without \\b, 'ORD-12345' matches its first four digits and you return an id that does not exist. {4} pins the length exactly; \\b makes sure nothing is glued on either side.",
      complexity: 'O(n) over the text.' },

    { id: 'pt-re-mask', group: TXT, lvl: 3,
      title: 'Mask the card numbers',
      fn: 'mask',
      brief: 'Replace every run of 12 or more digits in the text with the same number of asterisks.\n\nShorter numbers — dates, quantities, order sizes — must be left alone.',
      sig: 'def mask(text: str) -> str',
      starter: 'import re\n\n\ndef mask(text):\n    # your code here\n    pass\n',
      examples: [
        { in: "mask('card 4111111111111111 x2')", out: "'card **************** x2'" }],
      tests: [
        { call: "mask('card 4111111111111111 x2')", expect: "'card **************** x2'" },
        { call: "mask('order 12 on 2024')", expect: "'order 12 on 2024'", name: 'short numbers survive' },
        { call: "mask('')", expect: "''" },
        { call: "mask('123456789012')", expect: "'************'", hidden: true, name: 'exactly twelve' },
        { call: "mask('12345678901')", expect: "'12345678901'", hidden: true, name: 'eleven is left alone' }],
      hint: 'Pass a function as the replacement in re.sub — it receives the match object, so you can return the right number of asterisks.',
      solution: "import re\n\n\ndef mask(text):\n    return re.sub(r'\\d{12,}', lambda m: '*' * len(m.group()), text)\n",
      walk: "Two things worth knowing here. {12,} means twelve or more, so eleven-digit numbers are untouched. And the replacement argument to re.sub can be a FUNCTION — it is handed the match, which is how the mask ends up the same length as whatever it replaced.",
      complexity: 'O(n) over the text.' },

    { id: 'pt-re-log-levels', group: PRS, lvl: 2,
      title: 'Count the log levels',
      fn: 'count_levels',
      brief: 'Each log line starts with a timestamp then a level in capitals — INFO, WARN or ERROR.\n\nReturn a dict of level to how many lines had it. Lines that do not fit the shape are ignored.',
      sig: 'def count_levels(lines: list[str]) -> dict',
      starter: 'import re\n\n\ndef count_levels(lines):\n    # your code here\n    pass\n',
      examples: [
        { in: "count_levels(['10:00 INFO up', '10:01 ERROR down'])", out: "{'INFO': 1, 'ERROR': 1}" }],
      tests: [
        { call: "count_levels(['10:00 INFO up', '10:01 ERROR down'])", expect: "{'INFO': 1, 'ERROR': 1}" },
        { call: 'count_levels([])', expect: '{}', name: 'no lines' },
        { call: "count_levels(['rubbish'])", expect: '{}', name: 'unparseable lines are skipped' },
        { call: "count_levels(['1 INFO a', '2 INFO b', '3 WARN c'])", expect: "{'INFO': 2, 'WARN': 1}", hidden: true },
        { call: "count_levels(['1 info a'])", expect: '{}', hidden: true, name: 'levels are capitals' }],
      hint: 'Search each line for r"(INFO|WARN|ERROR)" and count the hits with a dict or a Counter.',
      solution: "import re\nfrom collections import Counter\n\n\ndef count_levels(lines):\n    counts = Counter()\n    for line in lines:\n        found = re.search(r'\\b(INFO|WARN|ERROR)\\b', line)\n        if found:\n            counts[found.group(1)] += 1\n    return dict(counts)\n",
      walk: "Returning dict(counts) rather than the Counter itself matters: a Counter compares equal to a dict, but printing one in a report looks wrong. `if found` is the guard that skips lines that do not match — without it, .group() on None raises AttributeError, which is the usual failure here.",
      complexity: 'O(n) over the lines.' },

    { id: 'pt-json-flatten', group: PRS, lvl: 3,
      title: 'Flatten the nested record',
      fn: 'flatten',
      brief: 'API responses arrive as nested dicts. Flatten one into a single level, joining the keys with dots.\n\n{"a": {"b": 1}} becomes {"a.b": 1}. Lists and other values are left as they are.',
      sig: 'def flatten(record: dict) -> dict',
      starter: 'def flatten(record):\n    # your code here\n    pass\n',
      examples: [
        { in: "flatten({'a': {'b': 1}, 'c': 2})", out: "{'a.b': 1, 'c': 2}" }],
      tests: [
        { call: "flatten({'a': {'b': 1}, 'c': 2})", expect: "{'a.b': 1, 'c': 2}" },
        { call: 'flatten({})', expect: '{}', name: 'nothing to flatten' },
        { call: "flatten({'a': 1})", expect: "{'a': 1}", name: 'already flat' },
        { call: "flatten({'a': {'b': {'c': 3}}})", expect: "{'a.b.c': 3}", hidden: true, name: 'three levels deep' },
        { call: "flatten({'a': {'b': [1, 2]}})", expect: "{'a.b': [1, 2]}", hidden: true, name: 'lists stay whole' }],
      hint: 'Recurse: when a value is a dict, flatten it and stick the parent key plus a dot on the front of each of its keys.',
      solution: "def flatten(record, prefix=''):\n    out = {}\n    for key, value in record.items():\n        full = prefix + key\n        if isinstance(value, dict):\n            out.update(flatten(value, full + '.'))\n        else:\n            out[full] = value\n    return out\n",
      walk: "A default argument carries the prefix down the recursion, so the caller still gets to write flatten(record). isinstance(value, dict) is the test that decides whether to recurse — checking for a list too would be a change in the spec, and the hidden test pins the current behaviour down.",
      complexity: 'O(n) over every key in the tree.' },

    { id: 'pt-json-defaults', group: PRS, lvl: 2,
      title: 'Fill in the config',
      fn: 'with_defaults',
      brief: 'A config dict from a user may be missing keys. Return a new dict with every default filled in and the user\'s own values kept.\n\nDo not change either dict you were given.',
      sig: 'def with_defaults(config: dict, defaults: dict) -> dict',
      starter: 'def with_defaults(config, defaults):\n    # your code here\n    pass\n',
      examples: [
        { in: "with_defaults({'a': 1}, {'a': 0, 'b': 2})", out: "{'a': 1, 'b': 2}" }],
      tests: [
        { call: "with_defaults({'a': 1}, {'a': 0, 'b': 2})", expect: "{'a': 1, 'b': 2}" },
        { call: "with_defaults({}, {'b': 2})", expect: "{'b': 2}", name: 'nothing supplied' },
        { call: "with_defaults({'z': 9}, {})", expect: "{'z': 9}", name: 'no defaults' },
        { call: '_unchanged()', expect: 'True', hidden: true, name: 'the inputs must not be modified' },
        { call: "with_defaults({'a': None}, {'a': 5})", expect: "{'a': None}", hidden: true, name: 'an explicit None still wins' }],
      setup: "def _unchanged():\n    given = {'a': 1}\n    fallback = {'b': 2}\n    with_defaults(given, fallback)\n    return given == {'a': 1} and fallback == {'b': 2}\n",
      hint: 'Copy the defaults, then update the copy with the user config. The order is what decides which value wins.',
      solution: 'def with_defaults(config, defaults):\n    merged = dict(defaults)\n    merged.update(config)\n    return merged\n',
      walk: "Two lines, and both details are deliberate. dict(defaults) makes the copy, so neither input is touched — the hidden test checks exactly that. Updating WITH the user config means their values overwrite the defaults, including an explicit None; flip the order and you would silently ignore what the user asked for.",
      complexity: 'O(n) over the keys.' },

    { id: 'pt-dates-month-counts', group: 'Dates & times', lvl: 2,
      title: 'Orders per month',
      fn: 'per_month',
      brief: 'Given date strings in YYYY-MM-DD form, count how many fall in each month.\n\nReturn a dict keyed by YYYY-MM. Any string that is not a valid date is skipped.',
      sig: 'def per_month(dates: list[str]) -> dict',
      starter: 'def per_month(dates):\n    # your code here\n    pass\n',
      examples: [
        { in: "per_month(['2024-05-01', '2024-05-20', '2024-06-02'])", out: "{'2024-05': 2, '2024-06': 1}" }],
      tests: [
        { call: "per_month(['2024-05-01', '2024-05-20', '2024-06-02'])", expect: "{'2024-05': 2, '2024-06': 1}" },
        { call: 'per_month([])', expect: '{}', name: 'no dates' },
        { call: "per_month(['not a date'])", expect: '{}', name: 'rubbish is skipped' },
        { call: "per_month(['2024-02-30'])", expect: '{}', hidden: true, name: 'the 30th of February is not a date' },
        { call: "per_month(['2023-12-31', '2024-01-01'])", expect: "{'2023-12': 1, '2024-01': 1}", hidden: true }],
      hint: "datetime.strptime(text, '%Y-%m-%d') parses it and raises ValueError on anything invalid. Catch that and move on.",
      solution: "from datetime import datetime\n\n\ndef per_month(dates):\n    counts = {}\n    for text in dates:\n        try:\n            parsed = datetime.strptime(text, '%Y-%m-%d')\n        except ValueError:\n            continue\n        key = parsed.strftime('%Y-%m')\n        counts[key] = counts.get(key, 0) + 1\n    return counts\n",
      walk: "Parsing rather than slicing the string is the point: text[:7] would happily accept '2024-02-30' and 'not a da'. strptime validates the calendar, and the try/except turns a bad row into a skip instead of a crash. counts.get(key, 0) + 1 is the no-imports way to tally.",
      complexity: 'O(n) over the dates.' },

    { id: 'pt-dates-gap', group: 'Dates & times', lvl: 3,
      title: 'The longest gap',
      fn: 'longest_gap',
      brief: 'Given date strings in YYYY-MM-DD form, return the largest number of days between two consecutive dates once they are in order.\n\nFewer than two dates means a gap of 0.',
      sig: 'def longest_gap(dates: list[str]) -> int',
      starter: 'def longest_gap(dates):\n    # your code here\n    pass\n',
      examples: [
        { in: "longest_gap(['2024-01-01', '2024-01-05', '2024-01-06'])", out: '4' }],
      tests: [
        { call: "longest_gap(['2024-01-01', '2024-01-05', '2024-01-06'])", expect: '4' },
        { call: "longest_gap(['2024-01-01'])", expect: '0', name: 'one date has no gap' },
        { call: 'longest_gap([])', expect: '0' },
        { call: "longest_gap(['2024-01-10', '2024-01-01'])", expect: '9', hidden: true, name: 'unsorted input' },
        { call: "longest_gap(['2024-02-28', '2024-03-01'])", expect: '2', hidden: true, name: '2024 is a leap year' }],
      hint: 'Parse them all, sort, then look at each neighbouring pair. Subtracting two datetimes gives a timedelta with a .days.',
      solution: "from datetime import datetime\n\n\ndef longest_gap(dates):\n    parsed = sorted(datetime.strptime(d, '%Y-%m-%d') for d in dates)\n    best = 0\n    for earlier, later in zip(parsed, parsed[1:]):\n        best = max(best, (later - earlier).days)\n    return best\n",
      walk: "zip(parsed, parsed[1:]) is the tidy way to walk neighbouring pairs — no index arithmetic, and it handles the empty and single-date cases without a special branch. The leap-year test is there to make sure you subtracted real dates rather than doing arithmetic on the strings.",
      complexity: 'O(n log n) for the sort.' },

    { id: 'pt-cls-basket', group: CLS, lvl: 2,
      title: 'A shopping basket',
      fn: 'Basket',
      brief: 'Write a class Basket with .add(name, price), .total() and .count.\n\nThe same item may be added more than once. .remove(name) takes one copy out and does nothing if it is not there. An empty basket totals 0.',
      sig: 'class Basket:  # .add(name, price), .remove(name), .total(), .count',
      starter: 'class Basket:\n    def __init__(self):\n        # your code here\n        pass\n',
      examples: [
        { in: "b = Basket(); b.add('tea', 2.5); b.total()", out: '2.5' }],
      tests: [
        { call: "_basket([('tea', 2.5), ('jam', 1.5)]).total()", expect: '4.0' },
        { call: 'Basket().total()', expect: '0', name: 'an empty basket' },
        { call: "_basket([('tea', 2.5)]).count", expect: '1' },
        { call: "_removed([('tea', 2.5), ('jam', 1.5)], 'tea')", expect: '1.5', hidden: true, name: 'removing takes the price off' },
        { call: "_removed([('tea', 2.5)], 'nope')", expect: '2.5', hidden: true, name: 'removing something absent does nothing' }],
      setup: "def _basket(pairs):\n    b = Basket()\n    for name, price in pairs:\n        b.add(name, price)\n    return b\n\n\ndef _removed(pairs, name):\n    b = _basket(pairs)\n    b.remove(name)\n    return b.total()\n",
      hint: 'Keep a list of (name, price) tuples. count is len() of that list, total is the sum of the prices.',
      solution: "class Basket:\n    def __init__(self):\n        self.items = []\n\n    def add(self, name, price):\n        self.items.append((name, price))\n\n    def remove(self, name):\n        for i, (item_name, _) in enumerate(self.items):\n            if item_name == name:\n                del self.items[i]\n                return\n\n    def total(self):\n        return sum(price for _, price in self.items)\n\n    @property\n    def count(self):\n        return len(self.items)\n",
      walk: "count is a @property, so it is read as b.count with no brackets and can never drift out of step with the list — the alternative, incrementing a counter in add and remove, is exactly the kind of duplicated state that goes wrong. The `return` inside remove stops after the first copy, and falling out of the loop quietly is what makes removing something absent a no-op.",
      complexity: 'O(1) to add, O(n) to remove or total.' },

    { id: 'pt-ml-threshold', group: 'Machine learning by hand', lvl: 3,
      title: 'Pick the threshold',
      fn: 'best_threshold',
      brief: 'Given predicted probabilities and the true 0/1 labels, try every threshold in the list of candidates and return the one with the highest F1 score.\n\nA row counts as predicted positive when its probability is greater than or equal to the threshold. On a tie, return the LOWEST threshold. If no threshold scores above 0, return the lowest candidate.',
      sig: 'def best_threshold(probs: list[float], labels: list[int], candidates: list[float]) -> float',
      starter: 'def best_threshold(probs, labels, candidates):\n    # your code here\n    pass\n',
      examples: [
        { in: 'best_threshold([0.2, 0.8], [0, 1], [0.5, 0.9])', out: '0.5' }],
      tests: [
        { call: 'best_threshold([0.2, 0.8], [0, 1], [0.5, 0.9])', expect: '0.5' },
        { call: 'best_threshold([0.9, 0.9], [1, 1], [0.5, 0.9])', expect: '0.5', name: 'a tie takes the lowest' },
        { call: 'best_threshold([0.1], [0], [0.5])', expect: '0.5', name: 'nothing scores, so the lowest candidate' },
        { call: 'best_threshold([0.4, 0.6, 0.7], [0, 1, 1], [0.3, 0.5, 0.8])', expect: '0.5', hidden: true },
        { call: 'best_threshold([0.6, 0.6], [1, 0], [0.5, 0.7])', expect: '0.5', hidden: true, name: 'half right beats nothing caught' }],
      hint: 'For each candidate, count true positives, false positives and false negatives, work out precision and recall, then F1 = 2PR / (P + R). Guard every division.',
      solution: 'def best_threshold(probs, labels, candidates):\n    best_score = -1\n    best = min(candidates)\n    for t in sorted(candidates):\n        tp = sum(1 for p, y in zip(probs, labels) if p >= t and y == 1)\n        fp = sum(1 for p, y in zip(probs, labels) if p >= t and y == 0)\n        fn = sum(1 for p, y in zip(probs, labels) if p < t and y == 1)\n        precision = tp / (tp + fp) if tp + fp else 0\n        recall = tp / (tp + fn) if tp + fn else 0\n        f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0\n        if f1 > best_score:\n            best_score = f1\n            best = t\n    return best\n',
      walk: "The threshold is a decision you make after training, and this is that decision written out. Three divisions, three guards: with no predicted positives precision is undefined, with no real positives recall is, and F1 is undefined when both are zero — every one of those happens on real data. Walking the candidates in sorted order with a strict `>` comparison is what makes ties resolve to the lowest threshold.",
      complexity: 'O(candidates × n).' },

    { id: 'pt-ml-precision-at-k', group: 'Machine learning by hand', lvl: 2,
      title: 'Precision in the top k',
      fn: 'precision_at_k',
      brief: 'A model scores every customer and you can only contact the top k. Given the scores and the true 0/1 labels, return the fraction of the top k that were really positive.\n\nIf k is bigger than the list, score everything you have. If k is zero or less, return 0.',
      sig: 'def precision_at_k(scores: list[float], labels: list[int], k: int) -> float',
      starter: 'def precision_at_k(scores, labels, k):\n    # your code here\n    pass\n',
      examples: [
        { in: 'precision_at_k([0.9, 0.1, 0.8], [1, 0, 0], 2)', out: '0.5', note: 'the top two are 0.9 and 0.8; one was positive' }],
      tests: [
        { call: 'precision_at_k([0.9, 0.1, 0.8], [1, 0, 0], 2)', expect: '0.5' },
        { call: 'precision_at_k([0.9, 0.8], [1, 1], 5)', expect: '1.0', name: 'k bigger than the list' },
        { call: 'precision_at_k([0.9], [1], 0)', expect: '0', name: 'nobody contacted' },
        { call: 'precision_at_k([], [], 3)', expect: '0', hidden: true, name: 'nothing to score' },
        { call: 'precision_at_k([0.1, 0.2, 0.3], [1, 0, 0], 1)', expect: '0.0', hidden: true, name: 'the highest score was wrong' }],
      hint: 'Pair the scores with the labels, sort by score descending, take the first k and average their labels.',
      solution: 'def precision_at_k(scores, labels, k):\n    if k <= 0 or not scores:\n        return 0\n    ranked = sorted(zip(scores, labels), key=lambda pair: pair[0], reverse=True)\n    top = ranked[:k]\n    return sum(label for _, label in top) / len(top)\n',
      walk: "This is the metric a business actually cares about when there is a budget: not \"how good is the model everywhere\" but \"of the thousand people we can call, how many were worth calling\". Slicing past the end of a list is safe in Python, which is why `ranked[:k]` handles the too-big k on its own — but dividing by `len(top)` rather than by k is what keeps that case correct.",
      complexity: 'O(n log n) for the sort.' },

    { id: 'pt-ml-cost', group: 'Machine learning by hand', lvl: 3,
      title: 'What the errors cost',
      fn: 'total_cost',
      brief: 'Given the true 0/1 labels and the predicted 0/1 labels, along with the cost of one false positive and one false negative, return the total cost.\n\nCorrect predictions cost nothing. If the two lists are different lengths, raise ValueError.',
      sig: 'def total_cost(labels: list[int], preds: list[int], fp_cost: float, fn_cost: float) -> float',
      starter: 'def total_cost(labels, preds, fp_cost, fn_cost):\n    # your code here\n    pass\n',
      examples: [
        { in: 'total_cost([1, 0], [0, 1], 5, 100)', out: '105' }],
      tests: [
        { call: 'total_cost([1, 0], [0, 1], 5, 100)', expect: '105' },
        { call: 'total_cost([1, 1], [1, 1], 5, 100)', expect: '0', name: 'all correct costs nothing' },
        { call: 'total_cost([], [], 5, 100)', expect: '0' },
        { call: '_raises()', expect: 'True', hidden: true, name: 'mismatched lengths raise' },
        { call: 'total_cost([0, 0, 1], [1, 1, 0], 2, 10)', expect: '14', hidden: true, name: 'two false alarms and one miss' }],
      setup: "def _raises():\n    try:\n        total_cost([1], [1, 0], 1, 1)\n    except ValueError:\n        return True\n    return False\n",
      hint: 'A false positive is predicted 1 where the truth was 0; a false negative is predicted 0 where the truth was 1. Count each and multiply.',
      solution: 'def total_cost(labels, preds, fp_cost, fn_cost):\n    if len(labels) != len(preds):\n        raise ValueError(\'labels and preds must be the same length\')\n    fp = sum(1 for y, p in zip(labels, preds) if y == 0 and p == 1)\n    fn = sum(1 for y, p in zip(labels, preds) if y == 1 and p == 0)\n    return fp * fp_cost + fn * fn_cost\n',
      walk: "This is the argument behind every \"which metric?\" answer: once a false negative costs twenty times a false positive, the threshold that maximises accuracy is the wrong threshold. The length check matters because `zip` silently stops at the shorter list — a mismatch would quietly under-count instead of telling you something is wrong.",
      complexity: 'O(n).' },

    { id: 'pt-fn-no-mutate', group: 'Debugging', lvl: 2,
      title: 'It changed the caller\'s list',
      fn: 'add_item',
      brief: 'add_item(items, x) should return a NEW list with x on the end, leaving the list it was given untouched.\n\nThe version below mutates its argument. Fix it.',
      sig: 'def add_item(items: list, x) -> list',
      starter: 'def add_item(items, x):\n    items.append(x)\n    return items\n',
      examples: [
        { in: 'add_item([1, 2], 3)', out: '[1, 2, 3]' }],
      tests: [
        { call: 'add_item([1, 2], 3)', expect: '[1, 2, 3]' },
        { call: 'add_item([], 1)', expect: '[1]', name: 'starting from nothing' },
        { call: '_original_kept()', expect: 'True', name: 'the caller\'s list must not change' },
        { call: '_twice()', expect: '[[1, 2], [1, 3]]', hidden: true, name: 'two calls must not stack up' },
        { call: "add_item(['a'], 'b')", expect: "['a', 'b']", hidden: true }],
      setup: "def _original_kept():\n    given = [1, 2]\n    add_item(given, 3)\n    return given == [1, 2]\n\n\ndef _twice():\n    base = [1]\n    return [add_item(base, 2), add_item(base, 3)]\n",
      hint: 'Copy first: items + [x] builds a new list, and so does list(items) followed by an append.',
      solution: 'def add_item(items, x):\n    return items + [x]\n',
      walk: "`items + [x]` builds a new list and leaves the original alone; `.append` changes the object the caller still holds. The _twice test is the one that exposes it — with the mutating version the second call returns [1, 2, 3], because the first call already changed the list underneath it. If a function is not documented as mutating its argument, it must not.",
      complexity: 'O(n) time and space for the copy.' },

    { id: 'pt-str-report-line', group: 'Text handling', lvl: 2,
      title: 'Line up the report',
      fn: 'line',
      brief: 'Format one line of a report: the name padded out to 12 characters, then the amount with a pound sign, thousands separated and exactly two decimal places.\n\nThe amount is right-aligned in 10 characters.',
      sig: 'def line(name: str, amount: float) -> str',
      starter: 'def line(name, amount):\n    # your code here\n    pass\n',
      examples: [
        { in: "line('Tea', 1234.5)", out: "'Tea          £1,234.50'" }],
      tests: [
        { call: "line('Tea', 1234.5)", expect: "'Tea          £1,234.50'" },
        { call: "line('Coffee', 0)", expect: "'Coffee           £0.00'", name: 'zero still gets two decimals' },
        { call: "len(line('Tea', 1234.5))", expect: '22', name: 'every line is the same width' },
        { call: "line('Marmalade Jam', 5)", expect: "'Marmalade Jam     £5.00'", hidden: true, name: 'a long name is not cut off' },
        { call: "line('X', 1000000)", expect: "'X           £1,000,000.00'", hidden: true }],
      hint: "f-strings do all of it: f'{name:<12}' pads the name out on the right, f'{amount:,.2f}' groups thousands and fixes two decimals, and .rjust(10) pushes the money over to the right.",
      solution: "def line(name, amount):\n    return f'{name:<12}' + f'£{amount:,.2f}'.rjust(10)\n",
      walk: "The format spec is the whole answer: `<12` left-aligns the name in twelve characters, `,` groups the thousands and `.2f` forces two decimal places even on a whole number. Padding never TRUNCATES — a name longer than twelve characters pushes the line out rather than being cut, which is what the hidden tests pin down.",
      complexity: 'O(1).' },

    { id: 'pt-test-average-guard', group: 'Debugging', lvl: 2,
      title: 'The average that crashes',
      fn: 'average',
      brief: 'average(values) should return the mean of the numbers in the list, ignoring anything that is not a number, and 0 for an empty list.\n\nThe version below crashes on both.',
      sig: 'def average(values: list) -> float',
      starter: 'def average(values):\n    return sum(values) / len(values)\n',
      examples: [
        { in: 'average([1, 2, 3])', out: '2.0' },
        { in: "average([1, 'x', 3])", out: '2.0' }],
      tests: [
        { call: 'average([1, 2, 3])', expect: '2.0' },
        { call: "average([1, 'x', 3])", expect: '2.0', name: 'text is ignored' },
        { call: 'average([])', expect: '0', name: 'empty gives zero, not a crash' },
        { call: "average(['a', 'b'])", expect: '0', hidden: true, name: 'nothing usable at all' },
        { call: 'average([2, None, 4.0])', expect: '3.0', hidden: true, name: 'None is not a number' }],
      hint: 'Filter first with isinstance(v, (int, float)), then guard against the filtered list being empty.',
      solution: 'def average(values):\n    numbers = [v for v in values if isinstance(v, (int, float)) and not isinstance(v, bool)]\n    if not numbers:\n        return 0\n    return sum(numbers) / len(numbers)\n',
      walk: "Two guards, in the right order: filter to the values you can actually add, THEN check that anything survived. Excluding bool is the detail that separates a careful answer from a passing one — True is an int in Python, so a stray flag would otherwise count as 1 and quietly move the mean.",
      complexity: 'O(n) time, O(n) for the filtered list.' },

    { id: 'pt-gen-chunks', group: 'Algorithms', lvl: 2,
      title: 'Hand it out in batches',
      fn: 'batches',
      brief: 'Write a GENERATOR that yields the items in batches of size n, as lists.\n\nThe last batch may be shorter. If n is zero or less, yield nothing.',
      sig: 'def batches(items: list, n: int)',
      starter: 'def batches(items, n):\n    # your code here\n    pass\n',
      examples: [
        { in: 'list(batches([1, 2, 3], 2))', out: '[[1, 2], [3]]' }],
      tests: [
        { call: 'list(batches([1, 2, 3], 2))', expect: '[[1, 2], [3]]' },
        { call: 'list(batches([], 3))', expect: '[]', name: 'nothing to batch' },
        { call: 'list(batches([1, 2], 0))', expect: '[]', name: 'a nonsense batch size' },
        { call: 'list(batches([1, 2, 3, 4], 2))', expect: '[[1, 2], [3, 4]]', hidden: true, name: 'exact fit' },
        { call: 'next(batches(list(range(1000000)), 3))', expect: '[0, 1, 2]', hidden: true, name: 'must be lazy, not build them all' }],
      hint: 'Loop the start index in steps of n with range(0, len(items), n) and yield the slice each time.',
      solution: 'def batches(items, n):\n    if n <= 0:\n        return\n    for start in range(0, len(items), n):\n        yield items[start:start + n]\n',
      walk: "A bare `return` inside a generator ends it — it does not return a value, and it is how you say \"yield nothing\" for the invalid batch size. The million-item test passes instantly because a generator only produces the batch you asked for; a version that built a list of every batch first would still work, but it is not what was asked for and it would be the slow answer on real data.",
      complexity: 'O(n) overall, O(batch) memory at a time.' },

    { id: 'pt-gen-running-max', group: 'Algorithms', lvl: 2,
      title: 'Best so far',
      fn: 'running_max',
      brief: 'Return a list holding, for each position, the largest value seen up to and including it.\n\nAn empty list gives an empty list.',
      sig: 'def running_max(nums: list) -> list',
      starter: 'def running_max(nums):\n    # your code here\n    pass\n',
      examples: [
        { in: 'running_max([1, 3, 2, 5])', out: '[1, 3, 3, 5]' }],
      tests: [
        { call: 'running_max([1, 3, 2, 5])', expect: '[1, 3, 3, 5]' },
        { call: 'running_max([])', expect: '[]', name: 'nothing at all' },
        { call: 'running_max([4])', expect: '[4]' },
        { call: 'running_max([-5, -9, -1])', expect: '[-5, -5, -1]', hidden: true, name: 'all negative' },
        { call: 'len(running_max(list(range(100000))))', expect: '100000', hidden: true, name: 'must not be quadratic' }],
      hint: 'Carry the best value seen so far in a variable and update it as you go — do not call max() on a growing slice.',
      solution: 'def running_max(nums):\n    out = []\n    best = None\n    for n in nums:\n        if best is None or n > best:\n            best = n\n        out.append(best)\n    return out\n',
      walk: "Seeding `best` with None rather than 0 is what keeps the all-negative case right — a classic hidden test. The tempting one-liner, [max(nums[:i + 1]) for i in range(len(nums))], is correct but O(n²) and the 100,000-element test is there to make that cost visible. itertools.accumulate(nums, max) is the neat library answer.",
      complexity: 'O(n) time, O(n) for the output.' }
  );
})();
