/* More core definitions (batch 12): foundations, KNN, logistic regression, Naive Bayes,
   decision trees, SVM. Simple, central vocabulary each topic was still missing. DEFS-tagged
   with reveals for the Definitions filter, flashcards and read+recall. Loads before app.js. */
(function () {
  var Q = (window.QUESTIONS = window.QUESTIONS || {});
  var D = (window.DEFS = window.DEFS || {});
  function def(qk, q, correct, distractors, name, text, explain, simple) {
    (Q[qk] = Q[qk] || []).push({ q: q, choices: [correct].concat(distractors), explain: explain, simple: simple, widget: { reveal: { name: name, text: text } } });
    D[q] = 1;
  }

  /* ===== Core Definitions (found1) — 10 ===== */

  def("found1",
    "What is a dataset in machine learning?",
    "A structured collection of examples, typically rows of features with (for supervised tasks) a label.",
    ["The single file of trained weights that a model saves after fitting has finished.",
     "The list of hyperparameter settings tried during tuning together with their scores.",
     "Any table that contains at least one column of continuous numeric measurements.",
     "The set of predictions a model has produced since it was deployed."],
    "Dataset",
    "The raw material of ML: a collection of examples, usually a table where each row is one case and each column one feature (plus a label column in supervised learning).",
    "Everything else is defined relative to the dataset — splits carve it up, features describe its columns, and the model's job is to generalise from it to cases it doesn't contain.",
    "The big table of examples the model learns from.");

  def("found1",
    "What is a prediction?",
    "The model's output for a given input — its best guess at the label or value.",
    ["The true answer recorded for an example when the dataset was originally labelled.",
     "The difference between a model's training score and its score on the test set.",
     "The subset of features the model decided were most relevant for the task.",
     "A guarantee about the accuracy the model will achieve on future data."],
    "Prediction",
    "What a trained model produces when shown an input: a class label, a probability, or a number. Predictions on unseen data are the entire point of training.",
    "Keeping 'prediction' and 'label' separate is the grammar of evaluation: metrics compare the two, residuals subtract them, and confusion matrices cross-tabulate them.",
    "The model's answer to a new question.");

  def("found1",
    "What are a model's parameters (weights)?",
    "The internal numbers learning adjusts to fit the data, like coefficients in a linear model.",
    ["The settings a person chooses before training, such as the learning rate or tree depth.",
     "The counts of rows and columns that describe the size of the training dataset.",
     "The list of feature names the model expects to receive at prediction time.",
     "The scores achieved on each fold of cross-validation during model selection."],
    "Model parameters (weights)",
    "The values the training algorithm learns from data — regression coefficients, tree split points, cluster centroids. What changes during fitting IS the parameters.",
    "The parameter/hyperparameter split is the field's first vocabulary test: parameters are learned by the algorithm during training; hyperparameters are chosen by you before it starts.",
    "The knobs the algorithm turns by itself while learning.");

  def("found1",
    "What does 'training' (fitting) a model mean?",
    "Adjusting the model's parameters so its predictions match the training examples as well as possible.",
    ["Running the model on the test set repeatedly until its accuracy stops changing.",
     "Converting the dataset's categorical columns into numbers the model can read.",
     "Choosing which algorithm to use by comparing published benchmark results.",
     "Writing the rules of the model by hand based on domain expertise."],
    "Training (fitting)",
    "The optimisation phase: an algorithm tunes the model's parameters to minimise a loss on the training data — .fit() in sklearn terms.",
    "Training is where the loss function, the optimiser and the data meet; everything after it (validation, testing, deployment) works with the parameters this step produced.",
    "The learning step: show examples, adjust the dials until the answers fit.");

  def("found1",
    "What is inference (prediction time)?",
    "Using an already-trained model to make predictions on new inputs, with no further learning.",
    ["The statistical test that decides whether a model's accuracy is significantly above chance.",
     "The stage where the model updates its weights slightly for every new example it sees.",
     "The process of inferring which features caused the model to overfit during training.",
     "Re-training the model from scratch each time a new batch of data arrives."],
    "Inference",
    "The deployment phase: weights are frozen and the model just computes outputs for incoming data. Its speed and memory needs are often what production systems care about most.",
    "Training happens once on big hardware; inference happens millions of times, everywhere — which is why train-time cost and predict-time cost are different budgets (KNN being the classic pay-at-inference example).",
    "Using the finished model — no more learning, just answering.");

  def("found1",
    "In sklearn convention, what are X and y?",
    "X is the feature matrix (rows × columns); y is the target vector of labels or values.",
    ["X is the training half of the data and y is the testing half after a random split.",
     "X is the model's predictions and y is the residual error left after subtracting them.",
     "X is the set of numeric features and y is the set of categorical features.",
     "X is the input layer of the model and y is its list of hyperparameters."],
    "Feature matrix X and target y",
    "The universal calling convention: X holds one row per example and one column per feature; y holds the answer for each row. fit(X, y) learns the mapping X → y.",
    "The shapes tell the story — X is (n_samples, n_features), y is (n_samples,) — and half of practical debugging is making real data conform to exactly this shape.",
    "X is the question sheet, y is the answer column.");

  def("found1",
    "What is noise in a dataset?",
    "Random variation in features or labels that carries no learnable pattern.",
    ["Any feature whose values are negative or fall outside the range zero to one.",
     "The rows of the dataset that belong to whichever class is least frequent.",
     "Information that competitors have deliberately inserted to corrupt your model.",
     "Features that are measured in decibels or other logarithmic units."],
    "Noise",
    "The unpredictable component of data: measurement error, typos in labels, genuine randomness in the world. It sets the ceiling on achievable accuracy.",
    "Overfitting is, by definition, mistaking noise for signal — the model memorises fluctuations that will never repeat. Irreducible error is noise's contribution to every future prediction.",
    "The static in the signal — variation no model can ever predict.");

  def("found1",
    "What are missing values in a dataset?",
    "Cells with no recorded value, which most models cannot accept and must be dropped or imputed.",
    ["Feature values equal to zero, which models automatically skip during training.",
     "Rows belonging to classes that appear in the test set but not in training.",
     "Values that are present but fall more than three standard deviations from the mean.",
     "Columns whose names are absent from the dataset's documentation."],
    "Missing values",
    "Empty cells (NaN) from unanswered questions, sensor failures or joins. Standard handling: drop rows/columns, or impute with a mean/median/model — plus often a missingness flag, since the absence itself can be informative.",
    "Missingness is rarely random — income is missing more often for certain groups — so how you handle it changes the model. Handling must be learned from training data only.",
    "Blanks in the table — and models don't accept blanks.");

  def("found1",
    "What is the difference between binary and multiclass classification?",
    "Binary chooses between exactly two classes; multiclass chooses among three or more.",
    ["Binary uses numeric features only, while multiclass can also accept categorical ones.",
     "Binary predicts hard labels while multiclass can only ever output probabilities.",
     "Binary is supervised while multiclass is a form of unsupervised learning.",
     "Binary models train faster but are always less accurate than multiclass ones."],
    "Binary vs multiclass classification",
    "Spam/not-spam is binary; cat/dog/bird is multiclass. Some algorithms are natively multiclass (trees, NB); others extend from binary via one-vs-rest or softmax.",
    "The distinction ripples through everything: which averaging your F1 uses, whether ROC-AUC needs a per-class treatment, and how a logistic model must be generalised.",
    "Two options is binary; a menu of three or more is multiclass.");

  def("found1",
    "What is data cleaning?",
    "Fixing quality problems — duplicates, impossible values, inconsistent formats — before modelling.",
    ["Deleting enough rows that the remaining classes are exactly balanced in size.",
     "Normalising every feature so that its values lie strictly between zero and one.",
     "Removing all features that are not statistically significant predictors of the target.",
     "Encrypting sensitive columns so models cannot learn from personal information."],
    "Data cleaning",
    "The unglamorous first mile: deduplicate records, fix 'N/A'-as-string problems, reconcile units and category spellings ('UK' vs 'U.K.'), handle impossible values like negative ages.",
    "Model quality is capped by data quality — a boosted ensemble on dirty data loses to a linear model on clean data, which is why practitioners report spending most of their time here.",
    "Tidy the table before you teach from it.");

  /* ===== k-Nearest Neighbours (easy) — 9 ===== */

  def("easy",
    "In KNN, what is k?",
    "The number of nearest neighbours consulted when making a prediction.",
    ["The number of features kept after selection to make the distance computation cheaper.",
     "The number of classes the classifier is able to distinguish between.",
     "The maximum distance at which a training point may still cast a vote.",
     "The number of times the training data is rescanned before the model converges."],
    "k (number of neighbours)",
    "KNN's one central hyperparameter: how many of the closest training points get a vote. k=1 trusts a single neighbour; large k polls a wide crowd.",
    "Every KNN behaviour traces back to k — flexibility, noise-resistance, boundary smoothness — which is why choosing it by validation is the core KNN skill.",
    "How many neighbours you ask before deciding.");

  def("easy",
    "What is a 'nearest neighbour' of a point?",
    "The training example whose feature values put it closest to that point under the chosen distance.",
    ["The training example that shares the most feature names with the query point.",
     "The example that was added to the dataset immediately before the query point.",
     "Any training point that belongs to the same class as the query point.",
     "The centroid of the cluster that the query point falls inside."],
    "Nearest neighbour",
    "The most similar known example: compute the distance from the query to every training point; the smallest distance wins. 'Neighbour' is geometry, not metaphor.",
    "The whole KNN family — classification, regression, imputation, anomaly detection — is variations on one move: find the closest labelled experiences and borrow their answers.",
    "The most similar example the model has ever seen.");

  def("easy",
    "What is the query (test) point in KNN?",
    "The new, unlabelled input whose neighbours are being looked up to make a prediction.",
    ["The training point that sits closest to the centre of the whole dataset.",
     "The point deliberately removed from training to serve as the validation set.",
     "The furthest outlier, queried first to establish the scale of distances.",
     "A synthetic point generated midway between the two classes."],
    "Query point",
    "The point being classified: KNN measures the distance from it to every stored training example, ranks them, and lets the top k answer.",
    "Naming it separates KNN's two populations — the stored, labelled memory versus the incoming unknowns — and clarifies that all of KNN's work happens per-query, at prediction time.",
    "The newcomer asking: who around here is most like me?");

  def("easy",
    "How are similarity and distance related in KNN-style methods?",
    "They are inverses: the smaller the distance between two points, the more similar they are.",
    ["They are unrelated quantities that must both be computed separately for each pair.",
     "Similarity applies to categorical features while distance applies to numeric ones.",
     "Distance is similarity multiplied by the number of dimensions in the data.",
     "They are identical: two points at distance 0.9 have similarity 0.9."],
    "Similarity vs distance",
    "Two views of one idea: metrics like Euclidean measure how far apart points are; similarities like cosine measure how alike they are. Small distance = high similarity.",
    "Libraries and papers switch freely between the two framings (1 − similarity is a common conversion), so reading them as a single concept avoids constant confusion.",
    "Close means alike — distance and similarity are the same dial read from opposite ends.");

  def("easy",
    "What happens to a KNN model when k is very small (like 1)?",
    "It becomes highly flexible and noise-sensitive: single mislabelled points carve out wrong islands.",
    ["It underfits, predicting the same majority class for every possible query point.",
     "It refuses to classify queries that are not exact copies of training points.",
     "Its training time grows dramatically because more distances must be stored.",
     "Its decision boundary becomes a single straight line through the data."],
    "Effect of small k (overfitting)",
    "With k=1, every training point — including every error — rules its own little territory. The boundary is jagged, training accuracy is perfect, and generalisation suffers.",
    "This is the high-variance end of KNN's dial: maximally faithful to the sample, maximally exposed to its noise. The classic symptom is a large train–test accuracy gap.",
    "Trusting one neighbour means trusting every typo in the data.");

  def("easy",
    "What happens to a KNN model when k is very large?",
    "It oversmooths: local patterns wash out, and predictions drift toward the overall majority class.",
    ["It overfits, because more neighbours means more parameters to memorise the data with.",
     "It becomes unable to classify points that lie near the training data's boundary.",
     "Its predictions become undefined whenever k exceeds the number of features.",
     "It automatically switches from classification to regression behaviour."],
    "Effect of large k (oversmoothing)",
    "At the extreme k = n, every query gets the same answer: the dataset's majority class. Long before that, small genuine pockets of one class are outvoted by the surrounding crowd.",
    "This is the high-bias end of the dial — stable but insensitive. The right k balances the two failure modes, which is exactly what a validation curve over k displays.",
    "Poll the whole city and every neighbourhood gives the same answer.");

  def("easy",
    "What is a point's neighbourhood in feature space?",
    "The region of nearby points — the local area whose examples drive KNN's prediction.",
    ["The set of features whose values are non-zero for that particular point.",
     "The cluster label assigned to the point by a preliminary k-means run.",
     "All points that share the point's most important single feature value.",
     "The bounding box drawn around the entire training dataset."],
    "Neighbourhood (in feature space)",
    "The local patch of feature space around a point. KNN's core bet is that labels are locally consistent — a point's neighbourhood mostly shares its class.",
    "Neighbourhood size is what k and radius parameters really control, and 'local methods' (KNN, DBSCAN, LOF, t-SNE) are exactly the family whose conclusions come from neighbourhoods rather than global fits.",
    "The point's local area — its street, not the whole map.");

  def("easy",
    "What defines the family of distance-based algorithms?",
    "Their conclusions come from computed distances between points, making scaling and metric choice critical.",
    ["They all require the target variable to be a physical distance measured in metres.",
     "They only work on datasets that contain exactly two numeric feature columns.",
     "They learn a distance function from labels instead of using feature values.",
     "They are the algorithms that cannot be used inside a sklearn Pipeline."],
    "Distance-based methods",
    "KNN, k-means, DBSCAN, hierarchical clustering and SVMs-with-RBF all reason from point-to-point distances — so they share sensitivities: feature scales, irrelevant features, and high dimensionality.",
    "Spotting the family membership transfers your knowledge: the scaling rule you learned for KNN applies verbatim to k-means and DBSCAN, and the curse of dimensionality haunts them all equally.",
    "One family, one creed: you are what you're close to.");

  def("easy",
    "Why does KNN have essentially zero training cost?",
    "It just stores the training data; all real work — distance computation — happens at prediction time.",
    ["Because its parameters are estimated in closed form from the feature means.",
     "Because it trains on a small random sample rather than the full dataset.",
     "Because the distances between all pairs are precomputed by the data loader.",
     "Because it reuses the weights of a previously trained neural network."],
    "Store now, compute later (KNN's cost profile)",
    "Fitting KNN is a memcpy; predicting means measuring distance to (potentially) every stored point. The cost profile is inverted relative to parametric models, which pay at training and predict cheaply.",
    "This shapes deployment: KNN's latency grows with training-set size, motivating spatial indexes and approximate search — and explaining why 'lazy learning' is a budget statement, not an insult.",
    "Learning is free; every answer is where the bill arrives.");

  /* ===== Logistic Regression (logreg1) — 9 ===== */

  def("logreg1",
    "What is a linear model?",
    "A model whose prediction is built from a weighted sum of the input features.",
    ["Any model whose training time grows linearly with the number of rows.",
     "A model that can only be applied to features measured on a ruler-like scale.",
     "A model whose predictions always increase over time in a straight line.",
     "Any model fitted by the method of gradient descent."],
    "Linear model",
    "The family built on w·x + b: linear regression, logistic regression, linear SVMs. Each feature contributes independently, in proportion to its weight.",
    "Linearity is both the power (interpretability, speed, convex training) and the constraint (straight-line boundaries) — feature engineering exists largely to smuggle curvature into this family.",
    "Prediction by recipe: so many points per unit of each ingredient, added up.");

  def("logreg1",
    "In binary classification, what are the positive and negative classes?",
    "The class of interest (positive, label 1) versus the other (negative, label 0) — a naming convention.",
    ["The classes with above-average and below-average feature values respectively.",
     "The majority class and the minority class of the training data respectively.",
     "The classes whose examples were labelled correctly and incorrectly by annotators.",
     "The class predicted with probability above 0.9 versus everything else."],
    "Positive vs negative class",
    "Pure convention with real consequences: 'positive' is usually the event you're hunting (fraud, disease, churn), coded 1. Precision, recall, TP/FP counts are all defined relative to it.",
    "Flipping which class is positive flips precision and recall into different numbers — so metric values are meaningless until you know which class was declared positive.",
    "Pick which outcome counts as 'the thing we're looking for' — every metric leans on that choice.");

  def("logreg1",
    "What does logistic regression actually output before any threshold is applied?",
    "A probability between 0 and 1 for the positive class.",
    ["A hard class label, either exactly 0 or exactly 1, with no gradations.",
     "An unbounded score whose units depend on the scale of the input features.",
     "The index of the training example most similar to the query.",
     "A confidence interval around the most likely class label."],
    "Probability output",
    "The sigmoid maps the weighted score into (0, 1), so the raw output reads as P(positive | x) = 0.83. The class label only appears when a threshold cuts the probability.",
    "Keeping the probability (predict_proba) rather than the label preserves information — for ranking, cost-weighted decisions and calibration checks — and is why threshold choice is a separate, later decision.",
    "It answers 'how likely?', not 'yes or no' — the yes/no is your cut, not the model's.");

  def("logreg1",
    "What is the default decision rule in most logistic regression implementations?",
    "Predict the positive class when the predicted probability exceeds 0.5.",
    ["Predict the positive class when the weighted score exceeds the largest feature value.",
     "Predict whichever class was more frequent in the training data, ignoring probabilities.",
     "Predict positive only when the probability exceeds the class's base rate squared.",
     "Alternate between the classes to keep the predicted distribution balanced."],
    "The default 0.5 threshold",
    "p > 0.5 — equivalently, weighted score z > 0 — is the symmetric default: choose the more probable class. It silently assumes both error types cost the same.",
    "Real problems rarely have symmetric costs, so 0.5 is a starting point, not a law: lowering the threshold buys recall, raising it buys precision, and cost analysis picks the right point.",
    "'Whichever is more likely' — sensible, but only when both mistakes hurt equally.");

  def("logreg1",
    "How do you read the sign and size of a logistic regression coefficient?",
    "Sign gives the direction of the effect on the odds; size (on scaled features) gives its strength.",
    ["Sign shows whether the feature is categorical; size shows how many categories it has.",
     "Sign indicates data-entry errors; size counts how many rows contain the feature.",
     "Sign shows which class the feature belongs to; size gives its rank in importance.",
     "Both are meaningless individually and only their product can be interpreted."],
    "Reading coefficients (sign and size)",
    "Positive weight → the feature pushes toward the positive class; negative → away. With standardised features, magnitudes are comparable, and exponentiating a weight gives its odds ratio per unit.",
    "This direct readability is logistic regression's enduring selling point — but it holds per-feature only when features aren't strongly correlated, which is what multicollinearity breaks.",
    "Plus pushes toward 'yes', minus toward 'no', and bigger pushes harder.");

  def("logreg1",
    "Why is plain linear regression a poor tool for binary classification?",
    "Its outputs aren't probabilities — they escape [0, 1] — and outlying points drag the boundary.",
    ["It cannot accept categorical features, which classification problems always contain.",
     "It requires more training data than any classification algorithm can provide.",
     "Its predictions are probabilities, but for the wrong one of the two classes.",
     "It can only be fitted when the two classes are exactly equal in size."],
    "Why not linear regression for classification",
    "Fitting a line to 0/1 labels yields predictions like 1.4 and −0.2, and squared error lets far-away easy points bend the boundary. The sigmoid fixes the range; log loss fixes the sensitivity.",
    "This contrast is the cleanest motivation for logistic regression: same weighted sum underneath, but a link function and loss chosen for probabilities rather than quantities.",
    "A ruler drawing through 0s and 1s predicts nonsense like 140% — you need the S-curve.");

  def("logreg1",
    "What do max_iter and convergence warnings mean when fitting logistic regression?",
    "The optimiser ran out of allowed iterations before settling; results may be off — scale features or raise the cap.",
    ["The model found more classes in the target column than it was configured to accept.",
     "Training data contained missing values, which the solver filled with column means.",
     "The regularisation parameter was so strong that every coefficient became zero.",
     "The dataset was too small for the number of cross-validation folds requested."],
    "max_iter and convergence",
    "Fitting is iterative optimisation; max_iter caps the steps. A ConvergenceWarning means the stop was hit mid-descent — commonly caused by unscaled features stretching the loss surface.",
    "The right response is usually to standardise features first, then raise max_iter — not to ignore the warning, since an unconverged fit has quietly wrong coefficients.",
    "'Ran out of steps before reaching the bottom' — rescale the features, give it more steps.");

  def("logreg1",
    "In logistic regression, what three steps take raw features to a class label?",
    "Weighted sum → sigmoid to probability → threshold to label.",
    ["Standardise → cluster the rows → assign each cluster's majority label.",
     "Threshold each feature → count the votes → apply the sigmoid to the count.",
     "Sigmoid each feature → sum the results → pick the class of the nearest neighbour.",
     "Rank the features → drop the weakest half → average the remainder."],
    "Score → probability → label pipeline",
    "z = w·x + b condenses the evidence; σ(z) converts it to a probability; the threshold converts probability to a decision. Three stages, each independently inspectable.",
    "Debugging maps onto the stages: weird coefficients → stage 1, poor calibration → stage 2, wrong precision/recall balance → stage 3 (and only stage 3 is free to change after training).",
    "Add up the evidence, squash it to a chance, then make the call.");

  def("logreg1",
    "What does it mean that logistic regression is a discriminative model?",
    "It learns the boundary P(class | features) directly, without modelling how the data was generated.",
    ["It is a model whose use is restricted by fairness regulations in some industries.",
     "It discriminates between numeric and categorical features, handling each separately.",
     "It learns the full joint distribution of features and labels, like Naive Bayes.",
     "It can only be trained on datasets where the classes are linearly separable."],
    "Discriminative model",
    "Discriminative models (logistic regression, SVMs, trees) model the conditional P(y|x) or the boundary itself; generative models (Naive Bayes) model P(x|y) and invert via Bayes.",
    "The practical trade: discriminative models usually win on accuracy with enough data, while generative ones can win when data is scarce and their distributional story is roughly right.",
    "It learns to tell classes apart — not to describe what each class looks like.");

  /* ===== Naive Bayes (bayes1) — 9 ===== */

  def("bayes1",
    "How does Naive Bayes estimate its probabilities during training?",
    "By counting frequencies: how often each class occurs, and each feature value within each class.",
    ["By gradient descent on the log loss until the class boundaries stop moving.",
     "By repeatedly resampling the data and averaging the resulting decision boundaries.",
     "By measuring the distance from each example to the mean of its class.",
     "By solving a system of equations that makes all features independent."],
    "Estimating probabilities by counting",
    "Training NB is bookkeeping: P(spam) ≈ share of spam emails; P('free' | spam) ≈ share of spam containing 'free'. One pass through the data, tallying.",
    "This is why NB trains near-instantly, streams naturally (partial_fit just updates counts), and works from modest data — and why smoothing matters, since raw counts of rare events are fragile.",
    "Learning by tallying: count how often everything happens in each class.");

  def("bayes1",
    "How does Naive Bayes turn its per-class scores into a final prediction?",
    "It predicts the class with the highest posterior — the argmax over class scores.",
    ["It averages the scores of all classes and predicts the class nearest that average.",
     "It predicts positive whenever any single feature's likelihood exceeds one half.",
     "It samples a class at random with probability proportional to each score.",
     "It predicts the class whose score changed most since the previous example."],
    "Argmax decision rule",
    "Each class gets a score (prior × likelihoods); the largest wins. Because only the ranking matters, the shared evidence denominator can be skipped entirely.",
    "The argmax view explains NB's robustness: probabilities can be badly miscalibrated while the winner — the only thing argmax reads — stays correct.",
    "Score every class, pick the top of the leaderboard.");

  def("bayes1",
    "What does the alpha parameter control in MultinomialNB and friends?",
    "The strength of additive smoothing — how many pseudo-counts protect unseen feature values.",
    ["The learning rate used when the model's counts are updated by gradient steps.",
     "The fraction of features randomly ignored in each training pass for regularisation.",
     "The decision threshold applied to the posterior before a label is emitted.",
     "The maximum number of classes the model is willing to distinguish."],
    "alpha (smoothing strength)",
    "alpha=1 is Laplace smoothing (add one imaginary count everywhere); alpha<1 (Lidstone) smooths more gently; larger alpha pulls all probabilities toward uniform.",
    "It is NB's main tuning knob — effectively its regulariser: too little leaves rare-word estimates jumpy, too much blurs real differences between classes. Tune it on validation data.",
    "How many imaginary sightings every word gets for free, so 'never seen' never means 'impossible'.");

  def("bayes1",
    "Why is text classification the classic home turf of Naive Bayes?",
    "Word counts give huge, sparse feature sets where per-feature counting is cheap and surprisingly effective.",
    ["Because text features are truly statistically independent, making the naive assumption exact.",
     "Because Naive Bayes is the only algorithm able to accept string inputs directly.",
     "Because documents are always short enough to fit inside the probability tables.",
     "Because text datasets never contain class imbalance or labelling errors."],
    "Text classification (NB's home turf)",
    "Bag-of-words creates tens of thousands of features — deadly for many models, natural for NB, which just keeps a count per word per class. Spam filtering made it famous.",
    "The independence violations (words co-occur heavily) hurt calibration but not ranking much, so NB remains the fast, strong baseline every text pipeline should try first.",
    "Counting words per class is exactly the game NB was built to play.");

  def("bayes1",
    "What is the likelihood table a categorical Naive Bayes model effectively stores?",
    "For each class, the probability of each feature value — one row of estimates per class.",
    ["The pairwise correlation between every two features, computed within each class.",
     "The list of training examples the model considers most typical of each class.",
     "The confusion matrix obtained on the training data after fitting completes.",
     "A ranking of the features by their overall predictive importance."],
    "Likelihood table",
    "The trained model IS this table: P(value | class) for every feature value and class, plus the class priors. Prediction just looks up and multiplies the relevant cells.",
    "Seeing NB as a lookup table demystifies it — inspection (sklearn's feature_log_prob_) shows exactly which words scream 'spam', making NB one of the most auditable classifiers.",
    "The cheat sheet: one probability per word per class, learned by counting.");

  def("bayes1",
    "How are Naive Bayes' class priors usually set?",
    "From training-data class frequencies — though they can be overridden with domain knowledge.",
    ["Always to the uniform distribution, giving every class an equal starting chance.",
     "By cross-validating over all possible prior values and keeping the best scorer.",
     "From the test set's class proportions, measured just before evaluation begins.",
     "They are learned by gradient descent along with the likelihood parameters."],
    "Priors from class frequencies",
    "By default, P(class) is its share of the training data — 3% fraud in training means a 3% head start. fit_prior/class_prior let you replace this with known deployment rates.",
    "The prior is where base-rate reasoning enters the classifier, and adjusting it is the principled fix when training class balance differs from reality (e.g. after resampling).",
    "Each class starts with its market share as its head start.");

  def("bayes1",
    "Why do Naive Bayes' class scores get normalised at the end (divided by the evidence)?",
    "So the scores become proper probabilities that sum to one across the classes.",
    ["To remove the influence of the prior, which would otherwise bias the prediction.",
     "Because unnormalised scores would always favour the class with fewer features.",
     "To convert log-space scores back into distances for the final comparison.",
     "It is required to keep the counts from overflowing 32-bit integers."],
    "Posterior normalisation",
    "prior × likelihoods gives each class an unnormalised score; dividing by their sum (the evidence) rescales them into probabilities summing to 1 — that's all predict_proba adds.",
    "Normalisation changes presentation, not the winner: argmax is identical either way, which is why implementations postpone it and why the evidence term is 'just a normaliser'.",
    "Rescale the scores so they read as percentages that add to 100.");

  def("bayes1",
    "Roughly how does Naive Bayes compare to logistic regression as training data grows?",
    "NB is strong with little data; logistic regression usually overtakes it as data grows.",
    ["The two are mathematically identical, so their accuracies are always equal.",
     "NB always dominates because it uses probability theory rather than optimisation.",
     "Logistic regression is stronger with little data; NB wins on very large datasets.",
     "Neither can outperform the other unless the features are first decorrelated."],
    "NB vs logistic regression (data-size story)",
    "The classic generative-vs-discriminative result: NB's assumptions act like a strong prior — quick to reach decent accuracy, but the assumption's error becomes a floor; logistic regression converges slower but toward a better ceiling.",
    "Practical translation: tiny labelled set or streaming setting → try NB; plenty of data and correlated features → expect logistic regression (or beyond) to win.",
    "NB sprints, logistic regression wins the marathon.");

  def("bayes1",
    "What does it mean that Naive Bayes handles high-dimensional data gracefully?",
    "Parameters grow only linearly with features, so thousands of features stay cheap and estimable.",
    ["It automatically deletes all but the twenty most predictive features before training.",
     "It projects the features onto two dimensions before estimating any probabilities.",
     "Its accuracy is provably independent of how many features the data contains.",
     "It stores the full joint table over all features, which GPUs make affordable."],
    "Linear parameter growth (high-dimensional grace)",
    "Modelling the full joint distribution of d binary features needs ~2^d numbers; the naive factorisation needs ~2d per class. That collapse is the assumption's entire payoff.",
    "It's why NB shrugs at 50,000-word vocabularies that would drown other generative approaches — the naive assumption trades correlational fidelity for tractable estimation.",
    "One number per word instead of one per word-combination — that's the naive bargain.");

  /* ===== Decision Trees (trees1) — 9 ===== */

  def("trees1",
    "What is a branch in a decision tree?",
    "One outcome-path leaving a node's test — e.g. the 'yes' side of 'age ≤ 30?'.",
    ["A copy of the tree trained on a bootstrap sample of the original data.",
     "A feature that appears in more than one split within the same tree.",
     "The list of leaves that share the same predicted class label.",
     "Any subtree that was removed from the model during pruning."],
    "Branch",
    "Each internal node asks a question; each possible answer is a branch leading to the next node. Following branches from root to leaf traces a prediction.",
    "Branches are the tree's control flow — 'branching logic' in code and flowcharts is the same structure, which is why trees feel readable to non-specialists.",
    "The yes-road and the no-road leading out of each question.");

  def("trees1",
    "What is the depth of a decision tree?",
    "The length of the longest root-to-leaf path — how many questions the tree can ask in sequence.",
    ["The total number of training examples stored across all of its leaf nodes.",
     "The number of distinct features the tree uses at least once in its splits.",
     "The count of leaves divided by the count of internal decision nodes.",
     "The number of classes the tree is able to distinguish at its leaves."],
    "Tree depth",
    "Depth counts stacked decisions: a depth-3 tree asks at most three questions per prediction and can carve at most 2³ = 8 regions.",
    "Depth is the tree's primary capacity dial — each extra level doubles potential regions, which is why max_depth is the first overfitting control everyone reaches for.",
    "How many questions deep the longest interrogation goes.");

  def("trees1",
    "What is a pure node?",
    "A node whose examples all share one class — impurity zero, nothing left to split.",
    ["A node whose split uses exactly one feature rather than a combination of features.",
     "A node containing an equal number of examples from every class in the data.",
     "A node whose examples all have identical feature values but different labels.",
     "The root node before any splitting has been applied to the data."],
    "Pure node",
    "All one class: Gini and entropy both read zero, and growth stops there naturally — the node becomes a leaf that predicts its class with certainty.",
    "Purity is the destination the splitting criterion steers toward; 'grow until pure' is also exactly how trees memorise noise, which is why pruning exists.",
    "A room where everyone agrees — no more questions needed.");

  def("trees1",
    "What is the splitting criterion of a decision tree?",
    "The score — like Gini drop or information gain — used to compare candidate splits and pick the best.",
    ["The rule deciding how many trees to grow before the ensemble is complete.",
     "The distance metric used to group similar examples into the same leaf.",
     "The percentage of data reserved for testing each split's accuracy.",
     "The order in which features were listed in the original dataset."],
    "Splitting criterion",
    "At each node the algorithm auditions every candidate question and scores how much purer the children would be; the criterion (Gini, entropy, or variance reduction for regression) is that scoring rule.",
    "It's the tree's definition of a 'good question' — and the reason tree training needs no gradient: just evaluate, compare, and take the best split, greedily.",
    "The judge that rates every possible question and crowns the most clarifying one.");

  def("trees1",
    "What are the candidate splits a tree considers at a node?",
    "Every usable feature-threshold question — e.g. each feature at each observed cut point.",
    ["Only the splits that were used by the node's parent and grandparent nodes.",
     "A single random question, accepted if it improves purity and rejected otherwise.",
     "The set of splits suggested by a domain expert before training begins.",
     "Only splits on features that are perfectly correlated with the target."],
    "Candidate splits",
    "For numeric features, the midpoints between consecutive sorted values; for categorical ones, value groupings. The training algorithm scores this whole menu at every node.",
    "Knowing the menu explains training cost (features × thresholds × nodes) and why histogram methods — which shrink the threshold menu into bins — speed boosting libraries up so dramatically.",
    "Every question the node could possibly ask, all auditioned.");

  def("trees1",
    "What does a leaf predict in a classification tree?",
    "The majority class of the training examples that landed in that leaf.",
    ["The class of the single training example closest to the leaf's centre.",
     "A class chosen at random, weighted by the tree's overall class balance.",
     "The class predicted by the leaf's sibling, inverted for diversity.",
     "Whatever class the root node's first split assigned to that side."],
    "Majority class at a leaf",
    "Each leaf remembers its training population and answers with its most common class (and can report the mix as a probability). Regression leaves answer with the mean instead.",
    "The leaf-as-committee view makes min_samples_leaf intuitive: tiny committees of one or two examples give unreliable verdicts, which is precisely leaf-level overfitting.",
    "Each leaf answers with the winner of its own little election.");

  def("trees1",
    "What conditions make a tree stop splitting a node?",
    "Purity reached, or a limit hit — max depth, too few samples, or no split improves enough.",
    ["The node's feature values exceed the range observed at the root node.",
     "A fixed thirty-second time budget per node runs out during training.",
     "The node's examples fail a normality test on their feature distribution.",
     "The validation accuracy of the whole tree reaches exactly 100%."],
    "Stopping conditions",
    "Growth halts when a node is pure, when structural caps bite (max_depth, min_samples_split, min_samples_leaf, max_leaf_nodes), or when the best available split gains less than min_impurity_decrease.",
    "These conditions ARE pre-pruning: each is a knob trading fit against simplicity, and tuning them is how a single tree is kept honest without a separate pruning pass.",
    "Stop when everyone agrees, or when the rulebook says you've asked enough.");

  def("trees1",
    "Why are decision trees called white-box models?",
    "Their logic is fully inspectable — any prediction can be traced through explicit, readable rules.",
    ["Because their default visualisation renders nodes on a white background.",
     "Because they can only be trained on datasets that have been anonymised.",
     "Because their internal weights are all constrained to be positive numbers.",
     "Because they hide their split thresholds to protect the training data."],
    "White-box model (tree interpretability)",
    "A trained tree is a flowchart: every decision is a human-readable comparison, and the exact reason for any prediction is its root-to-leaf path. Contrast black boxes, where logic is distributed across thousands of weights.",
    "This transparency is why single trees survive in regulated and high-stakes settings despite weaker accuracy — and what ensembles sacrifice when they average hundreds of trees.",
    "The reasoning is on display — you can read the flowchart yourself.");

  def("trees1",
    "Why don't decision trees require feature scaling?",
    "Splits compare each feature only against its own thresholds, so units and scales are irrelevant.",
    ["Because trees internally standardise every feature before choosing any split.",
     "Because trees only accept features that are already between zero and one.",
     "They do require scaling; skipping it silently degrades every split's quality.",
     "Because trees convert all numeric features into categorical bins first."],
    "Trees don't need feature scaling",
    "'Income ≤ 40,000?' works identically whether income is in pounds or thousands — no cross-feature distance is ever computed, so scales never mix. Monotone transforms of features leave the tree unchanged.",
    "This is a defining split in preprocessing needs: distance- and gradient-based models demand scaling; trees and their ensembles (forests, boosting) simply don't care.",
    "Each feature is measured against itself, so nobody needs a common ruler.");

  /* ===== Support Vector Machines (svm1) — 8 ===== */

  def("svm1",
    "What does it mean for data to be linearly separable?",
    "A straight line (or flat hyperplane) can split the classes with zero training errors.",
    ["The features are uncorrelated enough for a linear model to be fitted stably.",
     "Every feature individually separates the classes when examined on its own.",
     "The two classes contain exactly the same number of training examples.",
     "The data can be sorted into separate files, one for each class label."],
    "Linear separability",
    "Separable data admits a perfect flat boundary — the setting where hard-margin SVMs exist and the perceptron converges. Most real datasets are not separable in their raw features.",
    "The concept organises the SVM story: separable → maximise the margin; non-separable → soften the margin (C) or lift to a space where separation appears (kernels).",
    "Can one straight cut divide the two teams perfectly?");

  def("svm1",
    "How does an SVM cope with data that is not linearly separable?",
    "Two tools: the soft margin tolerates some violations, and kernels reshape the space.",
    ["It deletes the overlapping examples from both classes until separation appears.",
     "It refuses to train, reporting that no valid model exists for the data.",
     "It switches internally to a decision-tree algorithm for the hard regions.",
     "It duplicates the boundary, using one line per class instead of one overall."],
    "Handling non-separable data",
    "The C parameter buys slack — margin violations are allowed but charged — while the kernel trick maps points into a higher-dimensional space where a flat cut may exist.",
    "The two mechanisms compose: a soft-margin RBF SVM is the everyday configuration, its two knobs (C and gamma) respectively pricing violations and setting the kernel's reach.",
    "Bend the rules a little (soft margin), or bend the space itself (kernels).");

  def("svm1",
    "What behaviour does a large C versus a small C produce in a soft-margin SVM?",
    "Large C punishes violations hard (narrow margin, overfit risk); small C tolerates them (wide margin, smoother).",
    ["Large C widens the margin without limit while small C collapses it to zero.",
     "Large C speeds training dramatically while small C makes it exhaustive.",
     "Large C forces more support vectors while small C forbids having any.",
     "C changes only the output probabilities and never the boundary itself."],
    "Large C vs small C",
    "C prices each margin violation. Expensive violations (high C) make the fit contort around individual points; cheap ones (low C) let the boundary stay broad and calm.",
    "C is SVM's bias-variance dial in one number — the first hyperparameter to tune, typically on a log scale, watching validation score rather than training fit.",
    "High C: 'no mistakes allowed!' Low C: 'stay relaxed, ignore stragglers.'");

  def("svm1",
    "What behaviour does a large gamma versus a small gamma produce with an RBF kernel?",
    "Large gamma gives each point tiny, intense influence (wiggly boundary); small gamma spreads influence smoothly.",
    ["Large gamma increases the number of features while small gamma removes them.",
     "Large gamma makes the boundary more linear while small gamma adds corners.",
     "Gamma controls only convergence speed and never affects the fitted model.",
     "Large gamma shrinks the dataset while small gamma augments it."],
    "Large gamma vs small gamma",
    "Gamma is the inverse reach of each training point's similarity bubble: huge gamma → islands around individual points (memorisation); tiny gamma → influence so broad the boundary approaches linear.",
    "Gamma and C are tuned together on a 2-D log grid; the pairing (high C, high gamma) is the classic overfitting corner, and validation curves over gamma show textbook bias-variance shape.",
    "Gamma sets each point's aura: pinpoint spotlights or broad floodlights.");

  def("svm1",
    "How do you choose which kernel to try for an SVM?",
    "Start linear for high-dimensional/sparse data, RBF as the general default; validate rather than guess.",
    ["Always use the polynomial kernel, since it strictly generalises the other kernels.",
     "Choose by the number of classes: linear for two, RBF for three or more.",
     "Match the kernel to the loss function: hinge pairs only with sigmoid kernels.",
     "The kernel makes no practical difference, so the fastest one is always right."],
    "Choosing a kernel",
    "Rules of thumb: many features / text → linear (often via LinearSVC); moderate features with suspected non-linearity → RBF; known structure (e.g. degrees of interaction) → polynomial. Then let validation arbitrate.",
    "The kernel is an assumption about the shape of similarity in your problem — the most consequential modelling choice an SVM user makes, and one metric scores can actually settle.",
    "Linear first when features are many; RBF as the trusty default; let the scores decide.");

  def("svm1",
    "Why does maximising the margin help an SVM generalise?",
    "A wide buffer means small perturbations of new points don't flip their side of the boundary.",
    ["A wider margin guarantees fewer support vectors and therefore less memory use.",
     "The margin width equals training accuracy, so maximising both is identical.",
     "Wide margins make the kernel matrix sparse, which reduces numerical error.",
     "It doesn't; the margin is maximised purely for computational convenience."],
    "Why a wide margin generalises",
    "Among all perfect separators, the widest-margin one is least committed to the training sample's quirks: future points drawn near the training ones still land on the correct side.",
    "Margin theory formalises this — generalisation bounds tighten as margins widen — making SVMs the textbook case of building the safety buffer directly into the objective.",
    "Leave the widest possible no-man's-land, and tomorrow's points won't cross it by accident.");

  def("svm1",
    "What is a margin violation?",
    "A training point inside the margin or on the wrong side — permitted, at a cost, by the soft margin.",
    ["A test point whose prediction differs from the majority of its neighbours.",
     "A support vector that appears twice in the training data by duplication.",
     "A kernel value that exceeds one, violating the similarity definition.",
     "Any feature whose variance exceeds the margin's width."],
    "Margin violation",
    "Soft-margin SVMs let points trespass into the buffer zone (or beyond), tracking each trespass with a slack variable and charging it C per unit in the objective.",
    "Violations are the currency of the C trade-off — and the violating points are themselves support vectors, which is why messier data yields larger, slower SVM models.",
    "A point standing in the no-man's-land — allowed, but it costs the model points.");

  def("svm1",
    "In sklearn, when would you reach for LinearSVC instead of SVC?",
    "For large datasets with a linear kernel: it uses a specialised fast solver that scales far better.",
    ["When you need predicted probabilities, which only LinearSVC can provide.",
     "When the data has fewer than one hundred rows and accuracy is critical.",
     "When you want the RBF kernel, which LinearSVC implements more precisely.",
     "Never; LinearSVC is a deprecated alias kept for backwards compatibility."],
    "SVC vs LinearSVC",
    "SVC(kernel='linear') solves the kernelised problem (~quadratic in n); LinearSVC attacks the linear primal directly (liblinear), staying practical at hundreds of thousands of rows.",
    "The rule of thumb: kernels or small data → SVC; big data where linear suffices (text especially) → LinearSVC. Same idea, different engines for different scales.",
    "Same straight boundary, but the express engine for big data.");

})();
