/* Python coding test — problem bank 0: first programs.
   Deliberately small. The point is the loop of write → run → read the failures →
   fix, on problems where the logic is never the hard part. */
(function () {
  window.PYTESTS = window.PYTESTS || [];

  window.PYTESTS.push(

    { id: 'pt-add-two', group: 'First programs', lvl: 1,
      title: 'Add two numbers',
      fn: 'add',
      brief: 'Return the sum of two numbers.\n\nThis one is a warm-up for the runner itself: write the line, press Run tests, and see what a passing test looks like.',
      sig: 'def add(a, b)',
      starter: 'def add(a, b):\n    # your code here\n    pass\n',
      examples: [{ in: 'add(2, 3)', out: '5' }],
      tests: [
        { call: 'add(2, 3)', expect: '5' },
        { call: 'add(0, 0)', expect: '0' },
        { call: 'add(-1, 1)', expect: '0', name: 'negatives' },
        { call: 'add(2.5, 0.5)', expect: '3.0', hidden: true, name: 'decimals too' }],
      hint: 'One line: return a + b.',
      solution: 'def add(a, b):\n    return a + b\n',
      walk: 'The word `return` is what hands the answer back to whoever called the function. Without it the function does its work and returns None — which is the single most common reason every test fails at once.',
      complexity: 'O(1).' },

    { id: 'pt-greet', group: 'First programs', lvl: 1,
      title: 'Say hello',
      fn: 'greet',
      brief: 'Return a greeting: for the name "Ada", return "Hello, Ada!".',
      sig: 'def greet(name)',
      starter: 'def greet(name):\n    # your code here\n    pass\n',
      examples: [{ in: "greet('Ada')", out: "'Hello, Ada!'" }],
      tests: [
        { call: "greet('Ada')", expect: "'Hello, Ada!'" },
        { call: "greet('Bob')", expect: "'Hello, Bob!'" },
        { call: "greet('')", expect: "'Hello, !'", hidden: true, name: 'no name given' }],
      hint: "An f-string is easiest: f'Hello, {name}!'",
      solution: "def greet(name):\n    return f'Hello, {name}!'\n",
      walk: "Return the string, do not print it — a test can only check what comes back. Printing and returning are different things, and mixing them up is the second most common beginner mistake after the missing return.",
      complexity: 'O(1).' },

    { id: 'pt-is-even', group: 'First programs', lvl: 1,
      title: 'Even or odd',
      fn: 'is_even',
      brief: 'Return True if a whole number is even, False if it is odd.',
      sig: 'def is_even(n)',
      starter: 'def is_even(n):\n    # your code here\n    pass\n',
      examples: [{ in: 'is_even(4)', out: 'True' }, { in: 'is_even(7)', out: 'False' }],
      tests: [
        { call: 'is_even(4)', expect: 'True' },
        { call: 'is_even(7)', expect: 'False' },
        { call: 'is_even(0)', expect: 'True', name: 'zero is even' },
        { call: 'is_even(-2)', expect: 'True', hidden: true, name: 'negatives are too' }],
      hint: 'n % 2 gives the remainder after dividing by 2. If that is 0, the number is even.',
      solution: 'def is_even(n):\n    return n % 2 == 0\n',
      walk: "The comparison n % 2 == 0 already IS True or False, so return it directly — no if-statement needed. Writing `if n % 2 == 0: return True else: return False` works but says the same thing twice.",
      complexity: 'O(1).' },

    { id: 'pt-biggest', group: 'First programs', lvl: 1,
      title: 'The biggest of three',
      fn: 'biggest',
      brief: 'Return the largest of three numbers.',
      sig: 'def biggest(a, b, c)',
      starter: 'def biggest(a, b, c):\n    # your code here\n    pass\n',
      examples: [{ in: 'biggest(1, 9, 5)', out: '9' }],
      tests: [
        { call: 'biggest(1, 9, 5)', expect: '9' },
        { call: 'biggest(4, 4, 4)', expect: '4', name: 'all equal' },
        { call: 'biggest(-5, -1, -9)', expect: '-1', name: 'all negative' },
        { call: 'biggest(0, -1, -2)', expect: '0', hidden: true }],
      hint: 'max() takes as many arguments as you like.',
      solution: 'def biggest(a, b, c):\n    return max(a, b, c)\n',
      walk: 'Reaching for the built-in beats writing three comparisons — less code, and no chance of an if-chain that misses a case. Knowing what is already in the language is a real part of the job.',
      complexity: 'O(1).' },

    { id: 'pt-rectangle', group: 'First programs', lvl: 1,
      title: 'Area of a rectangle',
      fn: 'area',
      brief: 'Return the area of a rectangle from its width and height.\n\nIf either measurement is negative, return 0 — a shape cannot have a negative side.',
      sig: 'def area(width, height)',
      starter: 'def area(width, height):\n    # your code here\n    pass\n',
      examples: [{ in: 'area(3, 4)', out: '12' }],
      tests: [
        { call: 'area(3, 4)', expect: '12' },
        { call: 'area(0, 5)', expect: '0' },
        { call: 'area(-2, 5)', expect: '0', name: 'negative side' },
        { call: 'area(2.5, 2)', expect: '5.0', hidden: true }],
      hint: 'Check the bad case first and return early; then the normal case is one clean line.',
      solution: 'def area(width, height):\n    if width < 0 or height < 0:\n        return 0\n    return width * height\n',
      walk: 'Guard clauses — handling the awkward case first and returning immediately — keep the main line of the function unindented and easy to read. That habit scales all the way up to production code.',
      complexity: 'O(1).' },

    { id: 'pt-count-list', group: 'First programs', lvl: 1,
      title: 'How many, and how much',
      fn: 'summary',
      brief: 'Given a list of numbers, return a tuple of (how many there are, their total).\n\nAn empty list gives (0, 0).',
      sig: 'def summary(nums)',
      starter: 'def summary(nums):\n    # your code here\n    pass\n',
      examples: [{ in: 'summary([1, 2, 3])', out: '(3, 6)' }],
      tests: [
        { call: 'summary([1, 2, 3])', expect: '(3, 6)' },
        { call: 'summary([])', expect: '(0, 0)' },
        { call: 'summary([5])', expect: '(1, 5)' },
        { call: 'summary([-1, 1])', expect: '(2, 0)', hidden: true }],
      hint: 'len() counts, sum() adds. Returning two things means returning a tuple: return a, b.',
      solution: 'def summary(nums):\n    return len(nums), sum(nums)\n',
      walk: 'Returning several values really returns one tuple — the brackets are optional. sum([]) is 0 and len([]) is 0, so the empty case needs no special handling.',
      complexity: 'O(n).' },

    { id: 'pt-last-item', group: 'First programs', lvl: 1,
      title: 'The last one',
      fn: 'last',
      brief: 'Return the last item of a list, or None if the list is empty.',
      sig: 'def last(items)',
      starter: 'def last(items):\n    # your code here\n    pass\n',
      examples: [{ in: 'last([1, 2, 3])', out: '3' }],
      tests: [
        { call: 'last([1, 2, 3])', expect: '3' },
        { call: 'last([])', expect: 'None', name: 'nothing there' },
        { call: "last(['only'])", expect: "'only'" },
        { call: 'last([0])', expect: '0', hidden: true, name: 'a zero is still an item' }],
      hint: 'items[-1] is the last one — but check the list is not empty first, or it raises IndexError.',
      solution: 'def last(items):\n    if not items:\n        return None\n    return items[-1]\n',
      walk: 'The line `if not items` is the Python way of asking whether it is empty — an empty list is falsy. The zero test is there to stop you writing `if items[-1]:` and treating a legitimate 0 as nothing.',
      complexity: 'O(1).' },

    { id: 'pt-shout', group: 'First programs', lvl: 1,
      title: 'Shout it',
      fn: 'shout',
      brief: 'Return the text in capitals with an exclamation mark on the end, and no stray spaces round it.\n\n"  hello " becomes "HELLO!".',
      sig: 'def shout(s)',
      starter: 'def shout(s):\n    # your code here\n    pass\n',
      examples: [{ in: "shout('  hello ')", out: "'HELLO!'" }],
      tests: [
        { call: "shout('  hello ')", expect: "'HELLO!'" },
        { call: "shout('hi')", expect: "'HI!'" },
        { call: "shout('')", expect: "'!'", hidden: true },
        { call: "shout('Already Loud')", expect: "'ALREADY LOUD!'", hidden: true }],
      hint: 'Chain the string methods: strip the ends, upper-case it, then add the mark.',
      solution: "def shout(s):\n    return s.strip().upper() + '!'\n",
      walk: 'String methods return NEW strings, so they chain left to right: strip first, then upper, then glue on the mark. Nothing is changed in place — strings are immutable.',
      complexity: 'O(n).' },

    { id: 'pt-celsius', group: 'First programs', lvl: 1,
      title: 'Celsius to Fahrenheit',
      fn: 'to_fahrenheit',
      brief: 'Convert a temperature in Celsius to Fahrenheit, rounded to one decimal place.\n\nThe formula is F = C × 9/5 + 32.',
      sig: 'def to_fahrenheit(c)',
      starter: 'def to_fahrenheit(c):\n    # your code here\n    pass\n',
      examples: [{ in: 'to_fahrenheit(100)', out: '212.0' }],
      tests: [
        { call: 'to_fahrenheit(100)', expect: '212.0' },
        { call: 'to_fahrenheit(0)', expect: '32.0' },
        { call: 'to_fahrenheit(-40)', expect: '-40.0', name: 'the scales cross here' },
        { call: 'to_fahrenheit(37)', expect: '98.6', hidden: true }],
      hint: 'Watch the order of operations: the multiplication happens before the + 32.',
      solution: 'def to_fahrenheit(c):\n    return round(c * 9 / 5 + 32, 1)\n',
      walk: 'Python follows normal arithmetic precedence, so no brackets are needed round the multiplication — but adding them costs nothing and removes the doubt. round(x, 1) keeps the answer to one decimal place.',
      complexity: 'O(1).' },

    { id: 'pt-count-letter', group: 'First programs', lvl: 1,
      title: 'Count a letter',
      fn: 'count_letter',
      brief: 'Count how many times a letter appears in a piece of text, ignoring case.',
      sig: 'def count_letter(text, letter)',
      starter: 'def count_letter(text, letter):\n    # your code here\n    pass\n',
      examples: [{ in: "count_letter('Banana', 'a')", out: '3' }],
      tests: [
        { call: "count_letter('Banana', 'a')", expect: '3' },
        { call: "count_letter('Banana', 'B')", expect: '1', name: 'case ignored' },
        { call: "count_letter('', 'a')", expect: '0' },
        { call: "count_letter('aaa', 'b')", expect: '0', hidden: true }],
      hint: 'Lowercase both sides first, then .count() does the work.',
      solution: 'def count_letter(text, letter):\n    return text.lower().count(letter.lower())\n',
      walk: 'Normalising BOTH sides is the point — lowercasing only the text still fails when the letter arrives capitalised. Doing it in one place, at the start, is a habit worth forming.',
      complexity: 'O(n).' },

    { id: 'pt-sum-loop', group: 'First programs', lvl: 1,
      title: 'Add them up, by hand',
      fn: 'total',
      brief: 'Return the total of a list of numbers — written as a loop, without using sum().\n\nThe point is the shape: a running total that starts at zero and grows.',
      sig: 'def total(nums)',
      starter: 'def total(nums):\n    # your code here — use a loop, not sum()\n    pass\n',
      examples: [{ in: 'total([1, 2, 3])', out: '6' }],
      tests: [
        { call: 'total([1, 2, 3])', expect: '6' },
        { call: 'total([])', expect: '0', name: 'nothing adds to nothing' },
        { call: 'total([-5, 5])', expect: '0' },
        { call: 'total([2.5, 2.5])', expect: '5.0', hidden: true }],
      hint: 'Start a variable at 0 before the loop, add each number to it inside, and return it after the loop ends.',
      solution: 'def total(nums):\n    running = 0\n    for n in nums:\n        running += n\n    return running\n',
      walk: 'Three details matter: the accumulator starts OUTSIDE the loop (inside, it would reset every time), the return is outside too (inside, it would stop after the first number), and starting at 0 makes the empty list work for free.',
      complexity: 'O(n).' },

    { id: 'pt-double-list', group: 'First programs', lvl: 1,
      title: 'Double every number',
      fn: 'double_all',
      brief: 'Return a NEW list with every number doubled. Leave the original list untouched.',
      sig: 'def double_all(nums)',
      starter: 'def double_all(nums):\n    # your code here\n    pass\n',
      examples: [{ in: 'double_all([1, 2, 3])', out: '[2, 4, 6]' }],
      tests: [
        { call: 'double_all([1, 2, 3])', expect: '[2, 4, 6]' },
        { call: 'double_all([])', expect: '[]' },
        { call: 'double_all([-1])', expect: '[-2]' },
        { call: "(lambda src: (double_all(src), src)[1])([1, 2])", expect: '[1, 2]', hidden: true, name: 'the original is unchanged' }],
      hint: 'Build a new list — either append inside a loop, or write it as one comprehension.',
      solution: 'def double_all(nums):\n    return [n * 2 for n in nums]\n',
      walk: 'A list comprehension is the Python way to say "a new list, made from that one". The hidden test checks you built a new list rather than editing the caller\'s — a side effect that causes real bugs later.',
      complexity: 'O(n).' },

    { id: 'pt-grade', group: 'First programs', lvl: 1,
      title: 'Grade a score',
      fn: 'grade',
      brief: 'Turn a score out of 100 into a grade:\n\n· 70 or more → "A"\n· 50 to 69 → "B"\n· below 50 → "C"',
      sig: 'def grade(score)',
      starter: 'def grade(score):\n    # your code here\n    pass\n',
      examples: [{ in: 'grade(85)', out: "'A'" }, { in: 'grade(50)', out: "'B'" }],
      tests: [
        { call: 'grade(85)', expect: "'A'" },
        { call: 'grade(50)', expect: "'B'", name: 'exactly on the boundary' },
        { call: 'grade(49)', expect: "'C'" },
        { call: 'grade(70)', expect: "'A'", hidden: true, name: 'the other boundary' },
        { call: 'grade(0)', expect: "'C'", hidden: true }],
      hint: 'Test the highest band first, then elif for the next one down — once a branch matches, the rest are skipped.',
      solution: "def grade(score):\n    if score >= 70:\n        return 'A'\n    elif score >= 50:\n        return 'B'\n    return 'C'\n",
      walk: 'Ordering from the top down means each elif only has to check its own lower edge. Both boundary tests are deliberate: 50 and 70 are exactly where an if-chain written with > instead of >= goes wrong.',
      complexity: 'O(1).' },

    { id: 'pt-initials', group: 'First programs', lvl: 1,
      title: 'First letter, capitalised',
      fn: 'initial',
      brief: 'Return the first letter of a name as a capital.\n\nAn empty name returns an empty string.',
      sig: 'def initial(name)',
      starter: 'def initial(name):\n    # your code here\n    pass\n',
      examples: [{ in: "initial('ada')", out: "'A'" }],
      tests: [
        { call: "initial('ada')", expect: "'A'" },
        { call: "initial('Bob')", expect: "'B'" },
        { call: "initial('')", expect: "''", name: 'nothing to take' },
        { call: "initial(' ada')", expect: "'A'", hidden: true, name: 'leading space' }],
      hint: 'Strip the spaces first — then, if anything is left, take character 0 and upper-case it.',
      solution: "def initial(name):\n    name = name.strip()\n    if not name:\n        return ''\n    return name[0].upper()\n",
      walk: "name[0] on an empty string raises IndexError, so the guard is not optional. Stripping first is what makes ' ada' give A rather than a space — real names arrive with stray whitespace more often than you would think.",
      complexity: 'O(1).' },

    { id: 'pt-fizz-simple', group: 'First programs', lvl: 1,
      title: 'Divisible by three',
      fn: 'threes',
      brief: 'Return a list of the numbers from 1 to n that divide exactly by 3.',
      sig: 'def threes(n)',
      starter: 'def threes(n):\n    # your code here\n    pass\n',
      examples: [{ in: 'threes(10)', out: '[3, 6, 9]' }],
      tests: [
        { call: 'threes(10)', expect: '[3, 6, 9]' },
        { call: 'threes(2)', expect: '[]', name: 'none yet' },
        { call: 'threes(3)', expect: '[3]', name: 'n itself counts' },
        { call: 'threes(0)', expect: '[]', hidden: true },
        { call: 'len(threes(300))', expect: '100', hidden: true }],
      hint: 'range(1, n + 1) gives 1 up to n inclusive; keep the ones where i % 3 == 0.',
      solution: 'def threes(n):\n    return [i for i in range(1, n + 1) if i % 3 == 0]\n',
      walk: 'range stops BEFORE the number you give it, so n + 1 is what includes n itself — the single most common off-by-one in Python. n of 0 produces an empty range, so it needs no special case.',
      complexity: 'O(n).' },

    { id: 'pt-swap-case', group: 'First programs', lvl: 1,
      title: 'Words in reverse',
      fn: 'last_word',
      brief: 'Return the last word of a sentence.\n\nAn empty sentence returns an empty string.',
      sig: 'def last_word(sentence)',
      starter: 'def last_word(sentence):\n    # your code here\n    pass\n',
      examples: [{ in: "last_word('the sky is blue')", out: "'blue'" }],
      tests: [
        { call: "last_word('the sky is blue')", expect: "'blue'" },
        { call: "last_word('single')", expect: "'single'" },
        { call: "last_word('')", expect: "''" },
        { call: "last_word('  trailing spaces  ')", expect: "'spaces'", hidden: true }],
      hint: 'split() breaks the sentence into a list of words; the last one is at index -1 — but check the list is not empty.',
      solution: "def last_word(sentence):\n    words = sentence.split()\n    if not words:\n        return ''\n    return words[-1]\n",
      walk: "split() with no argument ignores runs of whitespace and drops the empty pieces, so the trailing-spaces case takes care of itself. Naming the intermediate list makes the empty check obvious — one extra line that saves an IndexError.",
      complexity: 'O(n).' }
  );
})();
