/* Python coding test — problem bank 8: machine learning by hand.
   Writing the metric, the split and the classifier yourself in plain Python, so that
   the scikit-learn one-liner later is a shortcut rather than a mystery. These come up
   in data-science interviews far more often than people expect. */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var G = 'Machine learning by hand';

  window.PYTESTS.push(

    { id: 'pt-ml-accuracy', group: G, lvl: 1,
      title: 'Accuracy from scratch',
      fn: 'accuracy',
      brief: 'Given the true labels and the predicted labels, return the share that were right, as a number between 0 and 1.\n\nEmpty inputs return 0.',
      sig: 'def accuracy(y_true, y_pred)',
      starter: 'def accuracy(y_true, y_pred):\n    # your code here\n    pass\n',
      examples: [{ in: 'accuracy([1, 0, 1], [1, 0, 0])', out: '0.6666666666666666', note: 'two out of three' }],
      tests: [
        { call: 'round(accuracy([1, 0, 1], [1, 0, 0]), 4)', expect: '0.6667' },
        { call: 'accuracy([1, 1], [1, 1])', expect: '1.0' },
        { call: 'accuracy([], [])', expect: '0', name: 'nothing to score' },
        { call: 'accuracy([1, 0], [0, 1])', expect: '0.0', hidden: true, name: 'all wrong' },
        { call: "accuracy(['a', 'b'], ['a', 'a'])", expect: '0.5', hidden: true, name: 'labels need not be numbers' }],
      hint: 'zip the two lists together, count the pairs that match, divide by the length.',
      solution: 'def accuracy(y_true, y_pred):\n    if not y_true:\n        return 0\n    right = sum(1 for t, p in zip(y_true, y_pred) if t == p)\n    return right / len(y_true)\n',
      walk: 'zip pairs each truth with its prediction — the standard shape for every metric in this unit. Guard the empty case before dividing. Note that accuracy says nothing about WHICH class you get wrong, which is exactly why the next problems exist.',
      complexity: 'O(n).' },

    { id: 'pt-ml-confusion', group: G, lvl: 2,
      title: 'The confusion matrix',
      fn: 'confusion',
      brief: 'For binary labels of 1 (positive) and 0 (negative), return a dict with the four counts: "tp", "fp", "tn", "fn".\n\nA true positive is predicted 1 and truly 1; a false positive is predicted 1 but truly 0.',
      sig: 'def confusion(y_true, y_pred)',
      starter: 'def confusion(y_true, y_pred):\n    # your code here\n    pass\n',
      examples: [{ in: 'confusion([1, 0, 1, 0], [1, 1, 0, 0])', out: "{'tp': 1, 'fp': 1, 'tn': 1, 'fn': 1}" }],
      tests: [
        { call: 'confusion([1, 0, 1, 0], [1, 1, 0, 0])', expect: "{'tp': 1, 'fp': 1, 'tn': 1, 'fn': 1}" },
        { call: 'confusion([], [])', expect: "{'tp': 0, 'fp': 0, 'tn': 0, 'fn': 0}" },
        { call: "confusion([1, 1], [1, 1])['tp']", expect: '2' },
        { call: "confusion([0, 0], [1, 1])['fp']", expect: '2', hidden: true },
        { call: "sum(confusion([1, 0, 1, 0, 1], [1, 1, 0, 0, 1]).values())", expect: '5', hidden: true, name: 'the four counts must total the rows' }],
      hint: 'Four counters and one loop over the pairs. The name says predicted first: a false POSITIVE was predicted positive.',
      solution: "def confusion(y_true, y_pred):\n    counts = {'tp': 0, 'fp': 0, 'tn': 0, 'fn': 0}\n    for t, p in zip(y_true, y_pred):\n        if p == 1 and t == 1:\n            counts['tp'] += 1\n        elif p == 1 and t == 0:\n            counts['fp'] += 1\n        elif p == 0 and t == 0:\n            counts['tn'] += 1\n        else:\n            counts['fn'] += 1\n    return counts\n",
      walk: 'Everything else in classification is built from these four numbers. The way to keep them straight: the second word is what you PREDICTED, the first says whether you were right. The last hidden test is the sanity check worth running on any confusion matrix you write — the four counts must add up to the number of rows.',
      complexity: 'O(n).' },

    { id: 'pt-ml-precision-recall', group: G, lvl: 2,
      title: 'Precision and recall',
      fn: 'precision_recall',
      brief: 'Return a tuple of (precision, recall) for binary labels.\n\nPrecision is tp / (tp + fp) — of the ones you flagged, how many were right. Recall is tp / (tp + fn) — of the ones that mattered, how many you caught. When the denominator is zero, that score is 0.',
      sig: 'def precision_recall(y_true, y_pred)',
      starter: 'def precision_recall(y_true, y_pred):\n    # your code here\n    pass\n',
      examples: [{ in: 'precision_recall([1, 0, 1, 0], [1, 1, 0, 0])', out: '(0.5, 0.5)' }],
      tests: [
        { call: 'precision_recall([1, 0, 1, 0], [1, 1, 0, 0])', expect: '(0.5, 0.5)' },
        { call: 'precision_recall([1, 1], [1, 1])', expect: '(1.0, 1.0)' },
        { call: 'precision_recall([1, 1], [0, 0])', expect: '(0, 0.0)', name: 'nothing flagged at all' },
        { call: 'precision_recall([0, 0], [0, 0])', expect: '(0, 0)', hidden: true, name: 'no positives anywhere' },
        { call: 'round(precision_recall([1, 1, 1, 0], [1, 0, 0, 1])[0], 4)', expect: '0.5', hidden: true }],
      hint: 'Count tp, fp and fn first, then guard each division separately — the two denominators can be zero independently.',
      solution: 'def precision_recall(y_true, y_pred):\n    tp = sum(1 for t, p in zip(y_true, y_pred) if t == 1 and p == 1)\n    fp = sum(1 for t, p in zip(y_true, y_pred) if t == 0 and p == 1)\n    fn = sum(1 for t, p in zip(y_true, y_pred) if t == 1 and p == 0)\n    precision = tp / (tp + fp) if (tp + fp) else 0\n    recall = tp / (tp + fn) if (tp + fn) else 0\n    return precision, recall\n',
      walk: 'A model that never predicts positive has no precision to speak of — the denominator is zero, which is why the guard is not optional. That degenerate case is exactly what a "99% accurate" fraud model looks like from the inside.',
      complexity: 'O(n).' },

    { id: 'pt-ml-f1', group: G, lvl: 2,
      title: 'The F1 score',
      fn: 'f1',
      brief: 'Return the F1 score: the harmonic mean of precision and recall, 2·p·r / (p + r).\n\nIf both are zero, return 0.',
      sig: 'def f1(precision, recall)',
      starter: 'def f1(precision, recall):\n    # your code here\n    pass\n',
      examples: [{ in: 'f1(0.5, 0.5)', out: '0.5' }],
      tests: [
        { call: 'f1(0.5, 0.5)', expect: '0.5' },
        { call: 'f1(1.0, 1.0)', expect: '1.0' },
        { call: 'f1(0, 0)', expect: '0', name: 'both zero' },
        { call: 'round(f1(1.0, 0.0), 4)', expect: '0.0', hidden: true, name: 'perfect precision, no recall' },
        { call: 'round(f1(0.8, 0.4), 4)', expect: '0.5333', hidden: true }],
      hint: 'Guard the p + r == 0 case, then one line of arithmetic.',
      solution: 'def f1(precision, recall):\n    if precision + recall == 0:\n        return 0\n    return 2 * precision * recall / (precision + recall)\n',
      walk: 'The harmonic mean punishes imbalance: precision 1.0 with recall 0.0 gives an F1 of 0, where a plain average would have said 0.5. That is the whole point of using it — a model that catches one fraud perfectly and misses the other thousand is not half-good.',
      complexity: 'O(1).' },

    { id: 'pt-ml-split', group: G, lvl: 2,
      title: 'Train/test split by hand',
      fn: 'split',
      brief: 'Split a list of rows into (train, test) where the LAST fraction goes to test.\n\nA test_size of 0.2 on 10 rows gives 8 train and 2 test. Round the test count down, and always keep at least one row in each side when there are two or more rows.',
      sig: 'def split(rows, test_size)',
      starter: 'def split(rows, test_size):\n    # your code here\n    pass\n',
      examples: [{ in: 'split([1,2,3,4,5,6,7,8,9,10], 0.2)', out: '([1,2,3,4,5,6,7,8], [9, 10])' }],
      tests: [
        { call: 'split([1,2,3,4,5,6,7,8,9,10], 0.2)', expect: '([1,2,3,4,5,6,7,8], [9, 10])' },
        { call: 'split([1, 2], 0.5)', expect: '([1], [2])' },
        { call: 'split([], 0.2)', expect: '([], [])' },
        { call: 'len(split(list(range(100)), 0.3)[1])', expect: '30', hidden: true },
        { call: 'len(split([1, 2, 3], 0.01)[1])', expect: '1', hidden: true, name: 'at least one row in test' }],
      hint: 'The cut point is len(rows) - int(len(rows) * test_size), then two slices — but clamp it so neither side is empty.',
      solution: 'def split(rows, test_size):\n    n = len(rows)\n    if n == 0:\n        return [], []\n    n_test = int(n * test_size)\n    if n >= 2:\n        n_test = max(1, min(n - 1, n_test))\n    cut = n - n_test\n    return rows[:cut], rows[cut:]\n',
      walk: 'The real train_test_split shuffles first, which matters enormously — a file sorted by date or by class would otherwise give you a test set that is nothing like the training set. Here the point is the arithmetic and the clamp: a split that hands back an empty test set is a bug that quietly reports a perfect score.',
      complexity: 'O(n) for the slices.' },

    { id: 'pt-ml-standardise', group: G, lvl: 2,
      title: 'Standardise a column',
      fn: 'standardise',
      brief: 'Rescale a list of numbers to have a mean of 0 and a standard deviation of 1 — the z-score of each value.\n\nUse the population standard deviation (divide by n). If every value is the same, return a list of zeros.',
      sig: 'def standardise(nums)',
      starter: 'def standardise(nums):\n    # your code here\n    pass\n',
      examples: [{ in: 'standardise([1, 2, 3])', out: '[-1.2247, 0.0, 1.2247]' }],
      tests: [
        { call: '[round(x, 4) for x in standardise([1, 2, 3])]', expect: '[-1.2247, 0.0, 1.2247]' },
        { call: 'standardise([5, 5, 5])', expect: '[0.0, 0.0, 0.0]', name: 'no spread — must not divide by zero' },
        { call: 'standardise([])', expect: '[]' },
        { call: 'round(sum(standardise([2, 4, 6, 8])), 6)', expect: '0.0', hidden: true, name: 'z-scores sum to zero' },
        { call: '[round(x, 4) for x in standardise([0, 10])]', expect: '[-1.0, 1.0]', hidden: true }],
      hint: 'Mean first, then the standard deviation, then (x - mean) / sd for each value — with the zero-spread case guarded.',
      solution: 'def standardise(nums):\n    n = len(nums)\n    if n == 0:\n        return []\n    mean = sum(nums) / n\n    sd = (sum((x - mean) ** 2 for x in nums) / n) ** 0.5\n    if sd == 0:\n        return [0.0] * n\n    return [(x - mean) / sd for x in nums]\n',
      walk: 'This is what StandardScaler does. The constant-column case is the trap — real datasets are full of columns with one value, and dividing by a zero spread raises. In a pipeline you would learn the mean and sd from the training set only, and apply those same two numbers to the test set.',
      complexity: 'O(n).' },

    { id: 'pt-ml-distance', group: G, lvl: 1,
      title: 'Euclidean distance',
      fn: 'distance',
      brief: 'Return the straight-line distance between two points, given as lists of coordinates of the same length.',
      sig: 'def distance(a, b)',
      starter: 'def distance(a, b):\n    # your code here\n    pass\n',
      examples: [{ in: 'distance([0, 0], [3, 4])', out: '5.0' }],
      tests: [
        { call: 'distance([0, 0], [3, 4])', expect: '5.0' },
        { call: 'distance([1, 2, 3], [1, 2, 3])', expect: '0.0', name: 'same point' },
        { call: 'distance([], [])', expect: '0.0' },
        { call: 'round(distance([1, 1], [2, 2]), 4)', expect: '1.4142', hidden: true },
        { call: 'distance([0], [-3])', expect: '3.0', hidden: true, name: 'sign does not matter' }],
      hint: 'Square the differences, add them up, take the square root. zip pairs the coordinates for you.',
      solution: 'def distance(a, b):\n    return sum((x - y) ** 2 for x, y in zip(a, b)) ** 0.5\n',
      walk: 'Squaring removes the sign, which is why the last test works. This one line is the whole basis of k-Nearest Neighbours and k-Means — and the reason both need their features scaled first: a column measured in thousands drowns out a column measured in units.',
      complexity: 'O(d) in the number of dimensions.' },

    { id: 'pt-ml-knn', group: G, lvl: 3,
      title: 'k-Nearest Neighbours, by hand',
      fn: 'knn_predict',
      brief: 'Given training points, their labels, one new point and a k, return the majority label among the k nearest training points.\n\nBreak ties in the vote by choosing the label that comes first alphabetically. Distance is straight-line.',
      sig: 'def knn_predict(X, y, point, k)',
      starter: 'def knn_predict(X, y, point, k):\n    # your code here\n    pass\n',
      examples: [{ in: "knn_predict([[0], [1], [10]], ['a', 'a', 'b'], [0.5], 2)", out: "'a'" }],
      tests: [
        { call: "knn_predict([[0], [1], [10]], ['a', 'a', 'b'], [0.5], 2)", expect: "'a'" },
        { call: "knn_predict([[0], [10]], ['a', 'b'], [9], 1)", expect: "'b'", name: 'k = 1 takes the nearest' },
        { call: "knn_predict([[0], [1]], ['b', 'a'], [0.5], 2)", expect: "'a'", name: 'tie broken alphabetically' },
        { call: "knn_predict([[0, 0], [3, 4]], ['x', 'y'], [0, 1], 1)", expect: "'x'", hidden: true, name: 'two dimensions' },
        { call: "knn_predict([[0], [1], [2]], ['a', 'b', 'b'], [1.4], 3)", expect: "'b'", hidden: true, name: 'k larger than the nearest group' }],
      hint: 'Pair each training point with its distance, sort by distance, take the first k labels, then count them.',
      solution: "from collections import Counter\n\ndef knn_predict(X, y, point, k):\n    def dist(p):\n        return sum((a - b) ** 2 for a, b in zip(p, point)) ** 0.5\n    pairs = sorted(zip(X, y), key=lambda pair: dist(pair[0]))\n    labels = [label for _, label in pairs[:k]]\n    counts = Counter(labels)\n    best = max(counts.values())\n    return sorted(l for l in counts if counts[l] == best)[0]\n",
      walk: 'The whole algorithm: measure, sort, vote. "Fitting" a k-NN stores the training data and nothing else — all the work happens at prediction time, which is why it is slow to predict and instant to train. The tie-break has to be stated, because `Counter.most_common` would otherwise decide it by insertion order.',
      complexity: 'O(n log n) per prediction from the sort — O(n) with a heap.' },

    { id: 'pt-ml-majority', group: G, lvl: 1,
      title: 'The baseline everyone must beat',
      fn: 'baseline_accuracy',
      brief: 'A "most frequent class" model predicts the commonest label for every row. Return the accuracy that model would score on the given labels.\n\nEmpty input returns 0.',
      sig: 'def baseline_accuracy(y)',
      starter: 'def baseline_accuracy(y):\n    # your code here\n    pass\n',
      examples: [{ in: 'baseline_accuracy([1, 1, 1, 0])', out: '0.75' }],
      tests: [
        { call: 'baseline_accuracy([1, 1, 1, 0])', expect: '0.75' },
        { call: 'baseline_accuracy([])', expect: '0' },
        { call: "baseline_accuracy(['a', 'b'])", expect: '0.5', name: 'a perfect tie' },
        { call: 'baseline_accuracy([0] * 99 + [1])', expect: '0.99', hidden: true, name: 'the imbalanced-data trap' },
        { call: 'baseline_accuracy([1])', expect: '1.0', hidden: true }],
      hint: 'The accuracy of always guessing the commonest label is simply its share of the rows.',
      solution: 'from collections import Counter\n\ndef baseline_accuracy(y):\n    if not y:\n        return 0\n    return Counter(y).most_common(1)[0][1] / len(y)\n',
      walk: 'This number is the one your model has to beat, and the hidden test shows why it matters: on data that is 99% one class, a model that has learned nothing at all scores 99%. Quote the baseline next to every accuracy you report.',
      complexity: 'O(n).' },

    { id: 'pt-ml-mae', group: G, lvl: 1,
      title: 'Mean absolute error',
      fn: 'mae',
      brief: 'Return the mean absolute error between the true values and the predictions — the average size of the mistake, ignoring direction.\n\nEmpty input returns 0.',
      sig: 'def mae(y_true, y_pred)',
      starter: 'def mae(y_true, y_pred):\n    # your code here\n    pass\n',
      examples: [{ in: 'mae([10, 20], [12, 18])', out: '2.0' }],
      tests: [
        { call: 'mae([10, 20], [12, 18])', expect: '2.0' },
        { call: 'mae([5], [5])', expect: '0.0' },
        { call: 'mae([], [])', expect: '0' },
        { call: 'mae([0, 0], [-3, 3])', expect: '3.0', hidden: true, name: 'errors must not cancel out' },
        { call: 'round(mae([1, 2, 3], [1, 2, 10]), 4)', expect: '2.3333', hidden: true }],
      hint: 'abs() on each difference, then the mean. Without abs, the errors cancel and you measure bias instead.',
      solution: 'def mae(y_true, y_pred):\n    if not y_true:\n        return 0\n    return sum(abs(t - p) for t, p in zip(y_true, y_pred)) / len(y_true)\n',
      walk: 'MAE is in the units of the target, which makes it the easiest regression metric to explain to a stakeholder: "we are out by £2 on average". RMSE squares the errors first, so one terrible prediction moves it far more — which one you report is a judgement about what a big miss costs.',
      complexity: 'O(n).' },

    { id: 'pt-ml-gini', group: G, lvl: 3,
      title: 'Gini impurity',
      fn: 'gini',
      brief: 'Return the Gini impurity of a list of labels: 1 minus the sum of each class\'s squared share.\n\nA pure group (all one label) is 0. An empty list is 0.',
      sig: 'def gini(labels)',
      starter: 'def gini(labels):\n    # your code here\n    pass\n',
      examples: [{ in: "gini(['a', 'a', 'b', 'b'])", out: '0.5' }],
      tests: [
        { call: "gini(['a', 'a', 'b', 'b'])", expect: '0.5' },
        { call: "gini(['a', 'a'])", expect: '0.0', name: 'pure group' },
        { call: 'gini([])', expect: '0' },
        { call: "round(gini(['a', 'b', 'c']), 4)", expect: '0.6667', hidden: true, name: 'three equal classes' },
        { call: "round(gini(['a'] * 9 + ['b']), 4)", expect: '0.18', hidden: true }],
      hint: 'Count each label, turn the counts into shares, and subtract the sum of their squares from 1.',
      solution: 'from collections import Counter\n\ndef gini(labels):\n    n = len(labels)\n    if n == 0:\n        return 0\n    counts = Counter(labels)\n    return 1 - sum((c / n) ** 2 for c in counts.values())\n',
      walk: 'This is the number a decision tree minimises: at every split it tries to make the two sides purer than the parent. 0 means "all one class" and the maximum approaches 1 as the classes multiply and even out — 0.5 for two equal classes, 0.667 for three.',
      complexity: 'O(n).' },

    { id: 'pt-ml-crossval-folds', group: G, lvl: 3,
      title: 'Make the cross-validation folds',
      fn: 'folds',
      brief: 'Split the numbers 0 to n-1 into k folds of as-equal size as possible, in order, and return them as a list of lists.\n\nEarlier folds take the spare rows. If k is 0 or bigger than n, return an empty list.',
      sig: 'def folds(n, k)',
      starter: 'def folds(n, k):\n    # your code here\n    pass\n',
      examples: [{ in: 'folds(6, 3)', out: '[[0, 1], [2, 3], [4, 5]]' }, { in: 'folds(7, 3)', out: '[[0, 1, 2], [3, 4], [5, 6]]' }],
      tests: [
        { call: 'folds(6, 3)', expect: '[[0, 1], [2, 3], [4, 5]]' },
        { call: 'folds(7, 3)', expect: '[[0, 1, 2], [3, 4], [5, 6]]' },
        { call: 'folds(5, 0)', expect: '[]', name: 'k of zero' },
        { call: 'folds(2, 5)', expect: '[]', hidden: true, name: 'more folds than rows' },
        { call: '[len(f) for f in folds(10, 4)]', expect: '[3, 3, 2, 2]', hidden: true, name: 'the spare rows go early' }],
      hint: 'Every fold gets n // k rows, and the first n % k folds get one extra. Walk a cursor along and slice.',
      solution: 'def folds(n, k):\n    if k <= 0 or k > n:\n        return []\n    base, spare = n // k, n % k\n    out = []\n    start = 0\n    for i in range(k):\n        size = base + (1 if i < spare else 0)\n        out.append(list(range(start, start + size)))\n        start += size\n    return out\n',
      walk: 'This is what KFold does before the shuffling and stratifying. The arithmetic — a base size plus one extra for the first few folds — is the part worth being able to write; it is the same reasoning as sharing 7 items between 3 people.',
      complexity: 'O(n).' }
  );
})();
