/* The Python side of the coding-test runner.

   One string, defined once and executed inside Pyodide the first time Python starts.
   It defines _ds_run(user_code, cases_json, opts_json) -> JSON string:

     { ok, error, stdout, results: [ {call, expect, got, pass, error, hidden, name} ] }

   Rules it enforces so the marking is fair:
     · the candidate's code runs in its own namespace, with stdout captured
     · every test case is evaluated separately, so one failure does not hide the rest
     · floats compare with a tolerance, and lists/sets can compare order-insensitively
     · a wall-clock budget stops an infinite loop taking the browser tab with it

   Kept in its own file (not inside app.js) so the Python reads as Python. */
(function () {
  window.PYHARNESS = [
    'import sys, io, json, time, math, traceback',
    '',
    'class _DSTimeout(Exception):',
    '    pass',
    '',
    'def _ds_fmt(v):',
    '    """A short, readable repr for the results table."""',
    '    try:',
    '        s = repr(v)',
    '    except Exception:',
    '        s = "<unprintable>"',
    '    return s if len(s) <= 300 else s[:297] + "..."',
    '',
    'def _ds_eq(got, exp, unordered=False, tol=1e-06):',
    '    """Equality that forgives float noise and, when asked, ordering."""',
    '    if isinstance(got, bool) or isinstance(exp, bool):',
    '        return got is exp',
    '    if isinstance(got, float) or isinstance(exp, float):',
    '        try:',
    '            if math.isnan(got) and math.isnan(exp):',
    '                return True',
    '            return abs(got - exp) <= max(tol, tol * abs(exp))',
    '        except TypeError:',
    '            return False',
    '    if isinstance(exp, (list, tuple)) and isinstance(got, (list, tuple)):',
    '        if len(got) != len(exp):',
    '            return False',
    '        a, b = list(got), list(exp)',
    '        if unordered:',
    '            try:',
    '                a, b = sorted(a, key=repr), sorted(b, key=repr)',
    '            except Exception:',
    '                pass',
    '        return all(_ds_eq(x, y, unordered, tol) for x, y in zip(a, b))',
    '    if isinstance(exp, dict) and isinstance(got, dict):',
    '        if set(got.keys()) != set(exp.keys()):',
    '            return False',
    '        return all(_ds_eq(got[k], exp[k], unordered, tol) for k in exp)',
    '    if isinstance(exp, set) and isinstance(got, (set, frozenset)):',
    '        return set(got) == set(exp)',
    '    try:',
    '        return bool(got == exp)',
    '    except Exception:',
    '        return False',
    '',
    'def _ds_clean_error(exc, user_code):',
    '    """Report the candidate\'s own line, not the harness\'s."""',
    '    kind = type(exc).__name__',
    '    msg = str(exc)',
    '    line = None',
    '    if isinstance(exc, SyntaxError) and exc.lineno:',
    '        line = exc.lineno',
    '    else:',
    '        tb = exc.__traceback__',
    '        while tb is not None:',
    '            if tb.tb_frame.f_code.co_filename == "<candidate>":',
    '                line = tb.tb_lineno',
    '            tb = tb.tb_next',
    '    out = kind + ": " + msg',
    '    if line:',
    '        src = user_code.split("\\n")',
    '        text = src[line - 1].strip() if 0 < line <= len(src) else ""',
    '        out += "  (line " + str(line) + ("  ->  " + text if text else "") + ")"',
    '    return out',
    '',
    'def _ds_run(user_code, cases_json, opts_json="{}"):',
    '    cases = json.loads(cases_json)',
    '    opts = json.loads(opts_json)',
    '    unordered = bool(opts.get("unordered"))',
    '    tol = float(opts.get("tol", 1e-06))',
    '    budget = float(opts.get("budget", 10.0))',
    '    out = {"ok": False, "error": None, "stdout": "", "results": []}',
    '    buf = io.StringIO()',
    '    real_stdout = sys.stdout',
    '    deadline = time.time() + budget',
    '    counter = [0]',
    '',
    '    def guard(frame, event, arg):',
    '        counter[0] += 1',
    '        if counter[0] % 4000 == 0 and time.time() > deadline:',
    '            raise _DSTimeout("over budget")',
    '        return guard',
    '',
    '    ns = {"__name__": "__candidate__"}',
    '    sys.stdout = buf',
    '    try:',
    '        try:',
    '            code_obj = compile(user_code, "<candidate>", "exec")',
    '        except SyntaxError as e:',
    '            out["error"] = _ds_clean_error(e, user_code)',
    '            return json.dumps(out)',
    '        sys.settrace(guard)',
    '        try:',
    '            exec(code_obj, ns)',
    '        except _DSTimeout:',
    '            out["error"] = "Timed out: your code ran for more than " + str(int(budget)) + " seconds. Look for a loop that never ends."',
    '            return json.dumps(out)',
    '        except Exception as e:',
    '            out["error"] = _ds_clean_error(e, user_code)',
    '            return json.dumps(out)',
    '        for c in cases:',
    '            row = {"call": c.get("call", ""), "name": c.get("name", ""),',
    '                   "expect": c.get("expect", ""), "hidden": bool(c.get("hidden")),',
    '                   "got": None, "pass": False, "error": None}',
    '            try:',
    '                got = eval(c["call"], ns)',
    '                exp = eval(c["expect"], dict(ns))',
    '                row["got"] = _ds_fmt(got)',
    '                row["expect"] = _ds_fmt(exp)',
    '                row["pass"] = _ds_eq(got, exp, c.get("unordered", unordered), tol)',
    '            except _DSTimeout:',
    '                row["error"] = "timed out"',
    '                out["results"].append(row)',
    '                out["error"] = "Timed out while running the tests — check for a loop that never ends."',
    '                return json.dumps(out)',
    '            except Exception as e:',
    '                row["error"] = _ds_clean_error(e, user_code)',
    '            out["results"].append(row)',
    '        out["ok"] = True',
    '    except Exception:',
    '        out["error"] = "The runner hit a problem:\\n" + traceback.format_exc()',
    '    finally:',
    '        sys.settrace(None)',
    '        sys.stdout = real_stdout',
    '        text = buf.getvalue()',
    '        out["stdout"] = text if len(text) <= 4000 else text[:4000] + "\\n… (output truncated)"',
    '    return json.dumps(out)',
    ''
  ].join('\n');
})();
