/* Coding problems, the first rung — even smaller than "one step at a time".
   Nothing here needs more than one line of thought, and several are the same
   problem as the one before with a single word changed. */
(function () {
  window.PYTESTS = window.PYTESTS || [];
  var G = 'First rung';

  function P(id, title, fn, brief, sig, starter, examples, tests, hint, solution, walk) {
    // Warm-ups, not test questions — a timed sitting should not open with "give back hello".
    window.PYTESTS.push({ id: id, group: G, lvl: 1, title: title, fn: fn, brief: brief, sig: sig,
      starter: starter, examples: examples, tests: tests, hint: hint, solution: solution, walk: walk,
      warmup: true, complexity: 'O(1) — one step, whatever the input.' });
  }

  P('r-give-word', 'Give back a word', 'word',
    'Write a function called word that takes nothing and gives back the text hello.',
    'def word() -> str',
    'def word():\n    # your code here\n    pass\n',
    [{ in: 'word()', out: "'hello'" }],
    [{ call: 'word()', expect: "'hello'" },
     { call: 'len(word())', expect: '5', name: 'five letters, no spaces' },
     { call: 'word().upper()', expect: "'HELLO'" },
     { call: "type(word()).__name__", expect: "'str'", hidden: true, name: 'text, not a number' },
     { call: "word() == 'hello'", expect: 'True', hidden: true }],
    "return 'hello' — with the quotes.",
    "def word():\n    return 'hello'\n",
    "The same shape as returning a number, with text instead. The quotes are what make it text; without them Python looks for a variable called hello.");

  P('r-give-true', 'Give back True', 'yes',
    'Write a function called yes that takes nothing and gives back True.',
    'def yes() -> bool',
    'def yes():\n    # your code here\n    pass\n',
    [{ in: 'yes()', out: 'True' }],
    [{ call: 'yes()', expect: 'True' },
     { call: 'not yes()', expect: 'False' },
     { call: 'yes() and yes()', expect: 'True' },
     { call: "type(yes()).__name__", expect: "'bool'", hidden: true },
     { call: "yes() == 'True'", expect: 'False', hidden: true, name: 'True is not the word True' }],
    'return True — a capital T, and no quotes.',
    'def yes():\n    return True\n',
    "True and False are values in their own right, spelled with capitals and no quotes. The hidden test is the lesson: the TEXT 'True' is a different thing entirely.");

  P('r-add-three', 'Add three numbers', 'add3',
    'Write a function called add3 that takes three numbers and gives back their total.',
    'def add3(a: int, b: int, c: int) -> int',
    'def add3(a, b, c):\n    # your code here\n    pass\n',
    [{ in: 'add3(1, 2, 3)', out: '6' }],
    [{ call: 'add3(1, 2, 3)', expect: '6' },
     { call: 'add3(0, 0, 0)', expect: '0' },
     { call: 'add3(-1, 1, 5)', expect: '5', name: 'negatives cancel' },
     { call: 'add3(10, 20, 30)', expect: '60', hidden: true },
     { call: 'add3(1.5, 1.5, 1)', expect: '4.0', hidden: true }],
    'Three names in the brackets, and add all three.',
    'def add3(a, b, c):\n    return a + b + c\n',
    'One more parameter than the two-number version. They arrive in the order they were written, so add3(1, 2, 3) puts 1 in a, 2 in b and 3 in c.');

  P('r-half', 'Half of a number', 'half',
    'Write a function called half that gives back half of the number it is given.',
    'def half(n: float) -> float',
    'def half(n):\n    # your code here\n    pass\n',
    [{ in: 'half(10)', out: '5.0' }],
    [{ call: 'half(10)', expect: '5.0' },
     { call: 'half(0)', expect: '0.0' },
     { call: 'half(7)', expect: '3.5', name: 'not always a whole number' },
     { call: 'half(-4)', expect: '-2.0', hidden: true },
     { call: 'half(1)', expect: '0.5', hidden: true }],
    'Divide by 2 with a single slash.',
    'def half(n):\n    return n / 2\n',
    'A single slash always gives a decimal, which is why 10 comes back as 5.0. Two slashes would throw the half away and give 3 for 7.');

  P('r-tenth', 'Ten percent of it', 'tenth',
    'Write a function called tenth that gives back 10 percent of the number it is given.',
    'def tenth(n: float) -> float',
    'def tenth(n):\n    # your code here\n    pass\n',
    [{ in: 'tenth(200)', out: '20.0' }],
    [{ call: 'tenth(200)', expect: '20.0' },
     { call: 'tenth(0)', expect: '0.0' },
     { call: 'tenth(55)', expect: '5.5' },
     { call: 'tenth(1)', expect: '0.1', hidden: true },
     { call: 'tenth(-10)', expect: '-1.0', hidden: true }],
    '10 percent is a tenth: divide by 10, or multiply by 0.1.',
    'def tenth(n):\n    return n / 10\n',
    'Percentages are just fractions: 10% is 10 out of 100, which is a tenth. Once that clicks, VAT and discounts are the same one-liner with a different number.');

  P('r-is-negative', 'Below zero', 'is_negative',
    'Write a function called is_negative that gives back True when the number is below zero.',
    'def is_negative(n: float) -> bool',
    'def is_negative(n):\n    # your code here\n    pass\n',
    [{ in: 'is_negative(-3)', out: 'True' }],
    [{ call: 'is_negative(-3)', expect: 'True' },
     { call: 'is_negative(3)', expect: 'False' },
     { call: 'is_negative(0)', expect: 'False', name: 'zero is not below zero' },
     { call: 'is_negative(-0.1)', expect: 'True', hidden: true },
     { call: 'is_negative(-0)', expect: 'False', hidden: true, name: 'minus zero is still zero' }],
    'return n < 0',
    'def is_negative(n):\n    return n < 0\n',
    'The comparison IS the answer — no if needed. The zero tests are there because < and <= differ by exactly one case, and that case turns up constantly.');

  P('r-is-zero', 'Exactly zero', 'is_zero',
    'Write a function called is_zero that gives back True only when the number is exactly 0.',
    'def is_zero(n: float) -> bool',
    'def is_zero(n):\n    # your code here\n    pass\n',
    [{ in: 'is_zero(0)', out: 'True' }],
    [{ call: 'is_zero(0)', expect: 'True' },
     { call: 'is_zero(1)', expect: 'False' },
     { call: 'is_zero(-1)', expect: 'False' },
     { call: 'is_zero(0.0)', expect: 'True', hidden: true, name: '0.0 is still zero' },
     { call: 'is_zero(0.1)', expect: 'False', hidden: true }],
    'Two equals signs ask the question: n == 0.',
    'def is_zero(n):\n    return n == 0\n',
    'One equals sign would try to STORE 0 in n, which is a syntax error inside a return. Two equals signs ask whether they are the same.');

  P('r-third-item', 'The third item', 'third',
    'Write a function called third that gives back the third item of a list.\n\nYou can assume the list has at least three items.',
    'def third(items: list)',
    'def third(items):\n    # your code here\n    pass\n',
    [{ in: 'third([10, 20, 30])', out: '30' }],
    [{ call: 'third([10, 20, 30])', expect: '30' },
     { call: "third(['a', 'b', 'c', 'd'])", expect: "'c'", name: 'the third, not the last' },
     { call: 'third([1, 2, 3])', expect: '3' },
     { call: 'third(list(range(10)))', expect: '2', hidden: true },
     { call: 'third([[1], [2], [3]])', expect: '[3]', hidden: true }],
    'Counting from zero, the third item is at position 2.',
    'def third(items):\n    return items[2]\n',
    'Zero, one, two — so the third item is items[2]. The four-item test is the one that catches anybody who reached for items[-1] instead.');

  P('r-first-two', 'The first two items', 'first_two',
    'Write a function called first_two that gives back a list of the first two items.\n\nA shorter list comes back as it is.',
    'def first_two(items: list) -> list',
    'def first_two(items):\n    # your code here\n    pass\n',
    [{ in: 'first_two([1, 2, 3, 4])', out: '[1, 2]' }],
    [{ call: 'first_two([1, 2, 3, 4])', expect: '[1, 2]' },
     { call: 'first_two([9])', expect: '[9]', name: 'a short list is fine' },
     { call: 'first_two([])', expect: '[]' },
     { call: "first_two(['a', 'b', 'c'])", expect: "['a', 'b']", hidden: true },
     { call: 'first_two([1, 2])', expect: '[1, 2]', hidden: true }],
    'A slice: items[:2] takes up to but not including position 2.',
    'def first_two(items):\n    return items[:2]\n',
    'Slicing past the end of a list is safe in Python, which is why the one-item and empty cases need no special handling at all. That is unusual and worth remembering.');

  P('r-count-x', 'How many times does it appear', 'count_of',
    'Write a function called count_of that counts how many times a value appears in a list.',
    'def count_of(items: list, value) -> int',
    'def count_of(items, value):\n    # your code here\n    pass\n',
    [{ in: 'count_of([1, 2, 1], 1)', out: '2' }],
    [{ call: 'count_of([1, 2, 1], 1)', expect: '2' },
     { call: 'count_of([1, 2, 3], 9)', expect: '0', name: 'not there at all' },
     { call: 'count_of([], 1)', expect: '0' },
     { call: "count_of(['a', 'b', 'a', 'a'], 'a')", expect: '3', hidden: true },
     { call: "count_of([1, '1'], 1)", expect: '1', hidden: true, name: 'the text 1 is a different value' }],
    'Lists have a .count() method that takes the value.',
    'def count_of(items, value):\n    return items.count(value)\n',
    "One method does the whole job. The hidden test is the reminder that 1 and '1' are different values, so they are counted separately.");

  P('r-add-item', 'Put one on the end', 'with_item',
    'Write a function called with_item that gives back a NEW list with the value added on the end.\n\nThe list you were given must not change.',
    'def with_item(items: list, value) -> list',
    'def with_item(items, value):\n    # your code here\n    pass\n',
    [{ in: 'with_item([1, 2], 3)', out: '[1, 2, 3]' }],
    [{ call: 'with_item([1, 2], 3)', expect: '[1, 2, 3]' },
     { call: "with_item([], 'a')", expect: "['a']", name: 'starting from nothing' },
     { call: '_unchanged()', expect: 'True', name: 'the original is untouched' },
     { call: 'with_item([1], 1)', expect: '[1, 1]', hidden: true, name: 'duplicates are fine' },
     { call: "with_item(['x'], 'y')", expect: "['x', 'y']", hidden: true }],
    'items + [value] builds a new list; .append would change the one you were given.',
    'def with_item(items, value):\n    return items + [value]\n',
    'Adding two lists makes a third. `.append` changes the caller\'s list in place, which the third test is watching for — and which is a real bug when the caller did not expect it.');
  window.PYTESTS[window.PYTESTS.length - 1].setup = 'def _unchanged():\n    given = [1, 2]\n    with_item(given, 3)\n    return given == [1, 2]\n';

  P('r-join-two', 'Join two words', 'join_two',
    'Write a function called join_two that joins two words with a single space between them.',
    'def join_two(a: str, b: str) -> str',
    'def join_two(a, b):\n    # your code here\n    pass\n',
    [{ in: "join_two('hello', 'there')", out: "'hello there'" }],
    [{ call: "join_two('hello', 'there')", expect: "'hello there'" },
     { call: "join_two('a', 'b')", expect: "'a b'" },
     { call: "join_two('', 'x')", expect: "' x'", name: 'the space is still there' },
     { call: "len(join_two('ab', 'cd'))", expect: '5', hidden: true, name: 'no extra spaces' },
     { call: "join_two('Zoe', 'Smith')", expect: "'Zoe Smith'", hidden: true }],
    "An f-string: f'{a} {b}' — or a + ' ' + b.",
    "def join_two(a, b):\n    return f'{a} {b}'\n",
    'The space between the curly brackets is a real character in the text. The length test exists because it is easy to end up with two spaces or none.');

  P('r-repeat', 'Repeat some text', 'repeat',
    'Write a function called repeat that gives back the text repeated n times, with nothing in between.',
    'def repeat(text: str, n: int) -> str',
    'def repeat(text, n):\n    # your code here\n    pass\n',
    [{ in: "repeat('ab', 3)", out: "'ababab'" }],
    [{ call: "repeat('ab', 3)", expect: "'ababab'" },
     { call: "repeat('x', 1)", expect: "'x'" },
     { call: "repeat('x', 0)", expect: "''", name: 'none of it' },
     { call: "repeat('', 5)", expect: "''", hidden: true },
     { call: "len(repeat('abc', 4))", expect: '12', hidden: true }],
    'Multiplying text repeats it: text * n.',
    'def repeat(text, n):\n    return text * n\n',
    'The * you use for numbers means "repeat" for text. Multiplying by 0 gives an empty string rather than an error, which is why that case needs no special handling.');

  P('r-capitalise', 'Capitalise a word', 'capitalise',
    'Write a function called capitalise that gives back the word with its first letter as a capital and the rest lower case.',
    'def capitalise(word: str) -> str',
    'def capitalise(word):\n    # your code here\n    pass\n',
    [{ in: "capitalise('ann')", out: "'Ann'" }],
    [{ call: "capitalise('ann')", expect: "'Ann'" },
     { call: "capitalise('ANN')", expect: "'Ann'", name: 'the rest goes lower case' },
     { call: "capitalise('')", expect: "''", name: 'nothing to capitalise' },
     { call: "capitalise('mcDONALD')", expect: "'Mcdonald'", hidden: true, name: 'it lower-cases the rest too' },
     { call: "capitalise('a')", expect: "'A'", hidden: true }],
    'Text has a .capitalize() method that does exactly this.',
    'def capitalise(word):\n    return word.capitalize()\n',
    "One method, and it handles the empty string without complaint. Note the American spelling in the method name — Python uses capitalize with a z, whatever your keyboard says.");

  P('r-trim', 'Tidy what someone typed', 'tidy',
    'Write a function called tidy that removes the spaces from both ends of some text and makes it lower case.',
    'def tidy(text: str) -> str',
    'def tidy(text):\n    # your code here\n    pass\n',
    [{ in: "tidy('  Ann  ')", out: "'ann'" }],
    [{ call: "tidy('  Ann  ')", expect: "'ann'" },
     { call: "tidy('BOB')", expect: "'bob'" },
     { call: "tidy('   ')", expect: "''", name: 'all spaces leaves nothing' },
     { call: "tidy(' New York ')", expect: "'new york'", hidden: true, name: 'inner spaces stay' },
     { call: "tidy('')", expect: "''", hidden: true }],
    'Two methods, one after the other: .strip() then .lower().',
    'def tidy(text):\n    return text.strip().lower()\n',
    'Methods chain left to right, so this strips first and then lower-cases the result. This exact line is the first thing to do to anything a person typed.');

  P('r-starts-with', 'Does it start with that', 'starts_with',
    'Write a function called starts_with that says whether some text begins with a given prefix.',
    'def starts_with(text: str, prefix: str) -> bool',
    'def starts_with(text, prefix):\n    # your code here\n    pass\n',
    [{ in: "starts_with('hello', 'he')", out: 'True' }],
    [{ call: "starts_with('hello', 'he')", expect: 'True' },
     { call: "starts_with('hello', 'lo')", expect: 'False', name: 'that is the end, not the start' },
     { call: "starts_with('hello', '')", expect: 'True', name: 'everything starts with nothing' },
     { call: "starts_with('', 'a')", expect: 'False', hidden: true },
     { call: "starts_with('Hello', 'he')", expect: 'False', hidden: true, name: 'capitals matter' }],
    'Text has .startswith(prefix), which already gives True or False.',
    'def starts_with(text, prefix):\n    return text.startswith(prefix)\n',
    'The method does the comparison for you. The capital-H test is the reminder that text comparison is case-sensitive — lower() both sides when you do not want that.');

  P('r-list-sum', 'Total a list, by hand', 'total_by_hand',
    'Write a function called total_by_hand that adds up a list of numbers WITHOUT using sum().\n\nAn empty list totals 0.',
    'def total_by_hand(nums: list) -> float',
    'def total_by_hand(nums):\n    # your code here\n    pass\n',
    [{ in: 'total_by_hand([1, 2, 3])', out: '6' }],
    [{ call: 'total_by_hand([1, 2, 3])', expect: '6' },
     { call: 'total_by_hand([])', expect: '0', name: 'nothing adds to nothing' },
     { call: 'total_by_hand([5])', expect: '5' },
     { call: 'total_by_hand([-1, 1])', expect: '0', hidden: true },
     { call: 'total_by_hand([0.5, 0.5])', expect: '1.0', hidden: true }],
    'Start a total at 0, loop, and add each number to it.',
    'def total_by_hand(nums):\n    total = 0\n    for n in nums:\n        total += n\n    return total\n',
    'The running-total shape, written out: start outside the loop, add inside it, return after it. sum(nums) is the same thing in one word, and worth using once you have written this once.');

  P('r-list-max', 'The biggest, by hand', 'biggest_by_hand',
    'Write a function called biggest_by_hand that finds the largest number in a list WITHOUT using max().\n\nYou can assume the list is not empty.',
    'def biggest_by_hand(nums: list) -> float',
    'def biggest_by_hand(nums):\n    # your code here\n    pass\n',
    [{ in: 'biggest_by_hand([3, 9, 4])', out: '9' }],
    [{ call: 'biggest_by_hand([3, 9, 4])', expect: '9' },
     { call: 'biggest_by_hand([5])', expect: '5' },
     { call: 'biggest_by_hand([-5, -1, -9])', expect: '-1', name: 'all negative' },
     { call: 'biggest_by_hand([1, 1, 1])', expect: '1', hidden: true },
     { call: 'biggest_by_hand([0, -1])', expect: '0', hidden: true }],
    'Start "best so far" at the FIRST item, then compare each one against it.',
    'def biggest_by_hand(nums):\n    best = nums[0]\n    for n in nums:\n        if n > best:\n            best = n\n    return best\n',
    'Starting at nums[0] rather than at 0 is the whole lesson: with an all-negative list, starting at zero would report 0, a number that is not even in the data.');

  P('r-evens', 'Keep the even numbers', 'evens',
    'Write a function called evens that gives back a new list holding only the even numbers.',
    'def evens(nums: list) -> list',
    'def evens(nums):\n    # your code here\n    pass\n',
    [{ in: 'evens([1, 2, 3, 4])', out: '[2, 4]' }],
    [{ call: 'evens([1, 2, 3, 4])', expect: '[2, 4]' },
     { call: 'evens([1, 3])', expect: '[]', name: 'none qualify' },
     { call: 'evens([])', expect: '[]' },
     { call: 'evens([0])', expect: '[0]', hidden: true, name: 'zero is even' },
     { call: 'evens([-2, -3])', expect: '[-2]', hidden: true, name: 'negatives count too' }],
    'A number is even when n % 2 == 0.',
    'def evens(nums):\n    return [n for n in nums if n % 2 == 0]\n',
    'The filtering comprehension: what to keep, where it comes from, and the condition on the end. The zero and negative tests are both cases where "even" is easy to get wrong by hand.');

  P('r-longer-than', 'Words above a length', 'longer_than',
    'Write a function called longer_than that keeps only the words longer than n characters.',
    'def longer_than(words: list, n: int) -> list',
    'def longer_than(words, n):\n    # your code here\n    pass\n',
    [{ in: "longer_than(['a', 'abc', 'abcd'], 2)", out: "['abc', 'abcd']" }],
    [{ call: "longer_than(['a', 'abc', 'abcd'], 2)", expect: "['abc', 'abcd']" },
     { call: "longer_than(['ab'], 2)", expect: '[]', name: 'longer than, not equal to' },
     { call: 'longer_than([], 3)', expect: '[]' },
     { call: "longer_than(['hello', 'hi'], 0)", expect: "['hello', 'hi']", hidden: true },
     { call: "longer_than([''], 0)", expect: '[]', hidden: true }],
    'Same comprehension as the last one, with len(word) > n as the condition.',
    'def longer_than(words, n):\n    return [w for w in words if len(w) > n]\n',
    'One inch on from the evens problem: same shape, different test inside the if. Once that shape is automatic, most list questions are a one-liner.');

  P('r-dict-keys', 'List the keys', 'keys_of',
    'Write a function called keys_of that gives back a list of a dictionary\'s keys.',
    'def keys_of(d: dict) -> list',
    'def keys_of(d):\n    # your code here\n    pass\n',
    [{ in: "keys_of({'a': 1, 'b': 2})", out: "['a', 'b']" }],
    [{ call: "keys_of({'a': 1, 'b': 2})", expect: "['a', 'b']" },
     { call: 'keys_of({})', expect: '[]', name: 'nothing in it' },
     { call: "keys_of({'only': 9})", expect: "['only']" },
     { call: "keys_of({'b': 1, 'a': 2})", expect: "['b', 'a']", hidden: true, name: 'insertion order, not alphabetical' },
     { call: "len(keys_of({'a': 1, 'b': 2, 'c': 3}))", expect: '3', hidden: true }],
    'list(d) gives the keys — so does list(d.keys()).',
    'def keys_of(d):\n    return list(d)\n',
    'Turning a dictionary into a list gives you its KEYS, which surprises people the first time. The hidden test is the other lesson: dictionaries keep the order things were added, not alphabetical order.');

  P('r-dict-add', 'Add an entry', 'with_entry',
    'Write a function called with_entry that gives back a NEW dictionary with one extra key and value.\n\nThe dictionary you were given must not change.',
    'def with_entry(d: dict, key, value) -> dict',
    'def with_entry(d, key, value):\n    # your code here\n    pass\n',
    [{ in: "with_entry({'a': 1}, 'b', 2)", out: "{'a': 1, 'b': 2}" }],
    [{ call: "with_entry({'a': 1}, 'b', 2)", expect: "{'a': 1, 'b': 2}" },
     { call: "with_entry({}, 'a', 1)", expect: "{'a': 1}", name: 'starting from empty' },
     { call: '_kept()', expect: 'True', name: 'the original is untouched' },
     { call: "with_entry({'a': 1}, 'a', 9)", expect: "{'a': 9}", hidden: true, name: 'an existing key is replaced' },
     { call: "len(with_entry({'a': 1}, 'b', 2))", expect: '2', hidden: true }],
    'Copy it with dict(d) first, then set the key on the copy.',
    'def with_entry(d, key, value):\n    out = dict(d)\n    out[key] = value\n    return out\n',
    "Copy, change, return — the same three lines you use whenever a function must not disturb what it was handed. Setting a key that already exists REPLACES it, which the hidden test makes explicit.");
  window.PYTESTS[window.PYTESTS.length - 1].setup = "def _kept():\n    given = {'a': 1}\n    with_entry(given, 'b', 2)\n    return given == {'a': 1}\n";

  P('r-safe-first', 'The first item, safely', 'first_or_none',
    'Write a function called first_or_none that gives back the first item of a list, or None when the list is empty.',
    'def first_or_none(items: list)',
    'def first_or_none(items):\n    # your code here\n    pass\n',
    [{ in: 'first_or_none([5, 6])', out: '5' }],
    [{ call: 'first_or_none([5, 6])', expect: '5' },
     { call: 'first_or_none([])', expect: 'None', name: 'no crash on an empty list' },
     { call: "first_or_none(['a'])", expect: "'a'" },
     { call: 'first_or_none([0])', expect: '0', hidden: true, name: 'zero is a real first item' },
     { call: 'first_or_none([None, 1])', expect: 'None', hidden: true }],
    'Check the list has something in it before reaching for items[0].',
    'def first_or_none(items):\n    if not items:\n        return None\n    return items[0]\n',
    "The guard-first shape: deal with the impossible case, then get on with the normal one. Note `if not items` rather than `if len(items) == 0` — an empty list is already falsy, and the zero test proves the guard is about the LIST, not about the value inside it.");

  P('r-average-safe', 'An average that cannot crash', 'safe_average',
    'Write a function called safe_average that gives back the average of a list of numbers, or 0 when the list is empty.',
    'def safe_average(nums: list) -> float',
    'def safe_average(nums):\n    # your code here\n    pass\n',
    [{ in: 'safe_average([2, 4])', out: '3.0' }],
    [{ call: 'safe_average([2, 4])', expect: '3.0' },
     { call: 'safe_average([])', expect: '0', name: 'no dividing by zero' },
     { call: 'safe_average([5])', expect: '5.0' },
     { call: 'safe_average([1, 2, 3, 4])', expect: '2.5', hidden: true },
     { call: 'safe_average([-2, 2])', expect: '0.0', hidden: true }],
    'Guard the empty case first, then sum divided by len.',
    'def safe_average(nums):\n    if not nums:\n        return 0\n    return sum(nums) / len(nums)\n',
    'Exactly the guard you just wrote, protecting a division instead of an index. Without it, an empty list raises ZeroDivisionError and takes the whole script with it.');
})();
