/* More core definitions (batch 13): random forests, gradient boosting, stacking,
   model evaluation, performance optimisation, scikit-learn. Simple, central vocabulary
   each topic was still missing. DEFS-tagged with reveals. Loads before app.js. */
(function () {
  var Q = (window.QUESTIONS = window.QUESTIONS || {});
  var D = (window.DEFS = window.DEFS || {});
  function def(qk, q, correct, distractors, name, text, explain, simple) {
    (Q[qk] = Q[qk] || []).push({ q: q, choices: [correct].concat(distractors), explain: explain, simple: simple, widget: { reveal: { name: name, text: text } } });
    D[q] = 1;
  }

  /* ===== Random Forests (rf1) — 8 ===== */

  def("rf1",
    "What 'wisdom of the crowd' effect do random forests exploit?",
    "Many imperfect but independent judgements average into a far more reliable one.",
    ["Large crowds of trees can memorise the training data more completely than one tree.",
     "The trees vote on which single best tree should make all future predictions.",
     "Adding trees increases model capacity, letting the forest fit harder patterns.",
     "Crowds of trees share their split thresholds, correcting each other's values."],
    "Wisdom of the crowd",
    "The jelly-beans-in-a-jar effect: individual guesses are noisy, but their errors point in different directions and cancel in the average — provided the guessers are diverse and not copying each other.",
    "This is the forest's entire theory of operation, and it explains both requirements: trees must be decent individually AND decorrelated (hence bootstrap + random features), or the averaging buys nothing.",
    "A hundred flawed opinions, averaged, beat one expert — if they err differently.");

  def("rf1",
    "What are the two sources of randomness in a random forest?",
    "Row randomness (bootstrap samples) and feature randomness (random subsets at each split).",
    ["Random initial weights in each tree and random learning rates between trees.",
     "Random label noise injected during training and random pruning afterwards.",
     "Random tree depths and a randomly chosen impurity measure per tree.",
     "A random train/test split re-drawn independently for every tree."],
    "Row vs feature randomness",
    "Each tree sees a bootstrap resample of the rows, and each split considers only a random draw of max_features columns. Together they make trees genuinely different.",
    "The two dials serve one goal — decorrelation — from two directions: different data changes what trees see, different feature menus change what they're allowed to ask.",
    "Shuffle who's in the class and which questions are on the menu — every tree learns differently.");

  def("rf1",
    "Why doesn't increasing n_estimators cause a random forest to overfit?",
    "More trees just average more independent votes; the ensemble converges rather than memorises.",
    ["It does overfit sharply, which is why forests are capped at fifty trees by default.",
     "Extra trees are trained on the test set, which keeps the forest honest.",
     "Each new tree is shallower than the last, reducing total capacity.",
     "Later trees only re-fit the examples the earlier trees got right."],
    "Why more trees don't overfit",
    "Adding trees narrows the average's variance toward a limit — performance plateaus but doesn't degrade. Contrast boosting, where each round adds capacity and CAN overfit.",
    "This asymmetry is a key practical divide: forest n_estimators is 'as many as you can afford'; boosting n_estimators is a genuine tuning knob needing early stopping.",
    "More voters steady the average — they can't make the crowd start memorising.");

  def("rf1",
    "What is the out-of-bag (OOB) sample of a single tree?",
    "The ~37% of training rows the tree's bootstrap draw missed.",
    ["The rows the tree misclassified during training, held aside for reweighting.",
     "A random third of the test set assigned to that tree for evaluation.",
     "The rows deleted from the dataset because they contained missing values.",
     "The duplicated rows that appear more than once in the tree's bootstrap."],
    "Out-of-bag sample",
    "Sampling n rows with replacement leaves each row out of any given tree's sample with probability (1−1/n)ⁿ ≈ 0.368. Those left-out rows are unseen data for that particular tree.",
    "Each row can be scored by the trees that never saw it — aggregating this across the forest yields OOB evaluation, a built-in validation estimate with no held-out split.",
    "Every tree accidentally leaves out a third of the class — perfect surprise examiners.");

  def("rf1",
    "How does a random forest report a probability for a class?",
    "As the share of trees voting for it (or the average of their leaf probabilities).",
    ["As the training accuracy of the single best tree in the whole ensemble.",
     "As one minus the forest's out-of-bag error on the training data.",
     "As the depth of the deepest tree that voted for that class, rescaled.",
     "As the inverse of the distance to the nearest training example."],
    "Vote share as probability",
    "predict_proba averages across trees: 87 of 100 trees saying 'churn' reads as p≈0.87. Disagreement among trees is the model's expression of uncertainty.",
    "These vote shares are far smoother than a single tree's 0/1 leaf outputs — one big reason forests calibrate better than trees — though they still benefit from a calibration check.",
    "The probability is just the size of the majority.");

  def("rf1",
    "When does a random forest most clearly beat a single decision tree?",
    "When the tree overfits — the forest keeps the flexibility but averages away the variance.",
    ["When the dataset is tiny, since forests need less data than single trees.",
     "When interpretability of individual predictions is the primary requirement.",
     "When features are on wildly different scales that trees cannot handle.",
     "When the true decision boundary is a single straight line."],
    "Forest vs single tree",
    "Same bias family, drastically lower variance: wherever a lone tree's accuracy swings with the sample (deep trees, noisy data), the forest's average is steadier and better on unseen data.",
    "The cost is transparency and compute — a forest is hundreds of flowcharts, not one — so the single tree survives where reading the logic matters more than the last few accuracy points.",
    "Keep the tree's flexibility, delete its moodiness — that's the forest trade.");

  def("rf1",
    "What are the practical limitations of random forests?",
    "Big and slower to predict, hard to read, and unable to extrapolate beyond seen values.",
    ["They cannot handle more than a few hundred training examples efficiently.",
     "They require careful feature scaling and one-hot encoding to work at all.",
     "They only support binary classification, never regression or multiclass.",
     "Their accuracy degrades every time the random seed is changed."],
    "Forest limitations",
    "Hundreds of deep trees cost memory and per-prediction time; the ensemble defies simple reading; and like all trees, predictions are capped at combinations of seen values — a regression forest cannot predict above its training maximum.",
    "Knowing the failure modes places the tool: brilliant tabular baseline, poor choice for tight latency budgets, regulated explainability, or trending targets that demand extrapolation.",
    "Heavyweight, hard to read, and it never predicts beyond what it has seen.");

  def("rf1",
    "In a random forest, why is each individual tree allowed to be a weak-ish, high-variance model?",
    "Averaging cancels variance, so the design spends everything on diversity and low bias instead.",
    ["Weak trees are legally required to prevent the ensemble from memorising data.",
     "High-variance trees train faster, and speed is the forest's only design goal.",
     "The first tree corrects the others, so their individual quality is irrelevant.",
     "It isn't allowed: each tree must individually beat the full forest's accuracy."],
    "Division of labour (trees vs ensemble)",
    "The architecture assigns jobs: trees chase the signal aggressively (deep, unpruned, low bias), and the ensemble layer handles stability (averaging kills the variance they generate).",
    "This division explains every default — no pruning, full depth, many trees — and contrasts with boosting, which flips the assignment: stable weak learners, ensemble chases the signal.",
    "Let each tree be bold and jittery; the average supplies the calm.");

  /* ===== Gradient Boosting (gb1) — 8 ===== */

  def("gb1",
    "What is the core difference between boosting and bagging?",
    "Bagging trains independent models in parallel and averages; boosting trains sequentially, each fixing what remains wrong.",
    ["Bagging is for classification while boosting works only on regression targets.",
     "Bagging uses deep trees while boosting uses linear models as its base learners.",
     "Boosting resamples the rows while bagging reweights the feature columns.",
     "They are two names for the same procedure implemented in different libraries."],
    "Boosting vs bagging",
    "Bagging = independent committee (variance reduction); boosting = relay team, each runner starting where the last stopped (bias reduction). Forests embody one, gradient boosting the other.",
    "The axis organises the whole ensemble zoo, predicts behaviour (forests plateau with more trees, boosting overfits), and explains why boosting can't parallelise across rounds.",
    "A parallel committee versus a relay of error-fixers.");

  def("gb1",
    "What does n_estimators mean for a gradient boosting model?",
    "The number of sequential boosting rounds.",
    ["The number of independent restarts averaged to smooth out randomness.",
     "The number of features each individual tree is permitted to consider.",
     "The maximum number of leaves allowed across the entire ensemble.",
     "The number of validation folds used to score the model internally."],
    "Number of boosting rounds",
    "Boosting builds its model round by round; n_estimators caps the sequence length. More rounds = more total capacity, in a way forest tree-counts are not.",
    "It trades off directly with learning rate (small steps need more of them), and its 'right' value is usually discovered rather than set — via early stopping on a validation set.",
    "How many correction passes the model is allowed to take.");

  def("gb1",
    "What happens when a boosting model runs for too many rounds?",
    "It starts fitting noise — training loss keeps falling while validation error turns upward.",
    ["Nothing; like a random forest, boosting is immune to adding more rounds.",
     "The learning rate automatically decays to zero, freezing the model safely.",
     "Earlier trees are deleted to make room, keeping total capacity constant.",
     "The model reverts to the single best round it encountered along the way."],
    "Too many rounds (boosting overfits)",
    "Because every round adds capacity aimed at the remaining error, the sequence will eventually chase noise. The validation curve is the classic U: down, bottom, creeping back up.",
    "This is THE difference from bagging in practice, and the reason early stopping is standard boosting hygiene rather than an optional refinement.",
    "An error-fixer that never stops eventually 'fixes' the noise too.");

  def("gb1",
    "Why is gradient boosting relatively sensitive to outliers and label noise?",
    "The largest remaining errors dominate the residuals, so later rounds obsess over exactly those points.",
    ["Its trees are too shallow to isolate outliers in their own leaves.",
     "The learning rate amplifies feature outliers exponentially each round.",
     "It standardises features internally, which magnifies extreme values.",
     "It isn't; boosting averages away outliers even better than bagging."],
    "Outlier sensitivity of boosting",
    "A mislabelled or extreme point keeps generating a big residual, drawing tree after tree — the sequential 'fix the biggest mistakes' logic has no way to conclude a point is beyond fixing.",
    "Mitigations map straight onto the mechanism: robust losses (Huber, absolute error), subsampling, and lower learning rates all dilute any single point's persistent pull.",
    "The squeakiest wheel gets every round's grease — even when it's a broken wheel.");

  def("gb1",
    "What does choosing the loss function in gradient boosting control?",
    "What 'error' means — and therefore what the residuals are that every tree fits.",
    ["Only the reporting metric; the trees themselves always fit squared error.",
     "The depth of each tree, which is derived from the loss's curvature.",
     "The colour scheme used when the boosting library plots its trees.",
     "Whether the model trains in parallel or must remain sequential."],
    "Loss function choice in boosting",
    "Gradient boosting is generic machinery around any differentiable loss: squared error, absolute error, Huber, log loss, quantile. The negative gradient of that loss IS what each tree learns.",
    "This pluggability is boosting's superpower — quantile loss turns the same engine into a prediction-interval machine — and the loss choice doubles as the outlier-robustness dial.",
    "Pick what counts as a mistake, and the trees chase exactly that.");

  def("gb1",
    "What does the validation-error curve over boosting rounds typically look like, and what do you do with it?",
    "A U-shape: falling, flattening, then rising — stop at (or restore) the bottom.",
    ["A straight declining line that justifies training for as long as possible.",
     "A flat line, since validation error is independent of the round count.",
     "A sawtooth that resets to its starting value every fifty rounds.",
     "An inverted U, peaking at the ideal number of rounds."],
    "The U-curve over rounds",
    "Early rounds fix real signal (both errors fall); late rounds fit noise (train falls, validation rises). The bottom of the validation U marks the honest stopping point.",
    "Early stopping just automates reading this curve — watch a validation metric, keep the best round, stop after patience runs out. Plotting it remains the best boosting diagnostic.",
    "Down, bottom, up — get off at the bottom.");

  def("gb1",
    "How does gradient boosting handle regression problems?",
    "Natively: start from the mean, then each tree fits the residuals of the running prediction.",
    ["It first bins the target into classes and then boosts a classifier on them.",
     "It cannot; boosting is mathematically restricted to classification tasks.",
     "It averages the outputs of independent regression trees, like a forest.",
     "It fits one linear regression per leaf of a single large tree."],
    "Boosting for regression",
    "With squared error, the story is at its cleanest: prediction starts at the target mean, residuals are literal subtraction leftovers, and each round's tree nudges predictions toward them.",
    "Regression is where 'fit the residuals' needs no metaphor — the classification version (residuals on the log-odds scale) is the same dance one abstraction up.",
    "Guess the average, then correct, correct, correct.");

  def("gb1",
    "Which knobs form gradient boosting's standard overfitting-control toolkit?",
    "Learning rate, number of rounds (with early stopping), tree depth, and row/feature subsampling.",
    ["Only the random seed, since boosting has no other tunable parameters.",
     "The number of parallel threads and the floating-point precision used.",
     "The order of the training rows and the naming of the feature columns.",
     "The train/test split ratio and the choice of evaluation metric."],
    "Boosting's regularisation toolkit",
    "Four families: shrink each step (learning_rate), cap the steps (n_estimators + early stopping), cap per-tree complexity (max_depth / num_leaves / min_child_weight), and inject randomness (subsample, colsample).",
    "Modern libraries add explicit penalties (lambda, alpha, gamma) on top, but tuning sessions overwhelmingly move these four levers — knowing the map beats memorising defaults.",
    "Smaller steps, fewer steps, simpler trees, and a bit of randomness.");

  /* ===== Stacking & Voting (stack1) — 8 ===== */

  def("stack1",
    "Why can a combination of models outperform its best single member?",
    "Members' errors partly cancel when they're accurate-on-average but wrong in different places.",
    ["Because combining models multiplies their accuracies rather than averaging them.",
     "Because ensembles train on more total data than any single member did.",
     "Because the combination inherits only the strengths and drops all weaknesses automatically.",
     "It cannot; the ensemble is always bounded by its best member's accuracy."],
    "Why ensembles beat single models",
    "If each model is right most of the time and their mistakes don't coincide, majority votes recover the truth even where individual members fail — error cancellation, not magic.",
    "The condition is doing all the work: accuracy AND diversity. Combining copies of one model achieves nothing, which is why every ensemble method engineers disagreement somewhere.",
    "Different blind spots cover for each other.");

  def("stack1",
    "What is the essential difference between voting and stacking?",
    "Voting combines with a fixed rule; stacking learns the combination from data.",
    ["Voting works only for regression while stacking works only for classification.",
     "Stacking requires identical base models while voting requires different ones.",
     "Voting needs out-of-fold predictions while stacking must avoid them.",
     "They differ only in name; both average predictions with equal weights."],
    "Stacking vs voting",
    "A voting ensemble applies a preset recipe (majority, average, fixed weights); stacking trains a meta-model to discover the best recipe — including context-dependent trust.",
    "Learned combination is strictly more expressive but buys new failure modes (meta-overfitting) and costs (out-of-fold plumbing) — the classic flexibility-versus-simplicity trade, one level up.",
    "A fixed rule versus a learned referee.");

  def("stack1",
    "How are ties typically broken in hard voting with an even number of models?",
    "By a convention such as class order — a reason to prefer odd committees or soft voting.",
    ["The ensemble abstains and returns no prediction for the tied example.",
     "The tied example is sent back for one extra round of model training.",
     "The most recently trained model's vote is counted twice by default.",
     "Ties are impossible because voting classifiers reject even-sized ensembles."],
    "Tie-breaking in hard voting",
    "A 2–2 split must resolve somehow; sklearn falls back to label order — arbitrary by design. Odd numbers of voters dodge binary ties; soft voting dissolves them entirely, since summed probabilities rarely tie.",
    "A small detail with visible consequences on borderline cases, and one of the standing arguments for soft voting whenever calibrated probabilities are available.",
    "Even juries deadlock — hire an odd number, or let confidence decide.");

  def("stack1",
    "When does soft voting typically beat hard voting?",
    "When members output reasonable probabilities.",
    ["When the base models are badly miscalibrated and overconfident on every input.",
     "When the ensemble contains models that cannot produce probability estimates.",
     "When classes are perfectly balanced, which is the only case soft voting handles.",
     "Never; hard voting is strictly more accurate whenever the two disagree."],
    "When soft beats hard voting",
    "A 95%-sure member should outweigh two 51%-sure opponents — soft voting lets it; hard voting counts all three equally. Averaged probabilities use strictly more information.",
    "The caveat is calibration: garbage confidences weighted are worse than ignored, so calibrate members (or fall back to hard voting) when probability quality is doubtful.",
    "Let strong convictions outvote coin-flip shrugs — if the convictions are honest.");

  def("stack1",
    "What happens to an ensemble when its members' errors are strongly correlated?",
    "The benefit collapses — everyone is wrong on the same cases, so combining can't fix them.",
    ["Accuracy improves, because correlated errors reinforce the correct answers too.",
     "Training becomes impossible, as the covariance matrix cannot be inverted.",
     "The ensemble automatically drops all but one of the correlated members.",
     "Nothing changes; only member accuracy affects ensemble performance."],
    "Correlated errors (ensemble failure mode)",
    "Averaging cancels independent noise, not shared blind spots: five models fooled by the same distribution shift vote unanimously and wrongly. Diversity is the entire margin of ensemble profit.",
    "This is why ensembles mix algorithm families, why forests randomise twice, and why an honest ensemble evaluation checks member disagreement, not just member accuracy.",
    "Five copies of the same mistake still lose the vote.");

  def("stack1",
    "What are the practical costs of running an ensemble instead of one model?",
    "Multiplied training/prediction compute, bigger memory, and harder explanations and maintenance.",
    ["Ensembles are cheaper on every axis, which is why they are universally deployed.",
     "Only training slows down; prediction cost never depends on member count.",
     "The single cost is licensing, since each member requires a separate library.",
     "Accuracy reliably drops in production, offsetting the validation gains."],
    "Cost of ensembles",
    "N members ≈ N× the compute and memory at both ends of the pipeline, plus N models to monitor, retrain and version — and a combined prediction no single flowchart explains.",
    "The gains are real but often a percentage point; deciding whether that point is worth N× the bill is a deployment judgement, which is also why distillation (compress the ensemble into one model) exists.",
    "Better answers, N times the bill — sometimes worth it, sometimes not.");

  def("stack1",
    "Besides different algorithms, how else can ensemble members be made diverse?",
    "Different feature subsets, data samples, seeds, or hyperparameter settings per member.",
    ["Diversity requires different algorithms; identical families cannot ever differ.",
     "By training each member for a different number of epochs on the test set.",
     "By assigning each member a different decision threshold after training.",
     "By letting each member choose its own target variable to predict."],
    "Sources of ensemble diversity",
    "Anything that changes what a member sees or how it searches breeds disagreement: feature views (one model on text features, one on numerics), bootstraps, seeds, depths, losses.",
    "Bagging and random subspaces are just this idea institutionalised; hand-built stacks borrow it deliberately, e.g. giving each base model a different slice of the feature space.",
    "Change the diet, the seed or the settings — clones learn nothing from each other.");

  def("stack1",
    "What is the simplest possible ensemble worth trying first?",
    "A plain average (or majority vote) of two or three different tuned models.",
    ["A five-level stack with nested cross-validation and a neural meta-learner.",
     "Retraining the best single model five times and keeping the luckiest run.",
     "An ensemble of one model, which captures most of the benefit already.",
     "A weighted blend whose weights are tuned on the test set for accuracy."],
    "The simple blend (baseline ensemble)",
    "Averaging a boosted model with a linear model and a forest — no learned weights, no stacking plumbing — routinely captures most of the achievable ensemble gain in one line of code.",
    "It's the ensemble analogue of the baseline rule: establish what a trivial combination earns before paying for stacking's complexity, and let validation prove the extra machinery's worth.",
    "Just average your two best, different models — then see if fancier is actually better.");

  /* ===== Model Evaluation (metrics1) — 9 ===== */

  def("metrics1",
    "What is a true positive?",
    "A case that is actually positive and that the model also predicted as positive.",
    ["A positive prediction later confirmed to have been made with high confidence.",
     "A case the model predicted positive that turned out to be negative.",
     "An actually-positive case that the model incorrectly cleared as negative.",
     "The first positive prediction the model makes on each new dataset."],
    "True positive (TP)",
    "Hit: the model said 'yes' and reality agreed — disease flagged in a sick patient, fraud caught in a fraudulent transaction. One of the four cells of the confusion matrix.",
    "TP counts sit in the numerators of both precision and recall — the two big metrics are just TP divided by different totals (predicted-positive vs actually-positive).",
    "The model shouted 'fraud!' and it really was fraud.");

  def("metrics1",
    "What is a false positive?",
    "A case that is actually negative but that the model predicted as positive.",
    ["A positive case the model found using an unreliable or leaked feature.",
     "A case predicted negative that later turned out to be positive after all.",
     "A prediction whose probability was positive but below the threshold.",
     "A duplicate positive prediction counted twice by mistake."],
    "False positive (FP)",
    "The false alarm (Type I error): a healthy patient flagged, a legitimate email binned as spam. Its real-world cost — wasted follow-up, blocked customers — varies wildly by task.",
    "FP is the error precision watches (precision = TP/(TP+FP)) and the one that dominates rare-positive settings, where even a small false-alarm rate swamps the true hits.",
    "The alarm rang for nothing.");

  def("metrics1",
    "What is a true negative?",
    "A case that is actually negative and that the model correctly predicted as negative.",
    ["A case the model refused to score due to missing feature values.",
     "An actually-negative case that the model incorrectly flagged as positive.",
     "Any prediction of the majority class, whether correct or incorrect.",
     "A negative case removed from evaluation to balance the classes."],
    "True negative (TN)",
    "Correct rejection: the model said 'no' and was right — the routine transaction passed, the healthy patient cleared. Usually the biggest cell in imbalanced problems.",
    "TN drives specificity and accuracy but is absent from precision, recall and F1 — the deliberate design that stops 'saying no a lot' from looking like skill on rare-event tasks.",
    "Nothing to see here — and the model correctly said so.");

  def("metrics1",
    "What is a false negative?",
    "A case that is actually positive but that the model predicted as negative — a miss.",
    ["A negative prediction the model made with less than half confidence.",
     "An actually-negative case that the model incorrectly flagged as positive.",
     "A positive case that appears in the training set but not in testing.",
     "The model's refusal to predict when classes are imbalanced."],
    "False negative (FN)",
    "The miss (Type II error): the cancer not flagged, the fraud waved through. Often the costliest cell — the whole reason recall-focused evaluation exists.",
    "FN is what recall punishes (recall = TP/(TP+FN)), and trading FN against FP by moving the threshold is the central act of tuning a deployed classifier.",
    "It slipped past the alarm.");

  def("metrics1",
    "How do you orient yourself in a confusion matrix's rows and columns?",
    "Check the convention: one axis is truth, the other prediction.",
    ["Rows and columns are interchangeable because the matrix is always symmetric.",
     "The larger numbers are always on the diagonal, which fixes the orientation.",
     "Rows are always the positive class and columns are always the negative class.",
     "The orientation doesn't matter as long as all four cells are reported."],
    "Reading a confusion matrix",
    "sklearn's confusion_matrix puts truth in rows, predictions in columns, classes in sorted order — so cell [0][1] is 'actually negative, predicted positive' (FP). Other tools flip it.",
    "Half of confusion-matrix confusion is orientation: metrics computed from a transposed reading silently swap precision with recall. Check the axes before reading anything.",
    "First find out which side is 'truth' — everything else follows.");

  def("metrics1",
    "What is a model's error rate?",
    "The fraction of predictions that were wrong — exactly one minus the accuracy.",
    ["The number of errors made per second of prediction time in production.",
     "The ratio of false positives to false negatives across the test set.",
     "The percentage of training epochs in which the loss failed to decrease.",
     "The share of examples on which the model outputs a probability near 0.5."],
    "Error rate",
    "Misclassification rate = (FP + FN) / total = 1 − accuracy. The same information as accuracy, framed as cost rather than success.",
    "The reframing has real uses: '99% → 99.5% accurate' undersells what 'error rate halved' states plainly — a habit worth keeping when comparing strong models.",
    "The flip side of accuracy: how often it gets it wrong.");

  def("metrics1",
    "What is the majority-class baseline and why is it computed?",
    "The accuracy of always predicting the most common class.",
    ["The accuracy of the best single-feature model, used to rank the features.",
     "The highest accuracy achievable by any model on the given dataset.",
     "The average of all class frequencies, weighted by their importance.",
     "A random classifier's accuracy after calibration on the test set."],
    "Majority-class baseline",
    "Predict 'not fraud' always: 99% accurate at 1% fraud prevalence. Every reported accuracy means nothing until compared against this free number (DummyClassifier computes it).",
    "It is the sanity check that exposes accuracy-on-imbalanced-data theatre — and the first row that belongs in any honest results table.",
    "First ask: what score does zero intelligence get?");

  def("metrics1",
    "Precision and recall answer two different questions. What are they?",
    "Precision: 'when it alarms, how often is it right?' Recall: 'of all real cases, how many did it catch?'",
    ["Precision: 'how fast is the model?' Recall: 'how much memory does it use?'",
     "Precision: 'how many decimals are reported?' Recall: 'how repeatable are they?'",
     "Both answer the same question on the positive and negative class respectively.",
     "Precision: 'is training done?' Recall: 'can the weights be restored later?'"],
    "The two questions (precision vs recall)",
    "Same cells, different denominators: precision divides hits by everything flagged; recall divides hits by everything real. A model can ace either one alone trivially.",
    "Framing them as questions keeps the trade-off honest: flag less to be right more often (precision), flag more to miss less (recall) — the threshold slides between the two.",
    "Right when it speaks vs thorough in its search.");

  def("metrics1",
    "Why must a classifier never be evaluated on data it was trained on?",
    "Training scores reward memorisation; only unseen data measures the generalisation you actually care about.",
    ["Because sklearn raises an exception when the same rows appear in fit and score.",
     "Because training data becomes corrupted by the fitting process itself.",
     "Training evaluation is fine for small models and only misleads deep networks.",
     "Because metrics are mathematically undefined on previously seen examples."],
    "Evaluate on unseen data",
    "A 1-NN classifier scores 100% on its own training set while knowing nothing general — the extreme of an effect present in every flexible model. Held-out data is the only honest examiner.",
    "This single rule generates the entire validation apparatus: splits, cross-validation, and the discipline of touching the test set once. Every leak is a violation of it in disguise.",
    "Never let the student grade their own memorised homework.");

  /* ===== Performance Optimisation (perf1) — 8 ===== */

  def("perf1",
    "What does comparing training error with validation error diagnose?",
    "The failure mode: both high = underfitting; low train but high validation = overfitting.",
    ["Which of the features contributed most to the model's final predictions.",
     "Whether the dataset was shuffled correctly before the split was made.",
     "The number of additional epochs required before convergence occurs.",
     "Whether the model's probabilities are well calibrated across classes."],
    "Train vs validation error (the diagnostic pair)",
    "Two numbers, four quadrants: high/high → too simple (bias); low/high → memorising (variance); low/low → healthy; high/low → check for bugs. The first look in any debugging session.",
    "The diagnosis routes the treatment — more capacity/features for bias, regularisation/data for variance — which is why this pair is checked before touching any hyperparameter.",
    "Two report cards: bad at both = too dumb; aces practice but flunks the exam = memorising.");

  def("perf1",
    "What are the standard fixes for an overfitting model?",
    "More data, stronger regularisation, less capacity, early stopping, or ensembling.",
    ["Raise the learning rate and remove the validation set to free more data.",
     "Add features until the training error reaches exactly zero.",
     "Switch the metric from accuracy to F1, which prevents memorisation.",
     "Duplicate the training rows so the model sees each pattern twice."],
    "Fixes for overfitting",
    "All levers push the same direction — restrain the fit: shrink capacity (depth, features), penalise complexity (L1/L2), stop earlier, average models, or dilute noise with more data.",
    "Choosing among them is context: data is strongest but dearest; regularisation is cheapest to try first; ensembling helps when you can afford the compute.",
    "Give it less rope: simpler, penalised, stopped earlier — or drown the noise in data.");

  def("perf1",
    "What are the standard fixes for an underfitting model?",
    "More capacity, better features, weaker regularisation, or longer training.",
    ["Collect much more data of exactly the same kind the model already sees.",
     "Strengthen the L2 penalty until the coefficients stabilise near zero.",
     "Remove the informative features that are distracting the model.",
     "Lower the decision threshold so more positives are predicted."],
    "Fixes for underfitting",
    "Underfitting means the model can't even express the pattern: deepen it, add interactions/polynomials, relax penalties, train to convergence. More of the same data won't help — the ceiling is representational.",
    "The data trap is worth naming: collection is the reflex fix, but a high-bias model at 10× the data is the same disappointed model — capacity first, then data.",
    "The student isn't lazy, the textbook is too thin — give it a richer model, not more of the same pages.");

  def("perf1",
    "What does the strength of a regularisation penalty control?",
    "The trade-off point between fitting the training data and keeping the model simple.",
    ["The number of features the dataset is allowed to contain before training.",
     "The random seed schedule used to initialise the model's parameters.",
     "How often the training loop reports its loss to the console.",
     "The size of the test set carved out for final evaluation."],
    "Regularisation strength (the dial)",
    "One scalar (alpha up = simpler; C up = fit harder) slides the model along the bias-variance axis. At the extremes: a constant model, or an unpenalised memoriser.",
    "It's the archetypal hyperparameter — tuned on a log scale, read off a validation curve — and the reason 'more regularisation' and 'less regularisation' are the everyday answers to the two classic failure modes.",
    "One dial from 'ignore the data' to 'memorise the data' — park it where validation peaks.");

  def("perf1",
    "Why should model scores be treated as noisy measurements rather than exact values?",
    "Splits, seeds and sampling all jitter scores.",
    ["Because floating-point arithmetic makes all metrics wrong by several percent.",
     "Because metrics libraries round every score to the nearest whole number.",
     "Scores are exact; any observed variation indicates a bug in the pipeline.",
     "Because models deliberately randomise outputs to prevent overfitting."],
    "Score noise (runs are measurements)",
    "Re-split the data or reseed the model and 0.847 becomes 0.852 — the score is a sample from a distribution. Cross-validation exists to average that distribution; its spread belongs next to its mean.",
    "The operational rule: an 'improvement' smaller than the fold-to-fold spread is weather, not climate — report mean ± std and resist celebrating noise.",
    "One run is one dice roll — judge the dice, not the roll.");

  def("perf1",
    "What is the start-simple workflow for building a model?",
    "Baseline first, then a simple model, adding complexity only when validation proves it pays.",
    ["Start with the most powerful model available and simplify only if it overfits.",
     "Try every algorithm simultaneously and keep whichever trains the fastest.",
     "Begin with the final architecture and tune it until the test score peaks.",
     "Skip baselines for deep problems, since simple models cannot run on them."],
    "Start-simple workflow",
    "Dummy baseline → linear/tree model → tuned ensemble, each step justified by a validation gain over the last. Complexity is bought, never assumed.",
    "The sequence catches broken pipelines early (a baseline that ties your big model is a smoke alarm), yields honest progress numbers, and often reveals that simple was enough.",
    "Earn complexity: every fancier model must beat the humbler one to stay.");

  def("perf1",
    "What is the overfit-a-tiny-sample sanity check?",
    "Verify the model can hit ~100% on a few rows — if it can't memorise, something is broken.",
    ["Confirm the model scores poorly on a tiny sample, proving it hasn't memorised.",
     "Train on the full data but evaluate on ten rows to speed up the metric.",
     "Delete all but ten features and check that accuracy stays unchanged.",
     "Run the model twice on one row and check the outputs differ."],
    "Overfit-a-tiny-sample check",
    "Any healthy flexible model should trivially memorise 50 rows. Failure means plumbing bugs — mangled labels, dead features, a broken loss — not modelling subtlety.",
    "It's the cheapest end-to-end test of the training loop, standard in deep learning and just as informative for classical pipelines: prove the machine CAN learn before asking whether it generalises.",
    "If it can't even cheat on ten examples, the wiring is broken.");

  def("perf1",
    "In iterating on a model, when do better features beat a better algorithm?",
    "Usually: informative features lift every model, while algorithm swaps rarely rescue weak inputs.",
    ["Never; modern algorithms extract all possible signal from any input features.",
     "Only for image data, where features cannot be learned automatically.",
     "Features and algorithms are interchangeable, so effort splits evenly.",
     "Only when the dataset has fewer than one hundred rows."],
    "Features beat algorithms (usually)",
    "The practitioner consensus for tabular work: a domain-informed ratio or date-gap feature routinely buys more accuracy than swapping the classifier — signal in beats cleverness applied.",
    "It sets the improvement priority: after the baseline, spend on understanding and encoding the data before touring the model zoo; 'garbage in, garbage out' is the same law from the other side.",
    "A better clue helps every detective; a smarter detective still can't read invisible ink.");

  /* ===== Advanced Scikit-learn (skl1) — 10 ===== */

  def("skl1",
    "What is sklearn's score() method shortcut?",
    "estimator.score(X, y) computes a default metric.",
    ["It prints the model's hyperparameters together with their current values.",
     "It returns the training loss recorded at the final iteration of fitting.",
     "It scores the model's code quality against the library's style guide.",
     "It estimates how long a call to predict will take on the given data."],
    "score() (default metric shortcut)",
    "One call, one number: the estimator's built-in default metric on the data you pass. Convenient for quick checks; the metrics module takes over when you need anything specific.",
    "Knowing WHICH default matters — accuracy can flatter imbalanced classifiers and R² hides error units — so treat score() as a glance, not an evaluation.",
    "The one-liner report card — using the library's choice of metric, not necessarily yours.");

  def("skl1",
    "What does the trailing underscore mean in sklearn attributes like coef_ or feature_importances_?",
    "It marks values learned from data during fit — they exist only on fitted estimators.",
    ["It marks attributes that are deprecated and scheduled for removal.",
     "It marks private attributes that user code is forbidden to read.",
     "It distinguishes NumPy arrays from ordinary Python list attributes.",
     "It marks settings that cannot be changed after the object is created."],
    "Trailing-underscore convention (fitted attributes)",
    "The API's grammar: constructor parameters have no underscore (C, max_depth); learned results end with one (coef_, cluster_centers_, classes_). Accessing them before fit raises NotFittedError.",
    "The convention makes code self-documenting — you can tell at a glance what was configured versus what was learned — and it's how sklearn distinguishes a blueprint from a trained model.",
    "No underscore: you chose it. Underscore: the data taught it.");

  def("skl1",
    "What is DummyClassifier (and DummyRegressor) for?",
    "Producing no-skill baselines — like always predicting the majority class or the mean.",
    ["Generating synthetic training data that mimics the original distribution.",
     "Stress-testing pipelines with deliberately corrupted feature values.",
     "A lightweight production model for latency-critical applications.",
     "Unit-testing sklearn itself; it has no use in normal projects."],
    "DummyClassifier / DummyRegressor",
    "Estimators that ignore the features entirely: majority class, stratified guessing, mean or median. Their score is the floor that any real model must clear.",
    "One line institutionalises the baseline habit — and instantly exposes accuracy theatre on imbalanced data, where the dummy's 99% reframes every other score in the table.",
    "The professional way to ask: what does guessing score?");

  def("skl1",
    "How do named steps work in an sklearn Pipeline?",
    "Each step gets a name, letting you address nested parameters like 'scaler__with_mean' in searches.",
    ["Names are decorative labels used only when the pipeline is printed.",
     "Steps are named after their position: 'step0', 'step1', with no alternatives.",
     "Names must match the estimator's class name or the pipeline won't build.",
     "Naming a step freezes it, excluding it from fitting and searching."],
    "Pipeline step names (and __ parameters)",
    "Pipeline([('scaler', StandardScaler()), ('clf', LogisticRegression())]) — the names become the address system: clf__C reaches into the pipeline in a GridSearchCV param grid.",
    "The double-underscore routing is what makes whole-pipeline tuning possible — preprocessing and model hyperparameters searched together, leak-free, inside one CV loop.",
    "Name the stages, then steer any dial by its address: stage__knob.");

  def("skl1",
    "What does make_column_selector do in a preprocessing pipeline?",
    "Selects columns by dtype or name pattern — e.g. all numeric ones — for a ColumnTransformer.",
    ["Deletes the columns whose correlation with the target falls below a threshold.",
     "Renames the columns of a DataFrame to match sklearn's naming conventions.",
     "Chooses the single best column to use as the model's only feature.",
     "Sorts the columns by importance before the model is trained."],
    "make_column_selector",
    "Instead of hard-coding column lists, select dynamically: make_column_selector(dtype_include=np.number) routes every numeric column to the scaler, object columns to the encoder.",
    "It keeps ColumnTransformers robust to schema drift — new columns route themselves by type — which is the difference between a pipeline that survives the next data refresh and one that breaks.",
    "Route columns by kind — numbers this way, categories that way — without naming names.");

  def("skl1",
    "What does handle_unknown='ignore' do in OneHotEncoder?",
    "Unseen categories at transform time encode as all zeros instead of raising an error.",
    ["It silently deletes any row that contains a category not seen in training.",
     "It replaces unknown categories with the most frequent training category.",
     "It disables the encoder's check that inputs are strings, allowing numbers.",
     "It merges rare training categories into a shared 'unknown' column."],
    "handle_unknown='ignore'",
    "Trained on {red, green, blue}, shown 'purple': default behaviour raises; with ignore, purple becomes a row of zeros in the colour block — the model sees 'none of the known colours'.",
    "Production data always eventually contains a new category, so this flag (or an explicit infrequent-category bucket) is the difference between a crash page and a graceful degrade.",
    "New colour? Shrug — encode it as 'none of the above' instead of crashing.");

  def("skl1",
    "Why do sklearn's text vectorizers and encoders often output sparse matrices?",
    "Most entries are zero, so storing only non-zeros saves enormous memory.",
    ["Sparse matrices train models to be robust against missing feature values.",
     "Sparse output is a licensing restriction of the SciPy dependency.",
     "Because sklearn cannot allocate dense arrays larger than one gigabyte.",
     "Sparsity encrypts the data, protecting the original text from recovery."],
    "Sparse matrices in sklearn",
    "A 100k-document TF-IDF matrix with a 50k vocabulary is ~0.1% non-zero; dense storage would be tens of gigabytes, sparse a few hundred megabytes. Many estimators consume sparse input natively.",
    "The practical edge: know which steps preserve sparsity and which (like StandardScaler with centering) densify it and explode memory — a top cause of surprise out-of-memory crashes.",
    "Don't store an ocean of zeros — keep only the few cells that aren't.");

  def("skl1",
    "Where do hyperparameters live in sklearn's API design?",
    "In the constructor — LogisticRegression(C=0.1) — set before fit and inspectable anytime.",
    ["They are passed to fit() alongside the data on every training call.",
     "They live in a global sklearn configuration object shared by all models.",
     "They are learned automatically during fit and stored with underscores.",
     "They are supplied per-prediction as arguments to predict()."],
    "Hyperparameters in the constructor",
    "The API contract: configuration at construction, data at fit. get_params/set_params expose the same settings programmatically — which is exactly the surface GridSearchCV manipulates.",
    "The separation is why searches, clones and pipelines compose so cleanly: an estimator is a reusable recipe whose settings are data-independent, until fit marries it to a dataset.",
    "Settings go in when you build the machine, data goes in when you run it.");

  def("skl1",
    "After selecting a model with cross-validation, what is the standard final training step?",
    "Refit the chosen configuration on all available training data before deployment.",
    ["Deploy the single CV-fold model that achieved the highest validation score.",
     "Average the weights of all fold models into one ensemble parameter set.",
     "Retrain on the test set to take advantage of every labelled example.",
     "Nothing; the cross-validation procedure already produced a final model."],
    "Final refit on all data",
    "CV's fold models exist to estimate performance, not to serve traffic; the winner's settings are refitted on the full training data so no labelled example is wasted (GridSearchCV's refit=True automates it).",
    "The two-phase logic — estimate with splits, then train on everything — is easy to fumble; deploying a fold model quietly throws away 20% of your data's teaching value.",
    "Use the folds to choose, then train the winner on everything you have.");

  def("skl1",
    "What does sklearn's set_config(transform_output='pandas') change?",
    "Transformers return labelled DataFrames instead of bare NumPy arrays.",
    ["It converts every estimator into a lazy, out-of-core streaming version.",
     "It makes fit() accept CSV file paths directly instead of arrays.",
     "It switches the backend from NumPy to GPU-accelerated tensors.",
     "It renders all pipelines as interactive diagrams in notebooks."],
    "Pandas output (set_config)",
    "By default transforms strip column names, returning arrays; the pandas output mode keeps feature names attached through scalers, encoders and pipelines.",
    "Named columns end the 'which column is which after one-hot?' archaeology — feature importances and debugging map straight back to meaningful names deep inside a pipeline.",
    "Keep the name tags on the columns as they flow through the machine.");

})();
