/* DataSense service worker — generated by build_sw.js. Do not edit by hand. */
const CACHE = 'datasense-5e5680e66001';
const ASSETS = [
  "./",
  "./index.html",
  "./fonts.css",
  "./widgets.js",
  "./data_primers.js",
  "./data_found.js",
  "./data_found2.js",
  "./data_found3.js",
  "./data_easy.js",
  "./data_medium.js",
  "./data_hard.js",
  "./data_logreg.js",
  "./data_logreg2.js",
  "./data_logreg3.js",
  "./data_bayes.js",
  "./data_bayes2.js",
  "./data_bayes3.js",
  "./data_bayes_nb.js",
  "./data_trees.js",
  "./data_trees2.js",
  "./data_trees3.js",
  "./data_svm.js",
  "./data_svm2.js",
  "./data_svm3.js",
  "./data_rf.js",
  "./data_rf3.js",
  "./data_gboost.js",
  "./data_gb3.js",
  "./data_stacking.js",
  "./data_stack3.js",
  "./data_metrics.js",
  "./data_metrics2.js",
  "./data_metrics3.js",
  "./data_perf.js",
  "./data_perf3.js",
  "./data_sklearn.js",
  "./data_skl3.js",
  "./data_kmeans.js",
  "./data_kmeans3.js",
  "./data_hier.js",
  "./data_hier3.js",
  "./data_dbscan.js",
  "./data_dbscan3.js",
  "./data_pca.js",
  "./data_pca3.js",
  "./data_tsne.js",
  "./data_tsne3.js",
  "./data_steps_found.js",
  "./data_steps_knn.js",
  "./data_steps_logreg.js",
  "./data_steps_bayes.js",
  "./data_steps_trees.js",
  "./data_steps_svm.js",
  "./data_steps_rf.js",
  "./data_steps_gboost.js",
  "./data_steps_stacking.js",
  "./data_steps_metrics.js",
  "./data_steps_perf.js",
  "./data_steps_sklearn.js",
  "./data_steps_kmeans.js",
  "./data_steps_hier.js",
  "./data_steps_dbscan.js",
  "./data_steps_pca.js",
  "./data_steps_tsne.js",
  "./data_steps_feng.js",
  "./data_steps_fsel.js",
  "./data_steps_msel.js",
  "./data_steps_xgb.js",
  "./data_widgets_found.js",
  "./data_widgets_knn.js",
  "./data_widgets_logreg.js",
  "./data_widgets_bayes.js",
  "./data_widgets_trees.js",
  "./data_widgets_svm.js",
  "./data_widgets_rf.js",
  "./data_widgets_gboost.js",
  "./data_widgets_stacking.js",
  "./data_widgets_metrics.js",
  "./data_widgets_perf.js",
  "./data_widgets_sklearn.js",
  "./data_widgets_kmeans.js",
  "./data_widgets_hier.js",
  "./data_widgets_dbscan.js",
  "./data_widgets_pca.js",
  "./data_widgets_tsne.js",
  "./data_feng.js",
  "./data_fsel.js",
  "./data_msel.js",
  "./data_xgb.js",
  "./data_defs.js",
  "./data_defs_extra.js",
  "./data_defs_g1.js",
  "./data_defs_g2.js",
  "./data_defs_g3.js",
  "./data_defs_g4.js",
  "./data_defs_g5.js",
  "./data_defs_g6.js",
  "./data_defs_new.js",
  "./data_cards_new.js",
  "./data_notes_new.js",
  "./data_scen.js",
  "./data_scen_algo1.js",
  "./data_scen_algo2.js",
  "./data_scen_ens.js",
  "./data_scen_feat.js",
  "./data_scen_eval.js",
  "./data_scen_unsup.js",
  "./data_order.js",
  "./data_compare.js",
  "./data_notes_a.js",
  "./data_notes_b.js",
  "./data_notes_c.js",
  "./data_notes_d.js",
  "./data_notes_e.js",
  "./data_notes_f.js",
  "./data_knn_dist.js",
  "./data_knn_k.js",
  "./data_why_found.js",
  "./data_why_knn.js",
  "./data_why_logreg_bayes.js",
  "./data_why_trees_svm.js",
  "./data_why_ensembles.js",
  "./data_why_metrics_perf.js",
  "./data_why_skl_clust1.js",
  "./data_why_clust2_dim.js",
  "./data_why_features_xgb.js",
  "./data_defs_tag.js",
  "./data_moredefs_g1.js",
  "./data_moredefs_g2.js",
  "./data_moredefs_g3.js",
  "./data_moredefs_g4.js",
  "./data_moredefs_g5.js",
  "./data_moredefs_g6.js",
  "./data_moredefs_g7.js",
  "./data_impdefs_a.js",
  "./data_impdefs_b.js",
  "./data_impdefs_c.js",
  "./data_moredefs_g8.js",
  "./data_moredefs_g9.js",
  "./data_moredefs_g10.js",
  "./data_moredefs_g11.js",
  "./data_moredefs_g12.js",
  "./data_moredefs_g13.js",
  "./data_moredefs_g14.js",
  "./data_moredefs_g15.js",
  "./data_work_defs.js",
  "./data_work_defs2.js",
  "./data_work_defs3.js",
  "./data_code_tasks.js",
  "./data_code_tasks2.js",
  "./data_code_tasks3.js",
  "./data_code_tasks4.js",
  "./data_code_tasks5.js",
  "./data_code_walks.js",
  "./data_code_levels.js",
  "./data_hard_true.js",
  "./data_defs_rank.js",
  "./app.js",
  "./manifest.webmanifest",
  "./favicon-16.png",
  "./favicon-32.png",
  "./icon-180.png",
  "./icon-192.png",
  "./icon-512.png",
  "./icon-192-maskable.png",
  "./icon-512-maskable.png"
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) { if (k !== CACHE) return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

// Cache-first for same-origin GET. Everything is precached and the cache name is
// content-versioned, so this is fast offline and still updates on redeploy.
self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && res.ok && res.type === 'basic') {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      }).catch(function () {
        if (req.mode === 'navigate') return caches.match('./index.html');
      });
    })
  );
});

// Allow the page to trigger an immediate update.
self.addEventListener('message', function (e) {
  if (e.data === 'skipWaiting') self.skipWaiting();
});
